### ISSUE TITLE
Spoof iframe UA

### ISSUE THREAD

**Issue by gagabs** [sereneblue/chameleon#1]
It's possible to bypass this addon:

[https://browserleaks.com/javascript](https://browserleaks.com/javascript)

Click in the iframe.contentWindow tab.

Check [this issue](https://gitlab.com/ntninja/user-agent-switcher/issues/9) for a possible fix.

**Comment by sereneblue** [comment]
Thanks for the great feedback so far! I'm currently looking into this.
