### ISSUE TITLE
Resist Fingerprinting and Site Preferences

### ISSUE THREAD

**Issue by zygoteplanets** [sereneblue/chameleon#100]
"Resist fingerprinting" makes Firefox reset website zoom settings while it is on.

**Comment by sereneblue** [comment]
I'm having difficulty reproducing this issue (FF 63 and FF 64 Dev Edition). Chameleon simply toggles the resist fingerprinting option in Firefox so I don't think it's an issue with Chameleon.

**Comment by Thorin-Oakenpants** [comment]
That's a feature of RFP, not a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1369357

**Comment by sereneblue** [comment]
Thanks for the info.
