### ISSUE TITLE
No Option  Setting to Periodic Random User Agent 

### ISSUE THREAD

**Issue by Jsmith123z** [sereneblue/chameleon#102]
I've set the option for no to periodically changing the fake user agent, as some advice states continually and randomly changing a spoofed user agent-could be tracked.
More unique keeping a static fake user agent.
I really like Chameleon's option to set no to periodically changing, and thought it was a great option, other user agent spoofers don't seem to have that option.

On Chameleon I'm finding the user agent "is still" changing randomly though even though I've set it to no"

**Comment by sereneblue** [comment]
It may change if you use one of the random profile options and restart the browser. Is this happening within one browser session?

**Comment by Jsmith123z** [comment]
Yes it seems to stay static within the same browser session, but change when a new browser window is open. Within one browser session it stays the same.
I thought it kept the fake profile just static period- when the no option was set? Ie a fixed fake user agent period?
It is a great add on well done!

**Comment by Jsmith123z** [comment]
It is static only within the one browser session. My mistake- I thought it was static for all browser sessions.
Thanks.

**Comment by Jsmith123z** [comment]
The no periodic change is good because I've seen other add ons keep on changing the user agent within the one browser session--completely slowing down the session.
Chameleon is a good, efficient user agent changer, with good  options, like no periodic change.

**Comment by sereneblue** [comment]
Thanks for the kind words. :)
