### ISSUE TITLE
about TZ spoofing

### ISSUE THREAD

**Issue by classmate01** [sereneblue/chameleon#104]
Hello! I found out this timezone spoofing was really great, is there any options to turn off the small window popping on the lower right? thanks!

**Comment by sereneblue** [comment]
There isn't an option to turn off the notification for the timezone/accept-language spoofing (it overrides the notification option). It only appears when you're spoofing values using the IP address and shouldn't change too often. It's implemented this way to inform the user of the values that Chameleon will use.
