### ISSUE TITLE
TLS 1.2 and 1.3 ?Built In Supercookie Privacy Workarounds

### ISSUE THREAD

**Issue by randyrandersn** [sereneblue/chameleon#105]
Something to keep in mind ... workarounds for tls 1.2 and tls 1.3 built in "supercookie".

https://www.privateinternetaccess.com/blog/2018/11/supercookey-a-supercookie-built-into-tls-1-2-and-1-3/

```
security.ssl.disable_session_identifiers (hidden feature)
security.ssl.enable_false_start
security.tls.enable_0rtt_data
privacy.firstparty.isolate
```

Maybe provide ability within Chameleon to set these, like other settings?

**Comment by sereneblue** [comment]
Thanks for the suggestions! I'll include these settings in the next update.
