### ISSUE TITLE
various web sites not working with Chameleon 

### ISSUE THREAD

**Issue by jahnson** [sereneblue/chameleon#106]

**Comment by jahnson** [comment]
umm, here is the description 
i have very few options selected in Chameleon, I have not changed them since the last issue when I listed them and the suggestion was made to turn one option off, which I did.  

example1: vergelijk,nl does not load.  Disable Chameleon and it loads 
example2: mail.be - sign in, screen is blank.  Disable chameleon, refresh and I am logged in and can proceed.  

Various other web sites, or parts thereof, do not function either.  When [part of] a web site does not work, I have developed the habit of first disabling Chameleon, and it usually solves the issue but kinda defeats the purpose.

**Comment by sereneblue** [comment]
Please try to find the option that causes issues with sites. A screenshot/log of the console window would be helpful.

For vergelijk.nl, spoofing the timezone causes it to break. A third party dependency conflicts with Chameleon but I'm not sure why.

I can't register an account on mail.be so I can't test it with Chameleon. If it's also a timezone issue, it makes it a little easier to debug.

**Comment by jahnson** [comment]
Spoofing the timezone was the breaker for both of these sites and a couple of others too.  Looks like we're back in business.  Thank you

**Comment by n8v8R** [comment]
@sereneblue 

Maybe you could consider code collaboration with https://github.com/joue-quroi/spoof-timezone

**Comment by WPFilmmaker** [comment]
@sereneblue same issue happens on instagram.com screen is blank if time spoofing is enabled, I wonder what time has to do with photos :D:D

**Comment by sereneblue** [comment]
Although not the same issue, it was a bug in time spoofing.
