### ISSUE TITLE
Provide a way to import/export settings

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#109]
This would be very useful when migrating to another browser (many privacy focused addons have this function, like privacy badger,noscript) and I feel also when users have to report bugs.

Also, right now there is no way, unless I check manually every setting, to let you know what settings I have with Chameleon and that might break a site (like #110 ) or the browser, so this could be useful for that as well.

**Comment by sereneblue** [comment]
There is a way to export the settings (the about tab). I'm going to take a look at importing settings soon.

**Comment by WPFilmmaker** [comment]
I must have overlooked! Thanks also for the importing settings!
