### ISSUE TITLE
Chameleon breaks search function on https://uk.megabus.com/

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#110]
This is the search function with Chameleon on: http://oi64.tinypic.com/2dgjrxu.jpg
And this is when you disable Chameleon:  http://oi66.tinypic.com/2zzqivb.jpg

I am running latest version of Chameleon on FF 63.0.3 on Linux 64bit. If you need more info please let me know :)

**Comment by sereneblue** [comment]
I've spent a significant amount of time trying to fix this issue. In hindsight, hacking the Date object is not a good idea (although a very good learning experience). In the next update, Chameleon will only spoof dates that have not been initialized with a value (messing around with timezones is not fun). v0.10.3 should reduce the number of errors related to time spoofing. Even with the new version, there is a small bug with the megabus site: you may have to select the return date twice to get the correct date. 

If you encounter any future issues with time spoofing, you should whitelist the site; it's a much simpler solution. :)

**Comment by WPFilmmaker** [comment]
@sereneblue thanks for your hard work! I was going to write it by myself, the best way would be whitelisting the problematic website. Will the new change be less effective at spoofing?If yes maybe it is worth keeping the old system but add a warning that it might break some website?

**Comment by sereneblue** [comment]
That's good to hear!

The old method also didn't spoof dates that were initialized with a value, so nothing changes spoofing wise. Chameleon's time spoofing helps a little bit but it's really best to change the system time if you don't need to quickly switch between timezones.
