### ISSUE TITLE
Question: Missing Options & Just As Complete As RAS?

### ISSUE THREAD

**Issue by 0pLuS0** [sereneblue/chameleon#111]
Hello,

Sorry if this has been asked before, but are there the same amount of ```Standard Options``` that RAS has? Is Chameleon just as complete?

These are all the settings I've been using, and wasn't sure if Chameleon contained all of these? There are some below in Chameleon, but from what I remember some of these are not... Some below, a few I believe are no longer in the latest Firefox too...

browser.cache.disk.enable - (user set boolean)
false

browser.cache.disk.smart_size.enabled - (user set boolean)
false

browser.cache.disk_cache_ssl - (user set string)
false

browser.cache.frecency_experiment - (user set integer)
-1

browser.cache.memory.enable - (user set boolean)
false

browser.cache.offline.enable - (user set boolean)
false

browser.formfill.enable - (user set boolean)
false

browser.safebrowsing.downloads.enabled - (user set boolean)
false

browser.safebrowsing.malware.enabled - (user set boolean)
false

browser.safebrowsing.phishing.enabled - (user set boolean)
false

browser.search.suggest.enabled - (user set boolean)
false

browser.search.update - (user set string)
false

browser.send_pings 
false

browser.sessionhistory.max_entries - (user set string) - (can only go back 2 pages)
2

browser.sessionstore.max_tabs_undo - (user set integer)
0

browser.sessionstore.privacy_level - (user set integer)
2

browser.urlbar.autocomplete.enabled - (user set boolean)
false

browser.zoom.siteSpecific - (user set string)
false

camera.control.face_detection.enabled - (user set boolean)
false

clipboard.autocopy - (user set boolean)
false

datareporting.healthreport.uploadEnabled - (user set boolean)
false

datareporting.policy.dataSubmissionEnabled - (user set boolean)
false

device.sensors.enabled - (user set boolean)
false

dom.allow_scripts_to_close_windows - (default boolean)
false

dom.battery.enabled - (user set string)
false

dom.disable_image_src_set - (default boolean)
false

dom.enable_resource_timing - - (user set string)
false

dom.enable_performance - (user set string)
false

dom.performance.enable_user_timing_logging - (default boolean)
false

dom.enable_user_timing - (user set string)
false

dom.event.clipboardevents.enabled - (user set boolean)
false

dom.event.contextmenu.enabled - (user set boolean)
false

dom.gamepad.enabled - (user set string)
false

dom.indexedDB.enabled - (user set string)
false

dom.storage.enabled - (user set boolean) 
false

dom.storage.default_quota - (user set integer)
0

extensions.getAddons.cache.enabled - (user set boolean)
false

extensions.update.enabled - (user set boolean)
false

geo.enabled - (user set boolean)
false

geo.wifi.logging.enabled - (default boolean)
false

geo.wifi.uri - (user set string)
leave 'value' blank

media.cache_size - (user set integer)
0

media.eme.enabled - - (default boolean)
false

media.navigator.enabled - (user set boolean)
false

network.cookie.alwaysAcceptSessionCookies
false

network.cookie.cookieBehavior - (user set integer)
1

network.cookie.lifetimePolicy - (user set integer)
2

```network.cookie.lifetime.days``` Not sure about this one?
90

network.dnsCacheEntries - (user set interger)
100

network.dnsCacheExpiration 
60

network.dns.disableIPv6 - (user set boolean)
true

network.dns.disablePrefetch - (user set boolean)
true

network.http.keep-alive.timeout
20

network.prefetch-next - (user set boolean)
false

Network.http.sendRefererHeader - (default string)
0

0 - Disable referrer.
1 - Send the Referer header when clicking on a link, and set document.referrer for the following page.
2 - Send the Referer header when clicking on a link or loading an image.

network.http.sendSecureXSiteReferrer - (user set boolean)
false

network.websocket.enabled - (user set boolean)
false

places.history.enabled - (user set boolean)
false

plugins.notifyMissingFlash - (user set boolean)
false

plugin.state.flash - flash (Disable asking to install flash)

0 <-- Never active
1 <-- Ask to active
2 <-- Default, always active

privacy.clearOnShutdown.offlineApps - (user set boolean)
true

privacy.firstparty.isolate - (user set boolean)
false

privacy.trackingprotection.enabled - (user set boolean)
true

security.OCSP.require - (user set boolean) - ```Suppose to be good```
true

security.ssl.require_safe_negotiation - (user set boolean)
true

security.ssl.treat_unsafe_negotiation_as_broken - (user set boolean)
true

security.tls.version.min - (user set integer)
3

social.directories - " " - (user set string)

social.remote-install.enabled - (user set boolean)
false

social.shareDirectory - empty

social.toast-notifications.enabled - (user set boolean)
false

social.whitelist - empty - (user set string)

toolkit.telemetry.archive.enabled - (user set string)
false

toolkit.telemetry.enabled - (user set string)
false

toolkit.telemetry.unified - (user set string)
false

toolkit.telemetry.server - (user set string)

toolkit.telemetry.shutdownPingSender - (modified boolean)
false

webgl.disabled - (user set string)
true

media.peerconnection.enabled - (user set boolean)
false

**Comment by sereneblue** [comment]
Please read the wiki. 

https://github.com/sereneblue/chameleon/wiki/Options

**Comment by 0pLuS0** [comment]
I used Chamelon and that is why I posted this, seems some options are not in it... Or I'm going blind... :)

**Comment by sereneblue** [comment]
Some options are no longer available in Firefox Quantum if I recall correctly. If there's anything you think should be added to the current list, feel free to send a pull request. The options can be found [here](https://github.com/sereneblue/chameleon/blob/master/src/popup.html#L373).

**Comment by 0pLuS0** [comment]
I use to be into this heavy for years, haven't been into it much lately, so that is why I posted all this for you to look through and see if there's anything here of benefit to add.

I do know there are a bunch of the dom that RAS didn't even include, actually some of these weren't in RAS, so I'm not sure if there's really an value to them anymore, but at some point there was...

**Comment by sereneblue** [comment]
I'll look over this list when I have some free time, busy with some other things at the moment.

**Comment by 0pLuS0** [comment]
What Enhancement are you adding here?

**Comment by 0pLuS0** [comment]
Looks good, I still wish we could change these options on the fly like before, because I go to so many sites in a day, I need to quickly change options on the fly, and that is why I don't update and still use RAS on an older version of FF...

Thanks
