### ISSUE TITLE
[bug] user-agent spoofing as Linux FF not recognised as such

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#114]
FF 63.x and Nightly 65, x64 on WIN 10 Pro v1809
Chameleon v0.9.23

Spoofing the user-agent with any FF version in the Linux OS section produces on Github

![github warning](https://user-images.githubusercontent.com/13611490/49657188-02af7a80-fa37-11e8-87dd-82a968a9efec.png)

No such issue with spoofing as any FF in the WIN macOS or Android section. Curiously whitelisting GitHub with no apparent settings applied does not cause such alert.

**Comment by n8v8R** [comment]
Also addons.mozilla.org does not recognise it recognise as FF when spoofed as FF from the Linux section. No such issue if FF is selected from macOS or WIN

**Comment by sereneblue** [comment]
Thanks, I just realized there's a typo in the useragents.
