### ISSUE TITLE
[UI suggestion] change depiction for eTag prevention

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#115]
The UI states `prevent etag tracking` vs the code `"spoofEtag": true,` which seems different semantics and which could be misleading since prevention can be achieved through different means, e.g. spoofing vs. blocking. The wiki does not elaborate on the matter either.

Thus would suggest to change the UI to `eTag spoofing` and expand a bit in the wiki of what Chameleon is actually doing in this regard (spoofing, not blocking).

Just an example of semantics being clear https://github.com/cowlicks/privacypossum

![stag tracking](https://user-images.githubusercontent.com/13611490/49685010-f75e5c80-fad3-11e8-90ef-ea414006fe96.png)

**Comment by sereneblue** [comment]
The code needs to be updated to `blockEtags`.  Thanks for noticing!
