### ISSUE TITLE
[wiki suggestion] add hint for reCaptcha being impeded by "protectWinName": true

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#117]
Since it took me a little while to figure out the cause of reCaptcha not showing the picture tiles I thought it might be helpful to mention in the wiki entry `Protect window.name` that if enabled (`"protectWinName": true`) reCaptcha is impeded and thus perhaps should be whitelisted for the domain in question.

---
A bit strange that reCaptcha is apparently not utilizing the postMessage API.

https://developer.mozilla.org/en-US/docs/Web/API/Window/name

> Modern web applications hosting sensitive data should, however, not rely on window.name for cross-domain messaging but instead utilize the postMessage API.

**Comment by sereneblue** [comment]
Thanks for finding this. I'll fix this in the next update.
