### ISSUE TITLE
[regression bug 10.0.1] audio spoofing + client rects causing some html elements to flicker when scrolling

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#118]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ :heavy_check_mark: ] I am running the latest version
- [ :heavy_check_mark:  ] I checked the documentation and found no answer
- [ :heavy_check_mark: ] I checked to make sure that this issue has not already been filed

## Expected Behavior
no flicker
## Current Behavior
certain html elements flickering when scrolling as experienced here with the header https://discuss.linuxcontainers.org

This regression been introduced with the last update to 10.0.1

## Relevant settings

flicker is happening with audio spoofing enabled. disabling it stops the flicker.
## Context (Environment)

FF 64.0 (64-bit) on W10 Pro v1809 b17763.194

**Comment by sereneblue** [comment]
I don't see any flickering with FF64 and FF65. Is webaudio enabled? Can you post any error messages that appears in the console tab of the DevTools?

**Comment by n8v8R** [comment]
It happens with FF 64,65,66 but now that you pointed to it - only in combination with `dom.webaudio.enabled, true`.

With `dom.webaudio.enabled, false` and `spoofAudioContext: true` there is no flickering.

**Comment by n8v8R** [comment]
With `dom.webaudio.enabled, false` and and `spoofAudioContext: true` the console showing this

> TypeError: window.AudioBuffer is undefined

**Comment by sereneblue** [comment]
I'm not sure why it's flickering for you but it may go away with the latest commit. If you have webaudio disabled, the audio context fingerprint isn't spoofed because the necessary variables aren't there. Chameleon now checks if it's possible to spoof the audio context before attempting to spoof it. I'll release a new version after fixing the import issue.

**Comment by n8v8R** [comment]
![flicker](https://user-images.githubusercontent.com/13611490/50050679-386cf700-00fa-11e9-8ef9-e62e91b4c677.gif)

**Comment by n8v8R** [comment]
Nope, except for this bit but reckon there is no correlation

> The resource at “https://www.google-analytics.com/analytics.js” was blocked because content blocking is enabled.[Learn More]
> Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.

**Comment by n8v8R** [comment]
With `dom.webaudio.enabled, true`

and having both, `client rects` and `audio context`, enabled the flicker is apparent. Turning off either `client rects` or `audio context` and the flicker is gone.

**Comment by sereneblue** [comment]
I'm able to replicate the issue now but debugging this might be a little difficult since there aren't any visible errors.

**Comment by n8v8R** [comment]
Perhaps some JS performance issue on DOM event (scrolling) handling. Looking at the performance chart there are is plenty of this showing when scrolling

![js performance](https://user-images.githubusercontent.com/13611490/50056586-fd001600-0155-11e9-9d77-95893db8a64c.png)

**Comment by sereneblue** [comment]
I've identified the issue. Thanks for the help!
