### ISSUE TITLE
[bug] reCaptcha with FF/Linux profile not working

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#120]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ :heavy_check_mark: ] I am running the latest version
- [ :heavy_check_mark:  ] I checked the documentation and found no answer
- [ :heavy_check_mark: ] I checked to make sure that this issue has not already been filed

## Expected Behavior
reCaptcha not working

## Current Behavior
reCaptcha working

## Relevant settings

Profile set to any of the FF/Linux combinations. Other browser/OS combinations do not exhibit the issue.

## Context (Environment)

FF Developer Edition 65.0b4 (64-bit) on W10 Pro v1809 b17763.194

Testing at https://patrickhlauke.github.io/recaptcha/

**Comment by sereneblue** [comment]
Can't believe I missed that! It was a typo in the user agents for FF + Linux. Thanks!

**Comment by n8v8R** [comment]
confirmed working now
