### ISSUE TITLE
[question] New permission "access browser tabs"

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#121]
Sorry for using this for a question but had no idea where else to ask. I tried to update to the latest version from 0.9.23 and I noticed that FF is saying chameleon is asking for new permission "access browser tabs", I looked at the changelog but couldn't figure out why such new requirement, could you explain it?
Thanks as usual for your hard work!

**Comment by sereneblue** [comment]
Sure!

In v0.10.0, there is a new whitelist editor. More details can be found [here](https://github.com/sereneblue/chameleon/wiki/Whitelist).

Chameleon uses the tabs permissions to get the URL of the current tab. Using this URL, Chameleon can now tell you if the domain is whitelisted and provide a button so you can easily add/edit a whitelist rule.

![image](https://user-images.githubusercontent.com/14242625/50038459-243bd380-ffee-11e8-9d4f-5e61ca3bece1.png)

The relevant commit can be found here:
https://github.com/sereneblue/chameleon/commit/9df048110f70763da63e8da0106a57a57e2675bd

**Comment by WPFilmmaker** [comment]
@sereneblue Thanks! As usual you are great ;) You can close this.
