### ISSUE TITLE
time spoofing and whastapp web

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#122]
- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

## How to reproduce
Send/Receive a message on whatsapp web interface, the messages' timestamp will show the wrong time. The time show will be according to the spoofed time zone in chameleon settings. I don't know if there is something which can be done (I opened this ticket as sereneblue mentioned that there could be impovements in such feature which was breaking some system), or if this is a consequence of time spoofing, but it is kinda annoying :/ 

Is anyone able to reproduce it?Maybe on different platforms? Ideas?

## Expected Behavior
Messages sent/received show real timestamp not the spoofed one

## Current Behavior
Timestamp for messages (both of sender and receiver) show the spoofed time, so it doesn't represent when they were really sent/received
## Relevant settings
Time spoofing is enabled

## Context (Environment)
FF 64 linux 64bit

**Comment by sereneblue** [comment]
It's because you're spoofing the timezone. I believe Gmail also has this behavior. You should whitelist the website.

**Comment by WPFilmmaker** [comment]
Thanks, that’s what I thought, you can close the ticket :)
