### ISSUE TITLE
Screen Resolution not working

### ISSUE THREAD

**Issue by usercase** [sereneblue/chameleon#123]
Hi,

This checking page : https://browserleaks.com/javascript reveals all the details about my screen resolution and everything is right.

In Options > Script Injection Options :
 - Enable screen injection is ON
 - Screen Size Spoofing is ON with 1920x1080

I tried unchecking _Enable screen injection_ and _Screen Size Spoofing_ several times with no impact.

By the way, colorDepth & pixelDepth are also revealed by the above web page.

Thanks for your help

--
Firefox 64.0
Chameleon 0.10.1

**Comment by sereneblue** [comment]
Can you post a screenshot of the results of browserleaks? Can you also post any error output in the console when you load browserleaks?

**Comment by usercase** [comment]
### 1. Browserleaks screenshot

<img width="684" alt="capture d ecran 2018-12-19 a 15 38 51" src="https://user-images.githubusercontent.com/45983715/50226748-4c3b8600-03a4-11e9-9985-efc1411b7dc2.png">

### 2. Console
_(Only the errors not the warnings and other messages)_

```
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable

SyntaxError: missing } after property list javascript:3:277
<anonyme>
blob:moz-extension://7331ba71-92ca-b94a-9f19-e73ab3c35e13/8f756bad-7dc8-7948-bc07-dcc80c715e18:301:127
inject
resource://gre/modules/ExtensionContent.jsm:497:18
next self-hosted:1210:9 injectInto
resource://gre/modules/ExtensionContent.jsm:400:14
next self-hosted:1210:9 loadContentScript
jar:file:///Applications/Firefox.app/Contents/Resources/omni.ja!/components/extension-process-script.js:311:63

---------

Error: WebExtension context not found! ExtensionParent.jsm:1039:13
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.removeSheet]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 65"  data: no]
runSafeSyncWithoutClone
resource://gre/modules/ExtensionCommon.jsm:65:12
cleanup/<
resource://gre/modules/ExtensionContent.jsm:367:13

---------

Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à inline (« script-src »). comments:1:1 

```


**Thanks for your help** 👍

**Comment by sereneblue** [comment]
Are you running any other extensions with WebExtensions?

**Comment by usercase** [comment]
Hi,

I use other extensions. But I disabled all of them except Chameleon and did the test again on browserleaks.com, I still have the problem.

**Comment by sereneblue** [comment]
Can you post your settings (on the about tab -> export)?

**Comment by usercase** [comment]
Do you have a link on how to do it ?

Cause in my settings I do not see an export option

**Comment by sereneblue** [comment]
It's the question mark in the tab.

https://github.com/sereneblue/chameleon/wiki/Report-a-bug

**Comment by usercase** [comment]
I know why it was not working : 

I got some problems with the whitelist options, I excluded some websites and I see that you rebuild that area. Those whitelist setting were causing the troubles. 

Now things are fixed about the resolution.

**Comment by sereneblue** [comment]
Happy to hear that you've resolved the issue!
