### ISSUE TITLE
FYI: user agent spoofing

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [sereneblue/chameleon#125]
# Prerequisites
- test page: it's under development and kinda under wraps, but the user agent FP'ing section is almost all done
- will email a link to @sereneblue if he wants it

## Relevant settings
- enabled script injection and screen size spoofing (as 1600x900) - left from #124 
- enabled spoofing UA as just Chrome 71 on Windows 7 (which is my actual OS, to reduce confusion)
- no other changes from default

## Context (Environment)
- FF65beta current build
- default vanilla profile
- Chameleon 10.3
- Chrome 71 latest build, vanilla profile

## note
- the http header field is meant to be empty - I haven't added it yet, but I checked and you match your js ua :)
- in the `browser, version, os` section I only return values for browser & version for Firefox. For the os, only the css os detection is added, but seems to work for chrome as well, as would tcp/ip detection.
- ps: I have not added in checking any values from iframes - I will do that last with the entire suite of tests

## this is just for your info

Here is what a brand new profile in portable Chrome 71.0.3578.**89** shows (I am on Windows 7 64 bit)
![ua-chrome-71nilla](https://user-images.githubusercontent.com/16656956/50741673-21e92580-11f8-11e9-807a-47237da70112.png)

And here is what a vanilla Firefox 65 spoofing as Chrome 71 looks like
![ua-ff65nilla-as-chrome71](https://user-images.githubusercontent.com/16656956/50741713-f61a6f80-11f8-11e9-9f39-f5612b705a93.png)

and here is a vanilla FF 65 with no spoofing
![ua-ff65nilla](https://user-images.githubusercontent.com/16656956/50741720-1e09d300-11f9-11e9-91c3-6ee0c7159583.png)

## some observations

Note: ignore the minor chrome version diff (`.80` vs `.98`)
Note: when I say FF only feature, I am ignoring forks like Palemoon and focusing on the major browsers you include as spoofs

- user agent:  chrome uses `WOW64` but the spoof uses `Win64; x64`. That's what Firefox uses. Is that an oversight? Or is that because I'm using a portable version or something? It's just an observation. I'm not a Chrome expert.
- navigator.appVersion: same as above: `WOW64` vs `Win64; x64`
- navigator.oscpu: this is a Firefox only feature. Chrome and other browsers return `undefined`. The spoof returns an actual value
- navigator.buildID: this is a Firefox only feature. Chrome and other browsers return `undefined`. The spoof returns a blank string or null or whatever
- navigator.buildID: I think I looked at this the other day and you spoof this for Firefox spoofs as `20100101`. Since FF64 it now always returns a fixed timestamp of `20181001000000` - see [here](https://www.fxsitecompat.com/en-CA/docs/2018/navigator-buildid-now-returns-a-fixed-timestamp/) - so you may want to change that for FF64+ spoofs. I can't check right now (due to other FF being open) but will do so if you want.
- navigator.platform: Chrome and Edge (and others, Opera does, so I guess all Chromium based ones will?) actually always return Win32 - see [Bugzilla 1472618](https://bugzilla.mozilla.org/show_bug.cgi?id=1472618). FF63+ now also always returns `Win32`. You spoof returns `Win64`

And last, but not least... not much you can do here
- Firefox users (I'm not interested in other browsers, but the same issues exist for them) cannot hide the fact they are using FF, or even their browser version. And it's also possible to get the OS. From the pic above of FF65 masquerading as Chrome71, I can use css, chrome:// detection, and one of **many** tested Firefox only features (most you can't disable) to detect the browser as Firefox. I can also **100% reliably** detect the browser version from FF60 thru to 65 (not interested in going back any further), and there are no prefs to disable these methods either - they are hard coded changes in how Firefox handles things. When I say you can't disable these - they are JS, so killing JS, like it always has, massively reduces the attack surface. The OS detection is a work in progress and can *probably* almost all be mitigated (I have more methods for OS detection not shown).

Hopefully there's some information in here you can use to better your spoofing. If you want anything, sing out.

**Comment by sereneblue** [comment]
Thank you for looking into this. I'll fix all of the above issues (minus the last point) in a future update.

I believe the Chrome user agent differs depending on the Windows version (I'll look into this). Windows 10 shows Win64. It's oversight on my part because I didn't check the user agent for the older versions of Windows.

About your last point, sadly it's a game of whack-a-mole. Every browser update introduces new features. Feature detection makes it impossible to spoof the browser, although there are other ways to detect the browser. Using NoScript/uMatrix should be enough to not make this much of an issue; there's only so much a WebExtension can do.

**Comment by sereneblue** [comment]
For the Chrome user agent, WOW64 is for a 32-bit browser on a 64-bit machine. Win64 is for a 64-bit browser.

**Comment by Thorin-Oakenpants** [comment]
Oh, that explains it then .. portableapps.com's paf is just a wrapper, it still gets the file online. Wonder why it gives me a 32bit version on a 64bit machine. That's a bit sucky. Stick with 64bit mate.

No-one can defeat feature detection when done right - but no-one really does it AFAIK - too much lower hanging fruit - my work here is more of a worst case scenario, assume state actors or whatever - aimed at Tor Browser regression testing, PoCs, Tor Uplift and RFP

Posted for you:
- Screen :white_check_mark:
- UA :white_check_mark:
- the other 20 sections ... getting there .. will post if they affect you

**Comment by sereneblue** [comment]
v0.10.4 addresses the above points. Feel free to reopen this issue if you find an issue. I look forward to those other sections. ;)
