### ISSUE TITLE
Firefox Legacy

### ISSUE THREAD

**Issue by bogachenko** [sereneblue/chameleon#128]
how about creating a new branch for older versions of Firefox?

Palemoon? Waterfox?
![default](https://user-images.githubusercontent.com/8535285/51089173-cf13ee80-1760-11e9-8d6c-890e7a014990.png)

**Comment by sereneblue** [comment]
I won't support legacy versions of Firefox. If users want to stick to pre-Quantum Firefox, they should fork RAS and maintain an updated version.
