### ISSUE TITLE
Let users to pick whitelist profile as you do for profile

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#130]
Right now user profile as a nice list you can select uas from. However if you try to whitelist a website and go on "whitelist profile" you have to manually add strings which is definitively complicated for the average user. I tried looking in the wiki page but couldn't add a custom ua :( could you add the same list to "whitelist profile"?

**Comment by sereneblue** [comment]
This will be addressed in the next update.
