### ISSUE TITLE
Can't add ua to Whitelist profile

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#131]
Don't know if it is related to #130 and I am just not tech savvy enough or if it is a bug but I can't add a custom profile to white list.

This is what I do:
Whitelist - Whitelist profile - in the "user agent" box I put a ua string (user real profile box is untoggled)

Since I am interested only in ua I leave the other boxes empty. There is no OK/Save button so I assume it is good. I close chameleon window but when I return to whitelist menu the "user agent" box is empty :( What am I doing wrong?

Firefox 64, 64bit Linux, Lubuntu 16.04.3, Chameleon 0.10.4.

**Comment by sereneblue** [comment]
I'm not sure what's causing the issue but the whitelist profile editor will be removed in then next version for something simpler.

**Comment by sereneblue** [comment]
v0.11.0 should be a bit simpler to use. Hope you enjoy it!
