### ISSUE TITLE
Whitelisting all domains

### ISSUE THREAD

**Issue by classmate01** [sereneblue/chameleon#132]
is there an options to whitelist all domains instead of manually adding one?? Just wanted to use these feature (oscpu platform vendor and etc.. which is amazing) coz I got a little prob with the chromeUA in profile settings which exposes my br0wser's real identity though i already checked the script injections. Thanks

**Comment by classmate01** [comment]
or is there any options we can edit or modify the navigator.objects

**Comment by sereneblue** [comment]
The next version of Chameleon will allow you to have a default whitelist profile that spoofs those properties.

**Comment by sereneblue** [comment]
Rereading the title, I'm not sure why you'd need to whitelist all domains? Selecting a profile should spoof all those properties for every site you visit. The whitelist currently prevents certain sites from being spoofed unless you use the custom whitelist profile (will be removed for something simpler) or use your real browser profile.

**Comment by classmate01** [comment]
selecting a profile doesn't spoof all those properties even if the script injector is checked. For instance in browserleaks.com when my firefox browser use a profile of *Chrome 71 or 72 Windows 10* it exposed that I am still using a firefox browser in the absense of Google Inc. in the navigator.vendor. Same goes with safari profile, browserleaks.com shows win32 in navigator.platform

**Comment by classmate01** [comment]
Wow great!
yeah after checking the macOS i just see the macintel its just maybe I was a little bit sleepy last night. Thanks for checking it out! 👍 I just wonder if its also possible to fake the installed plugins like PDF Plugins and Viewer

**Comment by classmate01** [comment]
I'm excited :) 👍

**Comment by WPFilmmaker** [comment]
@sereneblue would it b possible to fake flash plugin too? It would be a good addition IMO.

**Comment by sereneblue** [comment]
Considering Flash is pretty much dead at this point, I don't think it's worth faking.

**Comment by WPFilmmaker** [comment]
@sereneblue I thought it would make sense as those who use it are a minority thus stand out, if not flash what do you man by plugins? webrtc?unity?

**Comment by classmate01** [comment]
@WPFilmmaker 
You can check the image for the installed plugins in a normal chrome browser
https://i.imgur.com/yTTN471.png
Source: browserleaks

**Comment by sereneblue** [comment]
Flash is disabled by default in all major browsers so I don't think it's worth adding to the spoofed plugins. Also, it seems some browsers don't return anything for navigator.plugins (Edge and Firefox). I'll have to do some more research.

**Comment by sereneblue** [comment]
@classmate01 Although it should be technically possible to spoof the plugins, I can't get it to work. It's probably best to leave it to FF. :(

**Comment by classmate01** [comment]
its ok! thank you!!
