### ISSUE TITLE
[feature suggestion] add advanced tracking protection to standard options

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#133]
https://www.bleepingcomputer.com/news/security/mozilla-adding-cryptomining-and-fingerprint-blocking-to-firefox/

Suppose `privacy.trackingprotection.fingerprinting.enabled` is blocking relevant api entirely from querying the browser whilst `privacy.resistFingerprinting` does produce entropy data in response, at least that would be my understanding.

**Comment by sereneblue** [comment]
This will be in the next update. It's pretty easy to add. Thanks for pointing it out!

**Comment by sereneblue** [comment]
This was updated in v0.11.0.

**Comment by n8v8R** [comment]
It does not appear however in the UI

![tracking](https://user-images.githubusercontent.com/13611490/52632482-9e3aec80-2eb9-11e9-8706-2e30578c92a2.png)

**Comment by sereneblue** [comment]
It is in the UI.

Chameleon is controlling the trackers option.

When it's on, the dropdown shows "In all windows"
When it's off, the checkbox is unchecked.
When it's enabled for private browsing, the dropdown shows "Only In Private windows"

**Comment by n8v8R** [comment]
I am afraid it seems that we have a misunderstanding caused by my failure to express this better since I thought it was clear from the article that the advanced options should be

- `privacy.trackingprotection.fingerprinting.enabled`
- `privacy.trackingprotection.cryptomining.enabled`

**Comment by sereneblue** [comment]
Oh, I see. 

Those options can't be toggled by WebExtensions (at least for now).
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites

**Comment by n8v8R** [comment]
Hmpf, now I c 😉 

Maybe M should update that website (having silently alreadly expanded the API in Nighly) or will update the API/website once the feature arrives in the stable channel.
