### ISSUE TITLE
[Request] Get Rid of Issue in TimeZone and Language Spoofing According IP

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#134]
## Current Behavior
When using _some_ vpn servers, the TimeZone and Language Spoofing According Ip are working like a charm. With _some others_, one of these spoof continues to not work in a full satisfying way: Sometimes I use eg a server in NL and Chameleon spoofs time as UTC+1 (correct) but with Europe/Berlin instead of Europe/Amsterdam, sometimes, the UTC itself is wrong, sometimes the language is wrong (or even not displayed), etc.

## Request
So, why not to adopt the following radical solution: As the ip ranges of the vpn/proxies servers he uses are known by the user, Chameleon could offer to the user (in its UI or at least in a proper config file) the possibility to define/enforce what the time zone (and possibly the language) are for each given ip range he finds problematic. For this feature to work, Chameleon will only to have to determine which IP the user is using,  which seems easy.

## Relevant settings
Script injection activated. TimeZone set to "IP", Spoof Accept-Language set to "IP".

## Context (Environment)
FF 65 64bits on W7, Chameleon 0.10.4

**Comment by sereneblue** [comment]
There's a lot of bad IP information out there and it changes over time. Offloading it to a 3rd party service is better because they'll be able to keep the information updated far more than I'll be able to.

You've brought up an interesting issue with the mismatched timezone and timezone name. I'll take a look at this in a future update. If you're having issues with an IP not showing the language, please create an issue with the information returned from https://ipapi.co/json.

**Comment by Kraxys** [comment]
> 
> 
> There's a lot of bad IP information out there and it changes over time. Offloading it to a 3rd party service is better because they'll be able to keep the information updated far more than I'll be able to.
> 
In my request, you would not be required to keep any information updated: Just let the user the possibility to define somewhere in Chameleon that IP _XX.YY.ZZ_ (or IP range) has TimeZone _GMT+N_, language _uu, vv,_ etc.  It would solve the problem in case the user is able to detect that the way Chameleon attributes a TZ or a language to a specific IP or IP range is wrong.  For example when the user uses a paid VPN service, he is able to detects (because he can contact the VPN provider) whether or not Chameleon is wrong in attributing some given TZ and language to a given used IP range, and he is able to correct that too (as he knows the real TZ and language associated to the used IP range). Of course these assumptions are no more valid in case the user is browsing eg on Tor network because there is no onde in charge to contact, but in that case, it may be better to use TBB without any addon instead...

**Comment by MilesBHuff** [comment]
I really like the idea of adding a checkbox to make browser language and timezone match what you would predict given a particular IP.

**Comment by sereneblue** [comment]
v0.12.0 allows you to define IP rules. You can find it by visiting the whitelist tab. I'll update the wiki soon with more info.
