### ISSUE TITLE
Toggling on/off new FF protections against miners and fingerprinting?

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#135]
According to https://www.bleepingcomputer.com/news/security/mozilla-adding-cryptomining-and-fingerprint-blocking-to-firefox/

FF is implementing a way to block cryptominers and fingerprinting. While I think it could be a good move (lists and addons to do that already exist though), I remembered that in #74 where it was suggested that the best way was not to block fingerprinting but rather create noise for disguising (https://multilogin.com/how-canvas-fingerprint-blockers-make-you-easily-trackable/). Furthermore AFAIK chrome does not have this feature  (yet?), thus couldn't it be used to figure out who is a chrome vs firefox-disguised-as-chrome user? 

I haven't delved into how they wan to block fingerprinting as I am no coder but you can look at: https://bugzilla.mozilla.org/show_bug.cgi?id=1522567  it seems that it will be shipped by default on wih 67 and it is already available in beta and night builds.

Also since they define:
"Fingerprinting as: Browser fingerprinting is a method of tracking users by the configuration and settings information that is visible to websites they browse, rather than traditional tracking methods such as IP addresses and unique cookies."

and

"Cryptomining as: using scripts on websites that can use a computer’s resources to mine cryptocurrency without a user’s knowledge."

Do you think this could cause incompatibilities with chameleon?

"privacy.trackingprotection.fingerprinting.enabled" and "privacy.trackingprotection.cryptomining.enabled" are the strings in question. Would it make sense to add an option to toggle on/off such options from chameleon?

**Comment by sereneblue** [comment]
Yes, spoofing fingerprint values is generally the better solution. Blocking them does leave a fingerprint, however, if you're using NoScript/uMatrix you're already massively reducing the amount of tracking that's happening in your browser.

If known tracking domains are blocked from loading scripts, then it'd be similar to using the extensions I mentioned above. If fixed values are reported than that may be a fingerprint itself. I'm not sure if those about:config entries will have a WebExtension API to toggle them. If yes, I'll add them.

**Comment by WPFilmmaker** [comment]
You are right about not loading scripts. Just a little note, I realized I wasn't very clear in my message. I meant adding the option to "misc" menu the one where you can copy/paste strings from to use in about:config.

**Comment by sereneblue** [comment]
I don't think it'd be useful considering those options will be enabled by default when FF66 is released.

**Comment by WPFilmmaker** [comment]
@sereneblue a small note, wouldn't be helpful to disable such features automatically once non-FF profiles are selected? In order to conform to the fact that non-FF browsers don't have such features? (it would be the same as showing a FF profile but with a chrome-PDF plugin..)
