### ISSUE TITLE
Content types inconsistency

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#136]
## Expected Behavior
When spoofing FF ESR 60 on windows7, the _HTTP_ACCEPT_ header should be:
`text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`
(it's what is sent when using FF 60 ESR Portable on W7).

## Current Behavior
Currently, when spoofing FF ESR 60 on W7 while using FF 65, the _HTTP_ACCEPT_ header is:
`text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`

## Relevant settings
Chameleon 0.11.1

## Context (Environment)
FF 65 on W7

**Comment by sereneblue** [comment]
Thanks for being vigilant! This will be fixed in the next update.

**Comment by Saadi1988** [comment]
sorry, i can't send using "Pull request" so i write here:
1. build a panel like "Shields" in Brave(Mozilla based) browser. it is very good and useful.
2. more advanced settings. for example, for fake ip do just for some websites. or special settings(ie: cookie settings) for certain sites.
3. a new ui design for extension.

Thanks.

**Comment by sereneblue** [comment]
@[Saadi1988](/Saadi1988)

I think the button you were looking for is on the Issues page (New Issue). Also, Brave isn't Mozilla based, it's built upon Chromium.

1. Firefox already has something like that (Content Blocking) although it's not as granular. You maybe be able to replicate the functionality with a few web extensions. That is also not the focus of Chameleon.
2. Chameleon wasn't designed to give users granular control over settings for each site. Although the whitelist editor offers some options, it was an afterthought and doesn't offer the functionality that you're looking for.
3. This WebExtension was designed to be a spiritual successor to Random Agent Spoofer; I won't make any future cosmetic changes to the UI.
