### ISSUE TITLE
Wrong Platform

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#137]
## Expected Behavior
The platform should be consistent with the UA sent.

## Current Behavior
I'm using FF 65  on W7 64 bits. When selecting  for profile "FF 65 WIN7" (or FF65 Win8.1 or FF65 WIN10). the UA indicates WIN64, but the platform is WIN32. Tested on browserleaks (entry "Platform") and on ip-check (entry "System").
This inconstancy doesn't occur when I select FF 60 for profile.

**Comment by sereneblue** [comment]
Starting with FF63, navigator.platform returns Win32. It should actually be the reverse for FF60.

https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/platform

**Comment by Nalapl3** [comment]
I don't think it's right to do that. Tor Browser reports Win32 with "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0", but Chameleon reports Win64, which is making this user agent spoofing useless.

I'd very much appreciate an option to set a custom platform.
