### ISSUE TITLE
[fix] Redirect loop/cookies error /cdn-cgi/l/chk_jschl?s=*&jschl_vc=*&pass=*&jschl_answer=*.*

### ISSUE THREAD

**Issue by slrslr** [sereneblue/chameleon#138]
Hello on webhostingtalk and torrentz2.eu site (and certainly more sites too) happen an issue related to Chameleon and Cloudflare.

When i visit:
webhostingtalk.com/search.php?searchid=13677561
I see Cloudflare message that it is checking my browser, then it redirect me to failure page:
webhostingtalk.com/cdn-cgi/l/chk_jschl?s=*&jschl_vc=*&pass=*&jschl_answer=*.*

where it shows redirect loop error and as a possible cause it mention denied cookies.

"cdn-cgi..."" part is common for both domains.

When i whitelist the domain in Chameleon, then issue disappear.
Also the issue disappear when i untick Chameleon option Headers / Spoof Source Referer.

If anyone want to fix this redirect bug, i think good option is to [contact cloudflare](https://support.cloudflare.com/hc/en-us/requests) mentioning ones RAY id mentioned on redirection page.

**Comment by sereneblue** [comment]
Thanks for finding this bug! This will be fixed in the next update.
