### ISSUE TITLE
Disqus comments not loading on torrentfreak.com

### ISSUE THREAD

**Issue by slrslr** [sereneblue/chameleon#139]
I apologize if this is not right place for this.
I noticed that when i try to show disqus comments on the bottom of a torrentfreak post:
https://torrentfreak.com/web2web-serverless-websites-powered-by-torrents-bitcoin-161008/
it is loading, but nothing show up. When i disable Chameleon it load up OK.

v0.11.3, Firefox 66.0b8

**Comment by sereneblue** [comment]
Can you post your exported profile?

**Comment by Kraxys** [comment]
I think  a cause of disqus malfunctionning could be the activation of the window.name protection. I remember I have had to uncheck it in order to read disqus comments.

**Comment by Kraxys** [comment]
Could be due to window.name protection in Chameleon.

**Comment by Kraxys** [comment]
Could be due to window.name protection in Chameleon.

**Comment by slrslr** [comment]
Yes, the cause is Options/Script Injection Options/"Protect window.name*" option.
When is unticked, the disqus comments load OK.. When ticked, it does not load.

**Comment by sereneblue** [comment]
Thanks for your input @Kraxys.

@slrslr No, it won't be needed. I've fixed the issue. Thanks for reporting! ;)
