### ISSUE TITLE
No Notification For screen Size

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#140]
## Current Behavior
I have enabled notifications, enabled script injection and set screen size spoofing to "profile". But when my browser starts, I see only notification about UA and TimeZone, no notification about screen size is poping up. 

## Expected Behavior
Notification about the screen size should poping up when the browser starts, as are doing notifications about the UA and about the Time Zone

V0.11.3 on FF 65, W7

**Comment by sereneblue** [comment]
I'll update the notification in the next update.
