### ISSUE TITLE
Hidden Feature in Chameleon?

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#141]
I just noticed something strange: With Chameleon as sole extension, I get on browserleaks test sometimes 2 hardware concurrencies, and sometimes 4. Good, but there isn't any corresponding feature in Chameleon's UI, and I found nothing in the wiki.

**Comment by sereneblue** [comment]
It's automatically spoofed when you use a browser profile. Thanks for pointing this out, I've added some info to the wiki [here](https://github.com/sereneblue/chameleon/wiki/Profile).
