### ISSUE TITLE
Twitter status not appear properly

### ISSUE THREAD

**Issue by slrslr** [sereneblue/chameleon#143]
When i directly visit [some status page](https://twitter.com/jpgoldberg/status/1098356875630788608) on Twitter

It loads and immediately page become black with ["Create a new list" window](https://snag.gy/LNlcTP.jpg)

When i whitelist the site in Chameleon, it start working.

Chameleon exported settings [here](https://pastebin.com/eXg4uJFW)

**Comment by sereneblue** [comment]
Thanks for the detailed issue. I found some bugs while trying to import your settings that I've addressed. That will be in fixed the next update.

It's the spoof client rects option that's causing issues on Twitter. I'm not sure why it's caasing issues and the console doesn't show any errors, so there's not much I can do. Whitelisting is your best option (if you want to use the spoof client rects option).
