### ISSUE TITLE
youtube.com - page elements are gray when Chameleon is active

### ISSUE THREAD

**Issue by slrslr** [sereneblue/chameleon#144]
Hello,

it seems Youtube.com [do not want to work with Chameleon](https://snag.gy/0QdS2I.jpg).

When i whitelist the site in Chameleon (v0.11.4), it start working.

Chameleon exported settings [here](https://pastebin.com/eXg4uJFW)

I tried to disable a few configuration options, but not helped 😶, unsure where is the cause.

**Comment by WPFilmmaker** [comment]
Youtube is working fine for me. I don't think it is related to Chamelen but rather to FF or youtube. I experienced it myself several times. If you google "youtube grey preview" you will notice that it is a quite common issue (on FF... for whatever reasons YT seems to prefer Chrome...) . Some suggest to clear cache of FF but in my experience, it never worked. A similar issue is when the grey elements just disappear...in my experience all i could do was  live with it for a few days then all fixed itself.

**Comment by slrslr** [comment]
I tried to refresh youtube page using "Ctrl+F5 clears the cached files in browsers" that does not help. Is strange that when disabling Chameleon, youtube start working. But np, issue may be closed and i will have to whitelist youtube in Chameleon.

**Comment by WPFilmmaker** [comment]
I am still skeptical is related to Chameleon because when I have this issue YT fixes itself, without having to disable chameleon or to whitelist YT. @sereneblue maybe you know more?

**Comment by slrslr** [comment]
I tried to refresh youtube page using "Ctrl+F5 clears the cached files in browsers" that does not help and Firefox (i am on beta channel) incognito browsing mode (no cache) also has same issue. Is strange that when disabling Chameleon, youtube start working. But np, issue may be closed and i will have to whitelist youtube in Chameleon.

**Comment by sereneblue** [comment]
Youtube uses a non-standard API that causes issues when you use a Chrome profile using Firefox. It's best to whitelist the site.
