### ISSUE TITLE
[Workaround for #144] -Getting rid of greyed Youtube

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#145]
Issue #144 has been  closed before I had time to reply to it.

I fixed the problem  described in #144 in using the addon [Disable Polymer on Youtube](https://addons.mozilla.org/en-US/firefox/addon/disable-polymer-youtube/).

Withtout DPoY and Chameleon faking Chrome 72 on W10: Greyed Youtube.
With DPoY and Chameleon faking Chrome 72 on W10:  Normal Youtube.

Chameleon v0.11.4 FF 65 on W7

**Comment by sereneblue** [comment]
I'll fix this in the next update.
