### ISSUE TITLE
Chameleon does not display which 'profile option' is toggled

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#147]
I toggle one 'profile option', let's say random profile desktop. After a while I check Chameleon again and no option is toggled. It is weird because I can see that Chameleon is working but because of the missing toggle is not clear what option I selected.

Am I the only one who noticed this behavior?

Firefox 65.0.1, 64bit Linux, Lubuntu 16.04.3, Chameleon v0.11.5.

**Comment by sereneblue** [comment]
Are you selecting a specific profile or one of the random options? Also, can you post your settings and the profile that causes the issue the next time you encounter the bug?

**Comment by WPFilmmaker** [comment]
@sereneblue I select a random profile. I usually don't tweak chameleon too much after I set it, so I don't keep it in the bar. What I do is tweaking what I need->remove chameleon icon from the bar. I noticed that when I restart FF Chameleon forgets the toggle I selected.

**Comment by sereneblue** [comment]
Hm, for some reason I'm not able to replicate this issue. I cleaned up some code that might be the cause. Does v0.11.6 fix this issue?

If not, please try [debugging](https://github.com/sereneblue/chameleon/wiki/Debug) and let me know if you've found anything.

**Comment by WPFilmmaker** [comment]
@sereneblue can confirm that bug is not present anymore!
