### ISSUE TITLE
Skype for Web does not support FF anymore, can chameleon help?

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#148]
# My system:
Firefox 65.0.1, 64bit Linux, Lubuntu 16.04.3, Chameleon v0.11.5.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

## Expected Behavior
I can use Skype for Web (https://web.skype.com/)

## Current Behavior
Chameleon sends SfW in loop throwing: "Oops, it looks like something went wrong. Click OK to automatically reload Skype for Web." when you click OK the page reloads correctly and after few seconds it happens again.

I tried the following UAs and they all do the same:
- Win 7 Chrome 72
-Win 8 Chrome 72
-Win 8.1 Chrome 72
-Win 10 Chrome 72

- Edge 19 Win 10 causes STARTUP_LOAD_ERROR

I know Skype sucks...but @sereneblue can you give it a look? Should I whitelist it or maybe you can get some useful information on why it does that?

Edit: whitelisting is not an option as the website doesn't work with FF...

Edit2: I tried to clean cache but nothing..

Edit3: according to https://betanews.com/2019/03/08/new-skype-for-web/
"The latest version of Skype for Web only works in Windows 10 and macOS 10.12 or newer, and only in the Chrome and Microsoft Edge browsers. Firefox and Opera users are left out in the cold, and anyone running Chrome OS or Linux will be disappointed to learn that their operating systems are no longer supported."

Sounds great...........................

@sereneblue so basically chameleon is not enough to mask the fact that I am not using Windows...I hope you can learn something from the way they detect the OS and perfect Chameleon. As usual thanks a lot for your work!

**Comment by sereneblue** [comment]
Hm, I read about this earlier today. I believe changing the user agent fixes the issue but maybe Chameleon is doing something while spoofing that causes issues. I'll take a look at it.

**Comment by sereneblue** [comment]
@WPFilmmaker Are you experiencing issues with v0.11.6? 🤔

**Comment by WPFilmmaker** [comment]
@sereneblue I updated to v0.11.7 and tried again but still experience the issue :/
Can you reproduce it?(If you have a skype account)

**Comment by sereneblue** [comment]
I can reproduce the issue. It's probably caused by an injection option.

**Comment by sereneblue** [comment]
I think Microsoft may have updated the Skype website so it works for the Chrome profiles mentioned above. Does Skype work for you with the latest version of Chameleon and the Chrome profiles? Unfortunately, the Edge profile still doesn't work and I'm not sure why.

**Comment by WPFilmmaker** [comment]
@sereneblue I tried again as you suggested, unfortunately the website shows the same error (can log in but after few seconds a message popsup and goes in loop as I reported in the first message :/). User-Agent Switcherby Alexander Schlarb works fine. Do you know what  said addon does differently than chameleon? Last time I checked his gitlab page the addon had way less functions than chameleon and the dev stated he was not going to add features to create a Random Agent Spoofer successor so maybe the does not inject anything.

**Comment by sereneblue** [comment]
@WPFilmmaker I'm not sure what could be the cause of this issue. With script injection disabled, only the request headers and possibly the privacy settings are modified. Can you post your settings?

**Comment by WPFilmmaker** [comment]
@sereneblue:

    "blockEtag": false,
    "disableAuth": false,
    "disableRef": false,
    "enableDNT": false,
    "refererXorigin": 0,
    "refererTrimming": 0,
    "spoofAccept": true,
    "spoofAcceptLang": true,
    "spoofAcceptLangValue": "en-GB,en;q=0.5",
    "spoofSourceRef": false,
    "spoofVia": false,
    "spoofViaValue": 0,
    "spoofXFor": false,
    "spoofXForValue": 0,
    "upgradeInsecureRequests": false,
    "viaIP": "",
    "viaIP_profile": "",
    "xforwardedforIP": "",
    "xforwardedforIP_profile": "",
    "useragent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
  },
  "settings": {
    "customScreen": "",
    "enableScriptInjection": true,
    "interval": 0,
    "limitHistory": false,
    "minInterval": null,
    "maxInterval": null,
    "notificationsEnabled": true,
    "protectWinName": false,
    "screenSize": "default",
    "spoofAudioContext": true,
    "spoofClientRects": false,
    "timeZone": "America/New_York",
    "useragent": "win4",
    "useragentValue": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36",
    "webSockets": "allow_all"
  },
  "version": "0.11.10",
  "whitelist": {
    "enabled": true,
    "defaultProfile": "none",

**Comment by sereneblue** [comment]
Spoofing the accept header is the cause of this issue. This will be fixed in the next update.

**Comment by WPFilmmaker** [comment]
@sereneblue in the meanwhile you push a new version I am using User-Agent Switcher by Alexander Schlarb because it used to work...used to..it has been a few days that I can't use skype web :/ it throws always a "STARTUP_LOAD_ERROR". Do you experience this with the dev of chameleon? If not I will wait for the version to come out, if you do experience it, it means MS broke something again :/

**Comment by sereneblue** [comment]
I'm not experiencing any issues using the Windows Chrome 73 user agent with the addon you mentioned. That seems to be the only user agent that works with Skype. Edge gives the startup load error, the others show the browser not supported screen.

The dev version of Chameleon works with the same Chrome profile.

**Comment by WPFilmmaker** [comment]
@sereneblue A year and a half later I tried using skype for web and it still throws this error...with FF (chameleon disabled) it says site unsupported, trying with a spoofed edge or chrome throws STARTUP_LOAD_ERROR.

I am sure this is low priority but I would be greateful if you could give another look into this and see if something can be done, thanks 🤗

**Comment by sereneblue** [comment]
@WPFilmmaker Is Skype whitelisted? Also, disabling/changing WebRTC?

**Comment by sereneblue** [comment]
@WPFilmmaker Can you try again? I don't think the issue was with Chameleon.

**Comment by WPFilmmaker** [comment]
@sereneblue sorry for the late reply! turning on WebRTC solved the issue!
