### ISSUE TITLE
Real profile setting missing from whitelisted sites

### ISSUE THREAD

**Issue by quietlystorming** [sereneblue/chameleon#149]
## Expected Behavior
Select real profile from dropdown menu for individual whitelisted site.

## Current Behavior
Real profile is not found  in individual dropdown menus, only from main default whitelist profile menu.

## Relevant settings
n/a

## Context (Environment)
FF 65, Win8.1x64

**Comment by sereneblue** [comment]
Hm, when I implemented this, I assumed that the user would use their real profile as the default whitelist profile to make it more convenient for them. Thanks for submitting this issue. I'll add this in the next update.
