### ISSUE TITLE
Chameleon uglifies a bit Gmail when window.name is protected

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#150]
## Expected Behavior
After opening my Gmail account, a vertical scroll bar should appear on the right of the window

## Current Behavior
No vertical scroll bar, so that I can't scroll through my emails. 

## Relevant settings

After some tests, the culprit seems to be the window.name protection. When window.name protection is checked, no vertical scroll. When unchecked and after reloading the page, I have a vertical scroll to the right of my window and can scroll my emails.

 V0.11.6 on W7 64

**Comment by sereneblue** [comment]
Are you using the new Gmail interface? I can't replicate this issue. Can you post your settings?

**Comment by Kraxys** [comment]
I use the Gmail "standart"/default interface. 
Contrary to what I said previously, the "no vertical scroll" problem seems related to screen size faking, not window.name.
 When I fake a screen size of the order of my laptop's true screen size, I get the scroll. When I fake a large screen size, the scroll disappear (and the lines on gmail's interface are not displayed entirely, some parts to the right are missing).  I never have this problem with the HTML simplified interface. 
 
Strangely, I always get this problem with my testing browser (FF 65 portable with only Chameleon as active addon), but almost never with ab heavily customized FF 65 portable.

Settings:
headers": {
    "blockEtag": true,
    "disableAuth": true,
    "disableRef": false,
    "enableDNT": false,
    "refererXorigin": 0,
    "refererTrimming": 0,
    "spoofAccept": true,
    "spoofAcceptLang": true,
    "spoofAcceptLangValue": "en-US,en;q=0.5",
    "spoofSourceRef": false,
    "spoofVia": false,
    "spoofViaValue": 0,
    "spoofXFor": false,
    "spoofXForValue": 0,
    "upgradeInsecureRequests": true,
    "viaIP": "",
    "viaIP_profile": "69.164.246.244",
    "xforwardedforIP": "",
    "xforwardedforIP_profile": "69.164.246.244",
    "useragent": ""
  },
  "whitelist": {
    "enabled": false,
    "defaultProfile": "none",
    "urlList": []
  },
  "excluded": {
    "win": [
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      true,
      true,
      true,
      false,
      false,
      false
    ],
    "mac": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "linux": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "ios": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "android": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "all": [
      false,
      false,
      false,
      false,
      false
    ]
  },
  "settings": {
    "customScreen": "",
    "disableWebSockets": true,
    "enableScriptInjection": true,
    "interval": 0,
    "limitHistory": false,
    "minInterval": null,
    "maxInterval": null,
    "notificationsEnabled": true,
    "protectWinName": true,
    "screenSize": "profile",
    "spoofAudioContext": false,
    "spoofClientRects": false,
    "timeZone": "ip",
    "useragent": "random_win",
    "useragentValue": "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.97 Safari/537.36"
  },
  "version": "0.11.6"
}

FF 65 W7 x64

**Comment by Kraxys** [comment]
An incident question:
I just noticed that "viaIP_profile" and "xforwardedforIP_profile" above are set to 69.164.246.244... But why (and why this particular IP), as in the Chameleon profile I use I let the headers _xforwardedfor_ and _via_ unchecked ???

**Comment by sereneblue** [comment]
Thanks for the detective work; I was able to replicate the issue. It seems Gmail renders the UI according to the screen size rather than the actual viewport. I don't know why they chose to implement it this way. You should probably use the whitelist or the basic Gmail version to resolve this issue.

About the spoofed IPs, every time you modify your settings, Chameleon rebuilds the profile, generating a new spoof IP that will be used if you enable the relevant settings. It's old code that I haven't refactored that causes it to generate an IP even though the settings aren't checked. It's a minor issue that I will fix in the next update.
