### ISSUE TITLE
"Enable script injection" breaks functionality of the alternativeto.net

### ISSUE THREAD

**Issue by slrslr** [sereneblue/chameleon#151]
Hello, on https://alternativeto.net/software/clonezilla/ when i go to Chameleon Options / Script Injection Options / and tick "Enable script injection", reload page, it does not show the menu when i click to "any license" or "all platforms" - these links are big and are on the fold of 1st page..

When i disable option "Enable script injection" and reload page, it start working.

If interested, my other Chameleon settings are [here](https://pastebin.com/eXg4uJFW)

**Comment by sereneblue** [comment]
The issue is caused by the spoof client rects option. I'm not sure why it's causing the site to break, but I'll take a look at it.
