### ISSUE TITLE
Timezone spoofing

### ISSUE THREAD

**Issue by Goldinium** [sereneblue/chameleon#152]
Spoof timezone doesn't work
and also add a font spoofing/changer function
Many thanks

**Comment by sereneblue** [comment]
Please the timezone spoofing section on this page: 
https://github.com/sereneblue/chameleon/wiki/Options

If the above doesn't apply to your issue, feel free to expand on your comment.

Font spoofing has been mentioned before and will be implemented in the future although it's not a high priority item at the moment.
