### ISSUE TITLE
Disabling WebSockets Prevents To Log On Unseen.is

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#153]
## Current Behavior
I can't log in unseen.is when in "Script Injection Option" Disable WebSockets is checked.
I can log in as soon as I uncheck it.

Strangely, when I block WebSocket with the FF addon [Policy Control](https://addons.mozilla.org/en-US/firefox/addon/policy-control/), I can log on unseen.is. 

## Relevant settings

_Enable Script injection_ checked
_Disable WebSockets_ checked.

## Context (Environment)

Chameleon v/0.11.7 on FF 66, W7.

**Comment by sereneblue** [comment]
Thanks for creating this issue. I'm curious about how it's implemented in Policy Control.

**Comment by sereneblue** [comment]
Is the issue you're referring to the unsupported browser popup that appears when logging in?

**Comment by Kraxys** [comment]
> 
> 
> Is the issue you're referring to the unsupported browser popup that appears when logging in?

Yes tha's it.

**Comment by sereneblue** [comment]
Have you tried using Policy Control on a WebSocket demo site? It doesn't seem to work for me, both block all or block 3rd party. It did give me an idea though; perhaps it's best to add a similar option to Chameleon so that users have some flexibility with WebSockets.

**Comment by Kraxys** [comment]
> 
> 
> Have you tried using Policy Control on a WebSocket demo site?

No. maybe I should have. I just examinated the Policy Control's log (with _WebSocket_ set to _Block All_:
* With _Disable Websocked_ checked in Chameleon:  I can't log on unseen.is and there is nothing in Policy Control's logs.

*  With _Disable Websocked_ checked in Chameleon: I can log on unseen.is and some websocket blocking is displayed in Policy Control's log.

Do you know a test site for websockets ??

**Comment by sereneblue** [comment]
https://www.websocket.org/echo.html
This page should show "Uh-oh, the browser you're using doesn't have native support for WebSocket. That means you can't run this demo."

https://bestvpn.org/html5demos/web-socket/
This page should show "Not connected."

I used `Block all` for Websockets in Policy Control.

**Comment by Kraxys** [comment]
Thanks for the sites.

With Disable WebSocket unchecked in Chameleon and WebSocket set to Block all in P.C:
1) On websocked.org I get "This browser supports WebSocket" and nothing  on P.C.'s logs.
2) On bestvpn.org I get "session closed" (in a red rectangle) and a a P.C.'s websocket log. 

With Disable WebSocket checked in Chameleon WebSocket set to Block all in P.C:
1) On websocked.org: "Uh-oh" message
2) On bestvpn.org:  "Not connected"
In each casen no logs in P.C.

With Disable WebSocket unchecked in Chameleon and WebSocket set to Allow all in P.C:
1) On websocked.org: "This browser supports WebSocket"
2) On bestvpn.org:  "Socket open"

**Comment by sereneblue** [comment]
I tested it with only one of the addons enabled at a time. 

With Chameleon, the WebSocket object is overwritten, so websites can't use it because the functionality is gone. If your goal is to completely block WebSocket connections from being created that's the behavior you'd want. However, this will break many websites.

Policy Control doesn't inject itself into the browsing page like Chameleon. Instead, it filters requests based on the host of the tab and your preferences. It operates like a bouncer for network requests. This would let websites think that WebSockets are supported, but the connection would fail. This is the better implementation. I'll address this in a future update.
