### ISSUE TITLE
Script injection function not working after re-open firefox

### ISSUE THREAD

**Issue by yujab1** [sereneblue/chameleon#157]
hello, when i close firefox and open it again , all the option that related to script injecton such as screen size and time zone return to defualt value (i have check on panopticlick.eff.org and ipleak.net ) and i should un-tick and tick again script injection option on setting to work correctly!

**Comment by sereneblue** [comment]
Thanks for catching this. It looks like I may have broken something in the latest version. I will push an update as soon as I resolve this issue.
