### ISSUE TITLE
incorrect negativen - and positive + sign for time zone

### ISSUE THREAD

**Issue by yujab1** [sereneblue/chameleon#158]
v0.11.9

hello, you have write incorrect value for time zones
for example when i  set my time zone to america/ phoenix it should set to -420 but in your addons set to +420 !
all the time zone have this problem and are incorrect. west of greenwich should be negative (-) number and east of that should be positive (+) number.

**Comment by sereneblue** [comment]
I assume you're referring to the timezone offset returned by `getTimezoneOffset`? 

It's working as intended:

> Note that this means that the offset is positive if the local timezone is behind UTC and negative if it is ahead. For example, for time zone UTC+10:00 (Australian Eastern Standard Time, Vladivostok Time, Chamorro Standard Time), -600 will be returned.

More info can be found here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset
