### ISSUE TITLE
TimeZone Issue

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#159]
## Current Behavior
I have selected TimeZone according IP, and presently use a VPN servder in Prague.
ipapi.co gives Time Zone	Europe/Prague (+0200)
add0n.com/spoof-timezone.html  gives 
Main Frame DateTimeFormat method:	Europe/Paris
OffsetMethod/Iframe  DateTimeFormat method:	Europe/Prague

## Expected Behavior
Main Frame DateTimeFormat method sould be:	Europe/Prague

## Context (Environment)

Chameleon v. 0.11.9 on FF 66 W7

**Comment by sereneblue** [comment]
Hm, on that page it seems Chameleon isn't spoofing `Date method (inline)`, `DateTimeFormat`, and both the values listed under `iFrame`. I'll need to spend some time to resolve this issue.

I believe this may also be related to #134.

**Comment by sereneblue** [comment]
I've found the cause of the issue. When I changed the injection method to handle pages that gave a CSP issue, the injected code isn't immediately run. I've improved Chameleon's code to handle this.

It may be possible for pages that use CSP to get the original values depending on how quickly the scripts on the page are executed.

**Comment by Kraxys** [comment]
> 
> 
> I've found the cause of the issue. When I changed the injection method to handle pages that gave a CSP issue, the injected code isn't immediately run. I've improved Chameleon's code to handle this.
> 
> It may be possible for pages that use CSP to get the original values depending on how quickly the scripts on the page are executed.

Surely related. A few days ago I began to see how Chameleon behaves with option such as faking Screen Size or Faking IP, when ResisFingerprinting was checked at the same time
.
Concerning Screen Size, I think I found something interesting I will speak aboit later.
Concerning faking time, with a VPN server in Prague, I get :

1. Date method:	Mon Apr 22 2019 23:53:24 GMT+0200 (Central European Summer Time)
2. Date method (with delay):	Mon Apr 22 2019 21:53:26 GMT+0200 (Central European Summer Time)
2. Date method (inline):	Mon Apr 22 2019 23:53:24 GMT+0200 (Central European Summer Time)
3. DateTimeFormat method:	**UTC**
-> Server and PC time difference:	1436500 (in msecs)
-> Offset method:	-2 (in hours)
iFrame
1. Date method:	Mon Apr 22 2019 23:53:24 GMT+0200 (Central European Summer Time)
2. DateTimeFormat method:	Europe/Prague

So you see, only the UTC part (plausibly set by RFP) is wrond. All the the rest is OK.

**Comment by sereneblue** [comment]
If you're using RFP, you will get some interesting results when spoofing the timezone. If you refresh the page multiple times, you might see different values for the dates shown (either the spoofed value or the UTC value). This only applies to v0.11.6-v0.11.10; it's related to this issue.

I don't recommend using RFP and spoofing some things with script injection. Ideally, It should be either one or the other.
