### ISSUE TITLE
Video playing issue

### ISSUE THREAD

**Issue by Heri0n** [sereneblue/chameleon#160]
## Current Behavior
Video are no more playing on https://www.boursorama.com/videos
Strangely, this happens as soon as Chameleon is activated, even without any option ticked.  When I disable Chameleon, the videos can be played again 

## Relevant settings
Chameleon activated and no more.

## Context (Environment)
I'm using FF 66 on Windows 8.1

**Comment by sereneblue** [comment]
I'm not able to replicate this issue with v0.11.9 and FF67. Were you running any other extensions at the time? Can you replicate this issue? If you're able to replicate it, can you post the exported settings and any relevant error messages you find in the developer console when you load the page?

**Comment by Kraxys** [comment]
I could replicate but it's a cookie issue, not really a Chameleon's one. For being played, the site www.ultimedia.com has to send a cookie. Cookie settings such as Block All, Block Third Party or even Block Unvisited Third Party prevent the video to be played. Probably in unchecking all options in Chameleon you forgot the "cookie" part...
For playing videos on this site you have to set cookie to "Allow All", or to "Block trackers Only".
It's a bit harsh that even blocking only cookies relative to non visited 3rd party prevent video playing, and probably it doesn't comply to RGPD.
Examining further what happened, I saw that, cookie permission being set  to "reject trackers", www.ultimedia.com do send a cookie as expected, but then Cookie AutoDelete is not able to clear this one after all tabs relative to boursorama.com have been closed. If it's really the case, it's more a CAD issue.
Finally I found an issue relative to Chameleon: On one of my FF profile, I can't log on the site when TimreZone is spoofed. But it may be to to some addon's interaction, and I have ti invstigate further.

**Comment by Heri0n** [comment]
Thanks Kraxys for having investigated my issue so deeply !!

**Comment by Kraxys** [comment]
> 
> 
> Thanks Kraxys for having investigated my issue so deeply !!

Well, it's yet a bit strange. Here is what I get:

[Zero Cookie](https://postimg.cc/t7PbwD0Z)

As you can see, the sites www.boursorame.com and ultimedia.com are each setting a cookie (64KB and 48 KB respectively), but their number is **0**. It's not a Chameleon thing, but it's intriguing me. I had never seen that  before.

**Comment by sereneblue** [comment]
Thanks for the investigative work @Kraxys. Feel free to create an issue for the website giving you trouble with timezone spoofing.
