### ISSUE TITLE
Add CSS Exfil Protection?

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#161]
Summary:
" A method is detailed - dubbed CSS Exfil - which can be used to steal targeted data using Cascading Style Sheets (CSS) as an attack vector.  Due to the modern web's heavy reliance on CSS, a wide variety of data is potentially at risk, including: usernames, passwords, and sensitive data such as date of birth, social security numbers, and credit card numbers.  The technique can also be used to de-anonymize users on dark nets like Tor. Defense methods are discussed for both website operators as well as web users, and a pair of browser extensions are offered which guard against this class of attack."

Full article here: https://www.mike-gualtieri.com/posts/stealing-data-with-css-attack-and-defense

Here is the test to see if you are protected:
https://www.mike-gualtieri.com/css-exfil-vulnerability-tester

I was wondering if chameleon could add something to deal with such attack.

There is already an extension: https://addons.mozilla.org/en-US/firefox/addon/css-exfil-protection/ but I would rather avoid adding yet-another-addon that does one thing, thus I opened this ticket. 

Maybe @sereneblue you can make chameleon block such attack?

The addon is under MIT/X11 License and source is here: https://github.com/mlgualtieri/CSS-Exfil-Protection

Basically it has a toggle/untoggle option, it is not granular like NoScript or PrivacyBadger, so maybe implementing this won't be hard?

I hope you will consider this, however regardless of your decision thank you again for your work on chameleon!

**Comment by sereneblue** [comment]
Good suggestion. Although I'm trying not to add new features to Chameleon, the source code is freely available so it shouldn't take too long to add it. There's a backlog of bugs that I'd like to address first before I work on this feature.

**Comment by Kraxys** [comment]
@WPFilmmaker 
Meanwhile, you may be interested by the addon [**CSS Exfil Protection**](https://addons.mozilla.org/en-US/firefox/addon/css-exfil-protection/)

**Comment by sereneblue** [comment]
Quick status update, I've done some work on this issue. It's straightforward to add support for this but I ran into an issue with CSP. It passes 2/4 of the tests [here](https://www.mike-gualtieri.com/css-exfil-vulnerability-tester). I'd rather not modify the CSP headers while [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1462989) is still a bug in Firefox; sadly, I don't think an alternative solution exists.

**Comment by WPFilmmaker** [comment]
@sereneblue thanks for the update and for implementing it, are you following that's bugs updates? It seems comments will be disabled, any chance you can finish the work once they fix that?

**Comment by sereneblue** [comment]
Yeah, definitely. Once that bug is fixed, I'll resume work on this issue.

**Comment by WPFilmmaker** [comment]
@sereneblue it seems that https://bugzilla.mozilla.org/show_bug.cgi?id=1462989 was resolved and will be released with FF 77. So finally chameleon can have css exfil protection too 👍

**Comment by WPFilmmaker** [comment]
@sereneblue FF 77 is out :D

**Comment by sereneblue** [comment]
@WPFilmmaker I'll take another look at this issue again soon.

**Comment by sereneblue** [comment]
@WPFilmmaker This feature has been introduced in v0.21.2.
