### ISSUE TITLE
beautiful extension 

### ISSUE THREAD

**Issue by xzj8b3** [sereneblue/chameleon#162]
A reset option to the defaulth options in case of problems and reset would be convenient!!!

If possible

**Comment by sereneblue** [comment]
Thanks, this is pretty easy to implement. It'll be in the next update.

**Comment by xzj8b3** [comment]
> Thanks, this is pretty easy to implement. It'll be in the next update.

Thank you very much, so much for safety and to avoid messes to us newbies, but I see reading Wiki works well ... then gradually I will study every option!
