### ISSUE TITLE
[feature suggestion] augmented ip spoofing

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#163]
With geo/language fencing/sensing via ip header and other such nonsense deployed by a variety of domains I am obliged to frequently switch the custom IP.

Thus, it would be handy to be able to store more than one custom IP, preferably with an alias to recall with IP is which.

One step further would be to designate a spoofed IP header to particular domains.

**Comment by sereneblue** [comment]
I can add this as an option to the whitelist editor.
