### ISSUE TITLE
Add a string to disable DNS-over-HTTPS to "Copy link to about:config entry" options?

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#164]
DNS-over-HTTPS is a safety measure which Mozilla wants to implement in conjunction with cloudfare. I am not an expert but I don't trust it and seems I am not alone: https://ungleich.ch/en-us/cms/blog/2018/08/04/mozillas-new-dns-resolution-is-dangerous/

In 66.0.2 is turned off however Mozilla seems to want to enable it by default in the future (https://www.ghacks.net/2019/04/10/mozilla-still-on-track-to-enable-dns-over-https-by-default-in-firefox/)

@sereneblue and others what do you think?

in this page you can see what cloudfare retains for 24h: https://developers.cloudflare.com/1.1.1.1/commitment-to-privacy/privacy-policy/firefox/

To disable it when it will be enabled one has to set network.trr.mode to 5, I think it would be good adding such string to the list of "Copy link to about:config entry".

**Comment by sereneblue** [comment]
Wow, that's interesting. I can't say I'm surprised; just a bit concerned about the increased centralization of DNS queries to Cloudflare. Most users are not technical so this was probably the best way to force users to use DoH. Fortunately, power users have the option to configure this. 

I'll include it in the next Chameleon update, thanks for creating this issue!
