### ISSUE TITLE
Display glitches in popup menu

### ISSUE THREAD

**Issue by ReporterX** [sereneblue/chameleon#168]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

![Display glitches](https://user-images.githubusercontent.com/8235338/56413034-ae57b980-62b8-11e9-8b26-4c470f7dea40.jpg)

Not a big deal, but some minor glitches: 
The scrollbar hides part of the checkboxes.
It is a bit out of alignment. The checkbox is slightly higher than the item text.
It is a bit hard to find the right checkbox for the item, due to minor glitch and a bit far from the text. It would be better if lines are added. Something like: 

text 　　　　　 [ ]
----
text 　　　　　 [ ]
----
text 　　　　　 [ ]
----

or 

text 　　　　　 [ ]
text 　　　　　 [ ]
text 　　　　　 [ ]
text 　　　　　 [ ]
text 　　　　　 [ ]
----
text 　　　　　 [ ]
text 　　　　　 [ ]
text 　　　　　 [ ]
text 　　　　　 [ ]
text 　　　　　 [ ]
----

(one line every 5 items)

Thank you.

**Comment by sereneblue** [comment]
Thanks for the suggestion. I've updated the CSS to add some more spacing, alternating row colors and some color when you're hovering over a profile. The scrollbar is a bit of a pain, but I think with the updated CSS, it's manageable.

![export](https://user-images.githubusercontent.com/14242625/56449535-9009b200-62e8-11e9-98a8-10613bf165a8.png)
