### ISSUE TITLE
"Spoof Accept & Accept-Encoding headers" - using non-default value

### ISSUE THREAD

**Issue by ReporterX** [sereneblue/chameleon#169]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

The default value of content types in Firefox is: 
`text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`

When "Spoof Accept & Accept-Encoding headers" is checked, it is slightly different than the default: 
`text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`

I believe it is the best to use the default to reduce the number of entropy (anti-fingerprinting).

**Comment by sereneblue** [comment]
Thanks for pointing this out. When Firefox 65 was released, the accept header value was changed to `text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`. It seems Mozilla backtracked on this change with Firefox 66.

This will be fixed in the next update.
