### ISSUE TITLE
Option to exclude specific UAs

### ISSUE THREAD

**Issue by kekkc** [sereneblue/chameleon#17]
Hi,

first of all: huge thanks for this addon. The first that is technically able to replace RAS ;)

The only thing I missed was the ability to exclude some UAs. E.g. I only want to use desktop Firefox UAs for Windows & Linux (I had issues with some sites if they think I use Chrome).

Offtopic: RAS implemented profiles. All values (e.g. screen resolution, UA, x-forwarded-for) were changed periodically. So X-Forwarded-For followed was not changed for every image & request, but it followed the rule specified under "change periodically" and used the same entries until the period was over. Is Chameleon following this, too, or are all values changed for every single header request?

Offtopic2: X Origin Policy: this works great, but of course Chameleon can only implement it itself without changing the about:config setting. Maybe some tooltip should show that the about:config setting should be the default value, otherwise Chameleon has no chance and the setting in Chameleon takes no effect. Unfortunately, we don't get an WexExtension API ( https://bugzilla.mozilla.org/show_bug.cgi?id=1414078 ). However, it might get easier to get the "base domain" with this one: https://bugzilla.mozilla.org/show_bug.cgi?id=1315558

**Comment by sereneblue** [comment]
Excluding user agents is a good idea. You could also use a whitelist profile to mitigate the issue.

At the moment, some values are persistent (user agent, screen resolution), but others like X-Forwarded-For are changed for every request. I'll make this more consistent.

Thanks for the suggestion about the X Origin Policy. I'll add something to the UI in a future update.

**Comment by sereneblue** [comment]
v0.6.10 adds the ability to exclude useragents. I've also added a note for the X Origin Policy. I haven't updated the wiki yet so I'll try to do that ASAP. Thanks again for the feedback!
