### ISSUE TITLE
Chameleon Firefox Addon malicious redirecting?

### ISSUE THREAD

**Issue by Chindow** [sereneblue/chameleon#171]
When I use Chamelon on Firefox and I want to connect to a http website I am redirected to a fake website of my provider?  
![Bildschirmfoto vom 2019-04-19 16-30-41](https://user-images.githubusercontent.com/11065421/56428789-f1b62600-62c0-11e9-906b-9c733a0af714.png)
It happens only when clicking http websites. My provider argues that there is not any redirecting like this. When I deactivate Chameleon is doesn't happen. 
Therefore I think that it is a malicious redirecting code in Chameleon.

**Comment by sereneblue** [comment]
I can assure you there isn't any malicious redirecting code in Chameleon. 

Are you using any other extensions?
What links are you clicking?
Can you post your settings file?

**Comment by Chindow** [comment]
I called my provider again. It is an original message from my provider and it only appears it the case I described above. But I think that it it a false report and not the fault of Chameleon.

Chameleon is a great addon.

**Comment by sereneblue** [comment]
[This](https://www.delphipraxis.net/200030-vodafone-meint-ich-habe-einen-virus-2.html) thread may be helpful. I'm not sure if it's a tracking option that you've enabled that is triggering the redirect. It sounds like a DNS issue if Vodafone is your ISP.
