### ISSUE TITLE
Add a string to disable Hyperlink Ping Tracking to "Copy link to about:config entry" options?

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#172]
Seems Mozilla is planning new things... (like they did for #164).

from: https://www.ghacks.net/2019/04/20/mozilla-plans-to-enable-hyperlink-ping-tracking-by-default-in-firefox/

--What is HPT?--
"Ping is a new attribute that can be added to links to send information to another resource. Here is an example: <a href="https://www.ghacks.net/ ping="https://www.example.com/">This</a>

When a user clicks on the Ghacks Link, Example.com is notified that the click happened. It is possible to notify one or multiple resources about the link click."

--What is bad about it?--

Ping is used to track link clicks. The nature of how that is done is not transparent to users who click on links, as the ping attribute is not shown and links with pings are not highlighted when a user hovers over the link in the browser."

FF 66 has this disabled however it seems they plan on making it by default and t seems that Google removed the option to turn it off...

As per title could you add a string to "Copy link to about:config entry" so that when it is enabled users can easily disable it?

**Comment by sereneblue** [comment]
This is already in Chameleon.

![export](https://user-images.githubusercontent.com/14242625/56459924-eae2ee00-6368-11e9-9b7d-7f6b0f98fcea.png)

I'm not sure if this option will remain when hyperlink ping tracking is enabled by default. If not, I'll remove it from the list and work on blocking it with Chameleon.
