### ISSUE TITLE
Can I add Japanese to this add-on language?

### ISSUE THREAD

**Issue by Shitennouji** [sereneblue/chameleon#173]
Thank you for this add-on.
It works as expected.
For me, it is one of my favorite addons.

by the way,
This add-on is not available in Japanese. It is a barrier for Japanese who dislike applications in different languages.
If possible, I will cooperate in translating into Japanese.

**Comment by sereneblue** [comment]
Thanks for the kind words and offering to translate Chameleon!

I do plan to work on supporting multiple languages in the UI. There's some work I'll need to do first. Once everything's setup, I'll add a link to the readme and will tag you in this issue.

**Comment by Shitennouji** [comment]
I will be happy to help you.
By the way, soon I will go on vacation for about 20 days.
In the meantime, it can not respond because it performs "Digital Detox".
If you are ready, please do not hesitate to contact me.
See you later.

**Comment by sereneblue** [comment]
There's no rush, I still have plenty to work on and translations can be rolled out when they're completed. ;)

Enjoy your vacation!

**Comment by sereneblue** [comment]
@Shitennouji

Hope you enjoyed your vacation! I've done some work to get Chameleon ready for translations. It's almost ready, just a few more things I need to work out. Do you think the about:config part should be translated as well? This section might need to be updated to make it more clear about what to do with each option.

![image](https://user-images.githubusercontent.com/14242625/59139916-dc768300-8964-11e9-9586-517033eb1f7e.png)

**Comment by Shitennouji** [comment]
Hi, It’s been a while!

Translate to Japanese will help you with everything that needs translation.

As translation work in "The Crowdin project" has been experienced, it is OK.
https://crowdin.com/translate/chameleon/12/en-en
Since I am in regular work, the translation work will take about a week.
Until reply.

**Comment by sereneblue** [comment]
@Shitennouji Thanks for translating Chameleon! I'll try to have an update out soon, might need a little polish for the UI.
