### ISSUE TITLE
"Enable script injection" breaks functionality of the washingtonpost.com comments

### ISSUE THREAD

**Issue by linksky56** [sereneblue/chameleon#175]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [yes ] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed

## Current Behavior
When i check Enable script injection, the comments won't load.
https://www.washingtonpost.com/opinions/2019/04/28/pelosi-was-right-about-impeachment/?noredirect=on&utm_term=.b526ce7b6eb3

When i uncheck the box, the comments load fine.
I tried whitelisting washingtonpost.com and the comments still would not load.
The comments will only load when Enable script injection is disabled.

Thanks in advance, for any help you can give me.

**Comment by sereneblue** [comment]
Hm, this is a bit interesting. It might possibly be a CSP issue. I'll give this a deeper look soon.

**Comment by sereneblue** [comment]
I've spent quite some time trying to isolate the cause of this issue. It seems to be an issue with how injection is handled in two distinct places in the code (the CSP workaround and injecting into iframes). I'm still not sure why it's causing issues, so I'm going to take a look at improving the whitelist.

**Comment by sereneblue** [comment]
@linksky56 This issue is difficult to reliably reproduce; sometimes comments load and sometimes they don't. I've updated Chameleon's whitelist feature so it won't try to inject anything if you add a url to the whitelist. Let me know if you're still experiencing issues with the next update, v0.12.3.

**Comment by linksky56** [comment]
I've updated Chameleon to v0.12.3.
Still experiencing issues, comments still won't load.

**Comment by sereneblue** [comment]
@linksky56 Can you export your settings?Also, can you post any error messages that you see in the developer console after you refresh the page?

**Comment by linksky56** [comment]
Can you export your settings?
 chameleon_settings_1558317291942.json

{
  "excluded": {
    "win": [
      true,
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      true,
      true,
      true,
      false,
      false,
      false
    ],
    "mac": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "linux": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "ios": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "android": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "all": [
      true,
      false,
      false,
      false,
      false
    ]
  },
  "headers": {
    "blockEtag": false,
    "disableAuth": false,
    "disableRef": false,
    "enableDNT": false,
    "refererXorigin": 0,
    "refererTrimming": 0,
    "spoofAccept": false,
    "spoofAcceptLang": false,
    "spoofAcceptLangValue": "",
    "spoofSourceRef": false,
    "spoofVia": false,
    "spoofViaValue": 0,
    "spoofXFor": false,
    "spoofXForValue": 0,
    "upgradeInsecureRequests": false,
    "viaIP": "",
    "viaIP_profile": "",
    "xforwardedforIP": "",
    "xforwardedforIP_profile": "",
    "useragent": "Mozilla/5.0 (Windows NT 10.0; rv:60.0) Gecko/20100101 Firefox/60.0"
  },
  "ipRules": [],
  "settings": {
    "customScreen": "",
    "enableScriptInjection": true,
    "interval": -1,
    "limitHistory": false,
    "minInterval": 12,
    "maxInterval": 18,
    "notificationsEnabled": true,
    "protectKeyboardFingerprint": false,
    "protectWinName": false,
    "screenSize": "default",
    "spoofAudioContext": false,
    "spoofClientRects": false,
    "timeZone": "ip",
    "useragent": "random_win",
    "useragentValue": "",
    "webSockets": "allow_all"
  },
  "version": "0.12.3",
  "whitelist": {
    "enabled": true,
    "defaultProfile": "none",
    "urlList": [
      {
        "id": "5k2z",
        "domains": [
          {
            "domain": "www.washingtonpost.com",
            "re": false,
            "pattern": ""
          }
        ],
        "lang": "",
        "profile": "default",
        "spoofIP": "",
        "options": {
          "auth": false,
          "ip": false,
          "ref": false,
          "timezone": false,
          "websocket": false,
          "winName": false
        }
      }
    ]
  }
}



Also, can you post any error messages that you see in the developer console after you refresh the page?

Error: Permission denied to access object        embed.js:10:5656

This also appears beneath/with the error message sometimes:
PB Debug: Fired comments.showComments:[object Object]       a5a29d0f77.js:359:443

Hope the above info, is what you are asking for?
As you can see, I'm not very computer literate.

**Comment by sereneblue** [comment]
Thanks, it seems I made a typo. Hopefully v0.12.4 resolves this issue for you.

You created an issue on Github, use Firefox, and care about privacy; that sounds like a computer literate person to me. ;)

**Comment by linksky56** [comment]
Yeah!!!!! It Works! Thank you!

Now i need to go delete my old review and update with new more accurate review.
 
Thanks again
