### ISSUE TITLE
[REQUEST] Adding Time Zones and Languages

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#176]
This addon really gets better and better!  :)

Now, could you add the following Time Zones and Languages in the Whitelist/IP Rules section of Chameleon's GUI:

**1) Time Zones**:
America/Mexico_City (-0500) 
America/Toronto (-0400)
Atlantic/Reykjavik (+0000) 
Europe/Rom**a** (+0200)     EDITED
Europe/Madrid (+0200)
Europe/Paris (+0200)
Europe/Oslo (+0200)
Europe/Stockholm (+0200)
Europe/Copenhagen (+0200)
Europe/Luxembourg (+0200)
Europe/Zurich (+0200) 
Europe/Prague (+0200)
Europe/Belgrade (+0200)
Europe/Bucharest (+0300)
Europe/Riga (+0300)
Europe/Chis**i**nau (+0300)   EDITED
Africa/Cairo (+0200)
Asia/Jerusalem (+0300)  
Asia/Istanbul  (+0300)
Asia/Singapore (+0800) 
Australia/Melbourne (+1000) 

**2) Languages:** 
Canada         Languages	en-CA,fr-CA,iu
Egypt            Languages	ar-EG,en,fr
Singapore    Languages cmn,en-SG,ms-SG,ta-SG,zh-SG
Luxembourg Languages	lb,de-LU,fr-LU

Also, it would be convenient that the IPv4 ranges could be indicated as _a.b.c.d - e.f.g.h_ too, because when there are a few consecutive IP (eg 10) the user has either to derive the CIDR notation or to write the IPs one by one.

Version currently used: 0.12.0

EDIT:

0) For Languages it's more complicated than I though. For example, when using a russian VPN servers, ipapi.co says _Languages ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,my_, but when I use a russian FF portable, ip-check.info says the languages sent in the header are _ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3_.
So maybe, what I wrote in my second section above is totally useless.

1) For TimeZone, there is the problem of summer ws winter time... Most (all?) European countries have different time zone in winter an summer. It seems that winter time is summer time -1 which is logical, but I don't know whether all UE/European countries have adopted the summer/winter time zone system or not. And there is talk that this system will be removed soon. But maybe some countries will then stick on "winter time" and others on "summer time"... So it's a bit messy.

2) I forgot this one, particularly important because virtually all vpn providers provides servers there:
**Europe/Amsterdam (+0200)**  (Summer).  Winter time is +0100

There are many contries in the UE, even more in Europe, and each of them is hosting vpn/proxies servers from a provider from an other... I will gradually complete the TimeZone list:
Europe/Vienna (+0200) (Summer)  -  Winter +0100
Europe/Brussels (+0200) (Summer)  -  Winter +0100
Europe/Sofia (+0300) (Summer)   - Winter +0200
Europe/Zagreb (+0200) (Summer)   - Winter +0100
Europe/Tallinn (+0300) (Summer)   - Winter +0200
Europe/Helsinki (+0300) (Summer)   - Winter +0200
Europe/Athens (+0300) (Summer)   - Winter +0200
Europe/Budapest (+0200)(Summer) - Winter +0100
Europe/Dublin (+0100)(Summer) - Winter à+0000
Europe/Vilnius (+0300) (Summer)   - Winter +0200
Europe/Warsaw (+0200) (Summer)  -  Winter +0100 
Europe/Lisbonn (+0100)(Summer) - Winter à+0000
Europe/Bratislava (+0200) (Summer)  -  Winter +0100
Europe/Tirana (+0200) (Summer)  -  Winter +0100     NB: ipapi.co says "tiran**e**"
Europe/Ljubljana (+0200) (Summer)  -  Winter +0100
Europe/Kiev (+0300) (Summer)   - Winter +0200
Europe/Sarajevo (+0200) (Summer)  -  Winter +0100

**Comment by sereneblue** [comment]
I forgot to update the IP rules dropdown with the new timezones. Thanks for catching that. I'll also update some of the timezone names. I'm assuming `Europe/Roma` is `Europe/Rome`?

For the languages, yes it's a bit complicated. `English (Canada)` is already an option. The others, I'll need to do some research to find what values are used for them.

I'll update the UI for the IP rules to make it easier to display the IP range.

For the summer/winter time, are you referring to Daylight Saving Time?

**Comment by Kraxys** [comment]
> 
> 
> I forgot to update the IP rules dropdown with the new timezones. Thanks for catching that. I'll also update some of the timezone names. I'm assuming `Europe/Roma` is `Europe/Rome`?
>
Yes. 

> For the summer/winter time, are you referring to Daylight Saving Time?
Yes, That's it. I forgot the right English denomination.
> 

> I'll update the UI for the IP rules to make it easier to display the IP range.
> 
Thanks.

**Comment by sereneblue** [comment]
I'm not sure what's the 'correct' configuration for the locales you mentioned. Chrome and Edge have a dynamic `accept-language` header that change depending on how the locales are set up.

If you can find users with those locales, feel free to comment on this issue so that I can add them. If you're up to it, you can edit [this](https://github.com/sereneblue/chameleon/blob/master/src/js/data.js#L218) file using the online editor and submit a pull request. 

I've updated Chameleon to handle Daylight Saving Time [ca7e0334c43548dfe9deff0f4fe7861b392bb1c4].
