### ISSUE TITLE
[Bug] Chameleon disable random the spoof and via javascript will detect original values of OS/browser

### ISSUE THREAD

**Issue by koalaverde** [sereneblue/chameleon#177]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Expected Behavior
I expect spoofing of browser and hidding my original values.
This addons have a big bug, sometimes without any reason deactivate the javascript spoof, I add the photos, chameleon is active, spoof my browser but the site can detect via javascript original SO and browser, it's a big problem this. picture:

https://imgur.com/wisOh5O
https://imgur.com/G4aNRnd

I hope you can fix this problem. I see this bug from long time, usually i check many times in the sites if the spoof working e sometimes i find that do not working via javascript.

## Current Behavior
Chameleon show my original browser and os values via javascript in some sites

## Relevant settings
Javascript injection is ebables and sometimes without any reason do not work.
"Script injection" is active as you can see from the popup that shows the browser resolution, with "Script injection" disabled the popup does not show the browser resolution.

## Context (Environment)
Firefox 66.0.3 Windows 7 32 bit Chameleon 0.12 but this bug is in older version of chameleon too.

**Comment by sereneblue** [comment]
Thanks for opening an issue. Script injection is necessary for spoofing the screen resolution so if it's not checked, it won't show the spoofed resolution in the notification.

Can you export your settings (on the about tab) and post it here? 
Can you reliably reproduce this issue?
Are you running any other extensions that may conflict with Chameleon?

**Comment by koalaverde** [comment]
Hi

I reinstalled Firefox with chameleon to solve this problem i have not the old setting.

In old firefox (firefox 66.0.3) I had the basic settings with script injection enabled and profile option in resolution no other custom option setted.

In the same browser I had CanvasBlocker of kkapsner activated and I think is this the conflict with chameleon.

Some sites do not recognize the real browser e os values (probably because they don't detect them via javascript) but other site grab the original value bypassing chameleon protection (ip-check.info - http://browserspy.dk/browser.php - https://browserleaks.com/javascript).

I also used ras but with ras this problem was not there and I never noticed that the settings were disabled perhaps because ras saved the settings in about config and therefore always worked.

Currently I have uninstalled CanvasBlocker and at this moment the problem seems to have been solved, I checked all the sites and the chameleon settings are detected.

**Comment by Kraxys** [comment]
> 
> In the same browser I had CanvasBlocker of kkapsner activated and I think is this the conflict with chameleon.
> 
> Some sites do not recognize the real browser e os values (probably because they don't detect them via javascript) but other site grab the original value bypassing chameleon protection (ip-check.info - http://browserspy.dk/browser.php - https://browserleaks.com/javascript).

> Currently I have uninstalled CanvasBlocker and at this moment the problem seems to have been solved, I checked all the sites and the chameleon settings are detected.


Hi,

I'm using Chameleon alongside CanvasBlocker for months, and I never detected the issue you had. I just checked again on ip-check, browserspy and browserleaks, in setting Chameleon to fake Android 6.0.1 with Chrome 73, and spoofing is working as intended. But maybe it's because I have not the same CB settings as you? 

EDIT: On ip-check.info, during a very brief instant,  I saw something else than _Mozilla/5.0 (Linux; Android 6.0.1; N9136 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.90 Mobile Safari/537.36_ for user agant, something beginning with _Mozilla/5.0 (Windows..._ , which is my true OS

**Comment by Thorin-Oakenpants** [comment]
@sereneblue I haven't looked, but does Chameleon use any CSP header injection?

**Comment by sereneblue** [comment]
@koalaverde Perhaps it's a setting that you've toggled in Canvas Blocker that's conflicting with Chameleon? I use CB with Chameleon and I haven't experienced any issues.

@Kraxys Depending on how quickly the page loads, it's possible to obtain your true fingerprint, although in general, this is a non-issue; other extensions and external resources loaded on the page should cover this gap.

@Thorin-Oakenpants Chameleon uses a workaround to get around CSP blocking scripts from being injected. It's not ideal but it's the best practical solution. The headers aren't modified for security reasons.
