### ISSUE TITLE
[REQUEST] Fighting Against "Behavioral Fingerprinting"

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#178]
The way you are typing on your keyboard can be used to fingerprint you (cross browsers, maybe devices...) What is fingerprinted is **you**...
See for example: https://paul.reviews/behavioral-profiling-the-password-you-cant-change/

Currently to my knowledge, only 2 FF addons are able (in some way) to  defeat that: [ScriptSafe](https://addons.mozilla.org/en-US/firefox/addon/script-safe/) and [Behavioral-Keyboard-Privacy](https://addons.mozilla.org/en-US/firefox/addon/behavioral-keyboard-privacy/), but they seem to be abandoned, and moreover B.K.P remains "experimental" and seems to require [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) which itself seems abandoned too...

So I think it would be interesting to add such a feature to Chameleon in the future.

Problem is, I don't know how to test such a feature.... (so that you could just add that in the GUI and pretend it's working, lol).

Chameleon 0.12

**Comment by WPFilmmaker** [comment]
Maybe for reference: https://github.com/vmonaco/kloak

**Comment by sereneblue** [comment]
Sure, this is pretty straightforward to implement. It'll be in the next update.
