### ISSUE TITLE
[feature suggestion] augmented whitelisting

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#179]
I am not comprehending why features have gone into (separate) `ip rules` instead of incorporating such in the whitelisting. 
Commonly I would type a domain into the browser's url bar and not an ip. It would seem cumbersome first having to find out the ip (range) for a particular domain, notwithstanding that ip (range) might change over time for domains.

That aside, I would like to suggest for advanced whitelisting:

1. option for multiple domains, e.g. comma separated. Reason being that the same profile is utilized for various domains and each domain requiring a separate whitelist entry. Being able to add multiple domain entries for one profile would mitigate the number of whitelist entries.

1. As consequence of above, and perhaps in general too, the domain entries in the whitelist should be editable, which currently are not and thus if there is a change to the (multiple) domain(s) it currently requires to delete one whitelist profile and add another one. With an editable domain entry such would improve the workflow.

1. option to set a particular the time zone for a particular domain profile (as available on the `ip rules`)

**Comment by sereneblue** [comment]
IP rules isn't meant for domains. It's the IP rules to be used when you select the IP option for timezone or accept-language spoofing. I'll update the UI to clarify this.

1 & 2, good suggestions. This would require a bit of work to add but it should be in a future update.
3. There isn't a good reason to use a particular timezone with a specific domain. It should be consistent with the timezone you're using globally.

**Comment by n8v8R** [comment]
> IP rules isn't meant for domains. It's the IP rules to be used when you select the IP option for timezone or accept-language spoofing. I'll update the UI to clarify this.

Sorry, but I still do not get this (logic) or how the IP rules are to be utilized.

timezone spoofing is is within the Script Injection Options and I am not sure what the _IP option_ is meant to be in this conjunction?
What `IP (range)` is supposed is to be entered - Header IP (Via & X-Forwarded For)?
___
> 3. There isn't a good reason to use a particular timezone with a specific domain. It should be consistent with the timezone you're using globally.

From my perspective the logic chain reads - timezone is to match the node's geo IP (real or header spoofed or VPN/proxy). Hence, if a particular node IP (profile) is assigned to a particular domain than the timezone should match said IP or else it could trigger all sorts of confusion on server that compares the node's (geo) IP with the timezone.

**Comment by Kraxys** [comment]
> 
> 
> > IP rules isn't meant for domains. It's the IP rules to be used when you select the IP option for timezone or accept-language spoofing. I'll update the UI to clarify this.
> 
> Sorry, but I still do not get this (logic) or how the IP rules are to be utilized.
> 
> timezone spoofing is is within the Script Injection Options and I am not sure what the _IP option_ is meant to be in this conjunction?
>
The Chameleon feature consisting in adjusting TimeZone and/or Language according to the proxy/vpn used is not perfect. There are some errors. For exempl, some proxies I use in Romania are declared "German" by the Chameleon internal mechanism, I get German language and mostly I get for TimeZone GMT+2 instead of GMT+3. The IP rules in the whitelist section is just to correct that:  No, with the knowledge of the ips my romanian proxy use, I can force Chameleon to use GMT+3 for TimeZone when I use one of these IP. In fact, this new feature in Chameleon is the fulfillment of a request  #134 I made some weeks ago

**Comment by n8v8R** [comment]
@Kraxys thanks for the explanation, now it is clear what is for. It is not for me though since the local ISP is changing the connection ip every 24 hrs and from different ip ranges and the VPN/proxies service being utilized is not providing ip (ranges) but endpoint domains that need to be resolved - but that is another matter.

**Comment by sereneblue** [comment]
Thanks for the explanation @Kraxys.

**Comment by n8v8R** [comment]
@sereneblue Thank you for the implementation! 

option to set a particular time zone for a particular domain profile (as available on the ip rules) is not planned though?

**Comment by sereneblue** [comment]
Yes, the timezone per profile feature won't be implemented.
