### ISSUE TITLE
Youtube breaks

### ISSUE THREAD

**Issue by sereneblue** [sereneblue/chameleon#18]
Seems the user agent causes some issues with Youtube.

https://github.com/dillbyrne/random-agent-spoofer/issues/306

**Comment by sereneblue** [comment]
> document.registerElement is not a function

Firefox doesn't support [custom elements](https://caniuse.com/#feat=custom-elements).

**Comment by GLLM** [comment]
FYI : when I set dom.webcomponents.customelements.enabled to true preference in about:config, the site seems to work again !
as written in the link displayed in your previous post.

**Comment by sereneblue** [comment]
Hm, I'm still getting an issue with that option enabled. Try using any of the Linux Chrome profiles. Does your solution still work?

**Comment by GLLM** [comment]
It did 2-3 attempts with different Linux + Chrome/Chromium profiles and it works OK.
The video loads first and later only the other HTML blocks do.

:)

**Comment by TheDevKiller** [comment]
I have the same problem
http://i.imgur.com/9ZCfSdo.png

**Comment by sereneblue** [comment]
It's the Chrome profile that's causing issues. The best option for now is to create whitelist Youtube.

**Comment by sereneblue** [comment]
Using the new whitelist editor, just add `youtube.com` to your rules. I recommend using your real profile as your whitelist profile since it's convenient.
