### ISSUE TITLE
Firefox Add-on Signing

### ISSUE THREAD

**Issue by amadeous** [sereneblue/chameleon#181]
My Firefox recently upgraded and your extension got disabled.

Their docs recommend to ask add-on maintainers to sign their extension.

Could you please consider it ? Thanks a lot for your marvelous add-on !
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by forkoz** [comment]
He signed it... just mozilla's certificate is broken. So disable signing extensions.

**Comment by Kraxys** [comment]
Something is really wrong at AMO. Yesterday I was no more able to install any addon. Today, most of the  addon I instaled in the past are being disabled. Except on the profile where most connections to Mozilla's services are already disabled.

**Comment by sereneblue** [comment]
This is a Mozilla issue. We'll just have to sit back and wait for it to be resolved.

**Comment by amadeous** [comment]
Sorry for the inconvenience.
Thank you for your work !
