### ISSUE TITLE
Add a way to remove baidu from FF..

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#183]
I am no expert so I kindly ask more experienced users and sereneblue to give it a look at this and confirm whether my request makes sense or not.

Reading news today I found on quite interesting. It seems that mozilla decided to ship a baidu component not only to Chinese users, but globally, since region-specific solutions were more problematic to implement.

Link to the news: https://www.ghacks.net/2019/05/07/about-baidu-search-update-in-firefox/

I doubled checked and it is in my FF 66.0.3 (64-bit linux)...

The interesting part is this:
"Mozilla dropped Yahoo as the main search provider in 2017 for a number of reasons. The organization changed its search strategy from a global one to one that would seek out local partners in some regions, and Baidu happens to be one of the partners. 

Firefox users may install other search engines and even custom ones in the browser.

Firefox sends information with each request to partner search engines, and it appears that this code needed to be updated."

So basically FF phones a search engine people did not install...Now I don't know you, but I don't feel very comfortable having this kind of stuff in my FF especially since I never installed it and understood I had it because I read a news portal not mozilla...

More about baidu: https://en.wikipedia.org/wiki/Baidu which I think will make you raise a brow...

I was not able to find what info is sent to them, and I suspect chameleon won't be able to mask it anyway, so if you have more info please share it here.

It seems that not only they plan to continue this, but also extend this to ESRs versions.
Source: comment #30 in https://bugzilla.mozilla.org/show_bug.cgi?id=1541316.

My feature request:
Allow users to disable this (and future partners...) through a chameleon option.

Funny that such thing is under 'Firefox Features'....I don't know you but I don't need such features  :D

**Comment by sereneblue** [comment]
It looks like an update to something that already existed in Firefox but only for users using a zh locale. I'm not sure why it was pushed out to non-zh locale users. It doesn't look like it's sending anything besides making a test request to Baidu. 
https://www.baidu.com/baidu?wd=test&tn=monline_dg

If you're really concerned about this, you can simply add Baidu to your hosts file and map it to localhost. As much as I don't like this new 'feature', I'm not sure it's something that Chameleon can/should handle.

**Comment by WPFilmmaker** [comment]
Thanks to the clarification @sereneblue
