### ISSUE TITLE
[Features suggestion] Set Random IP of an specific Country

### ISSUE THREAD

**Issue by Saadi1988** [sereneblue/chameleon#184]
## Expected Behavior

Please add feature to fake a random IP in every Firefox startup. and possible to limit random IP to an specific country. 
i don't want to profile change every x minutes, rather every Firefox run startup.
And please improve initial extension load performance in Firefox startup.

Thanks.

**Comment by sereneblue** [comment]
I'm not sure what you mean by initial extension load performance? Chameleon shouldn't have a noticable impact on your Firefox startup time.

If you select one of the random profile options and keep the default change period ("no"), you'll have a random profile on each startup. 

Keep in mind that the spoofed IP headers don't actually hide your IP from most websites. Ideally, you should be using a VPN if you want to use random IPs. I don't think there's not much value in building on top of the spoofed IP headers feature.

**Comment by Saadi1988** [comment]
Ok. is it possible to define a custom profile and ip for just a defined website?

**Comment by sereneblue** [comment]
Yes, you'll need to use the whitelist editor. More details can be found [here](https://github.com/sereneblue/chameleon/wiki/Whitelist).

**Comment by Saadi1988** [comment]
Thankyou.
