### ISSUE TITLE
[notice] FF Nightly WX Brief not working with Chameleon enabled

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#185]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

## Expected Behavior
No interference with other WX
## Current Behavior
With Chameleon enabled this WX https://github.com/brief-rss/brief stops working, as outlined here https://github.com/brief-rss/brief/issues/449
## Relevant settings
Changing settings does not make a difference

## Context (Environment)
FF Nightly x_64 (issue present since release 09-05-19 or 10-05-19) on W10 Pro x_64 v1809 b17763.437

I suspect that some code change in the browser is causing this. Since this happening on the Nightly tree this is just to notify of a potential issue in the making.

**Comment by sereneblue** [comment]
Thanks, I'll keep an eye out for the changes in v68. Does the issue appear after a fresh install of Brief and Chameleon?

**Comment by n8v8R** [comment]
Yes, it does happen as well with a fresh FF profile, however there is good news - it is not Chameleon causing this but First Party Isolation. 

From what I have seen there are some changes in the current Nightly trunk with regard to FPI
