### ISSUE TITLE
[Request] More ways to enter IPs in IP Rules Section

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#186]
Adding Ips and rules in _Whitelist > TimeZone and Languages_ becomes rapidly boring when for the same time zone and languages, the IPs to enter are numerous without belonging to the same CIDR "segment".

So, where it possible to add IPs as a **list** (IPs being coma separated for example) ?

Ideally, it would be very convenient to allow the following ways to enter the IPs (for a same TimeZone & Language rule):
* single IP (currently done)
* Ip Range in CIDR notation (currently done)
* IPs list (coma separated)
* IP range in notation like _IP1 - IPn_

Using Chameleon 0.12.1 on W7

**Comment by sereneblue** [comment]
I can make some QoL improvements similar to the recent whitelist editor update. That should cover your third point. CIDR notation already addresses the IP range? You can use a site like https://ip2cidr.com/ to convert the IP range to CIDR.

**Comment by sereneblue** [comment]
I've decided to scrap my original idea; reworking the UI to be similar to the whitelist editor proved to be far more complex than I initially thought. I've opted for the simpler solution of comma separated IP ranges.

**Comment by Kraxys** [comment]
Thanks. Comma separated IP ranges will be good enough.
I'm going to test this feature.
