### ISSUE TITLE
Make profiles

### ISSUE THREAD

**Issue by Saadi1988** [sereneblue/chameleon#192]
Chameleon has whitelist option but also i need blacklist. 

+ fake screen resolution.

Thanks.

**Comment by Saadi1988** [comment]
infact special profile for every website.

**Comment by Saadi1988** [comment]
option to create a,b,c,... profile (that some features can be random) and set it for specified websites.

**Comment by Saadi1988** [comment]
Profile A: unspecified websites.
Profile B: facebook.com, instagram.com, .....
Profile C: x1.com, x2.com, x3.com ,....
........

**Comment by sereneblue** [comment]
The whitelist was created to fix websites that broke with script injection enabled. Although recent updates have made it possible to use as an 'advanced' mode for Chameleon, that's not its intended purpose. I think the current functionality should be enough to address your needs.

I plan to work on an extension that should give you more spoofing flexibility after [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1470651) feature is added to Firefox.
