### ISSUE TITLE
Give indication about what was blocked.

### ISSUE THREAD

**Issue by 945fc41467** [sereneblue/chameleon#20]
Some other apps like noScript, uBlock origin or uMatrix complete very well chameleon. And they have one common point with chameleon : they all frequently break websites pages.
With uMatrix and uBlock, it is possible to display on the icon the number of blocked request. So, if a domain is broken, I can guess which app is in cause and give some supplementary authorisation.

So it could be interesting to have a tab with the list of everything the website tried to do and the possibility to give temporary permission (until the end of the session). Maybe also the data et received (referer, user-agent…). Anything which could allow the user to know if the website is broken because of this app or anothe one and to find the good parameters.

**Comment by sereneblue** [comment]
It's a bit difficult to quantify what's being accessed with Chameleon. I don't think it'd happen too often so the user would have to add the website to the whitelist. I may add buttons to disable certain parts of the extension.

**Comment by 945fc41467** [comment]
Yes I think it depend on the feature. I have no idea how it is possible to detect that youtube is broken because the user-agent is define on chrome browser. But I think a possible canvas fingerprint could be detected as it is a script execution. I also guess that if the authorisation are disabled, it mean the website asked for authorisation ? So it could be interesting to know which one. I don't know if it is it possible to detect if the website honor do-not-track or not.

**Comment by sereneblue** [comment]
I experienced issues with a user agent switching extension so I think it's the user agent that's causing issues. I've read from a RAS issue that Youtube loads different formats depending on the browser. Not sure if that's still the case but I'll run some tests to pinpoint what's causing issues. 

For canvas fingerprinting, you should use [Canvas Blocker.](https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/). 

If Authorization is disabled, you will break some sites (sites that use a Bearer Token with an API, logging into a site that asks for credentials). It's not possible to detect if a website honors DNT, it may be counter productive to leave it as an option.

**Comment by sereneblue** [comment]
The new whitelist editor gives you some granular control over what affects a whitelisted rule. The simplest solution that will probably fix most issues is to add the domain of the current page to the whitelist and toggle the "use your real profile" option.

To learn more about the new whitelist editor, visit the [wiki](https://github.com/sereneblue/chameleon/wiki/Whitelist).
