### ISSUE TITLE
Problems in TimeZone/Languages IP Rules in v12.5

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#200]
Updating from v12.4 to v12.5 erased my TimeZone/Languages IP Rules. Moreover, when trying to reset these rules I get 2 problems: 
1) After resetting some rules and restarting firefox, I'm no more able to add new rules and the previous rules (added after updating Chameleon and just before restarting FF) are no more displayed.
2) Chameleon is no more able to find the correct timezone rule to use, and displays the notification "_unable to set timezone data. Using UTC_", and clicking on "_reload IP info_" makes nothing it seems this feature doesn't work either).

NB: 2)  happens when I use an IP belonging to the rules I defined again just before restarting FF, 

Chameleon v12.5  on FF 67 Windows 7

**Comment by sereneblue** [comment]
I'm sorry your whitelist settings were deleted. It looks like v0.12.4 was a breaking change and v0.12.5 didn't fix the issues (may have made things worse). Thanks for the helpful issue. I'm currently looking into this.
