### ISSUE TITLE
"Protect keyboard fingerprint" does not work as intended

### ISSUE THREAD

**Issue by Minimalist73** [sereneblue/chameleon#201]
## Expected Behavior
Make harder to fingerprint keyboard input

## Current Behavior
Tried the feature on https://www.keytrac.net/en/tryout after authentication my score was 100% so I've been detected as the same user. Feature should protect from this kind of behavior if I'm not wrong ?

## Relevant settings

Protect keyboard fingerprint with script injection.
## Context (Environment)

67.0.1 & W10

**Comment by sereneblue** [comment]
That's a textarea HTML element. The keyboard fingerprint only works for inputs. This is done for two reasons: keyboard fingerprinting is probably used for form elements (inputs) and performance concerns.

I'm not entirely sure how useful keyboard fingerprint protection is. I'd imagine the library used to get the fingerprint is loaded as a 3rd party script so something like uMatrix/NoScript would block it.
