### ISSUE TITLE
navigator.hardwareConcurrency should be 2 for Firefox Useragents

### ISSUE THREAD

**Issue by ilikenwf** [sereneblue/chameleon#202]
All versions past May 2, 2017 of Firefox report this value as 2, not 4 when resistFingerprinting is enabled, because 70% of Firefox users have 2 discrete CPUs anyway:

https://github.com/sereneblue/chameleon/blob/3ce32540bc2f9f592b70bb8d61db9b7f1af39fe5/src/js/lib/spoof.js#L77

**Comment by sereneblue** [comment]
Thanks! This will be fixed in the next update.
