### ISSUE TITLE
Chameleon doesn't Recognize Time&Date for an IP Manually Entered in WhiteList.

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#205]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I use the  browser where Chameleon is installed, with a proxy with latvian IP. 
Previously, in _Whitelist>View TimeZones and IP Rule_, I have defined a rule for this ip: _Language = Latvian, TimeZone = Europe/Riga_.
I have of course enabled WhiteList, and script injection. 

But when clicking in _Whitelist>ViewTimeZone>Reload IP infos_ I get only  the pop up "_Unable to get TimeZone. Using UTC._"

Interestingly, with this IP, ipapi.co display infos relative to an iranian IP, without any timezone info.
So, the popup  "unable to get timezone" would be normal if I had not already defined this IP's TimeZone in Chameleon whitelist.

FF 67 on Windows 7 64

**Comment by sereneblue** [comment]
Thanks for reporting this issue. This should be fixed in the next update.
