### ISSUE TITLE
Notifications stopped working

### ISSUE THREAD

**Issue by avital32** [sereneblue/chameleon#207]
Running the latest version of Chameleon and Firefox.
Have not yet found any topics about this, so it might just be me(?)
but randomly, the notifications stopped working, as well as the Whitelist options.

Never had a problem with this until today.

I have:
Reset Chameleon.
Deactivated.
Deactivated and removed x 4
Unchecked the enable notification box and restarted Firefox again, both with notifications enabled, as well as disabled.

While writing this, Firefox got a new update, 67.0.4 (64-bit) nothing did change.

Grateful for any suggestions!

**Comment by sereneblue** [comment]
I'm not able to replicate the notification issue with  FF67 and FF68 using v0.12.8. What do you mean by whitelist options?

Also, can you reliably reproduce this issue? If so, can you install and test with v0.12.7 and v0.12.6?

**Comment by avital32** [comment]
Its the Add/edit domain in the Whitelist tab that wont open. View whitelist and View Timezone/Language IP rules works fine, clicking one of those, and the html site opens. It used to open when clicking Add/edit domain too, but that and the enable notices stopped working all together.

I will try to install and test with v 0.12.7 and v 0.12.6
