### ISSUE TITLE
[info only] Mozilla plans to remove CPU info from User-Agent strings and navigator APIs

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#210]
In case of interest to keep an eye on the development

https://bugzilla.mozilla.org/show_bug.cgi?id=1556223

**Comment by sereneblue** [comment]
Thanks, I'll be updating the profiles when FF69 rolls out.

**Comment by n8v8R** [comment]
That may not happen yet with FF69, at least the bug has no target yet.

Perhaps you were referring to https://bugzilla.mozilla.org/show_bug.cgi?id=1559747

**Comment by sereneblue** [comment]
You're right, I was referring to that bug. I'll keep an eye out for the changes in the release notes and will update the profiles accordingly.

**Comment by sereneblue** [comment]
I've updated what I can for now. Linux and Android will be updated when the changes are included in the next(?) FF release.
