### ISSUE TITLE
Firefox mobile whitelist profiles do not save

### ISSUE THREAD

**Issue by bagnaram** [sereneblue/chameleon#213]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
When setting the profile for a whitelished item, it should save. 
## Current Behavior
Whitelisted profile setting reverts to "default profile" 
## Context (Environment)

Firefox mobile on Android 8.0.1

**Comment by sereneblue** [comment]
@bagnaram Are you using the latest version of Chameleon? There was an issue with Android with a previous version that should be fixed with the latest, v0.12.9.

**Comment by bagnaram** [comment]
Yes I am running 0.12.9. Is there any additional information I can provide to assist debugging?

**Comment by sereneblue** [comment]
@bagnaram Can you post your exported settings?

**Comment by bagnaram** [comment]
Sure.



On July 1, 2019 6:24:05 PM CDT, sereneblue <notifications@github.com> wrote:
>@bagnaram Can you post your exported settings?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sereneblue/chameleon/issues/213#issuecomment-507460221

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bagnaram** [comment]
Sorry I thought it would attach in email.
```
{
  "excluded": {
    "win": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "mac": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "linux": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "ios": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "android": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "all": [
      false,
      false,
      false,
      false,
      false
    ]
  },
  "headers": {
    "blockEtag": false,
    "disableAuth": false,
    "disableRef": false,
    "enableDNT": true,
    "refererXorigin": 0,
    "refererTrimming": 0,
    "spoofAccept": false,
    "spoofAcceptLang": true,
    "spoofAcceptLangValue": "vi-VN,vi;q=0.8,en-US;q=0.5,en;q=0.3",
    "spoofSourceRef": false,
    "spoofVia": false,
    "spoofViaValue": 0,
    "spoofXFor": false,
    "spoofXForValue": 0,
    "upgradeInsecureRequests": false,
    "viaIP": "",
    "viaIP_profile": "",
    "xforwardedforIP": "",
    "xforwardedforIP_profile": "",
    "useragent": ""
  },
  "ipRules": [],
  "settings": {
    "customScreen": "",
    "enableScriptInjection": true,
    "interval": 0,
    "kbDelay": 0,
    "limitHistory": false,
    "minInterval": null,
    "maxInterval": null,
    "notificationsEnabled": false,
    "protectKeyboardFingerprint": false,
    "protectWinName": false,
    "screenSize": "default",
    "spoofAudioContext": false,
    "spoofClientRects": false,
    "timeZone": "default",
    "useragent": "real",
    "useragentValue": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36",
    "webSockets": "allow_all"
  },
  "version": "0.12.9",
  "whitelist": {
    "enabled": true,
    "enabledContextMenu": false,
    "defaultProfile": "none",
    "urlList": [
      {
        "id": "spy55g",
        "domains": [
          {
            "domain": "chat.google.com",
            "re": false,
            "pattern": ""
          }
        ],
        "lang": "",
        "profile": "win4",
        "spoofIP": "",
        "options": {
          "auth": false,
          "ip": false,
          "ref": false,
          "timezone": true,
          "websocket": false,
          "winName": false
        }
      }
    ]
  }
}
```

**Comment by sereneblue** [comment]
Hm, even with your settings I'm not able to replicate this issue. Are you saving the rule after you change the whitelist profile? Just to be clear, are you trying to modify the rule for `chat.google.com`?

**Comment by bagnaram** [comment]
I am saving the rule and the setting persists for a while. I feel like after some determined period of time, the whitelisted profile setting reverts to "default profile", even after saving.

**Comment by bagnaram** [comment]
I have not been able to trace where or how it is happening, but try setting and saving a custom whitelist profile user agent. And then after a couple hours or restarts, it reverts.

**Comment by sereneblue** [comment]
Thanks for your patience. I was able to find the bug!

v0.12.10 will be released soon.

**Comment by bagnaram** [comment]
Awesome. cheers!
