### ISSUE TITLE
Spoof Timezone Doesn't Work

### ISSUE THREAD

**Issue by 0pLuS0** [sereneblue/chameleon#215]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

## Expected Behavior
Timezone should be spoofed when using option

## Current Behavior
I pick a GEO location to spoof the time zone and it still shows my local time zone

## Relevant settings

I've tried experirmented with various forms of settings for months with no sucess...

## Context (Environment)

Firefox 60.7.2 ESR
Windows 10 LTSC 2019

I like using Firefox ESR, I've been using it since Slackware uses, and my background is more in Linux than Windows, so I naturally installed an ESR version when I started using Windows 10.

I don't think there should be anything complicated about picking and using this option and then having it work, but I pick to spoof the timezone, then I pick a timezone, and then I look at various sites online like whoer.net and it reports back to me my local timezone.

In Linux I simply use ```TZ=Geolocation firefox``` and this works all the time, 100% in Linux.

**Comment by sereneblue** [comment]
Can you try visiting `https://add0n.com/spoof-timezone.html` and see if your timezone is spoofed? Also, are you checking `Enable script injection`? whoer shows the spoofed timezone for me under `System`. I believe the local timezone whoer displays is the timezone based on your IP address.

**Comment by WPFilmmaker** [comment]
@serenblue here it works too, maybe he/she didn't enable 'enable script injection'.

**Comment by andcha88** [comment]
@sereneblue Timezone spoofing won't work for me as well. Needed to add another one firefox add-on in order to make this possible. What's the issue?

**Comment by sereneblue** [comment]
> @sereneblue Timezone spoofing won't work for me as well. Needed to add another one firefox add-on in order to make this possible. What's the issue?

What website are you using to verify the spoofed timezone? Can you post your settings?

**Comment by andcha88** [comment]
I check my timezone at https://ipx.ac/run and https://browserleaks.com/javascript as well. If I use another plugin for spoofing my timezone it's working, with Chameleon it's not working anymore. Used to work though. Even if I tried to completely reset everything, still the same issue. Here's a printscreen of the settings I use: https://prnt.sc/p755up

**Comment by sereneblue** [comment]
> I check my timezone at https://ipx.ac/run and https://browserleaks.com/javascript as well. If I use another plugin for spoofing my timezone it's working, with Chameleon it's not working anymore. Used to work though. Even if I tried to completely reset everything, still the same issue. Here's a printscreen of the settings I use: https://prnt.sc/p755up

Thanks; from a quick test, it seems the keyboard fingerprint option is breaking timezone spoofing. I'll look into this further and will hopefully have a patch in place for the release later this week.

**Comment by andcha88** [comment]
That's great! Will be expecting the release 👍

**Comment by andcha88** [comment]
That's great! Will be expecting the release...
