### ISSUE TITLE
Bug : web.whatsapp.com is broken when using Resist fingerprinting

### ISSUE THREAD

**Issue by GLLM** [sereneblue/chameleon#22]
Hi @sereneblue 

I use web.whatsapp.com daily and I found out that Chameleon breaks the site :the QR code flashes and then disappear.
Thanks to trials & errors, I spotted the guilty setting : Resist fingerprinting.

I had to disable it in order to get my QR code properly.
Thanks

**Comment by GLLM** [comment]
Haha I see.
I'll do some digging then ! And check if a bug exists on Mozilla side.

**Comment by sereneblue** [comment]
I think this may have something to do with the canvas.

Since this isn't related to Chameleon, I'll be closing this issue.

**Comment by GLLM** [comment]
Fair enough @sereneblue :-)
