### ISSUE TITLE
Websockets are not properly blocked

### ISSUE THREAD

**Issue by DPTJKKVH** [sereneblue/chameleon#220]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Expected Behavior
In Chameleon I activate script injection and select configure it to block all websockets connections. I expect that websockets connections cannot be established and used.

## Current Behavior
http://demos.kaazing.com/echo/index.html
Using this website I am able to open a websocket connection and send as well as receive data through it.

## Relevant settings
Script Injection is enabled.
Websockets: Block all.

## Context (Environment)
Firefox 68.0 (64-bit)
Ubuntu 19.04

**Comment by sereneblue** [comment]
WebSockets are blocked. If you open the developer console, it shows `Firefox can’t establish a connection to the server at ws://demos.kaazing.com/echo?.kl=Y.`. However, it looks like that demo is using an HTTP long polling fallback. There's not much that can be done about that.

**Comment by DPTJKKVH** [comment]
@sereneblue Thanks for the quick reply. Are you sure nothing can be done?

If you use API-Killer-Websockets from eladkarako the test failes completely and no messages can be send: https://github.com/eladkarako/chrome_extensions/releases/download/LatestFirefox/api_killer_websocket-1.0.2.11-an+fx.xpi

Source code here: https://github.com/eladkarako/chrome_extensions/tree/store/API-Killer-WebSocket

Also do you think that HTTP long polling can be used for tracking, like websockets?

**Comment by sereneblue** [comment]
The extension you linked is obfuscated and there isn't any source code in the repo you provided.

Originally, Chameleon blocked WebSockets from being opened by overwriting the WebSocket variables. This is a bit of a hack and can cause websites to break. The cleaner way is to block the WebSocket connection from being opened (what Chameleon currently does), however, this doesn't protect you from sites that use HTTP long polling as a fallback if there's an issue with the WebSocket connection.

HTTP long polling is just an HTTP request, so yes, it can be used for tracking.

I don't want to reintroduce old problems again with overwriting the variables, but this is something I'd like to do some more research on.

**Comment by DPTJKKVH** [comment]
The code was open source at one point or at least not obfuscated. I remember that eladkarako complained that he had provide clean copies to Mozilla for reviews. This is one of the reasons why he now publishes on github only.

Would it help your research if I try and find an old version that was still released on addons.mozilla.org? I might have an old copy of the xpi somewhere.

**Comment by sereneblue** [comment]
@DPTJKKVH Yes, that would be much appreciated. I know that it replaces the WebSocket object but I'm not sure if also breaks sites like Chameleon used to. I haven't done much testing with that addon.

**Comment by DPTJKKVH** [comment]
@sereneblue Bad news.

I checked every device I have and searched through several backups but all are too new or up to date and thus already have the github version installed.

I then spent several hours trying to retrieve an "addons.mozilla.org"-version from web caches, archives and mirrors but without success.

As long as eladkarako is not willing to (confidentially) share his code with you, only a mozilla employee or someone else who still has the old version installed could provide us with a non obfuscated copy.

btw: I wonder if we are hunting a phantom anyway. After all he somehow gets his obfuscated addons signed by mozilla even though in the past he complained that he had to provide clear text versions for mozilla. Something does not add up here. Why would mozilla sign an addon that cannot be reviewed and isn't even published on their addon store?!

**Comment by sereneblue** [comment]
@DPTJKKVH Thanks for looking for the older version.

If a developer wants to distribute the addon themselves (the case here), it's immediately signed by Mozilla; the code isn't reviewed. Signing only allows users to install the extension in the release version of Firefox.

I'll look into this issue when I have some time available.

**Comment by DPTJKKVH** [comment]
@sereneblue Thanks for taking a look at this issue. It is very much appreciated. If you need help with testing or such at a later time feel free to contact me. I'll stay subscribed to this issue.

I'd like to add my take on the issue if you don't mind:
I understand that breakage should be avoided because privacy without functionality isn't worth much. However should you come to the conclusion that it's impossible to block HTTP long polling without breaking some sites you shouldn't simply leave things like they are. It's way too trivial to abuse. Instead I suggest to offer the user a choice in this:

The default mechanic should be like it is right now: Disconnecting WebSockets for either third party only or all connections but doing nothing against HTTP long polling. This retains the "most compatible" approach for the casual user.

Additionally there should be an "aggressive" mode that comes with the explicit warning "This will break many websites! Do not use if you don't know what you are doing!" or any other mechanic that prevents someone from accidentally activating this setting. This mode reintroduces the old blocking method that completely removes any WebSocket functionality including HTTP long polling. This would work beautifully with the whitelisting mechanic you already have by the way. (A feature that eladkarako addon is lacking!)

I know asking for this option is way easier than actually implementing it but there is no good solution for this issue right now and you would be the first one to provide it by "simply" adding your old approach alongside the current one.

If you read this far: Thank you for taking the time!

**Comment by sereneblue** [comment]
@DPTJKKVH I appreciate your thoughtful comments. That's actually what I have in mind for how I'll implement this feature if I can't find a way to block the long polling connection. I've been a bit busy with another project so I haven't had much time to work on Chameleon but the next release will contain a fix for this issue. ETA within the next week or two. :)

**Comment by sereneblue** [comment]
@DPTJKKVH Good news! After some more research, I was able to seamlessly block more WebSocket connections that use an HTTP fallback. This new functionality will be in the next update.

**Comment by DPTJKKVH** [comment]
@sereneblue This is incredible news! 👍 I can't wait to test the new version. I will report back if I find any issues but I already want to thank you very much! It was a very pleasant experience talking with you about this issue and you were very kind to pick it up and fix it in such short time. You made me very confident in trusting you and your addon and I already recommeded it to friends and family.

I'm always on the lookout for new and improved privacy features and do lots of testing. (This is how I stumpled upon the long polling fallback and the API-Killer addon.)

I hope you don't mind if I come back in the future if I find other potential leaks or other addons that might have better solutions to some issues so you can take a look at them and might include it in Chameleon.

I'm currently looking into how Canvas Blocker seems to more efficiently faking user agents and other system information even with javascript enabled. (Navigator API) However Canvas Blocker is lacking the fantastic Randomizer that Chameleon offers. So if both features could be combined that would be a match in heaven. As as I have a proper test case I will open a new issue.

Thank you so much! I really appreciate your work!

**Comment by sereneblue** [comment]
@DPTJKKVH 

I greatly appreciate the kind words. Chameleon wouldn't have gotten this far without it's users. Because of your efforts, Chameleon users will benefit from an improved WebSocket blocker. ;)

Sure, I don't mind if you create an issue for improvements. Do note, I will be working on other projects so I won't have as much time to commit to Chameleon development.

In regards to Canvas Blocker, you shouldn't enable any features that could conflict with Chameleon. You might get some undesired results; navigator API spoofing is better handled by Chameleon (because of profiles). Although Chameleon is a bit heavier, it's performance shouldn't cause any issues with web browsing. I do have plans for a major refactor/rewrite after the manifest v3 proposal has been finalized.

**Comment by sereneblue** [comment]
@DPTJKKVH v0.12.12 has been released with improved websocket blocking.

**Comment by DPTJKKVH** [comment]
@sereneblue I just tested it and it works flawlessly! It's good that you were able to block websockets and it's fallbacks while still exposing (or pretending) websocket compability.

Thank you again for taking the time to both looking into it and adding the new features in such a short time. 👍
