### ISSUE TITLE
Chameleon does not revert twitter's old UI

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#224]
Twitter released a new UI which many, me included, don't like as it is kinda mobilish and not desktopy :P 

Earlier on it was possible reverting to the old interface through the settings, however it is not possible any more.

Fortunately it was discovered that by spoofing UA with IE twitter would show the old UI.
UA is supposed to be: Mozilla/5.0 (Windows NT 9.0; WOW64; Trident/7.0; rv:11.0) like Gecko

Which I think it is IE on Windows.

Here is a detailed explaination of how it works:

https://www.ghacks.net/2019/07/26/restores-twitters-old-interface-with-goodtwitter-for-firefox-and-chrome/

Chameleon is even mentioned as solution. 

I added twitter.com to the whitelist with the following settings:

---------------
Current domain:
twitter.com

Status:
Whitelisted
Profile:
Internet Explorer 11 (Win 8.1) 

Enable whitelist is toggled
Spoof accept language is 'default'
Enable time spoofing is on.
-------------------------------------

Yet I still see the new UI.

Has someone else tried? Does it work? Maybe Chameleon does not work, maybe I misconfigured something or maybe they just removed the old UI. Help?:)

I am on FF 68.0.1 (Linux 64-bit), Chameleon Version 0.12.11.

**Comment by sereneblue** [comment]
Have you tried testing with the GoodTwitter addon? By the way, I don't think the user agent used by that addon exists (NT 9.0?). 

I'm not sure if I need to login to Twitter to see the new UI. I don't think the UI is tied to your cookies but have you tried logging in with a private window and Chameleon?

**Comment by WPFilmmaker** [comment]
@sereneblue, You are right NT 9.0 seems not to be a valid ua, no idea why it is mentioned there...
GoodTwitter is opensource so maybe you can give it a look (f you haven't already) to its source.

About the issue I tried in private mode and it works! It has something to do with cookies, in fact GoodTwitter can: 'Clear recent browsing history, cookies, and related data'. I cleaned the cookies and the old UI is back, thanks Chameleon and you :D

Closing this.

**Comment by WPFilmmaker** [comment]
Just want to point out that as July 2020 this hack is not working anymore. Twitter says the spoofed browser is not supported anymore and shows the new layout.
