### ISSUE TITLE
[feature suggestion] add * to header language spoofing

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#226]
Currently I am using a different WX for header language spoofing because missing in Chameleon the `*` as option. I could remove the other add-on, less potential interference between WX,  if `*` would be added in Chameleon.

This from the other WX for augmenting what I am looking for

![accept lang per site settings](https://user-images.githubusercontent.com/13611490/62303173-f2438880-b47b-11e9-858a-90edd743ba5f.png)

**Comment by sereneblue** [comment]
If you don't enable header spoofing for the accept-langauge, the extension shouldn't conflict with Chameleon.

Adding a wildcard doesn't fit well with Chameleon's whitelist functionality and makes things a bit more complicated. It's a limited use case so unfortunately I won't be adding this feature to Chameleon.
