### ISSUE TITLE
Adding Firefox 60.0 Windows 7

### ISSUE THREAD

**Issue by SolCastel** [sereneblue/chameleon#228]
The Tor Browser Bundle uses the user agent:
- Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0

i.e. Firefox 60.0 on Windows 7 (when using Window at least)

On Panopticlick run by the EFF
When I use Firefox normally I get - 24.1 in 1
When I use Firefox with best profile for Firefox I get - 16.88 in 1 (thanks a lot for that)

However, when I use Tor Browser Bundle (looking only at User Agent) I get - 9.5 in 1

That might just be the bias of the privacy crowd testing but its probably worth adding if not because its used by millions who use Tor on the daily

**Comment by sereneblue** [comment]
Tor Browser uses Firefox ESR for the user agent. If you use `Firefox ESR (Windows 7)`, you'll get 1 in 9.52.
