### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by mazbron** [sereneblue/chameleon#229]
Can you add option spoof IP like this?
https://i.postimg.cc/yNftDny3/screenshot-152.png

thanks

**Comment by sereneblue** [comment]
You can already spoof the Via/X-Forwarded-For headers on the headers tab. If you want to use it for a spoof the IP for a specific site, use the whitelist.

**Comment by mazbron** [comment]
Yep I know, but can you please add option ip range like ipfuck?

Thanks

**Comment by sereneblue** [comment]
What's your opinion on using the CIDR notation? It's not as flexible as an IP range, but I could reuse some of the existing code.

**Comment by sereneblue** [comment]
@mazbron I'll do some refactoring for the spoof IP header feature while adding this feature. The `Via` and `X-Forwarded For`will be replaced with a single option that controls both of these headers. I didn't have much time to implement this for the release today, so it'll be in the next update [v0.12.15](https://github.com/sereneblue/chameleon/milestone/3).
