### ISSUE TITLE
Unable to whitelist site

### ISSUE THREAD

**Issue by ceiphr** [sereneblue/chameleon#23]
Hello,
First off thank you so much for reviving this addon, I missed it!

I'm currently having problems adding a whitelist for youtube.
My current whitelist is:

`[
{"url": "youtube.com"},
{"url": "www.youtube.com"}
]`

I tried whitelisting the base domain and WWW but whenever I use a chrome user agent the site still fails to load.
I'm unsure if this my mistake or if there is a problem with the extension. Hope someone can help, thanks.

**Comment by sereneblue** [comment]
Thanks for pointing this out. It's a bug in the extension. v0.6.8 (c87589c8215c22b421265ed381c42bc18e099c2c) should fix it.
