### ISSUE TITLE
Javascript Leaking Useragent

### ISSUE THREAD

**Issue by SolCastel** [sereneblue/chameleon#230]
Thanks for your help last time (even though it mostly was my being stupid), I've got something else this time.

I keep getting a 'Browser headers different' on https://whoer.net/
Apparently my real useragent (which I can confirm is correct when checking what the leaked useragent is) is leaking via javascript ergo the title even though I am using Chameleon.

**Comment by sereneblue** [comment]
Did you enable script injection?

**Comment by rugabunda** [comment]
enabling script injection fixed it for me
