### ISSUE TITLE
social tracking added in FF70 (currently Nightly branch)

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#232]
`privacy.trackingprotection.socialtracking.enabled` been added as preference stanza

![Annotation 2019-08-14 183334](https://user-images.githubusercontent.com/13611490/63038714-14002f00-bec2-11e9-8bc8-3a723dbac0da.png)

**Comment by sereneblue** [comment]
@n8v8R I'll add that to Chameleon when FF70 is released.
