### ISSUE TITLE
Inaccurately reporting about:config in checklist

### ISSUE THREAD

**Issue by rugabunda** [sereneblue/chameleon#233]
Inaccurately reported session identifiers and tls false_start setting as its opposite.

Disable SSL False Start security.ssl.enable_false_start true
Disable SSL Session Identifiers security.ssl.disable_session_identifiers false

false_start is actually disabled, and session_identifiers are actually disabled.

**Comment by sereneblue** [comment]
@rugabunda Thanks for pointing this out! I'll have this fixed in the next update.

**Comment by rugabunda** [comment]
This occurred in 68.0.2, oddly its not reproducible in firefox bittubers 68.0a1

**Comment by rugabunda** [comment]
I just turned off https everywhere, and retested, the problem did not persist; then re enabled httpseverywhere, and tested again, and the problem did not persist.

**Comment by sereneblue** [comment]
@rugabunda I'm not sure what issue you're having? HTTPS Everywhere doesn't modify the about:config settings.

**Comment by rugabunda** [comment]
> 
> 
> @rugabunda I'm not sure what issue you're having? HTTPS Everywhere doesn't modify the about:config settings.

I noticed today it is falsely detecting that disk & ram cache were disabled...

**Comment by sereneblue** [comment]
> > @rugabunda I'm not sure what issue you're having? HTTPS Everywhere doesn't modify the about:config settings.
> 
> I noticed today it is falsely detecting that disk & ram cache were disabled...

I'm still not following you; web extensions don't have that capability. The checklist is just a checklist. It doesn't modify about:config settings.
