### ISSUE TITLE
New Tweaks To Add Please?

### ISSUE THREAD

**Issue by 0pLuS0** [sereneblue/chameleon#236]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Expected Behavior
Nothing but adding these new Tweaks

## Current Behavior
Lack of Tweaks missing

## Relevant settings

Below are some Tweaks I would like you to please consider adding to Chameleon, there are however some that might not be needed at all like the so called Insecure Chipers I have listed, which were an issue in the past.

***

browser.cache.disk.smart_size.enabled - (default boolean)
true
browser.cache.disk.smart_size.enabled - (user set boolean)
false

***

browser.cache.disk_cache_ssl - (default string)
true
browser.cache.disk_cache_ssl - (user set string)
false

***

browser.cache.frecency_experiment - (default integer in Tor)
0
browser.cache.frecency_experiment - (user set integer)
-1 ?

***

browser.search.suggest.enabled - (default boolean)
true
browser.search.suggest.enabled - (user set boolean)
false

***

browser.sessionhistory.max_entries - (default string)
50
browser.sessionhistory.max_entries - (user set string) - (can only go back 2 pages)
2

***

prevents firefox from storing a list of closed tabs
browser.sessionstore.max_tabs_undo - (default integer)
25
browser.sessionstore.max_tabs_undo - (user set integer)
0

***

browser.sessionstore.privacy_level - (default integer)
0
browser.sessionstore.privacy_level - (user set integer)
2

***

browser.zoom.siteSpecific - (default string)
true
browser.zoom.siteSpecific - (user set string)
false

***

clipboard.autocopy - (default boolean)
true
clipboard.autocopy - (user set boolean)
false

***

dom.enable_performance - (default string)
true
dom.enable_performance - (user set string)
false

***

(Are These DOM below good?)
------------
dom.enable_performance_navigation_timing
true
dom.enable_performance_navigation_timing
false

***

dom.enable_performance_observer
true
dom.enable_performance_observer
false

***

dom.gamepad.enabled - (default string)
true
dom.gamepad.enabled - (user set string)
false

***

dom.indexedDB.enabled - (default string) - Breaks Chamleon Add-On!
true
dom.indexedDB.enabled - (user set string)
false

***

dom.storage.default_quota - (default integer)  - *** Needed for some downloads ***
5120
dom.storage.default_quota - (user set integer)
0

***

Opting out of this daily ping will stop Firefox from sending 
the add-ons you have installed and most recent start-up time 
to Mozilla, and will also stop displaying updated metadata for 
your add-ons and discontinue personalized recommendations if 
they were displayed in the Get Add-ons pane of the Add-ons Manager.

extensions.getAddons.cache.enabled - (default boolean
true
extensions.getAddons.cache.enabled - (user set boolean)
false

***

extensions.update.enabled - (default boolean)   ???
true
extensions.update.enabled - (user set boolean)
false

***

media.cache_size - (default integer)
512000
media.cache_size - (user set integer)
0

***

#prevent websites from tracking microphone and camera status
media.navigator.enabled - (default boolean)
true
media.navigator.enabled - (user set boolean)
false

***

#only accept cookies from the site issuing them
network.cookie.cookieBehavior - (default integer)
0
network.cookie.cookieBehavior - (user set integer)
1

***

#delete cookies at the end of this session
network.cookie.lifetimePolicy - (default integer)
0
network.cookie.lifetimePolicy - (user set integer)
2

***

network.dnsCacheEntries - (default integer)
400
network.dnsCacheEntries - (user set interger)
100

***

disable IPv6 as it may leak your mac address
network.dns.disableIPv6 - (default boolean)
false
network.dns.disableIPv6 - (user set boolean)
true

***

network.dns.disablePrefetch - (default boolean)
false
network.dns.disablePrefetch - (user set boolean)
true

***

Network.http.sendRefererHeader - (default string)
2
Network.http.sendRefererHeader -  (user set string) - don't disable for dd-wrt to click the 'Apply Settings and 'Save' buttons.
0

0 - Disable referrer.
1 - Send the Referer header when clicking on a link, and set document.referrer for the following page.
2 - Send the Referer header when clicking on a link or loading an image.

***

network.http.speculative-parallel-limit - (default integer)
6
network.http.speculative-parallel-limit - (user set integer)
0

***

network.websocket ?

***

plugin.state.flash - flash (Disable asking to install flash)

0 <-- Never active
1 <-- Ask to active
2 <-- Default, always active

***

helps prevent cross domain tracking
privacy.firstparty.isolate - (default boolean)
true
privacy.firstparty.isolate - (user set boolean)
false

***

privacy.trackingprotection.enabled - (default boolean)
false
privacy.trackingprotection.enabled - (user set boolean)
true

***

security.OCSP.require - (default boolean)
false
security.OCSP.require - (user set boolean)
true

***

require safe negotiation
security.ssl.require_safe_negotiation - (default boolean)
false
security.ssl.require_safe_negotiation - (user set boolean)
true

treat unsafe negotiation as broken
security.ssl.treat_unsafe_negotiation_as_broken - (default boolean)
false
security.ssl.treat_unsafe_negotiation_as_broken - (user set boolean)
true

***

*** INSECURE CIPHERS TURN TO FALSE - Should this still be disabled?
security.ssl3.dhe_rsa_aes_128_sha - (default boolean)
true
security.ssl3.dhe_rsa_aes_128_sha  - (user set boolean)
false

***

security.tls.version.min - (default integer)
1
security.tls.version.min - (user set integer)
3

***

Should this still be disabled?
security.ssl3.dhe_rsa_aes_256_sha - (default boolean)
true
security.ssl3.dhe_rsa_aes_256_sha  - (user set boolean)
false

***

toolkit.telemetry.archive.enabled - (default boolean)
true
toolkit.telemetry.archive.enabled - (user set string)
false

***

toolkit.telemetry.shutdownPingSender - (default boolean)
true
toolkit.telemetry.shutdownPingSender - (modified boolean)
false

***

WebRTC implement STUN (Session Traversal Utilities for Nat), a protocol that allows to discover the public IP address. To disable it:
media.peerconnection.enabled - (default boolean
true
media.peerconnection.enabled - (user set boolean)
false

Additional WebRTC options
--------------

media.peerconnection.turn.disable = true
media.peerconnection.use_document_iceservers = false
media.peerconnection.video.enabled = false
media.peerconnection.identity.timeout = 1

## Context (Environment)

68.1.0 ESR - Linux x64

**Comment by Thorin-Oakenpants** [comment]
I would just like to caution against almost all of these: listing them for end-users will encourage playing with them: which is not good. Additionally, you would have to maintain it.

Examples:
- `tls min`: Firefox telemetry shows > 0.5% of encrypted pages use tls1.0 or 1.1. Changing this alters your fingerprint for basically zero security gain
- `ciphers`: changing ciphers also alters your fingerprint: and again, for basically zero security gain: I would rather trust Mozilla's engineers etc as to when these get deprecated
- `ciphers`: if a user changes any prefs, i.e they become `modified` in about:config, this can prevent Firefox flipping the pref in case they need to for security reasons.
- `browser.sessionstore.max_tabs_undo`: only applies to a very few edge cases: unless you use Session Restore, this data is session only. If you don't want history to touch the disk, then use PB mode (which stores it in memory)
- `dom.indexedDB.enabled`: pointless: it will break both web content and extensions that require it. This is not how you control persistent local web content storage
- `dom.storage.default_quota` : this is not how you handle persistent web storage: it'll just break web sites that don't know how to handle rejection
- `dom.gamepad.enabled` : pointless: if you don't have a gamepad then there is no issue. If you do and you connect it, then you probably want to use it. Also this pref alters your fingerprint
- `browser.cache.frecency_experiment` : this has nothing to with privacy or fingerprinting
- there are **so many more** in that list that make zero sense


With all due respect to OP, this looks like something from an uneducated list of tweaks. I mean look at `network.websocket` - no info, just a question mark. If suggestions are going to be made: at least research it and make a case for it. Quite a few look like someone just wants to copy Tor Browser's settings. That's not how it works.

**Comment by 0pLuS0** [comment]
Go easy on the WORDS, don't be insulting! ```uneducated```...

I said ```Consider``` these tweaks, if there is any value to these!

No one is copying anything just simply from TOR!

I have also spent YEARS on this subject over Firefox security, which at some point in time, these did have some merit!

Anyhow...

```P.S.``` One thing I will say, trying to disable WebRTC in Chameleon it didn't seem to work with the WebRTC Policy section. I had to also make sure to disable all of these to get it disabled.

media.peerconnection.turn.disable = true
media.peerconnection.use_document_iceservers = false
media.peerconnection.video.enabled = false
media.peerconnection.identity.timeout = 1  - (default 1000)


These below I'm not sure for WebRTC - I only disabled the first one;

media.gmp-provider.enabled = false
media.gmp-widedevine.enabled = false
media.gmp-widevinecdm.enabled= true ?

**Comment by 0pLuS0** [comment]
Here is an edited/modified list of the original.

***

browser.sessionhistory.max_entries - (default string)
50
browser.sessionhistory.max_entries - (user set string)
2

***

browser.sessionstore.max_tabs_undo - (default integer)
25
browser.sessionstore.max_tabs_undo - (user set integer)
0

***

browser.sessionstore.privacy_level - (default integer)
0
browser.sessionstore.privacy_level - (user set integer)
2

***

clipboard.autocopy - (default boolean)
true
clipboard.autocopy - (user set boolean)
false

***

extensions.getAddons.cache.enabled - (default boolean
true
extensions.getAddons.cache.enabled - (user set boolean)
false

***

extensions.update.enabled - (default boolean)   ???
true
extensions.update.enabled - (user set boolean)
false

***

media.navigator.enabled - (default boolean)
true
media.navigator.enabled - (user set boolean)
false

***

network.cookie.cookieBehavior - (default integer)
0
network.cookie.cookieBehavior - (user set integer)
1

***

network.cookie.lifetimePolicy - (default integer)
0
network.cookie.lifetimePolicy - (user set integer)
2

***

network.http.speculative-parallel-limit - (default integer)
6
network.http.speculative-parallel-limit - (user set integer)
0


***

plugin.state.flash - flash (Disable asking to install flash)

0 <-- Never active
1 <-- Ask to active
2 <-- Default, always active

***

privacy.firstparty.isolate - (default boolean)
false
privacy.firstparty.isolate - (user set boolean)
true

***

toolkit.telemetry.archive.enabled - (default boolean)
true
toolkit.telemetry.archive.enabled - (user set string)
false

***

toolkit.telemetry.shutdownPingSender.enabled - (default boolean)
true
toolkit.telemetry.shutdownPingSender.enabled - (modified boolean)
false

***

WebRTC
--------

media.peerconnection.enabled - (default boolean
true
media.peerconnection.enabled - (user set boolean)
false

media.peerconnection.turn.disable = true
media.peerconnection.use_document_iceservers = false
media.peerconnection.video.enabled = false
media.peerconnection.identity.timeout = 1
media.gmp-provider.enabled = false
media.gmp-widedevine.enabled = false
media.gmp-widevinecdm.enabled= false

**Comment by sereneblue** [comment]
@Thorin-Oakenpants @0pLuS0 The checklist will be updated in the near future. I've only glanced at some of the settings; yes, not every one of them is relevant. I believe some of the settings were included for security reasons (hardened Firefox) so not everything will be directly related to privacy/fingerprinting. 

I'll be taking a thorough look at these settings above and reevaluating the existing settings in the checklist after the next update is released.

**Comment by sereneblue** [comment]
@0pLuS0 

I suppose I can make an improvement to WebRTC handling. At the moment, Chameleon doesn't disable WebRTC, it only limits how much data is exposed. I can add an option to disable WebRTC. If it's enabled, it'll display the existing functionality.

> browser.sessionstore.privacy_level
> browser.sessionstore.max_tabs_undo
> extensions.getAddons.cache.enabled
> extensions.update.enabled
> media.navigator.enabled
> network.http.speculative-parallel-limit

These options will be added.

> clipboard.autocopy

This options only applies to *nix systems, however, this doesn't work for me on Arch Linux.

> network.cookie.cookieBehavior

The cookie policy option addresses this.

> network.cookie.lifetimePolicy

Ideally, this is what a container/private window should be used for. Power users who want their data deleted when the browser is closed can toggle the option in about:preferences.

> plugin.state.flash

Keeping the default option is fine in my opinion; won't be long until Flash is completely removed.
 
> privacy.firstparty.isolate 

Can be toggled by Chameleon.

> media.peerconnection.enabled - (default boolean
> media.peerconnection.enabled - (user set boolean)
> media.peerconnection.turn.disable = true
> media.peerconnection.use_document_iceservers = false
> media.peerconnection.video.enabled = false
> media.peerconnection.identity.timeout = 1

Adding an option to disable WebRTC will makes these options redundant.

> toolkit.telemetry.archive.enabled
> toolkit.telemetry.shutdownPingSender.enabled

These options are not needed if telemetry is disabled, an option that's present in the current checklist.
