### ISSUE TITLE
Screen size spoof does not work

### ISSUE THREAD

**Issue by Paola001011** [sereneblue/chameleon#242]
The screen size remains fixed at 1400 x 900. Even if I change resolution, it remains fixed at 1400 x 900. Why?

**Comment by sereneblue** [comment]
> The screen size remains fixed at 1400 x 900. Even if I change resolution, it remains fixed at 1400 x 900. Why?

Do you have keyboard fingerprint protection enabled?

**Comment by Paola001011** [comment]
now works!!! Why? Thanks !!

**Comment by sereneblue** [comment]
> now works!!! Why? Thanks !!

There was an extra parenthesis in the keyboard fingerprint protection injection code. I'll release an immediate update later today to address this issue. 

I'll have to make some major improvements in the tests to catch these types of errors.
