### ISSUE TITLE
[bug] import/export regression (again)

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#244]
It might be perceived as ungrateful since being only a user and not actually contributing code but that is now the fourth time in recent times that I am opening an issue related to im/export after code changes. Would it not be possible to somehow test im/export after code changes and prior releasing?

It sort of seems that with the introduction of new features/settings such then slips the code base for im/export and causing import to fail since the new settings are not recognized.
___
Anyway, v0.12.16 exhibits on import

> Could not import settings

**Comment by sereneblue** [comment]
> It might be perceived as ungrateful since being only a user and not actually contributing code but that is now the fourth time in recent times that I am opening an issue related to im/export after code changes. Would it not be possible to somehow test im/export after code changes and prior releasing?
> 
> It sort of seems that with the introduction of new features/settings such then slips the code base for im/export and causing import to fail since the new settings are not recognized.
> 
> Anyway, v0.12.16 exhibits on import
> 
> > Could not import settings

It's fine. I did test importing/exporting before releasing but it seems I'm missing something. This is definitely something that will be improved in the v0.20.0 release. That's going to be a major transition so I'll need to rethink the import/export functionality.

Can you post your settings file? v0.12.16 removed some settings and added some new ones.

**Comment by n8v8R** [comment]
[chameleon_settings.zip](https://github.com/sereneblue/chameleon/files/3639959/chameleon_settings.zip)

**Comment by sereneblue** [comment]
Are you trying to import your settings into an older version of Chameleon (probably v0.12.15)? I didn't encounter an issue when trying to import with the latest version.

**Comment by n8v8R** [comment]
Maybe what happened, though it would seem inexplicable, that WX been updated to v0.12.16 and the profile been exported without restarting the browser and then imported into other browser installations where the WX been updated to v0.12.16 as well but not having restarted the browsers.

Having restarted all browser instances the import then worked.... Pardon the bother... :man_facepalming:

**Comment by sereneblue** [comment]
> Maybe what happened, though it would seem inexplicable, that WX been updated to v0.12.16 and the profile been exported without restarting the browser and then imported into other browser installations where the WX been updated to v0.12.16 as well but not having restarted the browsers.
> 
> Having restarted all browser instances the import then worked.... Pardon the bother... 🤦‍♂

No worries. :) I'll add a validation to check the version before importing. Thanks for reporting this issue!
