### ISSUE TITLE
chameleon changes operating system and browser name unexpectedly

### ISSUE THREAD

**Issue by sixpointzero** [sereneblue/chameleon#25]
I'll let the screenshots from amiunique.org and doileak.com explain.
This is before I've enabled chameleon.

![am_i_unique](https://user-images.githubusercontent.com/19494538/41981202-f903225a-7a45-11e8-9acc-1bfbdab3f19a.png)
![do_i_leak](https://user-images.githubusercontent.com/19494538/41981203-f932d860-7a45-11e8-8d9f-c614d80cad38.png)

This is after I enable Chameleon with only a custom user agent (Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0), protecting window.name (what does i do?), and screen size spoofing.

![am_i_unique_2](https://user-images.githubusercontent.com/19494538/41982361-e25f3ca2-7a48-11e8-8f45-afcdf5ed9fbd.png)
![do_i_leak_2](https://user-images.githubusercontent.com/19494538/41982362-e2911bbe-7a48-11e8-80d7-1ab3e7383b23.png)

I didn't want to change my browser name and the operating system but it seems that Chameleon does it for me. This behaviour **increases** my fingerprint uniqueness rather than decreasing it.

Please fix this unexpected behaviour.

Thanks for the awesome add-on.

**Comment by sereneblue** [comment]
This is similar to the issue mentioned here:
https://github.com/sereneblue/chameleon/issues/19.

I'm not sure what's the best way to resolve it.

**Comment by sereneblue** [comment]
@sixpointzero Can you test with v0.7.0 with a few profiles? When the extension first starts, it's still showing the original values (maybe a bug I need to look into), however, after changing the profile again, it seems to work.
