### ISSUE TITLE
Recaptcha can't solve if chameleon active 

### ISSUE THREAD

**Issue by Iquaridys** [sereneblue/chameleon#250]
When surfing the website and using google recaptcha, it can't be finished.

when i try to deactivate chameleon, the capcha resolves. (I've tried several times)

how to use chameleon without breaking google recaptcha?

**Comment by sereneblue** [comment]
Hi @Iquaridys, can you post your exported settings? There was an issue in the past with script injection, but if I recall correctly, it was addressed.

**Comment by Iquaridys** [comment]
no change in about: config , no white list
![Capture3](https://user-images.githubusercontent.com/23011078/67065513-9a442600-f13c-11e9-8d01-8c7d7de30d7b.PNG)
![Capture4](https://user-images.githubusercontent.com/23011078/67065514-9a442600-f13c-11e9-82dd-bf5d840488f8.PNG)
![Capture5](https://user-images.githubusercontent.com/23011078/67065515-9a442600-f13c-11e9-9254-dfd0367be1bc.PNG)
![Capture](https://user-images.githubusercontent.com/23011078/67065516-9adcbc80-f13c-11e9-8ab2-10b1e9322f10.PNG)
![Capture2](https://user-images.githubusercontent.com/23011078/67065517-9adcbc80-f13c-11e9-907f-361b032c439f.PNG)

**Comment by sereneblue** [comment]
@Iquaridys 

Thank you for posting your settings. For future reference, you can export your settings by navigating to the tab with the question mark.

I've done some testing and it seems it's profile spoofing that is causing an issue.  I'll take a thorough look at this and will hopefully have an update soon to resolve this issue; I imagine other users also affected by this.

**Comment by koalarosa** [comment]
Hi @sereneblue 

I have notice about this, when i use chameleon Recaptcha becomes very difficult and is required numerous times, it seems that it detects something and increases the level of difficulty, sometimes even 10 times requires that it be completed despite it has always been completed correctly. especially with mobile profiles it seems that it is even more difficult to complete it and even if it is completed show again.

**Comment by sereneblue** [comment]
Hi @koalarosa,

It's a bit difficult to test but I think the only solution is for recaptcha urls/iframes to be permanently exempt from Chameleon's spoofing, injection and headers. I'm still experimenting but I don't think I'll have anything ready for a v0.12.x release.

**Comment by sereneblue** [comment]
In v0.20.0, ReCAPTCHA is excluded from script injection/header spoofing. This is a slight improvement over the current version because it doesn't spoof the request headers either.

Ideally, this would mean that Chameleon doesn't interfere with ReCAPTCHA at all, however, depending on your settings (first party isolation, tracking protection, etc) you will still have issues with the captcha. ReCAPTCHA v2 is fundamentally hostile to privacy so there isn't much more I can do to alleviate this issue.
