### ISSUE TITLE
What To Do - TCP/IP Stack OS Fingerprint?

### ISSUE THREAD

**Issue by 0pLuS0** [sereneblue/chameleon#258]
Hello,

What can we do in regards to the TCP/IP Stack and OS Fingerprinting?

Chamelon doesn't seem to address this issue, not even sure it can be on the browser level.

From what I read in Linux this is suppose to work, for sysctl but not really sure?

```net.ipv4.ip_default_ttl = 128```

For Linux users is there anything we can do to spoof the TCP/IP Stack?

THANKS

**Comment by sereneblue** [comment]
As you've deduced, Chameleon can't address this issue. Although I haven't used this tool it may be helpful: https://github.com/segofensiva/OSfooler-ng.

**Comment by 0pLuS0** [comment]
@sereneblue thanks for that link, this looks like, I'll look into it.

**Comment by sereneblue** [comment]
Using the Tor Browser gives you most of the benefits of using TOR because you'd have a non-unique fingerprint. Tor Browser and virtual machines don't spoof your TCP/IP stack OS fingerprint so outside of modifying your kernel, the tool I linked above is probably the simplest way to address this particular issue.

You could also try daisy chaining some VPNs instead of using Tor.

**Comment by 0pLuS0** [comment]
Well I can't get python-nfqueue to compile and honestly I'm just not in the mood to try and figure it out...

So to compile and build this, it's a bit of a pain, that is why I brought up TOR, it looked like it might do the trick.

Because when I used TOR and went to this SITE: https://www.browserleaks.com/ip

The OS was spoofed...

Hmm

**Comment by sereneblue** [comment]
I did read something where using a proxy changed the fingerprint, so maybe that has something to do with it. I guess if you're using a VPN/Proxy (I suppose this includes Tor?) the fingerprint doesn't matter because it probably won't be your real fingerprint anyway.

**Comment by 0pLuS0** [comment]
Yes a Socks 5 Proxy is suppose to help.

I'm a Geek, meaning I get the deal when it comes to security, nothing is the "One" soultion to address and fix the problem, security and things like OS Fingerprint take several approaches and various layers to fix, but many people are not Geeks and are just your average users that don't understand this.

So with something like Chameleon and the OS Spoofing side of it, they are going to think this will completely spoof the OS from the browser with this addon and it doesn't.

Maybe from the browser side, there will never be this ability to have the protection from the TCP/IP stack, other then possibly never allowing java script, but I ask that as time goes on/forward with this project, if there's nothing that can ever be done here, that you will at least look at other projects out there to point people towards, making them realize the Insecuritys/Holes that an addon like Chamelon still makes people vulnerable to, to help them find more solutions, to have a more complete security approach going on.

So if you get time in the future, please add in various projects and things you learn in the README here on Github....

Keep up the great work on Chameleon, it's really nice...

THANKS

**Comment by sereneblue** [comment]
> Yes a Socks 5 Proxy is suppose to help.
> 
> I'm a Geek, meaning I get the deal when it comes to security, nothing is the "One" soultion to address and fix the problem, security and things like OS Fingerprint take several approaches and various layers to fix, but many people are not Geeks and are just your average users that don't understand this.
> 
> So with something like Chameleon and the OS Spoofing side of it, they are going to think this will completely spoof the OS from the browser with this addon and it doesn't.
> 
> Maybe from the browser side, there will never be this ability to have the protection from the TCP/IP stack, other then possibly never allowing java script, but I ask that as time goes on/forward with this project, if there's nothing that can ever be done here, that you will at least look at other projects out there to point people towards, making them realize the Insecuritys/Holes that an addon like Chamelon still makes people vulnerable to, to help them find more solutions, to have a more complete security approach going on.
> 
> So if you get time in the future, please add in various projects and things you learn in the README here on Github....
> 
> Keep up the great work on Chameleon, it's really nice...
> 
> THANKS

Thanks for the valuable feedback. This is something I definitely am going to address when [v0.20.0](https://github.com/sereneblue/chameleon/projects/1) is released. After the extension has been rewritten, I plan to work on a user friendly site that will replace the current wiki and expand it with additional resources.

**Comment by 0pLuS0** [comment]
@sereneblue YES ```additional resources```, that sums it up very nicely, just what we need.

I really appreciate it!

THANKS

**Comment by koalarosa** [comment]
Hi i tried some firefox addons for vpn and change the TCP/IP Stack OS Fingerprint, tor browser change too the TCP/IP Stack OS Fingerprint, chameleon do not change.

I add a site to test witch.valdikss.org.ru

If i have windows 7 installed and i use firefox and Chameleon

- With Firefox and Chameleon active show Windows 7 - 8
- With Tor Browser show like os linux and change usually (probably detect os of relay not my OS)
- With addons vpn like addons.mozilla.org/it/firefox/addon/urban-vpn/ show linux not my OS

I think Chameleon can a solution because tor browser and firefox vpn addons change OS detected by TCP/IP Stack OS Fingerprint.

I search a solution to solve the TCP/IP Stack OS Fingerprint in my firefox.
