### ISSUE TITLE
Custom User Agent - Custom Screen Size Spoof

### ISSUE THREAD

**Issue by martha833** [sereneblue/chameleon#260]
when I insert a custom user agent desktop, I can't change the screen size spoof.

For example, I insert custom user agent desktop of my choice and then I go to modify the custom screen size by entering any value. The resolution always remains on 1440 x 900. Why doesn't it work? Thanks.

**Comment by sereneblue** [comment]
HI @martha833, 

Is script injection enabled? If so, can you post your [settings](https://github.com/sereneblue/chameleon/wiki/About)?

**Comment by koalarosa** [comment]
@sereneblue 

It's possibile in custom useragent to add all fileds to set the other values to spoof ?

This is an image of another addons where you can add and edit all value to spoof
[https://i.imgur.com/WNzkEyZ.png](https://i.imgur.com/WNzkEyZ.png)

Here the link of addon
addons.mozilla.org/it/firefox/addon/user-agent-string-switcher/

Without addition field custom spoofing is not good and will be detected.

Thanks

**Comment by sereneblue** [comment]
Hi @koalarosa,

If you're using a user agent for a popular platform/browser like Firefox/Chrome/etc, those values will automatically be injected for you. I'll be streamlining how profile injection works so custom user agent support will be removed in v0.20.0. I'm open to adding common profiles that may be missing if there's support behind it like some of the Chromium-based browsers, Brave and Vivaldi.

**Comment by koalarosa** [comment]
Thanks
