### ISSUE TITLE
chameleon breaks dropbox

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#263]
## Expected Behavior
You can click on files to see them/download folders etc.
## Current Behavior
Clickin on files or folders does nothing, disabling chameleon fixes the issue
## Context (Environment)
FF 70.0.1 (64-bit) Linux

**Comment by sereneblue** [comment]
Hi @WPFilmmaker,

Can you post your settings?

**Comment by WPFilmmaker** [comment]
@sereneblue sorry had not included them as I thought they would be too long.
I pasted the parts excluding the whitelisted sites:
{
  "excluded": {
    "win": [
      true,
      true,
      true,
      false,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true
    ],
    "mac": [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true
    ],
    "linux": [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true
    ],
    "ios": [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true
    ],
    "android": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "all": [
      false,
      true,
      true,
      true,
      false
    ]
  },
  "headers": {
    "blockEtag": true,
    "disableAuth": false,
    "disableRef": false,
    "enableDNT": false,
    "rangeFrom": "",
    "rangeTo": "",
    "refererXorigin": 0,
    "refererTrimming": 0,
    "spoofAccept": true,
    "spoofAcceptLang": true,
    "spoofAcceptLangValue": "en-US,en;q=0.5",
    "spoofSourceRef": true,
    "spoofIP": false,
    "spoofIPValue": 0,
    "upgradeInsecureRequests": false,
    "useragent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
  },
  "ipRules": [],
  "settings": {
    "customScreen": "",
    "enableScriptInjection": true,
    "interval": 0,
    "kbDelay": "2",
    "limitHistory": false,
    "minInterval": null,
    "maxInterval": null,
    "notificationsEnabled": false,
    "protectKeyboardFingerprint": true,
    "protectWinName": false,
    "screenSize": "1366x768",
    "spoofAudioContext": true,
    "spoofClientRects": true,
    "timeZone": "America/New_York",
    "useragent": "randomDesktop",
    "useragentValue": "",
    "webSockets": "allow_all"
  },
  "version": "0.12.20",
  "whitelist": {
    "enabled": true,
    "enabledContextMenu": false,
    "defaultProfile": "none",
    "urlList": [
   
        ],
        "lang": "",
        "profile": "default",
        "spoofIP": "",
        "options": {
          "auth": false,
          "ip": false,
          "ref": false,
          "timezone": true,
          "websocket": false,
          "winName": false
        }
      }
    ]
  }
}

**Comment by sereneblue** [comment]
Hi @WPFilmmaker,

Thanks for posting your settings. I tested your configuration and it seems Dropbox doesn't load when you use a spoofed timezone. Can you try disabling that and let me know if you're still experiencing issues? If so, it's probably another script injection setting that's at fault. You may want to whitelist dropbox.

**Comment by WPFilmmaker** [comment]
@sereneblue disabling script injection solves the issue, so i will probably whitelist dropbox. One thing I never understood is, when such breaks happen, is it because of chameleon's implementation or the websites? Is there room for improvements on chameleon side, which could reduce the number of breakages or it is mostly a websites' issue you have no control over?

**Comment by sereneblue** [comment]
@WPFilmmaker It's a mix of both. Some websites depend on some features that may not behave as expected or available after changing some Chameleon settings. If a website has issues with script injection settings (audio context/client rects/timezone), it's probably best to whitelist it.

Timezone spoofing is a bit of a hack that can interfere with libraries that depend on the Date object. Ideally, this object shouldn't be touched at all, but there isn't an alternative to dynamically modify the timezone. I hope to improve this with v0.20.0, but I can't make any guarantees.
