### ISSUE TITLE
ETag tracking preventation working?

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#264]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
## Context (Environment)

* W10 Pro x_64 v1909 b18363.535
* FX x_64 71+ with maiden profile
* C 0.12.20
## Expected Behavior
ETag tracking prevention to work, i.e. reponse header injected with ETag: ""
## Current Behavior
The browser console displaying the ETag as served by the remote node. Not sure whether it is rather an issue with the FX browser console not printing what the JS client actually sees (after the response was lifted from the wire) but rather what the browser gets on the wire.

reference page https://bewisse.com/modheader/headers/

![Annotation 2019-12-12 175156](https://user-images.githubusercontent.com/13611490/70732144-32f3be00-1d08-11ea-96b7-0089cf41e21c.png)

## Relevant settings

{
  "excluded": {
    "win": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "mac": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "linux": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "ios": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "android": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "all": [
      false,
      false,
      false,
      false,
      false
    ]
  },
  "headers": {
    "blockEtag": true,
    "disableAuth": false,
    "disableRef": false,
    "enableDNT": false,
    "rangeFrom": "",
    "rangeTo": "",
    "refererXorigin": 0,
    "refererTrimming": 0,
    "spoofAccept": false,
    "spoofAcceptLang": false,
    "spoofAcceptLangValue": "",
    "spoofSourceRef": false,
    "spoofIP": false,
    "spoofIPValue": 0,
    "upgradeInsecureRequests": false,
    "useragent": "Mozilla/5.0 (X11; Linux; rv:71.0) Gecko/20100101 Firefox/71.0"
  },
  "ipRules": [],
  "settings": {
    "customScreen": "",
    "enableScriptInjection": true,
    "interval": 0,
    "kbDelay": 0,
    "limitHistory": false,
    "minInterval": null,
    "maxInterval": null,
    "notificationsEnabled": false,
    "protectKeyboardFingerprint": false,
    "protectWinName": false,
    "screenSize": "default",
    "spoofAudioContext": false,
    "spoofClientRects": false,
    "timeZone": "default",
    "useragent": "linux7",
    "useragentValue": "Mozilla/5.0 (X11; Linux; rv:71.0) Gecko/20100101 Firefox/71.0",
    "webSockets": "allow_all"
  },
  "whitelist": {
    "enabled": false,
    "enabledContextMenu": false,
    "defaultProfile": "none",
    "urlList": []
  }
}

**Comment by sereneblue** [comment]
Hi @n8v8R,

Your hunch is right; the developer console does not show the actual headers that Firefox will use. I ran into this issue as well while working on that feature but found the reason why it was designed that way [here](https://medium.com/requestly-docs/list-of-headers-not-allowed-to-be-modified-by-chrome-extensions-c850b5c02fff). This is covered by one of the [test cases](https://github.com/sereneblue/chameleon/blob/4062a4437b1b3919db3a86cdf566cb5186202c7b/test/headers/headersTest.js#L134), so I can confirm that the feature does work.
