### ISSUE TITLE
[feature suggestion] deal with client hints

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#265]
Unless I missed it by perusing the WX's source code I would reckon that client hints headers could provide (limited) information about the user client and thus aiding profiling efforts.

Perhaps worthwile to consider adding to the WX -> I would probably **suggest to cancel related request headers** unequivocally since such request headers could even be opted in by a HTML meta element with the http-equiv attribute

https://developer.mozilla.org/en-US/docs/Glossary/Client_hints
>Client Hints are a set of HTTP request header fields for proactive content negotiation allowing clients to indicate a list of device and agent specific preferences.
___
https://tools.ietf.org/html/draft-grigorik-http-client-hints-03#section-9

> Client Hints defined in this specification do not expose any new  information about the user's environment beyond what is already available to, and may be communicated by, the application at runtime via JavaScript - e.g. viewport and image display width, device pixel ratio, and so on.
> 
> However, implementors should consider the privacy implications of various methods to enable delivery of Client Hints - see "Sending Client Hints" section.  For example, sending Client Hints on all requests may make information about the user's environment available to origins that otherwise did not have access to this data (e.g. origins hosting non-script resources), which may or not be the desired outcome.  The implementors may want to provide mechanisms to control such behavior via explicit opt-in, or other mechanisms. Similarly, the implementors should consider how and whether delivery of Client Hints is affected when the user is in "incognito" or similar privacy mode.
___
https://tools.ietf.org/html/draft-grigorik-http-client-hints-03#section-2.2.1

>When a client receives Accept-CH, it SHOULD append the Client Hint headers that match the advertised field-values.  For example, based on Accept-CH example above, the client would append DPR, Width,Viewport-Width, and Downlink headers to all subsequent requests.

**Comment by n8v8R** [comment]
As far as I could gather the remote server can opt in the client into revealing host information with the following request headers:

* Device-Memory <sup>**[1]**</sup>
* DPR
* Viewport-Width
* Width
* Downlink
___
<sup>**[1]**</sup> https://github.com/w3c/device-memory#the-header

**Comment by sereneblue** [comment]
Thanks for bringing this to my attention; it's the first time I've heard about this. I don't have any plans to add new features to the current version of Chameleon, however, this does look like something that will appear in v0.20.0. ;)

**Comment by sereneblue** [comment]
Hi @n8v8R,

I looked into this a bit and it seems Firefox [doesn't support](https://caniuse.com/#feat=client-hints-dpr-width-viewport) client hints at the moment. I don't think Mozilla will change their stance anytime soon so it'd be a bit premature to add this functionality. If the situation changes, I'll update Chameleon to handle these headers.

**Comment by kekkc** [comment]
Seems [user-agent-string-switcher](https://addons.mozilla.org/de/firefox/addon/user-agent-string-switcher/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) has supported it. Was this ever re-evaluated / implemented?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Client_hints
https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers#client_hints
