### ISSUE TITLE
Netflix won't play (error F7121-1331-P7)

### ISSUE THREAD

**Issue by fayak** [sereneblue/chameleon#27]
Hi,

Using chameleon on Firefox 61 on archlinux, I can't watch any netflix video because I get the F7121-1331-P7 error code. As soon as I disable the extension, netflix works again.

**Comment by sereneblue** [comment]
According to Netflix, the error you're getting "usually indicates that information stored in your browser needs to be refreshed. Follow the troubleshooting steps below to resolve this problem." What settings did you enable?

**Comment by fayak** [comment]
Yup, I tried investigating through netflix's help pages, but the usual "please upgrade Firefox" and stuff like this were'nt enough. I came accross a thread on reddit solving the problem by fixing privacy settings and I thought about chameleon I newly installed. 
I left all the default settings, I actually haven't tweaked chameleon yet :/
I have no idea which setting of chameleon is responsible for that at the moment, I will try finding it tomorrow

**Comment by fayak** [comment]
I don't think so. I'll have to try again, maybe I have an old version of chameleon (I didn't download it on the firefox module store)? I probably should have checked that earlier

**Comment by sereneblue** [comment]
You can check the version of Chameleon by clicking the question mark in the menu of the popup. I recommend installing it via AMO so you can get updates.

**Comment by fayak** [comment]
I just removed it and re-installed it using [https://addons.mozilla.org/fr/firefox/addon/chameleon-ext/](addons.mozilla.org), without doing anything in the plugin I still can't watch any netflix video

**Comment by sereneblue** [comment]
With v0.6.8 I encountered the same issue but using v0.8.5 works. I strongly recommend adding `netflix.com` to your whitelist. Some profiles will cause issues even with v0.8.5. Please check the [wiki](https://github.com/sereneblue/chameleon/wiki/Whitelist) for more info.
