### ISSUE TITLE
navigator.ProductSub

### ISSUE THREAD

**Issue by patch-work** [sereneblue/chameleon#273]
## Context (Environment)

FF 68.4.1esr on MacOS

## Relevant settings

FF 68esr on Win10

## Current Behavior

navigator.ProductSub = 20010725

ref. https://github.com/sereneblue/chameleon/blob/8ad77722e1b23acde3fa5aa6c8bcb53f5a09638d/src/js/lib/spoof.js

## Expected Behavior

navigator.ProductSub = undefined

ref. https://developer.mozilla.org/en-US/docs/Web/API/Navigator/productSub

test. https://amiunique.org/fp

**Comment by sereneblue** [comment]
Hi @patch-work,

Thanks for bringing this to my attention. Seems like Firefox returns `20100101` for this value. This will be fixed in the next update. `undefined` is only for Internet Explorer.
