### ISSUE TITLE
Failing webbrowsertools Timezone test. iframe.contentWindow

### ISSUE THREAD

**Issue by bobsburgers** [sereneblue/chameleon#274]
## Expected Behavior
To change the Time zone to match my ip when `[normal] iframe.contentWindow` is the selected option. 

`https://webbrowsertools.com/timezone/`

It works for all 4 of the other options. including the two he mentions always work

## Current Behavior
It returns my actual timezone

## Relevant settings

I removed my whitelisted sites. So idk if that broke it. 
`{
  "excluded": {
    "win": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "mac": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "linux": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "ios": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "android": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "all": [
      false,
      false,
      false,
      false,
      false
    ]
  },
  "headers": {
    "blockEtag": false,
    "disableAuth": false,
    "disableRef": false,
    "enableDNT": false,
    "rangeFrom": "",
    "rangeTo": "",
    "refererXorigin": 0,
    "refererTrimming": 0,
    "spoofAccept": false,
    "spoofAcceptLang": false,
    "spoofAcceptLangValue": "",
    "spoofSourceRef": false,
    "spoofIP": false,
    "spoofIPValue": 0,
    "upgradeInsecureRequests": false,
    "useragent": ""
  },
  "ipRules": [],
  "settings": {
    "customScreen": "",
    "enableScriptInjection": true,
    "interval": 0,
    "kbDelay": 0,
    "limitHistory": false,
    "minInterval": null,
    "maxInterval": null,
    "notificationsEnabled": true,
    "protectKeyboardFingerprint": false,
    "protectWinName": false,
    "screenSize": "default",
    "spoofAudioContext": false,
    "spoofClientRects": false,
    "timeZone": "ip",
    "useragent": "real",
    "useragentValue": "",
    "webSockets": "block_3rd_party"
  },
  "version": "0.12.23",
  "whitelist": {
    "enabled": true,
    "enabledContextMenu": false,
    "defaultProfile": "none",
    "urlList": []
  }
}`
## Context (Environment)

firefox dev and firefox 72.0.1 (64-bit) windows 10

I am looking into solving this myself but have not seen the issue yet. Thought your more experienced eyes might do better.

**Comment by sereneblue** [comment]
Hi @bobsburgers,

This is something I've noticed while I was working on v0.20.0's timezone spoofing. It seems some sites have updated their tests. I'm actively working on a solution for this.

**Comment by sereneblue** [comment]
Hi @bobsburgers,

This issue is resolved in v0.20.0. It'd take a bit of time to backport the changes to the current version of Chameleon and with the next major release of Chameleon coming soon (March), I'd rather use the time to get it out in a timely manner instead.
