### ISSUE TITLE
TCP/IP Stack OS Fingerprint it's possible spoofing ?

### ISSUE THREAD

**Issue by koalarosa** [sereneblue/chameleon#275]
Hi i tried some firefox addons for vpn and change the TCP/IP Stack OS Fingerprint, tor browser change too the TCP/IP Stack OS Fingerprint, chameleon do not change.

I add a site to test witch.valdikss.org.ru

If i have windows 7 installed and i use firefox and Chameleon

    With Firefox and Chameleon active show Windows 7 - 8
    With Tor Browser show like os linux and change usually (probably detect os of relay not my OS)
    With addons vpn like addons.mozilla.org/it/firefox/addon/urban-vpn/ show linux not my OS

I think Chameleon can a solution because tor browser and firefox vpn addons change OS detected by TCP/IP Stack OS Fingerprint.

I search a solution to solve the TCP/IP Stack OS Fingerprint in my firefox.

**Comment by sereneblue** [comment]
Hi @koalarosa,

You've commented on a similar issue about this here:
https://github.com/sereneblue/chameleon/issues/258

If you're using a VPN/proxy, your TCP/IP fingerprint can change. However, Chameleon doesn't offer that functionality, and because it's a WebExtension there's nothing that I can do to spoof it.

**Comment by koalarosa** [comment]
Hi @sereneblue 

I can't find defense from TCP/IP fingerprint, I use openvpn vpn associated with firefox and chameleon but TCP/IP fingerprint always detects the operating system accurately.

I read from you a solution to combine more vpn but i do not know how i can do this, can you help me to try this solution please ?

Do you know if I create a virtual machine (Virtualbox) with different OS if TCP/IP fingerprint detect the virtual machine OS only or if TCP/IP fingerprint can detect host machine OS ?

If you have suggestion to protect me from TCP/IP fingerprint, i will appreciate you

Thanks

**Comment by sereneblue** [comment]
There is a tool I mentioned in the other thread, [OSfooler-ng](https://github.com/segofensiva/OSfooler-ng). I haven't used it but apparently it can spoof the TCP/IP fingerprint. If you're using Windows, you may be able to tunnel your network traffic through a small Linux virtual machine to spoof your fingerprint.

**Comment by koalarosa** [comment]
Hi @sereneblue 
OSfooler-ng seem to working with linux, I know Windows only, if you tell me if i can use OSfooler-ng on Windows i'll happy.

Can you give me more information about the tunnelling solution you have indicated to me?

Thanks

**Comment by sereneblue** [comment]
Hi @koalarosa,

If you're using Windows and a SOCKS5 proxy, your OS fingerprint will most likely appear as Linux. Some details about that can be found here: https://xbuba.com/questions/47797151

You could try creating a Linux virtual machine with a dedicated network adapter and routing all your traffic through it. You'd be able to use OSfooler-ng to spoof your fingerprint.

There's not much help I can offer here but I think you should be worried more about using Windows than the TCP/IP fingerprint.
