### ISSUE TITLE
[acknoledgement]This extension isn’t monitored by Mozilla. Make sure you trust the extension before you install it

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#277]
Today I noticed that on mozilla addons page the following message appear on chameleon's page. Is there any way you can have it monitored by mozilla? I think, given this is a privacy addon, that message could scare away potential users, which would be a pity :/

**Comment by sereneblue** [comment]
Hi @WPFilmmaker, 

Every non-recommended extension has that warning if I recall correctly. It is unfortunate but there it isn't anything I can do about it. After the release of v0.20.0, I'll be creating a user friendly site that people can link to instead to make Chameleon more approachable to casual users.
