### ISSUE TITLE
Chameleon breaks the Zeronet

### ISSUE THREAD

**Issue by slrslr** [sereneblue/chameleon#288]
Hello,

i am running Chameleon v0.12.24 on Firefox beta (v.73.0) and Windows 10.
Here is [my Chameleon configuration](https://privatebin.net/?2c8f95742d12a82d#3e6Msnv3qB3JtkM1MP3qSBZJmb5NUBn7dbpKQBBRQSKu).

In recent days i have found that https://zeronet.io web interface stopped properly working.
When i disabled Chameleon, it started working again. Here are more details please: https://github.com/HelloZeroNet/ZeroNet/issues/2412
Maybe some of the recent commits caused this issue. Can you take a look please?

**Comment by sereneblue** [comment]
Hi @slrslr,

Can you post the password for the pastebin link?

**Comment by slrslr** [comment]
@sereneblue i am sorry, it is "cc"

**Comment by sereneblue** [comment]
Hi @slrslr,

There was an experimental change that was accidentally included in the previous version while I was building the extension. Some of the script injection changes that are present in v0.20.0 don't seem to play nicely with ZeroNet. I've excluded localhost URLs from script injection so it's resolved in v0.20.0 as well. Thanks for reporting this issue! I will be releasing v0.12.25 soon.

**Comment by WPFilmmaker** [comment]
This also solves the issue of whatsappweb!
