### ISSUE TITLE
Recaptcha questions not loading

### ISSUE THREAD

**Issue by slrslr** [sereneblue/chameleon#289]
Hello,

Chameleon v0.12.24, Firefox beta (73.0)

anyone else having trouble with recaptcha? it show up, i click it, but it will not load the antispam challenge.

Example page with recaptcha: https://localbitcoins.com/accounts/login/

When i whitelisted the site in Chameleon, recaptcha started working.

If needed, here is [my Chameleon configuration](https://privatebin.net/?2c8f95742d12a82d#3e6Msnv3qB3JtkM1MP3qSBZJmb5NUBn7dbpKQBBRQSKu). (pass word is cc)

Similar, older issue: https://github.com/sereneblue/chameleon/issues/250

**Comment by sereneblue** [comment]
HI @slrslr,

v0.12.25 resolves this issue. This was caused by the issue I mentioned [here](https://github.com/sereneblue/chameleon/issues/288#issuecomment-583882526).
