### ISSUE TITLE
Possible to modify to automatically enable after install?

### ISSUE THREAD

**Issue by maxiedaniels** [sereneblue/chameleon#290]
I’ve tried modifying the background.js file to startup with randomDesktop by default. However after launching a fresh Firefox and I installing the plugin, the UI shows random desktop selected, but the UA doesn’t actually spoof until I hit refresh on the UI.

Why is this?

**Comment by sereneblue** [comment]
Hi @maxiedaniels,

Thanks for opening this issue; you've found a bug! Default settings weren't properly being set by Chameleon. I do have a fix for this so it will be resolved in the next update. Just curious, are you trying to use Chameleon with a browser automation library?
