### ISSUE TITLE
Did the format change?

### ISSUE THREAD

**Issue by maxiedaniels** [sereneblue/chameleon#295]
It seems the format is .ts now instead of .js files, and I can't get Selenium+geckodriver to load the extension.. is there a newer format you've switched to?

**Comment by sereneblue** [comment]
Chameleon v0.20.0 is written using TypeScript; this requires a build process to get JS source files.

You can try using the xpi from the releases page or you can install NodeJS, checkout the branch, and run `npm run build`. The `dist` folder will contain JS source files.
