### ISSUE TITLE
Add option to disable MediaDevices.enumerateDevices()

### ISSUE THREAD

**Issue by Megver83** [sereneblue/chameleon#307]
When I go to https://browserleaks.com/webrtc I see that the site can still detect the existence of my camera and microphone. However, Tor Browser doesn't have that issue. I was about to replace Tor with my FF derivative (Iceweasel) thanks to extensions like Chameleon but this is one of the issues that still keeps me in TB. Anyways, that's my problem, but I thought it would be cool to see that feature in Chameleon, in that way privacy could be much more enhanced against fingerprinting.

Hope this feature gets into this awesome extension, thanks for your work.

**Comment by sereneblue** [comment]
Hi @Megver83,

Thanks for the great suggestion! I've added this as a feature in v0.20.0 which will be officially released before the end of the month. This feature is in the alpha 3 dev build, however, there's a small bug I noticed just after releasing alpha 3 so it doesn't work until you toggle another option on the same tab.  It's patched now, but the fix will be released in the next dev build. **Please use a separate Firefox installation if you'd like to test it**.
