### ISSUE TITLE
Chameleon breaks Google Calendar & Google Keep

### ISSUE THREAD

**Issue by sleesong** [sereneblue/chameleon#308]
## Expected Behavior (On Firefox, Windows PC)
Google Calendar & Google Keep load & work properly.
## Current Behavior (On Firefox, Windows PC)
Google Calendar will load, however "Reminders" under my calendar (alongside the calendar) does not load and remains in a perpetual "sync" icon.
Google Keep will also load the website, however does not load and remains in perpetual "sync". This breaks google keep completely.

NOTE: Whitelisting calendar.google.com & keep.google.com will restore these websites' functionality.

## Relevant settings

Nothing too special. Privacy is set to strict. Everything else is set to default.

## Context (Environment)

Firefox 75.0 (64-bit) Windows 10 Pro Version 1909

**Comment by sereneblue** [comment]
Hi @sleesong,

Can you post your exported settings?

**Comment by sleesong** [comment]
Hi sereneblue,

I'm not very savvy with back-end and programming but I've here's the
pref.js file. Hope that's what you need


user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200403170909");
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupRolloutPrefs.app.normandy.onsync_skew_sec",
3300);
user_pref("app.normandy.startupRolloutPrefs.layout.css.serialize-grid-implicit-tracks",
true);
user_pref("app.normandy.user_id", "9ab16d85-7cdb-43c8-8ce1-6b0f2440e0ca");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.auto.migrated", true);
user_pref("app.update.download.attempts", 0);
user_pref("app.update.elevate.attempts", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer",
1587241591);
user_pref("app.update.lastUpdateTime.background-update-timer", 1587241351);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer",
1587241711);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails",
1587244831);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1587241110);
user_pref("app.update.lastUpdateTime.search-engine-update-timer",
1587240990);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes",
1587241471);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1587237062);
user_pref("app.update.lastUpdateTime.xpi-signature-verification",
1587241831);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.editDialog.confirmationHintShowCount", 11);
user_pref("browser.cache.disk.amount_written", 1708545);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.hashstats_reported", 1);
user_pref("browser.contentblocking.category", "strict");
user_pref("browser.ctrlTab.recentlyUsedOrder", false);
user_pref("browser.download.lastDir", "C:\\Users\\Stuart
Leesong\\Downloads");
user_pref("browser.download.panel.shown", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 92);
user_pref("browser.newtabpage.activity-stream.impressionId",
"{8b60e342-1be9-41f8-ae41-2a525f9a9afc}");
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions",
"{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime",
"1587244568040");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime",
"1587246361040");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime",
"1587244600306");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime",
"1587248200306");
user_pref("browser.search.cohort", "nov17-1");
user_pref("browser.search.region", "AU");
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID",
"20200403170909");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 1113);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.buildID", "20200403170909");
user_pref("browser.startup.homepage_override.mstone", "75.0");
user_pref("browser.startup.lastColdStartupCheck", 1587068161);
user_pref("browser.startup.page", 3);
user_pref("browser.uiCustomization.state",
"{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"downloads-button\",\"support_lastpass_com-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"_3579f63b-d8ee-424f-bbb6-6d0ce3285e6a_-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"support_lastpass_com-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"bypasspaywalls_bypasspaywalls_weebly_com-browser-action\",\"_contain-facebook-browser-action\",\"_3579f63b-d8ee-424f-bbb6-6d0ce3285e6a_-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":4}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.placeholderName.private", "Google");
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.tipShownCount.searchTip_redirect", 1);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime",
"1584331343981");
user_pref("distribution.iniFile.exists.appversion", "75.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "2f86f83a354840bfa56944367e2ac359");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1587241592);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200403170909");
user_pref("extensions.lastAppVersion", "75.0");
user_pref("extensions.lastPlatformVersion", "75.0");
user_pref("extensions.pendingOperations", true);
user_pref("extensions.pocket.settings.test.panelSignUp", "control");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.@contain-facebook",
true);
user_pref("
extensions.webextensions.ExtensionStorageIDB.migrated.bypasspaywalls@bypasspaywalls.weebly.com",
true);
user_pref("
extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org",
true);
user_pref("
extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org",
true);
user_pref("
extensions.webextensions.ExtensionStorageIDB.migrated.support@lastpass.com",
true);
user_pref("
extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net",
true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{3579f63b-d8ee-424f-bbb6-6d0ce3285e6a}",
true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org
\":\"d31bd663-68d5-4be4-89c2-18775e6a91fb\",\"formautofill@mozilla.org
\":\"789e721a-60f5-468b-a5ad-7608fdfebf94\",\"screenshots@mozilla.org
\":\"e253b224-911c-4e0d-8275-41b008cfb3e1\",\"webcompat-reporter@mozilla.org
\":\"cd481f47-c96a-4ff2-8306-60926e746b35\",\"webcompat@mozilla.org
\":\"838b8ec6-ceca-4109-b647-da251ffec6e9\",\"default-theme@mozilla.org
\":\"7c1556e6-60ba-4326-a831-2257e097bd8c\",\"google@search.mozilla.org
\":\"a57e81c3-7964-4475-9c73-71907542583b\",\"
amazondotcom@search.mozilla.org
\":\"52c4a258-fc65-416d-b181-eecb0ee483ed\",\"bing@search.mozilla.org
\":\"1ce6e52d-fdfa-4b7d-a983-847bd5e78fdc\",\"ddg@search.mozilla.org
\":\"a3d30c41-b539-491e-9297-01239e6959b1\",\"ebay@search.mozilla.org
\":\"0b291279-70ee-4a51-99d1-bc047601ceee\",\"twitter@search.mozilla.org
\":\"a75748d6-5e30-46d8-b7db-30dd53c017e7\",\"wikipedia@search.mozilla.org
\":\"8a9b9ce4-495f-4f83-8a34-152cd6b41d30\",\"amazon@search.mozilla.org
\":\"ae2e7941-f8b3-4293-b20e-e243c026d745\",\"support@lastpass.com
\":\"e08b1a36-4246-4287-a06c-debeb51f1cd4\",\"uBlock0@raymondhill.net
\":\"0ddf1278-a50a-4eab-b053-491681ca5386\",\"
bypasspaywalls@bypasspaywalls.weebly.com
\":\"2322788d-a80a-45a1-8849-6b6de6606b3e\",\"@contain-facebook\":\"65a1d437-c88d-4776-becf-08d9a9d36d2d\",\"{3579f63b-d8ee-424f-bbb6-6d0ce3285e6a}\":\"0869c172-aea3-4e01-be36-c2217aae1087\"}");
user_pref("font.internaluseonly.changed", false);
user_pref("gfx.crash-guard.status.wmfvpxvideo", 3);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "75.0");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x0416");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "10.18.15.4281");
user_pref("idle.lastDailyNotification", 1587241140);
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-msvc-x64");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1584331669);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200403170909");
user_pref("media.gmp-manager.lastCheck", 1587068261);
user_pref("media.gmp-widevinecdm.abi", "x86_64-msvc-x64");
user_pref("media.gmp-widevinecdm.lastUpdate", 1585379660);
user_pref("media.gmp-widevinecdm.version", "4.10.1582.2");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1586684583);
user_pref("places.history.expiration.transient_current_max_pages", 87285);
user_pref("pref.privacy.disable_button.tracking_protection_exceptions",
false);
user_pref("print.printer_Adobe_PDF.print_bgcolor", false);
user_pref("print.printer_Adobe_PDF.print_bgimages", false);
user_pref("print.printer_Adobe_PDF.print_duplex", 0);
user_pref("print.printer_Adobe_PDF.print_edge_bottom", 0);
user_pref("print.printer_Adobe_PDF.print_edge_left", 0);
user_pref("print.printer_Adobe_PDF.print_edge_right", 0);
user_pref("print.printer_Adobe_PDF.print_edge_top", 0);
user_pref("print.printer_Adobe_PDF.print_evenpages", true);
user_pref("print.printer_Adobe_PDF.print_footercenter", "");
user_pref("print.printer_Adobe_PDF.print_footerleft", "&PT");
user_pref("print.printer_Adobe_PDF.print_footerright", "&D");
user_pref("print.printer_Adobe_PDF.print_headercenter", "");
user_pref("print.printer_Adobe_PDF.print_headerleft", "&T");
user_pref("print.printer_Adobe_PDF.print_headerright", "&U");
user_pref("print.printer_Adobe_PDF.print_in_color", true);
user_pref("print.printer_Adobe_PDF.print_margin_bottom", "0.5");
user_pref("print.printer_Adobe_PDF.print_margin_left", "0.5");
user_pref("print.printer_Adobe_PDF.print_margin_right", "0.5");
user_pref("print.printer_Adobe_PDF.print_margin_top", "0.5");
user_pref("print.printer_Adobe_PDF.print_oddpages", true);
user_pref("print.printer_Adobe_PDF.print_orientation", 0);
user_pref("print.printer_Adobe_PDF.print_page_delay", 50);
user_pref("print.printer_Adobe_PDF.print_paper_data", -1);
user_pref("print.printer_Adobe_PDF.print_paper_height", " 11.00");
user_pref("print.printer_Adobe_PDF.print_paper_name", "");
user_pref("print.printer_Adobe_PDF.print_paper_size_unit", 0);
user_pref("print.printer_Adobe_PDF.print_paper_width", "  8.50");
user_pref("print.printer_Adobe_PDF.print_resolution", 1200);
user_pref("print.printer_Adobe_PDF.print_reversed", false);
user_pref("print.printer_Adobe_PDF.print_scaling", "  1.00");
user_pref("print.printer_Adobe_PDF.print_shrink_to_fit", true);
user_pref("print.printer_Adobe_PDF.print_to_file", false);
user_pref("print.printer_Adobe_PDF.print_to_filename", "");
user_pref("print.printer_Adobe_PDF.print_unwriteable_margin_bottom", 0);
user_pref("print.printer_Adobe_PDF.print_unwriteable_margin_left", 0);
user_pref("print.printer_Adobe_PDF.print_unwriteable_margin_right", 0);
user_pref("print.printer_Adobe_PDF.print_unwriteable_margin_top", 0);
user_pref("print_printer", "Adobe PDF");
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.resistFingerprinting", true);
user_pref("privacy.sanitize.pending",
"[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("privacy.userContext.enabled", true);
user_pref("privacy.userContext.extension", "@contain-facebook");
user_pref("privacy.userContext.ui.enabled", true);
user_pref("privacy.window.maxInnerHeight", 767);
user_pref("privacy.window.maxInnerWidth", 1365);
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x0416");
user_pref("sanity-test.driver-version", "10.18.15.4281");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20200403170909");
user_pref("sanity-test.webrender.force-disabled", false);
user_pref("security.remote_settings.crlite_filters.checked", 1587068682);
user_pref("security.remote_settings.intermediates.checked", 1587068682);
user_pref("security.sandbox.content.tempDirSuffix",
"{fa63b2be-b932-4833-be6d-78e85f03915f}");
user_pref("security.sandbox.plugin.tempDirSuffix",
"{4bfc7857-96f0-4097-a11c-9e883b35c779}");
user_pref("services.blocklist.addons.checked", 1587129130);
user_pref("services.blocklist.gfx.checked", 1587068682);
user_pref("services.blocklist.pinning.checked", 1587068682);
user_pref("services.blocklist.plugins.checked", 1587068682);
user_pref("services.settings.clock_skew_seconds", -12);
user_pref("services.settings.last_etag", "\"1587160608365\"");
user_pref("services.settings.last_update_seconds", 1587241483);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check",
1587068682);
user_pref("services.settings.main.cfr-fxa.last_check", 1587068682);
user_pref("services.settings.main.cfr.last_check", 1587068682);
user_pref("services.settings.main.fxmonitor-breaches.last_check",
1587068682);
user_pref("services.settings.main.hijack-blocklists.last_check",
1587068682);
user_pref("services.settings.main.language-dictionaries.last_check",
1587068682);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check",
1587068682);
user_pref("services.settings.main.public-suffix-list.last_check",
1587068682);
user_pref("services.settings.main.sites-classification.last_check",
1587068682);
user_pref("services.settings.main.tippytop.last_check", 1587068682);
user_pref("services.settings.main.url-classifier-skip-urls.last_check",
1587068682);
user_pref("services.settings.main.whats-new-panel.last_check", 1587068682);
user_pref("services.settings.security.onecrl.checked", 1587068682);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("signon.rememberSignons", false);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1587068340);
user_pref("toolkit.startup.last_success", 1587068159);
user_pref("toolkit.telemetry.cachedClientID",
"c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200403170909");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not
found.");

**Comment by sereneblue** [comment]
Hi @sleesong,

No worries! Unfortunately, that's the Firefox preferences file. I was referring to Chameleon's settings. You can transfer your Chameleon settings between Firefox installations by exporting/importing them in the popup tab below.

![image](https://user-images.githubusercontent.com/14242625/79673527-678cf000-81a8-11ea-80fe-9acf3b85796f.png)

**Comment by sleesong** [comment]
Oh right sorry, you meant the extension's settings.

Here you go! I've attached the .json file

**Comment by sereneblue** [comment]
@sereneblue It seems Github doesn't post attachments if you reply via email. Can you try using something like https://hastebin.com/?

**Comment by sleesong** [comment]
No worries, here you go
https://hastebin.com/sezazebego.json

**Comment by sereneblue** [comment]
@sleesong 

I've found the cause of the issue: `Protect window.name`. It seems Google relies on this value, so it should not be cleared. v0.12.27 is the last release of the legacy version of Chameleon so I won't be able to push out an update to specifically address this issue, however, v0.20.0 will contain a fix. ETA before the end of the month. Thanks for reporting this issue!

**Comment by sleesong** [comment]
Oh wow, amazing. Keep up the good work! I love the extension :) Thanks
@sereneblue
