### ISSUE TITLE
Chameleon v0.20.0 beta

### ISSUE THREAD

**Issue by linksky56** [sereneblue/chameleon#312]
Hello,

Just installed the Chameleon v0.20.0 beta. Love it!!!
The UI is a 1000x more friendly and cleaner. Thank you!! Thank you!!!

So far have only found a couple glitches.

disqus.com comments are not loading/loading properly on web sites.
Here are some of the sites, I'm having problems with disqus comments.
politicalwire.com
thehill.com
mediaite.com

The other glitch, is the custom interval timer on the user-agent doesn't work.
The other ones, 1min., 5 min., 10, 20, 30 40 minutes etc.... work perfect.

Thanks again, for the new and improved Chameleon. Its Awesome!!!

**Comment by sereneblue** [comment]
Hi @linksky56,

Thanks for the kind words and valuable feedback. :) The fixes will be released in the next developer build v0.20.0-rc1.
