### ISSUE TITLE
Whitelist page appears broken in v0.20

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#324]
I was trying to check whether lives on fb are still broken and I tried to 'open in whitelist' facebook.com, the result is in the screenshot below:

The page is not functional at all, as there is no way to click 'ok' or 'cancel' and the only way to leave the page is close the tabl. 'Name' is also partially cut.

It seems that whitelist page is broken?

https://i.imgur.com/eeaLzjO.png

Chameleon 0.20 FF 75 Linux, Lubuntu 18.04

edit: after some tweaking it seems that it is a matter of zoom, for whatever reason chameleon text in that page is zoomed in, you need to zoom out (but then text is very small, not an ideal solution).

**Comment by sereneblue** [comment]
Hi @WPFilmmaker, thanks for reporting this issue. I've updated the modals on the options page so that they're easier to manage when the zoom setting is high. This should be fixed in the next update.

**Comment by WPFilmmaker** [comment]
Can confirm this is fixed:)
