### ISSUE TITLE
v20 Timezone spoofing break site

### ISSUE THREAD

**Issue by Minimalist73** [sereneblue/chameleon#325]
## Expected Behavior
Should spoof Timezone with a preset values (IP or static TZ)

## Current Behavior
Make page not loading things (for example, https://genius.com/ do not load properly with this feature enabled, when disabled the page work).

## Relevant settings

Done on a fresh Firefox profile with everything default except TZ enabled on "IP"

## Context (Environment)

Tested on Firefox 75 and ESR 68.7.0
Tested on Debian 10 and Fedora 30

**Comment by edwardont** [comment]
Confirmed on linux mint 19.1 Tessa 64-bit
Kernel Linux 4.15.0-99-generic x86_64
firefox 75, all up to date
breaks tutanota.com
switching timezone spoofing on/off recreates issue

here is tutanota.com bug report - sorry no copy/paste but hope its a start

![Screenshot at 2020-05-01 17-58-31](https://user-images.githubusercontent.com/49967953/80824114-b3428f00-8bd5-11ea-9b31-2a9b064dc254.png)

![Screenshot at 2020-05-01 17-58-43](https://user-images.githubusercontent.com/49967953/80824130-b9387000-8bd5-11ea-9a5f-7b43a0a05343.png)

![Screenshot at 2020-05-01 17-58-49](https://user-images.githubusercontent.com/49967953/80824300-10d6db80-8bd6-11ea-863c-c2407775a70d.png)

![Screenshot at 2020-05-01 17-58-55](https://user-images.githubusercontent.com/49967953/80824308-146a6280-8bd6-11ea-923e-2e8b9ea2aed1.png)

**Comment by Pintoski** [comment]
I confirm Spoofing Timezone (IP), breaks Youtube. 
Please fix this issue immediately.

**Comment by sereneblue** [comment]
Hi @Minimalist73, thanks for opening this issue. Thanks to the efforts of @h6a8ke1k, I was able to identify the issue and fix in v0.20.2.

@edwardont This was a separate issue that I've also managed to fix in v0.20.2.

@Pintoski This should also be fixed.
