### ISSUE TITLE
No text loading and nothing working 0.20.0

### ISSUE THREAD

**Issue by sipher123** [sereneblue/chameleon#330]
# Prerequisites

- [x] I am running the latest version (0.20.0)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
Launching the app for the first time, especially on a new installation of the latest version of Firefox and beginning to change the configuration… The app should allow me to do what the app does such as a homepage and each tab such as the user agent switcher.

## Current Behavior
Other than the green and white layout and some icons, no text is loaded (proven by hovering over the blank spaces) and no buttons work appropriately or not at all from the settings page.
![Screenshot_20200501-215326](https://user-images.githubusercontent.com/64660594/80840935-4db2ca80-8bf6-11ea-9c31-2f8e7774b2ec.jpg)
![Screenshot_20200501-215319](https://user-images.githubusercontent.com/64660594/80840957-5a372300-8bf6-11ea-8b3f-626b8360a6f4.jpg)
![Screenshot_20200501-215304](https://user-images.githubusercontent.com/64660594/80840968-628f5e00-8bf6-11ea-9799-2f6459e01e07.jpg)

## Relevant settings
Cannot download the default configuration post-installation because that button doesn't work.

## Context (Environment)
Android 8, Firefox for Android 68.7.0, fresh installation (and other scenarios as well before I reset the app or reinstalled from PlayStore). Note: I have toggled the fonts and it expectedly didn't impact the issue.

**Comment by sereneblue** [comment]
Hi @sipher123, thanks for reporting this issue. This was caused because of the fingerprint detection panel. I removed that functionality for Android devices. The fix will be available in the next update.
