### ISSUE TITLE
Chameleon break sites while all options are allowing

### ISSUE THREAD

**Issue by SunnyMoo** [sereneblue/chameleon#331]
Hi, with the new 0.20 version I reset all settings to start from scratch but I've got a breaking bug.

Bug is, if I enable Chameleon extension even with all options to default or allowing, it breaks some websites.
It's like Chameleon triggers an hidden option when enabled.
Whitelisting, settings reset, reinstall has no success.

Win10x64 latest FF latest Chameleon.
Here's screens of my settings. I tried to enable or disable but nothing changes.

![Annotation 2020-05-01 225434](https://user-images.githubusercontent.com/50081326/80841672-6e2b5680-8bef-11ea-8a6d-989deebc6f35.png)
![Annotation 2020-05-01 225459](https://user-images.githubusercontent.com/50081326/80841675-6f5c8380-8bef-11ea-9ced-808e076b5418.png)
![Annotation 2020-05-01 225520](https://user-images.githubusercontent.com/50081326/80841677-6ff51a00-8bef-11ea-844a-09b064d941e1.png)
![Annotation 2020-05-01 225541](https://user-images.githubusercontent.com/50081326/80841679-708db080-8bef-11ea-9bc6-25cea0cf44d8.png)
![Annotation 2020-05-01 225627](https://user-images.githubusercontent.com/50081326/80841682-708db080-8bef-11ea-8370-bffdd8667ac5.png)
![Annotation 2020-05-01 225644](https://user-images.githubusercontent.com/50081326/80841684-71264700-8bef-11ea-9879-fb94bb83a40a.png)

Thanks !

**Comment by sereneblue** [comment]
Hi @SunnyMoo, 

Can you let me know if this is happening with the latest version (v0.20.1) and if so, can you list which sites are breaking?

**Comment by ArujBarbaross** [comment]
Hi, 
Not sure it's the same issue, but for example [here](https://pikabu.ru/story/iz_rasskaza_znakomogo_seo_7417783#comments) the expand/collapse comment functionality gets broken. I'm currently using version 0.20.1.2.

**Comment by darkneptune** [comment]
> 
> 
> Hi @SunnyMoo,
> 
> Can you let me know if this is happening with the latest version (v0.20.1) and if so, can you list which sites are breaking?

it breaks:
https://cloud.disroot.org/

**Comment by SunnyMoo** [comment]
@darkneptune You should take some screenshots as this website needs to log in.

@sereneblue I don't understand my post disappeared.
Here we go again.

Hi @sereneblue !
Just updated to last AMO version shown as v0.20.1 in Chameleon.
Everything seems fine except https://my.netatmo.com/app/station which is broken as soon as I enable chameleon in extension panel. Changing settings or whitelisting has no effect.
Here's the whitelist rule and what Netatmo looks like with chameleon disabled/enabled.
![Annotation 2020-05-02 172535](https://user-images.githubusercontent.com/50081326/80868434-10981800-8c8a-11ea-9862-1ee7b222774f.png)
![Annotation 2020-05-02 172254](https://user-images.githubusercontent.com/50081326/80868435-142b9f00-8c8a-11ea-97d2-4e637c401bee.png)
![Annotation 2020-05-02 172453](https://user-images.githubusercontent.com/50081326/80868437-14c43580-8c8a-11ea-8413-c36d3a1a6f54.png)

**Comment by sereneblue** [comment]
@ArujBarbaross I'm also experiencing the same issue with this site. v0.20.2 doesn't resolve this but I hope to diagnose and have a fix available in the next update.

@darkneptune v0.20.2 should resolve the issue with https://cloud.disroot.org/ if you were using the timezone spoofing option. Can you provide more information about the issues with Spotify? Keep in mind that some profiles may not work with Spotify (ex IE 11 is not supported).

@SunnyMoo Can you test netatmo with v0.20.2?

**Comment by darkneptune** [comment]
@sereneblue Currently, with v 0.20.2, spotify is working good again too. Thanks. :)

**Comment by SunnyMoo** [comment]
@sereneblue Sadly v0.20.2 doesn't fix netatmo regardless of settings and whitelist.

**Comment by sereneblue** [comment]
Thanks @SunnyMoo for confirming. I'll look into this issue soon.

**Comment by SunnyMoo** [comment]
Sure, no problem. Thank you !

**Comment by sereneblue** [comment]
@SunnyMoo Can you test this with v0.20.3? I believe the issue may have been caused by the fingerprint detection panel.

@ArujBarbaross v0.20.3 seems to resolve the issue with this site.

**Comment by SunnyMoo** [comment]
@sereneblue you did it ! Netatmo now works as intended, through usual settings with whitelist.
Great and reactive support you provide here, many would take example on you !
Thank you very much for your work.

**Comment by darkneptune** [comment]
https://open.spotify.com works bad again :(

**Comment by sereneblue** [comment]
@darkneptune What browser profile is being used and can you attach your settings?
