### ISSUE TITLE
v0.20.0 generates errors in the console

### ISSUE THREAD

**Issue by h6a8ke1k** [sereneblue/chameleon#332]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Expected Behavior
No errors in the console.

## Current Behavior
This message appears on every web page:
```
TypeError: `target` argument of Proxy must be an object, got undefined
```

This message, mentioned by another issue, appears on some web pages:
```
TypeError: getTime method called on incompatible Object
```
The reason for the second message is that some js on those pages use `Date.prototype.getTime`.

## Context (Environment)

Firefox 68 ESR

**Comment by sereneblue** [comment]
Hi @h6a8ke1k,

Can you list the site that these errors appear on?

**Comment by h6a8ke1k** [comment]
For the first error: ``TypeError: `target` argument of Proxy must be an object, got undefined``
This error appears on every page, including `about:blank`.
I investigated the source of the error, and hope that it helps:
```
        // Proxy access to objects for fingerprint panel in popup
        window.AudioContext = new Proxy(window.AudioContext, {  
          construct: function(target, args) {
            if (!window.Nnrqkx_FP_DETECTED.fpPanel.audioContext) {
              window.Nnrqkx_FP_DETECTED.fpPanel.audioContext = true;
              window.top.postMessage({fp: 'audioContext', id: "Cnjfbqda"}, "*");
            }
            return new target(...args);
          }
        });
```
the error is generated from the above lines.

**Comment by h6a8ke1k** [comment]
The second error is `TypeError: getTime method called on incompatible Object`
It appears on some of the websites, an example is `https://amiunique.org/`.
You can investigate the reason. I am not accustomed to js debugging in Firefox. (Previously always using Chrome to debug.)

Another website mentioned in another issue is `https://genius.com/`, and I think I have found the issue.
There is code checking `String(new Date(NaN))`, which should return `Invalid Date` normally. After timezone spoofing, this error appears.

Hope the information helps.

**Comment by sereneblue** [comment]
Thanks for the detailed report @h6a8ke1k!

While you can disable WebAudio, it's generally better to feed trackers fake data. Not having any data could flag you as a unique individual and disabling features can cause some sites to break. The next update should resolve the issues with the audio context and fixes the bug with the Date object on `amiunique.org`. Please let me know if you're still experiencing issues after v0.20.2 is released.
