### ISSUE TITLE
v0.20.0 interferes with uBlock Origin's "prevent webrtc from leaking local IP address"

### ISSUE THREAD

**Issue by h6a8ke1k** [sereneblue/chameleon#333]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Expected Behavior
Using uBO with the option "prevent webrtc from leaking local IP address" together with Chameleon should not leak webrtc local ip address.

## Current Behavior
Using uBO with the option "prevent webrtc from leaking local IP address" on and using Chameleon will make uBO's prevention not effective, causing local IP address leak through webrtc.
Disabling Chameleon and use uBO alone can fix the issue.
So it seems that some of the Chameleon's scripts make uBO's webrtc block not working.

## Context (Environment)

Firefox 68 ESR

**Comment by sereneblue** [comment]
Hi @h6a8ke1k, I believe this is related to #334. It was a bug in Chameleon v0.20.0 that resets some browser preferences when it was initially loaded. You should be able to resolve this by setting the option again in uBlock or use Chameleon to control this feature, `Options > Standard > WebRTC Policy > Only use Public interface (best)`. Please let me know if you're still experiencing issues.

**Comment by h6a8ke1k** [comment]
Hi,
Thanks for you prompt response. I am using the official version (0.20.0.7) from addons.mozilla.org and the issue is not resolved by the methods you suggested.
Setting the option again in uBlock Origin does not have any effect. And the `media.peerconnection.enabled` flag is still true.
Manually setting the `media.peerconnection.enabled` to false has effect, but only temporary. Disabling Chameleon and enabling again will automatically reset the `media.peerconnection.enabled` flag to true.
Disabling Chameleon while uBO remains open will immediately make `media.peerconnection.enabled` change to false.
Interestingly, I cannot find `WebRTC Policy` in `Options > Standard` in Chameleon. My browser language is set to Chinese. Is that a potential reason? (Should not, because the layout is the same.)

**Comment by sereneblue** [comment]
Hi @h6a8ke1k, 

Can you try with v0.20.1? `media.peerconnection.enabled` is controlled by the `Disable WebRTC` option in Chameleon. That option can be found on the options tab below.

![image](https://user-images.githubusercontent.com/14242625/80855653-f66e2380-8c10-11ea-92ba-6e0a6e2b03f4.png)

`WebRTC Policy` is not shown if `Disable WebRTC` is enabled.

**Comment by h6a8ke1k** [comment]
With v0.20.1, the webrtc config is preserved. Thanks!
However, neither "Disable WebRTC" nor "WebRTC Policy" appears in that tab.
I tried to change the extension id in `manifest.json` and load using debug mode, and the options appear.
Maybe it is because I used old version (0.12.x) before? The storage may be preserved and the new version cannot correctly migrate the old version config.

**Comment by h6a8ke1k** [comment]
These options appear now. The issue should have been resolved. Thanks!

**Comment by h6a8ke1k** [comment]
I found where the problem is.
After enabling `blockMediaDevices` in the `injection` tab in Chameleon, the `Disable WebRTC` option disappears in `standard` tab. Maybe it is designed intentionally, but disabling media devices does not cause WebRTC to be disabled. (Tested in this version as well.)
So maybe you can make disabling media devices disable webrtc at the same time automatically, or you still make webrtc options available when media devices are disabled.
Thanks!

**Comment by sereneblue** [comment]
Thanks @h6a8ke1k. This issue has been addressed.
