### ISSUE TITLE
YouTube Polymer interface gets disabled, no avoiding

### ISSUE THREAD

**Issue by lewisclement** [sereneblue/chameleon#336]
## Expected Behavior
Using YouTube with a Firefox profile shouldn't disable the Polymer layout. Adding YouTube to the white list should definitely avoid so. And when disabling Chameleon this of course shouldn't happen.

## Current Behavior
All of the above situations result in appending `&disable_polymer=true` to YouTube urls. The only way to avoid this is by disabling Chameleon in `about:addons`.

## Relevant settings
Only the setting in `about:addons` makes any difference. Even disabling Chameleon by clicking the shield icon doesn't change anything.

## Context (Environment)
Happens with either 20.0 and 20.1.
Using Firefox 75.0 on an Ubuntu 18.04-based distro (64-bits).

**Comment by sereneblue** [comment]
Hi @lewisclement,

I've removed the code that specifically handles Youtube. It should land in the next update to be released later today.
