### ISSUE TITLE
v20 Update - Text not showing in Settings UI

### ISSUE THREAD

**Issue by randyrandersn** [sereneblue/chameleon#338]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
Be able to read text in the UI, am unable to check or change any settings.

## Current Behavior

![Chameleon-UI-1](https://user-images.githubusercontent.com/25313728/80864218-c8b8c700-8c70-11ea-8142-641f2c654cc2.png)

![Chameleon-UI-2](https://user-images.githubusercontent.com/25313728/80864227-dcfcc400-8c70-11ea-8b40-8cd0661c8c2e.png)

![Chameleon-UI-3](https://user-images.githubusercontent.com/25313728/80864228-e0904b00-8c70-11ea-94dd-041072eab760.png)

![Chameleon-UI-4](https://user-images.githubusercontent.com/25313728/80864231-e423d200-8c70-11ea-9632-aeb82c61eeef.png)

![Chameleon-UI-5](https://user-images.githubusercontent.com/25313728/80864234-e6862c00-8c70-11ea-9ba1-45c261a9dcc2.png)

These images are taken with dark mode checked, but text is not visible with light mode either.

## Relevant settings

I am using ghacks-user.js, is there something in there stopping UI text from being displayed?

Chameleon should work with ghacks-user.js.

## Context (Environment)

FF 75 in Arch Linux.

**Comment by sereneblue** [comment]
Hi @randyrandersn,

Do you have localStorage disabled? (`dom.storage.enabled` in about:config)

**Comment by randyrandersn** [comment]
Hmmm, I'd rather not have localstorage enabled but it does resolve the issue.

With this enabled should I be using another addon to clear this out?

**Comment by sereneblue** [comment]
@randyrandersn Don't worry, I've already got a fix that resolves this issue when localstorage is disabled. I just wanted to confirm the cause of the issue. You can keep local storage disabled, the next update will be out later today.
