### ISSUE TITLE
Whitelisting should disable all Chameleon manipulations

### ISSUE THREAD

**Issue by danielcra** [sereneblue/chameleon#34]
Disabling websockets or window.name breaks certain sites, therefore it would be helpful if whitelisting could be used to disable all Chameleon features, including those on the script injection tab. Currently this does not seem to be the case.

**Comment by sereneblue** [comment]
I'm aware of this issue: https://github.com/sereneblue/chameleon/issues/14

I'm working on rewriting the whitelisting feature now that the script injection finally works and the wiki is done.
