### ISSUE TITLE
About the ClientRects Spoofing

### ISSUE THREAD

**Issue by h6a8ke1k** [sereneblue/chameleon#341]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Expected Behavior
The fingerprint values should change after the spoofing is on.

## Current Behavior
The fingerprint values remain the same after enabling/disabling extension or closing/opening the browser. (Browser is always in incognito mode.) Also, the value is the same as the one when the extension is disabled.
I use the following website to get the fingerprint values:
[https://browserleaks.com/rects](https://browserleaks.com/rects)

If I am correct, I think your extension contains the spoofing code that will give slightly different random values when the extension / browser is restarted. So I guess it should be a bug.

## Context (Environment)

Firefox 68 ESR

**Comment by sereneblue** [comment]
Hi @h6a8ke1k, thanks for reporting this issue. It was a bug with iframes. This has been fixed and will be released tomorrow in v0.20.3.
