### ISSUE TITLE
Twitter loading posts with delay and when turn off chameleon, it loads immediately

### ISSUE THREAD

**Issue by slrslr** [sereneblue/chameleon#342]
v0.20.1
Windows 10
Firefox beta

https://twitter.com/home
shows: "Something went wrong."
instead of posts

When i turn off chameleon, and reload page it loads the posts OK.

Also when i keep chameleon enabled, but wait some time, switch to other tab/s and back it loads too.

When chameleon is turned off and i reload page, then it loads post immediately without need to wait/switch to other tabs.

If needed, [here is my Chameleon configuration](https://defuse.ca/b/O492aGzdCyonn6SG5I3mQc). (pass word is cc)

**Comment by sereneblue** [comment]
Hi @slrslr,

That config seems to be for v0.12.x. Did you export it from v0.20.1? Some non-Firefox profiles cause issues with Twitter. I'll try to see if I can find out why, but in the meantime you should try whitelisting the site with a Firefox profile.

**Comment by slrslr** [comment]
I used Chameleon only in Firefox, so i assume what i provided is not a "non-Firefox profile", it is from older version, but because i changed no settings since then, i assumed you would have enough information to replicate this issue. But now i updated link in the first post of this issue to have export for the current version.

I do not know what you mean by "whitelisting the site with a Firefox profile". If you mean to whitelist twitter site in chameleon, i just did that, but hope this issue can be fixed. If you need any more info., let me know please.

**Comment by sereneblue** [comment]
@slrslr The upgrade to v0.20.0 changed the settings format. You can still import your v0.12.x settings into Chameleon but your current settings provides some more information.

Thanks for posting your updated settings. I hope that whitelisting Twitter can fix the issue while I try to find the cause.

**Comment by Megver83** [comment]
unless you want to actually login to twitter, you could use nitter.net to view tweets and user profiles

**Comment by sereneblue** [comment]
@slrslr Are you still experiencing issues with Twitter (without the whitelist)?

**Comment by slrslr** [comment]
> @slrslr Are you still experiencing issues with Twitter (without the whitelist)?

Thanks, i am no longer experiencing the problem i initially described in this issue so maybe this issue can be closed.

Chameleon v0.21.7 - "twitter.com is not whitelisted"
