### ISSUE TITLE
New version breaks sites

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [sereneblue/chameleon#344]
**Gimme back the old version!**

Perhaps I can install it from a backup and disable updates until this bug is fixed.

I'm having to disable Chameleon to access site I've been accessing with the old version for a long time. Here's one: https://www.otcmarkets.com

All I get are blank pages on that site, even when I access different pages directly via search engine links. Of course the user agent is changed by the extension, but I tried all the usual desktop variations I used before. Also tried disabling a bunch of the settings, but it was futile.

Firefox 75
Chameleon 0.20.1

**Comment by sereneblue** [comment]
@GitTheHellOutaHere Please update to v0.20.2 and try accessing https://www.otcmarkets.com/ again.

**Comment by GitTheHellOutaHere** [comment]
Updating worked for that website. 

Thought I had the latest version since 0.20.1 appeared on its own and it's supposed to auto-update.

Thanks!
