### ISSUE TITLE
0.20.3 Vague case of expiring spoofing

### ISSUE THREAD

**Issue by sipher123** [sereneblue/chameleon#347]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
In Firefox for android, to leave the extension running in, say, iPhone Safari latest version profile and it would indefinitely appear as an iPhone on any site to the best of its capabilities. The one I like to test on is Whatismybrowser.

## Current Behavior
To give comparitive context, I am comparing with the previous version before 0.20 where it worked but was obviously used older spoof profiles. Say I leave Firefox running in the background, and come back in 12 hours (although I think it is much less time), the extension would fail to appear to work. Websites know with great detail that the current browser is a firefox with the correct version and OS and other javascript related information exposed. Note I'll be very clear in saying that when the app is functioning it works even if older cookies remain and I switch profile live And I do clear everything very often especially in these faulty situations to see if I did something wrong on my end.
![Screenshot_20200503-233149](https://user-images.githubusercontent.com/64660594/80927827-6a870380-8d98-11ea-974b-a438abba0a6e.jpg)
Although this <i>was</i> a workaround, I thought toggling the extension in app (clicking on the shield) would refresh the app. And it did, until too much time passed.

Anyway, the point is, the settings and spoofing may appear to 'stick' til the capabilities seem to stop overtime and then stop completely until I force stop and start firefox.

## Relevant settings
I obviously pick something that isn't my device, e.g. an iPhone safari profile.
![Screenshot_20200503-235152](https://user-images.githubusercontent.com/64660594/80927965-437d0180-8d99-11ea-850e-52b2c82b8e8a.jpg)
![Screenshot_20200503-235205](https://user-images.githubusercontent.com/64660594/80927968-47108880-8d99-11ea-8569-029ba3043c22.jpg)
![Screenshot_20200503-235228](https://user-images.githubusercontent.com/64660594/80927969-4aa40f80-8d99-11ea-8aff-bde28ac49a6c.jpg)

## Context (Environment)
Firefox for Android 68.7.0 Marshmallow

**Comment by sereneblue** [comment]
@sipher123 This looks like a bug; I've seen it before (#83). From my understanding of the previous issue, Chameleon used some unsupported features on Android that caused the addon to break somewhere. Hopefully, my hunch is correct and I will be able to resolve this issue for the next update.

**Comment by sereneblue** [comment]
@sipher123 Can you test with v0.20.3 and let me know if this is still happening? I haven't been able to replicate this issue. Also, is it just the spoofing that stops or are all of the extension settings reset?

**Comment by sipher123** [comment]
@sereneblue Doing some checks:
- [ ] Installed  0.20.3
- [ ] Immediately functioning spoof
- [ ] Spoof profile functioning after a short amount of time (e.g. 4-6 hours)
- [ ] Spoof functioning after 12 hours

What correct results should look like:
![Screenshot_20200505-162640](https://user-images.githubusercontent.com/64660594/81084000-396c1780-8eed-11ea-82fd-d54fc3a0e8ce.jpg)
The configuration is the same as the screenshots above.

**Comment by sipher123** [comment]
It looks like everything has been working smoothly. 😁 Thanks for the new update! Don't know what you did but it worked.

**Comment by sipher123** [comment]
Unfortunately, the problem isn't resolved on my end.
![Screenshot_20200507-000652](https://user-images.githubusercontent.com/64660594/81237196-e41c2d00-8ff6-11ea-836d-a0d08f6a748c.jpg)
The last activity was leaving the browser and doing something else which likely kicked it out of ram. So I open it up again, wait a bit to let all the add-ons load, and go to whatismybrowser only to do this again. Toggling don't work and it's not changing anything.
Not sure what do.

**Comment by sipher123** [comment]
I've tried everything I could think including resetting using the reset button, but what worked is a reinstall. I'm assuming that means continuous running causes the configuration at one point to fail permanently? Anyway, I'll see how long it takes before it fails again.

Also @sereneblue can I ask what are your plans for the new firefox android browser? Its already into beta and may reach stable quite soon but the app hasn't reached the recommendation list so the add-on may not be accessible to many soon, as soon as it could be.

**Comment by sipher123** [comment]
It didn't take long before it happened again because of the same circumstance, kicked out of ram e.g. from another app or battery optimisations.

**Comment by sereneblue** [comment]
> It didn't take long before it happened again because of the same circumstance, kicked out of ram e.g. from another app or battery optimisations.

Hi @sipher123, I've found the issue. It's a bug with iOS 12/13 mobile profiles. As a temporary workaround, you should use an iOS 11 profile. This will be resolved in v0.20.4. ETA tomorrow.

**Comment by sereneblue** [comment]
@sipher123 v0.20.4 has been released. Please let me know if you're still experiencing issues with iOS profiles after updating.
