### ISSUE TITLE
tracking protection

### ISSUE THREAD

**Issue by cincinnatus0** [sereneblue/chameleon#35]
even tho i have unticked/unchecked the option for enable tracking protection under options -> standard options. which is enabled by default!

in my Firefox preferences -> privacy & security -> tracking protection 
it states that An extension,  Chameleon, is controlling tracking protection.

issue is that i dont want Chameleon to control or even interfere with my tracking protection settings.

help is appreciated! 

thanks in advance
cin

**Comment by sereneblue** [comment]
Thanks for catching that. I've added a button to reset the standard option settings in v0.8.6.
