### ISSUE TITLE
Allow add/edit of spoofed useragent parameters, or at least add the current tor browser as an option

### ISSUE THREAD

**Issue by ilikenwf** [sereneblue/chameleon#350]
For the sake of fingerprinting I find that the tor browser useragent, platform, etc, all tend to blend in the most, except for whatever FF version or Chrome version is current.

I attempt to use canvasblocker but it fails to spoof the platform, I'm not sure what special sauce is going on here to make that work...

Regardless, having a way to add custom UA's would be nice.

**Comment by ilikenwf** [comment]
...in addition, it would be nice if we could have the ability to only share certain navigator properties in regard to these user agents, as despite having one chosen, the build ID isn't the 2010 one that most builds of Firefox now use, but is instead the actual build id...and hardware concurrency isn't reflecting the max of 2 for the value resistfingerprinting uses.

**Comment by sereneblue** [comment]
Hi @ilikenwf,

Tor Browser is the polar opposite of Chameleon when it comes to a browser fingerprint; It tries to maintain a uniform fingerprint for all users. There's no benefit to using a Tor Browser profile outside of it's browser.

According to [this](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/buildID), the build ID _should_ be static. If you're using RFP and select a browser profile, Chameleon takes priority and will overwrite the RFP values.

I'm open to adding more profiles but custom profiles add a bit more complexity for spoofing properties.
