### ISSUE TITLE
Page display broken when loaded

### ISSUE THREAD

**Issue by h6a8ke1k** [sereneblue/chameleon#361]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
The web pages display fully with css style when loaded.

## Current Behavior
When the web pages are first loaded, the style is broken. (seems like without any css) After a very short while, the display is normal. (less then 1 second usually but can be more if the page load is slow.)
If disable the extension there are no such problems.
The problem exists on many web pages, including github.

## Relevant settings

Even if the script injection is turned off completely, the issue remains.

## Context (Environment)

Firefox 68 ESR win64

**Comment by sereneblue** [comment]
Hi @h6a8ke1k, can you test with v0.20.3 and let me know if you're still experiencing issues?

**Comment by h6a8ke1k** [comment]
I have updated and the issue is resolved. Thanks!
By the way, could you please indicate what is causing this strange issue?

**Comment by sereneblue** [comment]
@h6a8ke1k It was probably the fingerprint detection panel. Some variables were overwritten which seems to have caused more trouble than it's worth.
