### ISSUE TITLE
Localization missing strings

### ISSUE THREAD

**Issue by Kaylier** [sereneblue/chameleon#363]
The non-english localizations (currently de, es, fr and zh_CN) are missing the following strings:
- popup.options.cookieNotPersistent
- options.modal.askReset
- options.modal.confirmReset
- options.about.knownIssues

These strings were introduced in commits 8aba53e, c7dd999 and a182400.

**Comment by sereneblue** [comment]
Hi @Kaylier,

I'm aware of this issue. I've done some work updating how localizations work in Chameleon to to eliminate the issue some users are experiencing with missing text in the UI. I haven't gotten around to updating the translation file on Crowdin but I will be doing that later today.

**Comment by sereneblue** [comment]
I've updated the localization file.
