### ISSUE TITLE
Can only use website with real profile.

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [sereneblue/chameleon#366]
With Chameleon 0.20.5's Random Profile (Desktop) enabled, [this](https://www.cnbc.com/pre-markets/) site will not load in Firefox 76.0.1.

Chameleon is set to change user agents hourly (macOS only). That works fine most of the time (after excluding Chrome, Edge & Safari agents).

But with a random profile all I get is a blank page. I  tried unchecking and changing all the settings, but nothing worked until I switched to Real Profile or disable Chameleon.

I just tried whitelisting the site with  a different profile, but that did nothing (possibly because of the [reported](https://github.com/sereneblue/chameleon/issues/362) broken whitelisting function?).

Could this be tied to the fact that there are no OS X user agents? (I'm using 10.12.6).
Don't know why that would matter, but since all the agents are 10.13+ it crossed my mind.

![Chameleon](https://user-images.githubusercontent.com/15519219/81627253-9adf2b00-93b2-11ea-96b8-dbe8c77a85d8.jpg)

**Comment by sereneblue** [comment]
@GitTheHellOutaHere This was an issue with plugin spoofing. v0.20.5 fixed an issue with plugins but it seems to have broken some sites. I've updated the code to better mimic plugins so this should be addressed in v0.20.6.
