### ISSUE TITLE
Request & Question: Please Make UI Smaller & Disable Notifications? 

### ISSUE THREAD

**Issue by 0pLuS0** [sereneblue/chameleon#369]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

I know the UI size is a small issue, but it would be really nice if this could be made smaller.

When I clicked the Chamelon icon for the first time and UI popped open I was shocked at how BIG it is. I personally think it's way to big, it was never like this before.

I also don't care for the notifications, with the number being displayed, telling me how many things are being blocked. As long as Chamelon is doing it's job, I have no interest in seeing this number. 

Also now at the bottom of the UI when you open it, now it displays the words, which it would be nice if these could be disabled, I have no need or interest in seeing them;

Audio context - Client Rects - Date - Screen - Websocket

68.8.0 ESR - Linux

THANKS

**Comment by sereneblue** [comment]
@0pLuS0 The fingerprint detection panel has been removed in v0.20.3, please update Chameleon. About the UI size, I can reduce it a bit.

**Comment by sereneblue** [comment]
I've reduced the popup size in v0.20.7. It should be a noticeable difference; a bit more compact than the current size but slightly larger than v0.12.x. It will be available in the update tomorrow.
