### ISSUE TITLE
support for other browsers

### ISSUE THREAD

**Issue by alekksander** [sereneblue/chameleon#37]
is support for other browsers planned? sadly blink seems to lead on the market, so there is big potential user base there.

**Comment by sereneblue** [comment]
Unfortunately, no. Chameleon uses some APIs that are specific to Firefox, notably, the [browser.contentScript](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts/register) API. I'm open to supporting other platforms if this API is implemented.

**Comment by SashaPetrovska** [comment]
you should support chrome, (at least brave). firefox is dying every day, I switched brave from firefox, and everything is big privacy focused. I loved your extension when I was in firefox but now I find this, it's kinda sad.

**Comment by sereneblue** [comment]
@SashaPetrovska I will reevaluate Chrome support when a firm timeline for Manifest v3 support is posted by Google and Mozilla. I'm still not sure yet how much of an impact it will have on Chameleon.

**Comment by 0x0480** [comment]
bumpp
