### ISSUE TITLE
2 improvements to the whitelist

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#372]
I would suggest a few improvements to how chameleon opens sites in whitelist, my observations derive from the fact that when I want to whitelist a site is probably because it is broken so I want a quick way to do it, and while doing it I noticed 2 petty things which I think could be improved:

1 put the name of the website in 'name' space (right now it is empty and you have to add manually, I think it makes sense to add the url as default name)

2 default language should be either system language or browser original language (right now it is alcoli because it is the first in the list, however I am sure 99% of users are not speakers of such language and have to change it)

With such improvements user would save a few clicks and make the whitelisting process faster.

**Comment by sereneblue** [comment]
HI @WPFilmmaker,

Thanks for the suggestions! v0.20.9 will address both of these items.
