### ISSUE TITLE
Domain whitelisting broken only subdomain works

### ISSUE THREAD

**Issue by SunnyMoo** [sereneblue/chameleon#373]
Hi,
Before v0.20.8 (or maybe earlier) you could whitelist with domain name (google.com)
With v0.20.8 you must use subdomain for whitelist to work (mail.google.com) otherwise it reads the domain as "not blacklisted".
Issue is for all domains and not limited to google.com of course ;)
Thanks !

FF 76.0.1 Chameleon v0.20.8

**Comment by sereneblue** [comment]
Hi @SunnyMoo,

This is a bug introduced in v0.20.8. It will be patched in v0.20.9.

**Comment by SunnyMoo** [comment]
Nice, thank you !
