### ISSUE TITLE
Replace "Block media devices" with "Hide media devices"

### ISSUE THREAD

**Issue by Megver83** [sereneblue/chameleon#376]
Hi @sereneblue! I've been using the latest version of Chameleon, and I really liked it. However, the "Block media devices" option does not really block them, 'cause when a site asks for access to my camera or microphone, I'm able to give it, instead of, e.g., throwing an error saying that the site could not ask for permission to get access to the device (like in Tor Browser).

However, I see that it looks like it still protects from fingerprinting, so just wanted to propose to do one of these two things:
1) Replace the text "Block media devices" with something like "Hide media devices" or "Protect from media devices fingerprinting", or
2) Actually make Chameleon to block media devices

Thanks for the gr8 work on this awesome extension!

**Comment by sereneblue** [comment]
Hi @Megver83,

Thanks for bringing this to my attention. v0.20.11 will be released later today with an update to properly block media devices.
