### ISSUE TITLE
chameleon breaks facebook.com

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#377]
I hope this won't be the same as #272... everything has always been working fine, today suddenly I got an error very similar to the one on whastappweb. Screenshot below. Disabling chameleon fixes the issues, has something changed in chameleon recently?Something that could interfere with fb? Or is it fb's side?

If possible I would rather avoid whitelisting fb. 
76.0.1 (64-bit) Linux, chameleon 0.20.10.1

https://i.imgur.com/RvMtI63.png

**Comment by sereneblue** [comment]
@WPFilmmaker Can you post your settings? Chameleon has a changelog so you can view the major changes between versions [here](https://github.com/sereneblue/chameleon/blob/develop/CHANGELOG.md). In v0.20.10, there was a small update to improve whitelist matching. Does this happen when loading the page while logged in/out?

**Comment by WPFilmmaker** [comment]
@sereneblue this is very weird...I had chameleon disabled because of this issue, today I re-enabled it to test what you suggested and it works fine...I suppose you haven't changed anything in these 3 days so must be on facebook's side. I am closing this as it works fine, I will reopen it if it happens again.

**Comment by WPFilmmaker** [comment]
@sereneblue I saw this issue happening a few times recdently but whenever I reloaded it would be all ok. Since yesterday fb is broken :/
FF 77.0.1 and Chameleon 0.20.16.1

**Comment by sereneblue** [comment]
> @sereneblue I saw this issue happening a few times recdently but whenever I reloaded it would be all ok. Since yesterday fb is broken :/
> FF 77.0.1 and Chameleon 0.20.16.1
> 
> edit: interestingly when the issue appears, if I disable chameleon, reload facebook.com and reenable chameleon even reloading the page the issue disappears.

@WPFilmmaker Are you using a specific profile with Facebook?

**Comment by WPFilmmaker** [comment]
@sereneblue no general one, I have facebook live whitelisted but no specific profile with Facebook. I double checked the edit above and can confirm disabling chameleon, reloading facebook and enabling it fixes the issues until I restart FF.

**Comment by sereneblue** [comment]
@WPFilmmaker How often do you encounter this issue? Also, can you post your settings?

**Comment by WPFilmmaker** [comment]
@sereneblue it seems to happen when i start FF. In order to use the site I have to do the procedure I explained above.
yes:
https://privatebin.net/?6728adbb2ed68353#4PGryusQLY6eRcJDgThU26d6WBRYbqfDvrF9g7sxLKVe (password 1234a)

**Comment by sereneblue** [comment]
@WPFilmmaker Sorry, I didn't chance to click on your link and it seem it's expired. Can you reupload your settings again?

**Comment by WPFilmmaker** [comment]
@sereneblue yes sorry I will paste it here:

{
  "config": {
    "enabled": true,
    "notificationsEnabled": false,
    "theme": "light"
  },
  "excluded": [
    "win1-gcr",
    "win2-gcr",
    "win3-gcr",
    "win4-edg",
    "win1-ff",
    "win2-ff",
    "win3-ff",
    "win4-ff",
    "win2-ie",
    "win1-ie",
    "win3-ie",
    "win1-esr",
    "win3-esr",
    "win4-esr",
    "win4-ie",
    "mac1-gcr",
    "mac2-gcr",
    "mac1-ff",
    "mac2-ff",
    "mac1-sf",
    "mac2-sf",
    "mac3-sf",
    "mac1-esr",
    "lin1-gcr",
    "lin2-gcr",
    "lin3-gcr",
    "lin1-cr",
    "lin2-cr",
    "lin3-cr",
    "lin1-ff",
    "lin2-ff",
    "lin3-ff",
    "lin1-esr",
    "lin3-esr",
    "ios1-sfm",
    "ios1-sft",
    "ios1-gcrm",
    "ios2-sft",
    "ios2-gcrm",
    "ios2-sfm",
    "ios3-sfm",
    "ios3-sft",
    "ios3-gcrm",
    "mac1-edg",
    "mac2-edg",
    "mac2-esr",
    "mac3-edg",
    "mac3-esr",
    "mac3-ff",
    "mac3-gcr",
    "lin2-esr",
    "ios1-gcrt",
    "ios2-gcrt",
    "ios3-gcrt",
    "and1-edgm",
    "and1-ffm",
    "and1-fft",
    "and1-gcrm",
    "and1-gcrt",
    "and2-edgm",
    "and2-ffm",
    "and2-fft",
    "and2-gcrm",
    "and2-gcrt",
    "and3-edgm",
    "and3-ffm",
    "and3-fft",
    "and3-gcrm",
    "and3-gcrt",
    "and4-edgm",
    "and4-ffm",
    "and4-fft",
    "and4-gcrm",
    "and4-gcrt",
    "win1-edg",
    "win2-edg",
    "win2-esr",
    "win3-edg"
  ],
  "headers": {
    "blockEtag": true,
    "enableDNT": false,
    "referer": {
      "disabled": false,
      "xorigin": 0,
      "trimming": 0
    },
    "spoofAcceptLang": {
      "enabled": true,
      "value": "en-US"
    },
    "spoofIP": {
      "enabled": false,
      "option": 0,
      "rangeFrom": "",
      "rangeTo": ""
    }
  },
  "ipRules": [],
  "options": {
    "cookieNotPersistent": false,
    "cookiePolicy": "allow_all",
    "blockMediaDevices": false,
    "disableWebRTC": true,
    "firstPartyIsolate": false,
    "limitHistory": false,
    "protectKBFingerprint": {
      "enabled": true,
      "delay": "2"
    },
    "protectWinName": false,
    "resistFingerprinting": false,
    "screenSize": "1366x768",
    "spoofAudioContext": true,
    "spoofClientRects": true,
    "spoofFontFingerprint": true,
    "timeZone": "America/New_York",
    "trackingProtectionMode": "never",
    "webRTCPolicy": "disable_non_proxied_udp",
    "webSockets": "allow_all"
  },
  "profile": {
    "selected": "randomDesktop",
    "interval": {
      "option": 0,
      "min": 1,
      "max": 1
    }
  },
  "settings": {
    "customScreen": "",
    "enableScriptInjection": true,
    "interval": 0,
    "kbDelay": "2",
    "limitHistory": false,
    "minInterval": null,
    "maxInterval": null,
    "notificationsEnabled": false,
    "protectKeyboardFingerprint": true,
    "protectWinName": false,
    "screenSize": "1366x768",
    "spoofAudioContext": true,
    "spoofClientRects": true,
    "timeZone": "America/New_York",
    "useragent": "randomDesktop",
    "useragentValue": "",
    "webSockets": "allow_all"
  },
  "version": "0.20.18.1",
  "whitelist": {
    "enabledContextMenu": false,
    "defaultProfile": "none",
    "rules": [
      {
        "id": "2d5f7595-0be7-4d70-8d8b-eb130cc72e43",
        "name": "Rule #1",
        "sites": [
          {
        
      {
        "id": "8614fadb-8cad-4317-ae05-ff592797f45c",
        "name": "Rule #2",
        "sites": [
          {
  
        "id": "3ba158e3-ec03-4fcb-801e-bebd373ea42e",
        "name": "whatsapp",
        "sites": [
          {
            "domain": "web.whatsapp.com"
          }
        ],
        "lang": "en-US",
        "profile": "default",
        "spoofIP": "",
        "options": {
          "name": false,
          "ref": false,
          "tz": false,
          "ws": false
        }
      },
      {
        "id": "bf3fb0eb-df72-4446-9008-b9720a2bd797",
        "name": "www.facebook.com",
        "sites": [
          {
            "domain": "www.facebook.com",
            "pattern": "watch/live|videos/"
          }
        ],
        "lang": "en-US",
        "profile": "default",
        "spoofIP": "",
        "options": {
          "name": false,
          "ref": false,
          "tz": false,
          "ws": false
        }
      }
    ]
  }
}

By the way the issue reappered today and also #272... the workaround of disabling reloading and reenabling does not work. I need to turn off chameleon in order to have facebook and whatsappweb to work :/

**Comment by sereneblue** [comment]
@WPFilmmaker Try updating to v0.20.20. That should fix the issue with whatsapp. I'm able to replicate the facebook issue so there's some progress. I'm curious what causes it. Looks like there's also some fixes I'll need to add to the settings migration/export.

**Comment by WPFilmmaker** [comment]
@sereneblue it seems that today (July 9) both site work..so the issue is intermittent I have no idea why, but I am glad you were able to reproduce on fb!

**Comment by sereneblue** [comment]
@WPFilmmaker I've isolated the issue. Chrome sends some additional headers (sec-fetch-*) that Firefox doesn't support and Chameleon doesn't send. It seems Facebook is expecting those headers from Chrome profiles (and Edge soon?). If they're not present, Facebook returns a `400 Bad Request` status code. Those missing headers will be added in the next update.

**Comment by WPFilmmaker** [comment]
@sereneblue Thanks a lot! do you think adding the missing headers will fix other sites too?(like whatsapp)

**Comment by sereneblue** [comment]
@WPFilmmaker Possibly. That issue (#272) was also the Chrome profile. I don't have a Whatsapp account to test it with.

**Comment by WPFilmmaker** [comment]
@sereneblue that's great. I will keep an eye on whatsapp in the future and report any issue :)
