### ISSUE TITLE
Spoof Screen Resolutions

### ISSUE THREAD

**Issue by classmate01** [sereneblue/chameleon#38]
I'm enjoying this Chameleon ++ new successor of RAS
Hopefully you can also migrate the screen resolution spoofing soon :)

**Comment by sereneblue** [comment]
Thanks for the kind words. The screen resolution spoofing feature is already included. ;)

https://github.com/sereneblue/chameleon/wiki/Options

**Comment by classmate01** [comment]
Hey thanks! I mean the mini browser size for mobile phone.
OMG! You reply so fast. Im starting to really love this addons :)
