### ISSUE TITLE
Chameleon breaks AWS Lambda console

### ISSUE THREAD

**Issue by Jaystified** [sereneblue/chameleon#389]
## Expected Behavior

Opening up the lambda console of AWS at any region ( for example for us-east-1 the url would be https://console.aws.amazon.com/lambda/home ) should load the page properly.

## Current Behavior

Only the page header is displayed. The rest of the page does not load.
Opening up the page console shows this error:
```
Loading failed for the <script> with source “blob:https://console.aws.amazon.com/...
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
TypeError: e.supportedLocalesOf is not a function
```

And not much else that doesn't also show up without chameleon.

## Relevant settings

v0.20.11
Settings have been reset to default. Real profile. Whitelisting AWS does nothing. 
Only disabling chameleon makes it work.

## Context (Environment)

Firefox 76.0 64bit on Linux Mint 19.3 cinnamon (Ubuntu 18.04 base)

**Comment by sereneblue** [comment]
Hi @Jaystified,

Thanks for reporting this issue. This issue is fixed in v0.20.12.
