### ISSUE TITLE
Bug in Chameleon v0.20.12.1

### ISSUE THREAD

**Issue by Escaping-Logic** [sereneblue/chameleon#391]
I updated Chameleon v0.20.11.1 to v0.20.12.1 and noticed a bug.
All my previous settings such as spoofed user agent, disabled referrer, and altered resolution are still working, but they won't change when different settings are applied. (Options appear to be saved in a different position, but nothing is executed and enforced).

I've tried disabling and enabling Chameleon, and running it in private windows with no luck.
The only option is to uninstall and download a new Chameleon extension from: https://addons.mozilla.org/en-US/firefox
(Note: All previous settings from Chameleon will be lost using this method).

Thankfully, I have Deep Freeze running that gives me a little more confidence to test and experiment.
(I currently have everything restored back to my custom setup with Chameleon v0.20.11.1).

Here's a list of my other updated extensions:
- Clear Browsing Data v3.1.1
- HTTPS Everywhere v2020.5.20
- NoScript v11.0.30
- Proxy Switcher and Manager v0.4.1
- Script Switch v1.1

I'm currently running Firefox 77.0.1 on a machine with Windows 7 installed.

I hope v0.20.12.1 can be patched soon... Thanks for your work, sereneblue.

Best Regards,

John

**Comment by Escaping-Logic** [comment]
I found a workaround by copying a backup of the older "3647222921wleabcEoxlt-eengsairo.sqlite" file to the "C:\Users\Admin\AppData\Roaming\Mozilla\Firefox\Profiles\7lhb7vha.default\storage\default\moz-extension+++0cde5bec-99ac-4898-b5d0-cbf90b58f2a3^userContextId=4294967295\idb\3647222921wleabcEoxlt-eengsairo.sqlite" directory.

It seems to now work at successful changing settings. 

If other people are experiencing similar problems, these steps my be too time consuming or confusing for some to follow... (I would still recommend a patch for v0.20.12.1 of Chameleon.)

**Comment by Escaping-Logic** [comment]
As I had expected, "3647222921wleabcEoxlt-eengsairo.sqlite" was just restoring my settings. Upon restarting Firefox my user agent was showing my real browser, and no other browser spoofs would work. This issue is not only affecting Windows 7 64-bit users, but my other machine using Mac OS 10.12.6 with Firefox 77.0.1 installed. I've disabled all other extensions on both machines, and the problem still persists.

Thanks to backups and Deep Freeze, I'll be sticking to v0.20.11.1 until v0.20.12.1 is updated. I've never had this problem before with Chameleon.

**Comment by sereneblue** [comment]
Hi @Escaping-Logic,

The issue you're experiencing seems to have been caused by the update for Firefox 77 that broke a few addons. There is a [workaround](https://old.reddit.com/r/firefox/comments/gvc7zd/none_of_my_extensions_work_now_with_firefox_77/) that could resolve the issue, however, I wasn't able to get this working with FF77 on Linux There's nothing I can do besides notify users about this issue.

**Comment by sereneblue** [comment]
@Escaping-Logic Upon further investigation, this does seem to be a bug with v0.20.12. I mispoke with my previous comment, although I'm puzzled why it occasionally worked with other Firefox versions. v0.20.13 addresses the issue: some code that was intended to be run for the initial migration from v0.12.x was being triggered.
