### ISSUE TITLE
Mapbox / OpenStreetMap is broken in v0.20.13 and v0.20.14

### ISSUE THREAD

**Issue by Escaping-Logic** [sereneblue/chameleon#394]
Interactive weather radar is broken on multiple sites using OpenStreetMap. There is no zoom function or other features when Chameleon v0.20.13 and v0.20.14 are installed with any custom settings enabled. This occurs with me on the latest version of Firefox using Windows 7, Mac OS 10.12.6, and Andriod 9.

Examples of websites using OpenStreetMap:

https://whdh.com/radar
https://www.wcvb.com/weather/radar
https://www.necn.com/weather

Best Regards,

John

**Comment by sereneblue** [comment]
Hi @Escaping-Logic,

Can you post your settings?

**Comment by Escaping-Logic** [comment]
> Hi @Escaping-Logic,
> 
> Can you post your settings?

This issue even occurs when all other extensions are disabled and no custom settings selected in chameleon. (I also changed tracking protection from custom to standard.)

Examples:

https://ibb.co/MppCRr3

https://ibb.co/fttry8v

Interactive radar working:

https://ibb.co/1Lnmg30

Interactive radar broken:

https://ibb.co/g3pXLNt

**Comment by sereneblue** [comment]
Hi @Escaping-Logic,

Thanks for posting some for more information. This does seem to be an issue. I'm currently looking into it.

**Comment by sereneblue** [comment]
This issue should be resolved in v0.20.15.
