### ISSUE TITLE
Interface Language Bug

### ISSUE THREAD

**Issue by btskc** [sereneblue/chameleon#395]
Since 0.20.4.2 this extension's Chinese interface does not display properly.
I've also tested that all versions other than es display the interface language correctly
Here are the test screenshots

de 
![de.PNG](https://i.loli.net/2020/06/19/vQKOAlU9T6PBCax.png)

fr
![fr.PNG](https://i.loli.net/2020/06/19/BDwLROrnpcXCV7q.png)

ja
![ja.PNG](https://i.loli.net/2020/06/19/vCy2ImWDBaObnqi.png)

ru
![ru.PNG](https://i.loli.net/2020/06/19/WADvoZ4SmhExabn.png)

zh-cn 0.20.3.1
![c.PNG](https://i.loli.net/2020/06/19/567MyXUapiulxIN.png)

zh-cn 0.20.15.1
![cnbug.PNG](https://i.loli.net/2020/06/19/L8eUlcJoz2tIQVs.png)

Test Version: win64 Firefox 77.0.1 
(PS: I didn't test es because there are four versions and I got lazy)

**Comment by sereneblue** [comment]
Hi @btskc,

Thanks for the extensive testing! This was caused because the locale for the browser was `zh-CN`, but Chameleon was expecting `zh_CN`. This should be fixed in the next version. I've also verified that all of the Spanish locales work.
