### ISSUE TITLE
The navigator properties are not fully spoofed

### ISSUE THREAD

**Issue by h6a8ke1k** [sereneblue/chameleon#408]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
The navigator properties obtained from multiple methods should be the same.

## Current Behavior
The spoofed navigator properties are able to be detected. This [page](https://canvasblocker.kkapsner.de/test/navigatorTest.php) can give a good test.

It seems that only a part of the methods of getting the navigator properties are being handled in Chameleon.

## Relevant settings
I am using Win10 Firefox 78 ESR and choose the profile "Win10 - Firefox 78 ESR." (So there should be no big differences. I do not intend to simulate another browser or system.) In addition, I set `privacy.resistFingerprinting` flag to false. (If this flag is set to true, then the spoof is not detected.)

If I choose some other profiles, the page above can detect more entries being spoofed.

**Comment by sereneblue** [comment]
Hi @h6a8ke1k,

Thanks for bringing this to my attention. It seems there is a leak in Chameleon with one of the tests on that page. I'm doing some testing and should probably have an update out tomorrow that addresses this issue.

**Comment by sereneblue** [comment]
@h6a8ke1k It seems this is an issue with the Workers API. I've addressed a navigator leak for `window.open` but there's nothing else I can do until Mozilla offers some way for WebExtensions to interact with that API. There is a bug opened here about this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1636977.

**Comment by uf0wxxel** [comment]
Thanks for your investigation! I will pay attention to the status of this bug.

**Comment by h6a8ke1k** [comment]
Thanks for your investigation! I will keep an eye on this firefox issue.
