### ISSUE TITLE
Enable font spoofing with real profile

### ISSUE THREAD

**Issue by h6a8ke1k** [sereneblue/chameleon#409]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
I think font spoofing can also be enabled for real profiles. Currently, when I select real profile, font spoofing is not working.

I looked at the font spoofing code and it seems that different platforms are given different font sets, which is good. Then, it is possible to detect current browser platform (e.g. from navigator) and automatically choose the appropriate sets of fonts.

Do you think it is an acceptable idea? (I have this request because currently navigator properties cannot be fully spoofed in firefox, so I want to stop using spoof profiles and only spoof the fonts.)

**Comment by sereneblue** [comment]
Hi @h6a8ke1k,

Thanks for the suggestion, this will be addressed in the next update.
