### ISSUE TITLE
Twitch.tv responsive layout

### ISSUE THREAD

**Issue by aalhitennf** [sereneblue/chameleon#410]
## Expected Behavior
When resizing window narrow enough, video should scale to certain point and chat should auto-hide, or when in theater mode, chat should move to bottom of video.

## Current Behavior
Video doesn't scale correctly. Chat doesn't hide or move to bottom of video on theater mode, stays on top of blocking part of video and it's buttons.

## Relevant settings
Screen size. Site works fine with "Default", anything else breaks the page. Any other setting doesn't seem to have effect on this. Whitelisting does nothing.

## Context (Environment)
Browser: Firefox 78.0.1 (64-bit)
OS: Arch Linux

Current behavior:
[Theater mode](https://i.imgur.com/phpWdEJ.png)
[Normal mode](https://i.imgur.com/pFytpzJ.png)

Expexted behavior:
[Theater mode](https://i.imgur.com/IsjhNuk.png)
[Normal mode](https://i.imgur.com/Uruhzf1.png)

**Comment by sereneblue** [comment]
Hi @aalhitennf,

There is a bug with the whitelist in v0.20.18. It should be resolved in v0.20.19. Screen size spoofing can cause some issues with sites but I couldn't reproduce this issue on Twitch. Do you have any other settings enabled?

**Comment by aalhitennf** [comment]
Thanks, whitelisting works now with v0.20.19, don't know why my extension didn't update automatically, had to remove and install again. Thought it was latest, my bad.  

Tested the "bug" with clean firefox profile and fresh chameleon install, only setting screen size and site breaks. So it seems to be twitch problem or just nothing cant be done to fix that, which is understandable.
