### ISSUE TITLE
Bug that prevents all rules from being evaluated in whitelist 0.20.18.1

### ISSUE THREAD

**Issue by kekkc** [sereneblue/chameleon#411]
Hi,

the version history says of 0.20.18.1 says "Bug that prevents all rules from being evaluated in whitelist", but somehow this version just created the bug for me that no rule from the whitelist is evaluated. Tested in a fresh nightly portable, adding "https://" to the whitelist entry, removing the entry and creating it freshly via "add page to whitelist" --> always the same result, whitelist is not evaluated.

Greetz

**Comment by sereneblue** [comment]
Hi @kekkc,

It appears you're correct, this is a bug present with v0.20.18. It'll be fixed in the next version.

**Comment by kekkc** [comment]
Works again, thanks for the quick fix ;)
