### ISSUE TITLE
bug   chamaleon  0.20.18.1

### ISSUE THREAD

**Issue by gallegonovato** [sereneblue/chameleon#412]
Good afternoon:

I'm using Chamaleon 0.20.18.1 . With this configuration:

Random mobile profile change every minute
In the Headers section marked only "False X-Forwarded-For/Via IP" and "Random IP".
In the Options, Injection, Screen Size section, choosing 1920x1080. In Standard we enable the 3 that come out, enable first part isolation, fingerprint resistance and disable webRTC. At Cookies we also mark.

And for example when I'm already registered in my tutanota email. Even if I've got it whitelisted, it doesn't make things normal. It comes out as the desktop version. Which didn't happen in the previous version. 

Instead with my hotmail mail, whitelisting works well. Both in this version and in the previous version.

I use lineageos and fennec or icecat mobile in its latest version both.

A hug

**Comment by sereneblue** [comment]
Hi @gallegonovato,

There is a bug in v0.20.18 that caused an issue with the whitelist. It's fixed in v0.20.19.

**Comment by gallegonovato** [comment]
Good afternoon @sereneblue 



Thank you very much for all your help and effort in creating this great complement.

A hug

Pd: Solved
