### ISSUE TITLE
Invalid just exported Profile File

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#413]
- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

On a clean FF 78 Portable without any addon, I have installed Chameleon, set up a profile, and then exported it. Then I made some changes in Chameleon addon settings, and finally I tried to import the just-exported chameleon profile file. But it failed, and I got the red error: **_Invalid setting value: profile.selected_**.

Its very weird that Chameleon doesn't consider as valid a file it has itself just made.

Here is the profile filre in question:

{
  "config": {
    "enabled": true,
    "notificationsEnabled": false,
    "theme": "light"
  },
  "excluded": [
    "win1-edg",
    "win1-gcr",
    "win1-ie",
    "win2-edg",
    "win2-gcr",
    "win4-gcr",
    "win4-edg",
    "win3-ie",
    "win3-gcr",
    "win3-edg",
    "win2-ie"
  ],
  "headers": {
    "blockEtag": true,
    "enableDNT": false,
    "referer": {
      "disabled": false,
      "xorigin": 0,
      "trimming": 0
    },
    "spoofAcceptLang": {
      "enabled": true,
      "value": "default"
    },
    "spoofIP": {
      "enabled": false,
      "option": 0,
      "rangeFrom": "",
      "rangeTo": ""
    }
  },
  "ipRules": [
    {
      "id": "c826774e-63ce-4f36-a4b6-160f38297a75",
      "name": "Rule#1 Amsterdam",
      "lang": "nl",
      "tz": "Europe/Amsterdam",
      "ips": [
        "85.17.28.139",        
      ]
    }
  ],
  "options": {
    "cookieNotPersistent": true,
    "cookiePolicy": "reject_trackers",
    "blockMediaDevices": true,
    "disableWebRTC": true,
    "firstPartyIsolate": true,
    "limitHistory": false,
    "protectKBFingerprint": {
      "enabled": false,
      "delay": 1
    },
    "protectWinName": false,
    "resistFingerprinting": true,
    "screenSize": "default",
    "spoofAudioContext": false,
    "spoofClientRects": false,
    "spoofFontFingerprint": false,
    "timeZone": "ip",
    "trackingProtectionMode": "always",
    "webRTCPolicy": "disable_non_proxied_udp",
    "webSockets": "allow_all"
  },
  "profile": {
    "selected": "windows",
    "interval": {
      "option": 0,
      "min": 1,
      "max": 1
    }
  },
  "version": "0.20.19.1",
  "whitelist": {
    "enabledContextMenu": true,
    "defaultProfile": "none",
    "rules": []
  }
}
## Context (Environment)
Chameleon 0.20.19
FF 78.01 on W10

**Comment by sereneblue** [comment]
Hi @Kraxys,

This is a bug in settings validation, it's missing a few profiles. I'll release an update ASAP to address this.
