### ISSUE TITLE
Font spoofing interferes with CanvasBlocker's canvas fingerprint spoof

### ISSUE THREAD

**Issue by h6a8ke1k** [sereneblue/chameleon#414]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
CanvasBlocker's canvas fingerprint spoof should work properly to spoof fingerprints got by all methods when font spoofing is enabled in Chameleon.

## Current Behavior
Some of the canvas fingerprints are not spoofed (showing real values) if font spoofing is enabled in Chameleon. Disabling font spoofing makes CanvasBlocker work properly.
The link to the test: [link](https://canvasblocker.kkapsner.de/test/test.html).

## Context (Environment)

Win10 64-bits with Firefox ESR 78

**Comment by sereneblue** [comment]
Thanks @h6a8ke1k,

I can replicate the issue. I'll look into this.

**Comment by asvc** [comment]
I can see that only `iFrame Test 3 - violating SOP` reporting the same value after refresh.

Running v0.20.24.

**Comment by asvc** [comment]
Same result on v0.21.0, only "iFrame Test 3 - violating SOP" stays unchanged.

**Comment by sereneblue** [comment]
@h6a8ke1k This is now resolved in v0.22.22.
