### ISSUE TITLE
Youtube with lines over the player.

### ISSUE THREAD

**Issue by fabianski7** [sereneblue/chameleon#420]
##  Current Behavior
By accessing youtube with the random profiles option active you can make the video player display lines over the video.

This problem seems to happen whenever the active profile browser is different from the firefox. See the examples I was able to play.

- [With the firefox profile, everything is normal](https://upload.vaa.red/Jb3JU#Q3qGO1QzKEthRJC1x3B6VxSeKYMwHtj0)
- [Chrome, the problem happens](https://upload.vaa.red/q7psV#VbKSNLI3dzcJ63WeHBj0KCIw6KlZjhGV)
- [Safari, ...](https://upload.vaa.red/7PpTV#08iVNTFMP6ewWoTo9IxdKLjF4h26w9gN)
- [Edge, ...](https://upload.vaa.red/ByH5w#fhecGLBMApWZvd5IrUyX6MES9jf9V0uN)

It's easy to solve this by creating a rule for the youtube.com domain with a profile with the firefox browser, but I decided to report this error since it took me a while to find out that the problem was being caused by the chameleon and there were many other active extensions to test.

Maybe youtube should have some specific rule by default to only use profiles with the firefox browser? The browser would always be the same but the operating system could be any other random, mac, linux, windows, etc.

This problem seems to have been partially reported in issue #415 [in this comment](https://github.com/sereneblue/chameleon/issues/415#issuecomment-658633150).

## Relevant settings
https://bin.disroot.org/?67dbf413b59c6676#CDoSNNj6FfE3J1WUcYv4qJQJyRCa5RstnVuih4g2ySpd

## Context (Environment)
Firefox 78.0.2
Linux 5.7.9

**Comment by sereneblue** [comment]
@fabianski7 Interesting. @slrslr also experienced this issue. I still can't replicate it even with your configuration. There was a similar issue with the Brave browser if fingerprinting was blocked. Can you test with Chameleon disabled and use a user agent extension with the problematic profiles to see if it's still happening?

**Comment by fabianski7** [comment]
> @fabianski7 Interesting. @slrslr also experienced this issue. I still can't replicate it even with your configuration. There was a similar issue with the Brave browser if fingerprinting was blocked. Can you test with Chameleon disabled and use a user agent extension with the problematic profiles to see if it's still happening?

do you use the [ghacks/user.js](https://github.com/ghacksuserjs/ghacks-user.js)?

I just tested with firefox without the modifications of this script and the problem really didn't happen.
So some change that is made through these modifications is causing conflict with chamaleon. Unfortunately I didn't have time to test which of these changes is causing this problem.

**Comment by sereneblue** [comment]
> > @fabianski7 Interesting. @slrslr also experienced this issue. I still can't replicate it even with your configuration. There was a similar issue with the Brave browser if fingerprinting was blocked. Can you test with Chameleon disabled and use a user agent extension with the problematic profiles to see if it's still happening?
> 
> do you use the [ghacks/user.js](https://github.com/ghacksuserjs/ghacks-user.js)?
> 
> I just tested with firefox without the modifications of this script and the problem really didn't happen.
> So some change that is made through these modifications is causing conflict with chamaleon. Unfortunately I didn't have time to test which of these changes is causing this problem.

I don't use that but it could be a modified about:config preference that's causing the issue. You can use [this](https://www.ghacks.net/2020/04/09/how-to-display-only-modified-preferences-on-aboutconfig/) guide to get a list of all your modified preferences.

**Comment by slrslr** [comment]
> get a list of all your modified preferences

about:config
Show all
Ctrl+Shift+K
paste following code next to >> and hit enter
```
var elements = document.getElementsByTagName('tr');
[...elements].filter(
el => !el.classList.contains('has-user-value')
).forEach(
el => el.style.display = (el.style.display === 'none') ? 'table-row' : 'none'
);
```
it listed 517 items in my case where many are private ones, you would be able to debug this having that? I would have to anonymize some values and that may break working things if you used that.. Btw. if need to send something in private, it is https://sereneblue.github.io/chameleon/contact/ ?

**Comment by sereneblue** [comment]
Thanks @slrslr. I'll try to see if I can replicate the issue using those preferences.

**Comment by slrslr** [comment]
Today i have found similar issue on https://snipboard.io where i pasted PrintScreen of my computer screen and it shown similar lines, only vertical. After i whitelisted site, the image cropping, saving, upload worked on that site and stripes disappear.

**Comment by sereneblue** [comment]
> Today i have found similar issue on https://snipboard.io where i pasted PrintScreen of my computer screen and it shown similar lines, only vertical. After i whitelisted site, the image cropping, saving, upload worked on that site and stripes disappear.

Do you see any visible error messages in the developer console when you paste an image? It looks like snipboard uses a canvas so that's probably where the issue is coming from. Which profiles cause an issue with snipboard?

@fabianski7 Can you try disabling screen size spoofing to see if that resolves the issue? If not, can you test with Chameleon disabled (from Firefox's about:addons page) and changing the user agent to Chrome?

**Comment by slrslr** [comment]
I removed snipboard.io from whitelist and cycled many profiles and Ctrl+F5 + image upload, but the issue no longer appears. Tried both with websockets disabled and enabled. So, please discard my previous message.

i am not fabianski7, but when i changed Screen Size from default to custom one in Chameleon settings, it not removed bad stripes from Youtube video. But i have **found option which removes the sripes from YT video - Options / Standard / Enable resist fingerprinting**
when unticked stripes are aways and issue not happen... @sereneblue can You try to enable this option to see whether stipes will appear for you on YT video?

**Comment by fabianski7** [comment]
> Can you try disabling screen size spoofing to see if that resolves the issue?

I tested it, the lines still appear

> If not, can you test with Chameleon disabled (from Firefox's about:addons page) and changing the user agent to Chrome?

Same behavior, the lines keep appearing.

It seems that it is not a problem of the chameleon...

I tested what the @slrslr  said and that really seems to be the conflict. I tested it on a new firefox profile, with the `privacy.resistFingerprinting` preference set as false and the problem doesn't happen

**Comment by sereneblue** [comment]
@slrslr Thanks for the thorough testing. I tried testing with a Chrome user agent and RFP enabled (Chameleon disabled) and was able to replicate the issue.

I compared the warnings with RFP/Chrome enabled and disabled and this appeared:

`Blocked https://www.youtube.com/watch?v=dQw4w9WgXcQ from extracting canvas data, but prompting the user. from extracting canvas data, but prompting the user.`

I checked about:config and there is a setting for this: privacy.resistFingerprinting.autoDeclineNoUserInputCanvasPrompts. If you set that to true and reload the Youtube page, FF will ask you to grant Youtube permission to extract canvas data. If you accept and reload the page, the lines no longer appear. I'm not sure why this issue only appears with a non-FF user agent, but with this solution you can continue to use Chameleon with RFP.

**Comment by slrslr** [comment]
when i modified that FF option as described, reloaded page, FF prompted me if want to allow youtube to unquely identify me, since i not wanted to allow it, i clicked somethwere else wanting to discover more details about this, but this prompt no longer appears on page refresh and bad stipes on the video remains.i am not aware about any way to fix this for everyone if they enable Resist fingerprinting chameleon option, only ideas are:
A) chameleon detect that option enabled and show some information box on youtube page to allow people disable it for youtube or such - that seems like a bit overkill to maintain up to date.
B) all people who enabled resist fingerprinting option will automatically have this option disabled on youtube -> seems questionable to do this for everyone without asking, and possibly hard to maintain outdated rules

**Comment by sereneblue** [comment]
The permission should appear in the location bar as a picture icon. If you click that, you should be able to grant the permission.

![image](https://user-images.githubusercontent.com/14242625/89488597-7064fa00-d776-11ea-817a-d49bf11b53b2.png)

I'm inclined to go with the first option. There's already a page in the wiki for some problematic sites, I can expand on this a bit more and display a badge on the icon with a link to https://sereneblue.github.io/chameleon/wiki/known-issues.

You can temporarily disable Chameleon by clicking the shield icon on the popup. The only issue with this is that changes made to Firefox preferences (RFP, tracking protection, etc) are left intact.
