### ISSUE TITLE
Is Chameleon interfering with History dates?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [sereneblue/chameleon#422]
Lately when I _Show All History_, all of my activity is listed under the wrong time - it's 11 hours off.

E.g. it's 11:21 pm here now, and although I came to GitHub about 20 minutes ago, History shows I got here at 6:01 am.

I suspected my VPN might be causing it, but the timezone doesn't change when I change countries.

I went to https://whatismytimezone.com/ and it shows GMT +0000.
I have repeatedly tried to attach the screenshot in both jpg and png formats, but keep getting an error message.

Because of the [prior issue,](https://github.com/sereneblue/chameleon/issues/375) I've left the Timezone setting on Default.

I didn't see any related posts in the Mozilla support forum. 
I just went to that forum at 11:23 pm, and History says it was 6:23 am. **That was 11 hours ago!**

My system clock is accurate.

Firefox 78.0.2

Chameleon 0.20.21-rc1

**Comment by sereneblue** [comment]
@GitTheHellOutaHere Do you have RFP enabled?

**Comment by GitTheHellOutaHere** [comment]
Resist fingerprinting? It was.

So I disabled it and checked again, disabled Privacy Settings and checked again, then disabled Firefox's Enhanced Tracking protection and checked again. No change.

Sorry - when I posted last night it was late and I was headed to bed. I should have first tried disabling Chameleon and then other extensions. I just did that, eventually disabling ALL of them plus my VPN. No change.

This is looking more like a FF issue.

I found [this](https://support.mozilla.org/en-US/questions/1191823) post saying privacy.resistFingerprinting could interfere with the timezone.

So I opened about:config, typed **resist** in the box and changed every true to false. Still no change.


I dunno - I'm flummoxed.

**Comment by sereneblue** [comment]
When `privacy.resistFingerprinting` is enabled, it changes your timezone to UTC. 

This could be a bug with Chameleon's UI because it may not show the actual value if you modify the about:config value. Try toggling it with Chameleon, without touching about:config and see if that resolves the issue.

**Comment by GitTheHellOutaHere** [comment]
I did.
I said I disabled it and checked again. And then did more diagnostics.

**Comment by sereneblue** [comment]
Disabling Chameleon doesn't affect certain Firefox settings like RFP.

**Comment by GitTheHellOutaHere** [comment]
I also changed ALL resist settings in about:config to FALSE.

I thought changing those settings would also change the Fingerprinters setting in prefs>Privacy & Security>Custom, but oddly it does not.

So I also made sure that box was unchecked as well (Tracking content too).
And STILL couldn't get the correct time.

**Comment by GitTheHellOutaHere** [comment]
Issue posted on mozillaZine, should have a reply (helpful or not) soon.

**Comment by GitTheHellOutaHere** [comment]
PROBLEM SOLVED!

I didn't restart after toggling privacy.resistFingerprinting.
Toggling that setting also toggles it within my 2 extensions with that feature.

You can delete this thread, sorry to have wasted your time!
