### ISSUE TITLE
Etag tracking issue

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [sereneblue/chameleon#424]
I tried to submit this via your contact page, but instead of a confirmation I got this:

![SereneBlue 405](https://user-images.githubusercontent.com/15519219/88376505-15520100-cd8d-11ea-9710-16050d2d03e3.jpg)

I'm not familiar with Etag tracking and I don't code. I read about Etags but still don't understand what they're for.

I was having trouble using a site so I disabled Chameleon (because it's usually the cause). The site began working so I re-enabled it and began disabling settings to discover the one causing the issue. Turned out to be Ett.

The site is http://inmateinformation.lanecounty.org/Disclaimer
Click the disclaimer and on the next page as you begin entering letters (at least 2) in either of the the NAME boxes, the page fills with people whose names match (try DA, MI or ST in the FIRST NAME box).

But with Ett enabled, entering letters does nothing - its as if JavaScript is being blocked. I checked the page source and searched for "etag", but etag  was not present. If it's not present, then why does blocking it break the page? Is that not how Etags work?

I try to block everything I can to protect my privacy and it sounds like blocking Etags is a good idea. The vast majority sites still work correctly, so are they not using Etags? Is that site misconfigured? Is this a Chameleon bug? Or is it working properly and that's just the consequences of blocking Etags on certain websites?

**Comment by sereneblue** [comment]
@GitTheHellOutaHere I'm not sure what happened with the contact form, but it seems to be resolved now. Might have been an issue with Netlify.

Etags shouldn't interfere with the page. It modifies the response header, so it doesn't touch client side Javascript. You shouldn't notice anything different with that option enabled. I couldn't replicate this issue, so it seems like something else is causing issues. Do you see any errors in the developer console when you try to use the search feature? Also, can you post your config?

**Comment by GitTheHellOutaHere** [comment]
Restarting Firefox seemed to have fixed it because it works for me
    now too with Etag tracking blocked.
    
    I sometimes encounter issues with another extension that won't fill
    in forms like it's supposed to.
    Then I restart Firefox and it works (usually).
    
    Strange that unchecking Ett made it work, but guess it was a glitch.
    Still don't know what Etags do, but I'll continue blocking them.
    
    Thanks.
    
    On 7/24/20 4:29 PM, sereneblue 
      wrote:
    
    
      
      
      @GitTheHellOutaHere I'm not sure
        what happened with the contact form, but it seems to be resolved
        now. Might have been an issue with Netlify.
      Etags shouldn't interfere with the page. It modifies the
        response header, so it doesn't touch client side Javascript. You
        shouldn't notice anything different with that option enabled. I
        couldn't replicate this issue, so it seems like something else
        is causing issues. Do you see any errors in the developer
        console when you try to use the search feature? Also, can you
        post your config?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sereneblue/chameleon/issues/424#issuecomment-663772434",
"url": "https://github.com/sereneblue/chameleon/issues/424#issuecomment-663772434",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
