### ISSUE TITLE
Extension UI does not fully displays

### ISSUE THREAD

**Issue by amadeous** [sereneblue/chameleon#425]
# Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
When I click on the Chameleon extension icon, I should see the whole extension tab, as in here.
![Normal behavior](https://sereneblue.github.io/chameleon/ui1.png)

## Current Behavior
I only see a portion of it and cannot scroll. Thus, I cannot perform the actions at the bottom of the tab as I use to do with the previous interface. Could you do something about it?
![extension-size](https://user-images.githubusercontent.com/7584409/88563503-56b70a80-d032-11ea-9246-dd9a0b54d9f8.png)

## Relevant settings
Configuration can be found [here](https://gist.github.com/amadeous/a014c5631c8ac30b0a414fb80f0262b6).

## Context (Environment)
Firefox 78.0.2 (64 bits) on Ubuntu 18.04.4 LTS

Thank you for this extension! :smiley:

**Comment by sereneblue** [comment]
Hi @amadeous,

Is Chameleon the only extension that you're experiencing issues with?

**Comment by amadeous** [comment]
Hi @sereneblue,

Yes, it is. Every extension displays in full, except one that have scroll bars so I can access the complete UI and it does not bother me.

**Comment by sereneblue** [comment]
> Hi @sereneblue,
> 
> Yes, it is. Every extension displays in full, except one that have scroll bars so I can access the complete UI and it does not bother me.

I installed FF 78.0.2 + Chameleon in a new Ubuntu 18.04 virtual machine and I wasn't able to replicate this issue. 
It's odd that Chameleon is the only extension that's giving issues. The dimensions for the popup are explicitly defined so I'm not sure why it's causing issues. Can you try creating a new Firefox profile and installing Chameleon there to see if you're still experiencing issues?

**Comment by sereneblue** [comment]
@amadeous Have you updated to FF79?

**Comment by amadeous** [comment]
I updated to FF79 and also tried to uninstall chameleon, restart firefox and re-installed it again. Still doesn't work...
I will try to create a new profile by sunday later. But what would cause this extension in particular to have a strange size? Why would a new profile change something? I did not edit any parameters related to this extension (except these handled by Chameleon).

**Comment by Thorin-Oakenpants** [comment]
The size and location is all fine, your fonts are too big
![eeek](https://user-images.githubusercontent.com/16656956/89090676-00c8c680-d394-11ea-970f-6e11da0d152e.png)

- what are your default fonts and size (serif, sans serif, monospace)
- what is your system or font scaling settings? - e.g. [click](https://www.omgubuntu.co.uk/2020/04/ubuntu-20-04-fractional-scaling-support-setting)

**Comment by sereneblue** [comment]
@amadeous I was curious if an about:config preference (like zoom levels) might have been causing an issue but I think @Thorin-Oakenpants is onto something.

**Comment by Thorin-Oakenpants** [comment]
`layout.css.devPixelsPerPx` default `-1.0` is a safe way to increase "everything" .. e.g. setting it to `1.2` makes everything 20% bigger, including the popup. Whereas, and I can't test because I do not want to mess with it, changing system settings does not affect the "chrome/containers" per se, just makes "content" bigger

RFP handles this pref nicely: windows still round to 100x200's etc, LBing still works .. etc. System scaling fucks RFP up

**Comment by sereneblue** [comment]
> `layout.css.devPixelsPerPx` default `-1.0` is a safe way to increase "everything" .. e.g. setting it to `1.2` makes everything 20% bigger, including the popup. Whereas, and I can't test because I do not want to mess with it, changing system settings does not affect the "chrome/containers" per se, just makes "content" bigger
> 
> RFP handles this pref nicely: windows still round to 100x200's etc, LBing still works .. etc. System scaling fucks RFP up

I resolved the UI issue by explicitly setting the font size for the popup. I use `layout.css.devPixelsPerPx`with my default Firefox profile. It's the better option compared to scaling the display settings.

**Comment by Thorin-Oakenpants** [comment]
> I resolved the UI issue

good boy 🍻

**Comment by amadeous** [comment]
My `layout.css.devPixelsPerPx` is indeed set to `-1` and my KDE fonts settings are mainly Noto Sans 12. I increased values in FF as well because the text was really too small but it worked fine so far… I adapted FF font current values and I can see the whole Chameleon UI.
Thank you for the solution, the fix and the great extension @sereneblue!

**Comment by sereneblue** [comment]
@amadeous v0.20.22 has been released. Feel free to change your font size or increase `layout.css.devPixelsPerPx`.
