### ISSUE TITLE
Request: Add The Option To "Toggle" about:config Options & Mouse Over?

### ISSUE THREAD

**Issue by 0pLuS0** [sereneblue/chameleon#43]
Hello,

First let me say thanks for picking up where RAS left off, at least I hope this is where this project is going, to be the RAS replacement for future Firefox versions?

For the ```Misc Options``` and ```Reporting Options``` can you please make this so we can Toggle them on and off in the Add-On? It's a pain to have to go into about:config when something needs to be changed which can be often, because you know, some of these will break website function, so we need a faster way with the ability to toggle on/off.

Also, I don't see there is the ability at present to tell which Profile you are using unless you simply pay attention at the Notification when starting Firefox. It would be really nice if you could please make a ```Mouse Over``` notification, when you place your mouse on the Chameleon icon, there will be a popup displayed, how RAS works, showing the Profile you are on.

Thank you for your time and consideration, I hope you can please make these changes in the near future!

**Comment by sereneblue** [comment]
Unfortunately, Chameleon isn't able to toggle about:config options because WebExtensions are unable to do so. The best we can hope for is for Mozilla to add new APIs to toggle certain options.

The mouse over feature is a good idea. I'll add it in the next version.

**Comment by 0pLuS0** [comment]
Ahh I won't be able to upgrade Firefox then, I'm going to have to stay below Quantum versions, because I have to constantly toggle on/ff, I'm constantly online surfing various sites all day long, it would be to time consuming to have to constantly go in about:config and change settings all the time.

I hope you realize, even for the average person that is going to surf around quite a bit, hobby like surfer, they are also going to need the ability to change this quickly, without this ability, I'm afraid Chameleon isn't going very far.

Also do you have just as many options for about:config that RAS had?

Another thing, I don't recall you having ```telemetry``` options, any and all should be included to kill this nasty crap.

My understanding, there is also suppose to be social media crap too, these from what I understand in previous versions;

social.directories
social.remote-install.enabled
social.toast-notifications.enabled
social.whitelist

This really SUCKS! 

Any hope on this, any word, anyone know anything about a possible change on this? What's your thoughts on this WebExtensions? Seems like it messed up the Add-On scene for previous development...

**Comment by sereneblue** [comment]
Yes, I'm aware that it's a usability problem but there's not much I can do about it. That's a limitation of WebExtensions. Chameleon's primary feature is spoofing the browser profile, the about:config options to enhance privacy is just an extra. The contentScript API introduced in Firefox 59 is required to properly spoof the resolution, browser, and OS.

I believe most of the about:config options are there; some may have removed because they no longer exist. There are a few telemetry options listed under `Reporting Options`. You can read more about them on the [wiki](https://github.com/sereneblue/chameleon/wiki/Options#reporting-options). I don't see any of the social entries you mentioned in Firefox 62's about:config. I guess they've been removed?

Although WebExtensions aren't as powerful as previous addons, I understand why Mozilla made the decision to remove them. They had too much power (bad for security) and hindered Firefox development. The best thing we can do is move on and request Mozilla to create new APIs to toggle certain settings.

**Comment by 0pLuS0** [comment]
Well I'll sit and wait then I guess, in the meantime I'm back to older FF ESR so I can keep RAS for now.

Keep up the great work, I'm sure we are going to need it!

Thanks

**Comment by 0pLuS0** [comment]
I know it hasn't been long, any changes in this?

It's really a pain to have to copy and paste and manually change, especially when a website doesn't work and you have to constanly go back and forth, this is just to troublesome, there needs to be something done...

Can't there be these links in Chameleon like they are now, and we click them and they just open up the about:config with the name listed and already showing, and all we have to do now is just enable/disable the option? At least this would make things a little better...

**Comment by 0pLuS0** [comment]
There's not even a way to have the links clickable and have them load the about:config page automatically?

This is really the killer here I see for this addon, if you can't ever figure out some way around this, or to make it a littler easier.

I'm a Geek, I've been at this a long long long time, and I can tell you even as a Geek, this is never going to fly for the majority of users. Even with RAS, as simple as that was, it was a limited amount of users, this is going to limit it even further.

I hope something can be accomplished...

Thanks

**Comment by sereneblue** [comment]
It's a browser limitation; there's nothing I can do about it. The only thing I can suggest is reaching out to Mozilla to add more WebExtension APIs.

**Comment by sereneblue** [comment]
From what I've read, Mozilla won't allow WebExtensions to access about:config entries and that won't change. There's a few people asking for WebExtension APIs for some of the entries listed above but it's a bit time consuming to keep track of all of the conversations. 

Unfortunately, I'm currently working on resolving the existing issues so I can cut back on Chameleon development (no new features, just bug fixes and minor updates) to work on other things.
