### ISSUE TITLE
The translations in Chameleon Dashboard doesn't take affect

### ISSUE THREAD

**Issue by giwhub** [sereneblue/chameleon#432]
I just noticed translations didn't work in Chameleon Dashboard.

![深度截图_选择区域_20200803012239](https://user-images.githubusercontent.com/14066437/89128500-9b5a0e80-d528-11ea-8b2b-75fdad68435d.png)

**Comment by sereneblue** [comment]
@giwhub I forgot to update the fallback locale for the dashboard page. I'll release an update ASAP. Thanks for mentioning it.
