### ISSUE TITLE
Cookies Rule Problem

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#434]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

## Expected Behavior
The cookies rule should remain the one the user  has chosen.

## Current Behavior
The Chameleon cookies rule is stucked on "Allow all" . When I select a different rule,  Chameleon reset it to "Allow all". Strangely enough, the cookies rule in Firefox (Tools->options->privacy) remains set to block all third parties ((I have in FF selected "Custom").

## Context (Environment)

FF 79 on W10.

**Comment by sereneblue** [comment]
When does Chameleon reset your cookie settings to "Allow all"? If you make changes to the cookie settings, it should visible change the setting on the `about:preferences` page.

![image](https://user-images.githubusercontent.com/14242625/89360372-38868580-d696-11ea-9c45-19db1da010dc.png)

**Comment by Kraxys** [comment]
In about:preferences Il have selected "block all third parties". And Firefox says that Chameleon is controlling this setting. 

But when I, click on Chameleon -> Options -> cookie, the option "Allow All" is displayed.


More Precisely, when I set it to "reject third parties", then click on home (chameleon), then goes to options -> cookies, "reject 3rd parties" is still displayed. But when I click elsewhere on my screen, and then go to chameleon/option/cookies, what is displayed is "Allow all".

**Comment by sereneblue** [comment]
@Kraxys I'll have to update how these special preferences are handled. When changes are made to about:config they aren't reflected in the Chameleon UI. I was able to reproduce the issue with "Allow all" appearing, this does seem like a bug. This should be addressed in the next update.

**Comment by Kraxys** [comment]
In fact, despite "Allow all" displayed as cookie rule, when I export my profile, I see:

`"ipRules": [],
  "options": {
    "cookieNotPersistent": true,
    "cookiePolicy": "reject_third_party"`

So it may only be a display problem. The rule effectively applied seems to be "reject 3rd party".

**Comment by sereneblue** [comment]
Hi @Kraxys,

Yes, this was a bug in the UI. It should be resolved in v0.21.0.
