### ISSUE TITLE
Websockets preference is being reset to "Allow all"

### ISSUE THREAD

**Issue by asvc** [sereneblue/chameleon#442]
## Expected Behavior
"Websockets" preference persists.

## Current Behavior
Please refer to the screen-recording:
![chameleon_websockets](https://user-images.githubusercontent.com/300146/90310580-4633da80-dee2-11ea-81da-5444f41fbb69.gif)

## Relevant settings

[chameleon_1597487289000.json.log](https://github.com/sereneblue/chameleon/files/5078482/chameleon_1597487289000.json.log)

## Context (Environment)

FF 79.0
Chameleon v0.20.24

**P.S.** Might be relevant to https://github.com/sereneblue/chameleon/issues/220

**Comment by sereneblue** [comment]
Hi @asvc,

I've made some updates to the UI in v0.21.0 that should resolve this issue.
