### ISSUE TITLE
Add spoof of WebGL Vendor and Renderer?

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#45]
Currently amiunique.org can detect WebGL Vendor and WebGL Renderer even when using chameleon. It can even detect whether you are running in  virtualmachine or not. Could you add support for such protection? Thank you very much.

About WebGL Vendors:  
-NVIDIA Corporation
-AMD (Not sure about the exact naming)
-VMware Inc. (for virtual machines) 

About WebGL Renderers:
-EVGA GeForce GTX 1070
-EVGA GeForce GTX 1060
-EVGA GeForce GTX 1080
-EVGA GeForce GTX 1050
-EVGA GeForce GTX 960
-EVGA GeForce GTX 1050 Ti

_Data from Amazon UK and US best sellers (for no. of revies) and https://store.steampowered.com/hwsurvey/videocard/_

**Comment by sereneblue** [comment]
I'm not too sure how to go about this. Ideally, if a user is concerned about being tracked via WebGL, they'd disable it in about:config.

On Windows, Firefox returns `Google Inc.` for the vendor with  Linux, Firefox returns `VMWare Inc.`.

**Comment by WPFilmmaker** [comment]
@sereneblue That's a good point, though, wouldn't it make the browser more unique? I don't think many disable WebGL...But I am no expert, so if you are not sure about it I would say either leave it open for further opinions or close the ticket.

**Comment by sereneblue** [comment]
Hm, I wonder if disabling WebGL creates a more unique fingerprint compared to using a specific graphics card. I think most desktop users have an integrated graphics card. If I had to choose, I'd disable WebGL. Outside of a few things like games, it's not necessary for websites to have access to it.

**Comment by slrslr** [comment]
> disable it in about:config

if anyone needs, then it seem to be the option "webgl.disabled". Set it to true.

Here is how to do it not only for the **Firefox** but also for the **Chrome**: https://ipleak.com/articles/what-is-webgl-and-how-to-disable

In my case it decreased uniqueness to:
One in x browsers have this value: 8.83
And on [other testing site](https://amiunique.org/fingerprint) to 14% similarity ratio (not bad).
