### ISSUE TITLE
Please add a license to the software

### ISSUE THREAD

**Issue by arhayati** [sereneblue/chameleon#453]
Hey. Thanks for great plugin. However, it doesn't have a license  therefore it's not software libre. Would you mind adding a license? I suggest GNU AGPL or GNU GPL.

**Comment by sereneblue** [comment]
HI @arhayati,

Thanks for mentioning this. Chameleon was originally released under the GPLv3 license, but that information got lost after the v0.20.0 update. I'll add a license to the repository.

**Comment by arhayati** [comment]
But the license is not still added!

**Comment by sereneblue** [comment]
@arhayati It's in the [develop](https://github.com/sereneblue/chameleon/tree/develop) branch. The changes will be merged to master soon.
