### ISSUE TITLE
Chameleon v0.21.1 does not remember UAs options selected in the previous version

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#455]
Today I casually checked chameleon settings (I usually tweak it and don't have it in the toolbar)

I realized my UA was linux and was like wtf :o 

I checked the settings and chameleon had done the same as #323, UA selection had been reset and my preferences overridden (I only had windows 10 and chrome on, but the new preferences included linux and mac as well).

I am sure this is not an intentional thing, however such things should not change without user knowing, because they could compromise privacy.

Thank you :)

Chameleon v0.20.1, FF 80.0.1 Linux, Lubuntu 18.04

**Comment by sereneblue** [comment]
Hi @WPFilmmaker, 

This is definitely not intentional. Was Chameleon the only addon affected? I just tried upgrading from v0.20.24 to the latest version and that didn't seem to affect anything.

**Comment by WPFilmmaker** [comment]
@sereneblue yes only addon affected, several desktop profile were allowed (I had set only windows 10) including firefox.
I thought maybe chameleon forgot settings but I checked today and the settings I reenable are there..so it seems it happened after the upgrade. I don't know what other info could help you :/

**Comment by sereneblue** [comment]
@WPFilmmaker I'll do some more testing to see if I can reproduce this issue.

**Comment by sereneblue** [comment]
@WPFilmmaker I haven't been able to reproduce this bug. Has this bug occurred since you first opened this issue?

**Comment by WPFilmmaker** [comment]
@sereneblue No, I am going to close it ;)
