### ISSUE TITLE
chameleon interferes with one site timetable

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#458]
Due to privacy reason I won't make which site is this publicly,
however @sereneblue sereneblue can find the link here: 

https://privatebin.net/?98b6a7100ab2d2ae#j9b9C5MQdb8JdsXBWbGkxPtKx5w3kffh1WqzvAeuw9P

(password: dspace:13292)

What happens is that chameleon interferes with the timetable. For example day 16 shows classes but in reality the day with classes is 17. So chameleon switches the day shown in the timetable to 1 day.

I don't know what info I can provide and whether you can fix this or I should just whitelist it but I think it refers to time spoofing.

Info: FF 80.0.1 (64-bit), Lubuntu 18.04  Chameleon 0.21.2.2

Chameleon settings:

https://privatebin.net/?125bf0f63a7b27e4#EVaW8bR2iDsRhA2nMm97bmtuXpwNL4NpRThrnG7HHzMZ

(no password needed)

**Comment by Thorin-Oakenpants** [comment]
Test by turning off `privacy.resistFingerprinting` and reloading the page - hard reload with F5 to make sure. RFP reports your time as UTC .. -> https://www.timeanddate.com/time/map/

e.g. let's say you're in California, USA (which is 7 hrs behind UTC) and your class is at 7pm .. then USA Pacific Time 7pm is actually 2am the following day in UTC time

Chameleon allows you to spoof a timezone, and lets say you were in New Zealand at +12, but lied that you were -7 in California, that difference is 19hrs .. easily enough to screw up your calendar. It's all relative.

I get it all the time, I look up a sports event and it reports the start time at if I was in the UK (I use RFP not chameleon)

**Comment by WPFilmmaker** [comment]
Thanks for the suggestion @Thorin-Oakenpants What you mentioned makes sense, but by privacy.resistFingerprinting you mean options-standard-enable resist fingerprinting? If yes I realized it was not enabled :/

**Comment by Thorin-Oakenpants** [comment]
RFP is one way to spoof your timezone. But chameleon also allows you to spoof it as well. The website is only going on what your browser is telling it, so you're telling it porkies (lies) as per what you set chameleon to do.

**Comment by sereneblue** [comment]
@WPFilmmaker If you're using RFP or timezone spoofing, this could cause issues with some sites. Since you're interacting with dates and calendars, text values can change depending on your spoofed localized timezone. If it's causing issues for you, I recommend whitelisting the site.
