### ISSUE TITLE
v0.21.2 - Installation Odd & Permissions Issue? Chameleon Not Working

### ISSUE THREAD

**Issue by 0pLuS0** [sereneblue/chameleon#460]
# Prerequisites

- [* ] I am running the latest version
- [ *] I checked the documentation and found no answer
- [ *] I checked to make sure that this issue has not already been filed

## Expected Behavior
Easy to install and just works

## Current Behavior
I installed from Mozilla, after the install, a window inside Firefox appeared with an Install button, I have a screen shot of, so it like wanted to install itself twice.

Now when I go to the settings Chameleon has had in the past, I see this;
```Grant permissions to modify settings``` and nothing happens, I don't see anything working, I can't access any of these settings.

## Context (Environment)
Windows 10

68.12.0 ESR

``` After I installed the addon from Mozilla, here is the Window with an Install button;```

![Install](https://user-images.githubusercontent.com/36190223/93659360-ed50e800-fa33-11ea-8536-53ca8d3d45e5.jpg)

```Here is a screenshot of the Permissions it's asking about, this also appears on the Cookie section too, not sure if these two sections are the only place, it's all I checked```

![permissions](https://user-images.githubusercontent.com/36190223/93659381-1ffae080-fa34-11ea-9734-3b94e135ff5d.jpg)

**Comment by sereneblue** [comment]
Hi @0pLuS0,

For v0.21.0+, the `privacy` permission is now optional. This is only supported in Firefox 75+, so users who install Chameleon on an older version of Firefox won't be able to enable it.

Fortunately, there is a separate build ([legacy version](https://github.com/sereneblue/chameleon/releases)) for Chameleon that requires the privacy permission. This was originally made for users using the old version of Firefox for Android. There aren't any functional differences besides the required privacy permission and updates coming directly from Github.

Privacy permissions are only needed for the options present, but disabled, on the Standard/Cookie tabs.

I'll update the UI to include this information for users using older Firefox versions.

**Comment by 0pLuS0** [comment]
@sereneblue 

Hi, is this something you did, or because of Firefox the permissions changed?

ESR technically isn't old, this is what Mozilla says about ESR;

https://support.mozilla.org/en-US/kb/switch-to-firefox-extended-support-release-esr

While it says it's developed for large organizations like universities and businesses, it doesn't mean any of the above need to use it, the reason anyone would want to use it, is because they just want a simpler, less bloated version of Firefox and don't need all the extras the normal releases come with.

Maybe you know Patrick Volkerding who developed Slackware;

https://en.wikipedia.org/wiki/Patrick_Volkerding

https://en.wikipedia.org/wiki/Slackware

Slackware is the oldest Linux Distro since 1993, and Slackware, since the release of ESR has been using since it began, and I can tell you for that length of time, there is nothing OLD about this!

So I'm only spewing all this, not just for your benefit, I'm assuming you might know all the above information, but to enlighten others, or possibly yourself too if you are not aware of this, because most end-users are clueless about Firefox ESR.

So I can tell you the main reason Slackware uses ESR, is because again, as I mentioned, less bloated with less of the BS features that most might not use, and having more in code, always increases the risk of bugs, you're a coder, you should know that...

```Bottom Line, ESR is the latest version of Firefox without the fancy toys is all...```

```ESR is not OLD``` :+1:

**Comment by sereneblue** [comment]
@0pLuS0 This was a change introduced in v0.21.0 to resolve the issue of overlap between different extensions managing the same Firefox preferences.

Yes, I'm aware of Firefox ESR, the new ESR should be [FF78](https://wiki.mozilla.org/Release_Management/Calendar) although it seems v68 is still getting updates.

Thanks for the suggestion. The legacy build is automatically built from Github when a new release is tagged so it'll be around as long as Chameleon. I could repurpose this to be a a build for ESR users.

**Comment by 0pLuS0** [comment]
Ok sounds great!

THANKS

**Comment by 0pLuS0** [comment]
@sereneblue 

I just got Firefox Setup 78.3.0esr for Windows, so I'm assuming that will work?

But the ```Install``` window that pops up after actually installing Chameleon off of Mozilla needs fixing, it shouldn't being shown needing to be installed, once it has...

THANKS

**Comment by sereneblue** [comment]
@0pLuS0 

Yes, it should work fine with Firefox 78. Thanks for mentioning the wiki issue. I'll update Chameleon and the wiki so the button is hidden for the first time install page load.
