### ISSUE TITLE
android support gone since firefox update

### ISSUE THREAD

**Issue by lebr0n23** [sereneblue/chameleon#461]
since firefox update, chameleon is not supported on android anymore, only on my desktop.
is any related update planned or is android support not in focus for the future.

thank you.

**Comment by sereneblue** [comment]
Hi @lebr0n23,

Chameleon does have support for Android. The new Firefox update currently has limited support for addons but this should change in the near future. More details can be found [here](https://blog.mozilla.org/addons/2020/09/02/update-on-extension-support-in-the-new-firefox-for-android/).
