### ISSUE TITLE
Timezone Error in Gmail 

### ISSUE THREAD

**Issue by coyy** [sereneblue/chameleon#465]
The email list in https://mail.google.com won't show up if Timezone is set other than default

**Comment by sereneblue** [comment]
@coyy Timezone spoofing is experimental and can cause issues with some sites. It's heavily used on Google sites (in some strange ways) which can lead to some issues. You can whitelist `mail.google.com` if you still want to timezone spoofing for other sites.

**Comment by sereneblue** [comment]
@coyy This timezone spoofing issue is resolved as of v0.21.13.
