### ISSUE TITLE
Is Chameleon completely disabled on all Google Pages?

### ISSUE THREAD

**Issue by sig222** [sereneblue/chameleon#466]
Hello,

In [this thread](https://github.com/sereneblue/chameleon/issues/339#issuecomment-623188593) you say you want to disable spoofing on any Google Pages. Does this only apply specifically to "spoofing" or to all Chameleon functions? How about these functions: "Block Media Devices", "protect Window.name", "1st party isolation", "deactivate WebRTC", "block Etag Tracking" etc... Are they also all disabled on all google Pages? I hope not. Google and Facebook are the worst. PS. Sorry for my bad English, I'm from Germany. I hope you anderstand me correctly. 
Greetings

**Comment by sereneblue** [comment]
Hi @sig222,

The following Google URLs/subdomains are exempt from Chameleon spoofing:

```
https://www.google.com/recaptcha/api2
https://accounts.google.com
https://docs.google.com
https://drive.google.com
https://accounts.youtube.com
```

If you're just browsing Google with a spoofed profile, spoofing will still work.

The browser profile, all of the options on the injection tab, and websockets are handled by Chameleon and will not be spoofed/blocked for those subdomains.

First party isolation and WebRTC settings are Firefox level preferences that Chameleon can't manage on a per-site basis.

**Comment by sig222** [comment]
Thank You!
