### ISSUE TITLE
"Real profile" always shows Windows NT 10.0 & Mozilla 78.0

### ISSUE THREAD

**Issue by sig222** [sereneblue/chameleon#468]
Hello, 

Why does "real profile" always show Mozilla/5.0 (Windows NT 10.0; rv:78.0) regardless of whether I use Windows 10 or 7 or Linux + Mozilla ver. 81.0? It is not specified anywhere in the settings. 
Thank You.
Greetings
sig

**Comment by sereneblue** [comment]
@sig222 Do you have resist fingerprinting enabled? The chain below shows which profile is used.

Chameleon profile (if spoofed) => RFP Spoofed Profile (if enabled) => Real Firefox Profile.

**Comment by sig222** [comment]
@sereneblue yes resist fingerprinting was enabled, Tank You!
