### ISSUE TITLE
'Resist fingerprinting' breaks unicode, even when Chameleon is disabled 

### ISSUE THREAD

**Issue by pannous** [sereneblue/chameleon#469]
##  Expected Behavior
'Resist fingerprinting' does not break unicode
'Resist fingerprinting' is not active when Chameleon is disabled
'Resist fingerprinting' is not active when page is whitelisted

## Current Behavior
'Resist fingerprinting' breaks unicode, both in address bar as well as on pages e.g.:
https://en.wiktionary.org/wiki/%F0%92%80%AD%F0%92%8C%89

This can only be remedied by setting 'Resist fingerprinting' to OFF or 
disabling the whole Chameleon plugin in about:addons

Disabling Chameleon via clicking the Chameleon shield so that it becomes red does NOT resolve the issue.

Adding a page to the whitelist does NOT resolve the issue.

## Relevant settings
'Enable resist fingerprinting' ON

## Context (Environment)
FF 81
Mac 10.15.6

**Comment by sereneblue** [comment]
Hi @pannous,

RFP is enabled even when Chameleon is not disabled. It's a Firefox level setting that doesn't offer granular control to programmatically enable it. I'm not sure there's anything I can do to help you fix this issue.

**Comment by pannous** [comment]
It's fine, it's a great product even without RFP enabled

**Comment by Thorin-Oakenpants** [comment]
https://en.wiktionary.org/wiki/Category:Sumerian_nouns

It's broken with or without RFP: it depends if your system has applicable fallback fonts. I'm not sure anyone uses Sumerian these days - they ceased around [1750 BCE](https://www.ancient.eu/Sumerians/) - just a guess why OSes don't ship with fonts for them
