### ISSUE TITLE
Issue with whitelisting chess.com

### ISSUE THREAD

**Issue by quiet23** [sereneblue/chameleon#472]
## Expected Behavior

Whitelisting should let the site to be operational.

## Current Behavior

On chess.com main page, if I try to enter Report bug mode using menu in the lower left corner of the screen (Help -> Report a Bug), the whole page (not page tab, it can be closed) freezes. chess.com is whitelisted, profile is the Real Profile. After disabling Chameleon the site functionality restores.

## Context (Environment)

Chameleon 0.21.5
Firefox 82.0 under Windows 8.1 64-bit.

**Comment by sereneblue** [comment]
Hi @quiet23,

Can you post your settings? Also, does Chameleon show that the website is whitelisted in the popup window?

**Comment by quiet23** [comment]
Hi, @sereneblue,

[chameleon_1603759824272.zip](https://github.com/sereneblue/chameleon/files/5442275/chameleon_1603759824272.zip)

<img width="800" alt="chess com whitelisted" src="https://user-images.githubusercontent.com/30497731/97243972-e24a5e00-1810-11eb-85d6-f614eba85df8.png">

**Comment by sereneblue** [comment]
@quiet23 Thanks, I've located the issue. This should be resolved in the next update.

**Comment by sereneblue** [comment]
@quiet23 This issue should be fixed in v0.21.6. Please let me know if you're still encountering issues.
