### ISSUE TITLE
[Request] The problem of successful payment on banking websites

### ISSUE THREAD

**Issue by Saadi2020** [sereneblue/chameleon#473]
1. I do not know how to work with IP Rules well. And for example, I do not understand the meaning of this option:"Spoof X-Forwarded-For/Via IP". What should I do? 
An example of my needs for spoof ip: I use a VPN anti-filter. Every time I enter YouTube.com from the Google search page, I have to go through reCAPTCHA due to the use of VPN.

2. The two last times I paid with Firefox on a banking website, payment was successful on website but not registered with the bank. After that, such a problem does not happen with the Edge browser. Could it be because of chameleon? Or because of a specific config?

3. Can you create an option to reset all configs in Firefox that are changed by the chameleon?

4. Can you assign a whitelist for exception sites so that chameleon do not affect them?

## Context (Environment)
Firefox Nightly. Windows 10 Pro x64

**Comment by sereneblue** [comment]
Hi @Saadish,

1. "Spoof X-Forwarded-For/Via IP" does not spoof your actual IP. It spoofs some header values that some servers use to determine your IP. You might need a better VPN provider or use a different server.
2. Difficult to tell if it's Chameleon or Firefox causing the issue. I'm not sure how to test this but what's your config?
3. Resetting those settings is a bit messy considering the user can change them at any time outside of Firefox. Although it's simple to do, it's probably better left to the user. The only Firefox preferences that are changed by Chameleon are shown on the `Standard` and `Cookie` tabs on the [Options](https://sereneblue.github.io/chameleon/wiki/options) page. 
4. Yes, that's the whitelist: https://sereneblue.github.io/chameleon/wiki/whitelist.

**Comment by Saadish** [comment]
Thank you for your answer. 
What I meant by the fourth question was that the websites included in this whitelist, won't affect, by changes in header and options. (Sorry, it seems online translators are not working properly). 
I think it is not possible. I don't want Firefox config changes to be applied to sites. I think this is not possible.

Sorry, Thanks.

**Comment by sereneblue** [comment]
@Saadish The whitelist generally exempts the header options from being changed. You are correct that the Firefox preferences affect whitelisted sites. It isn't possible, and probably won't be any time soon. RFP is usually the cause of a few issues, so you might want to leave that unchecked if you're using it.
