### ISSUE TITLE
"Web Browser Features Detection" able to fingerprint Chameleon

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#478]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Expected Behavior
Browsing with Chameleon should not be easily fingerprintable, and especially not cross session fingerprintable. 

## Current Behavior
What ever setting I select in Chameleon, I get exactly the same  "Web Browser Features" fingerprint on [Bowserleaks.com](https://browserleaks.com/features)

## Relevant settings
Any one of them. The fingerprint remain the same, even from a browser session to an other. The only thing a little able to change the fingerprint is the webrtc setting, a parameter you want not anyway to modify very often once chosen. 

## Context (Environment)

FF 83 on W10

**Comment by sereneblue** [comment]
@Kraxys Chameleon can't do much here. Feature detection works by checking what browser APIs/features are supported. Limiting JS in the browser using an extension like NoScript or uMatrix should limit the effectiveness of this approach. I don't think it's used widely compared to the low hanging fruit of using an IP/user agent/timezone/etc.

**Comment by Kraxys** [comment]
> 
> 
> @Kraxys Chameleon can't do much here. Feature detection works by checking what browser APIs/features are supported. Limiting JS in the browser using an extension like NoScript or uMatrix should limit the effectiveness of this approach. I don't think it's used widely compared to the low hanging fruit of using an IP/user agent/timezone/etc.

You are certainly right. I realise now that my message may sound a bit harsh, but that was not my intention. I was only surprised by this stubborn fingerprint, which I had never paid attention to until now. Using an addon such as uMatrix can effectively block certain features, thus changing the fingerprint, but what everyone chooses to block on his/her side can be seen as a different kind of footprint itself. It's a complicated problem. Same kind of difficulty as Apple had with Safari intelligent tracking prevention feature, or the EFF with one PrivacyBadger machanism. All that remains nevertheless probably theoretic for the moment but it is worrying.

**Comment by sereneblue** [comment]
> > @Kraxys Chameleon can't do much here. Feature detection works by checking what browser APIs/features are supported. Limiting JS in the browser using an extension like NoScript or uMatrix should limit the effectiveness of this approach. I don't think it's used widely compared to the low hanging fruit of using an IP/user agent/timezone/etc.
> 
> You are certainly right. I realise now that my post may have sounded a bit harsh, but that was not my intention. I was only surprised by this stubborn fingerprint, which I had never paid attention to until now. Using an addon such as uMatrix can effectively block certain features, thus changing the fingerprint, but what everyone chooses to block on his/her side can be seen as a different kind of footprint in itself. It's a complicated problem. Same kind of difficulty as Apple had with Safari intelligent tracking prevention feature, or the EFF with one PrivacyBadger mechanism. All that remains nevertheless probably theoretic for the moment but it is worrying.

It's definitely worrying. There's a useful page [here](https://arkenfox.github.io/TZP/) that's even more extensive! I do recommend using NoScript/uMatrix in the [wiki](https://sereneblue.github.io/chameleon/wiki/recommended-extensions/). The only alternative solution that really solves this is using the Tor Browser, but that can be a problem for day to day usage. I do think those addons should be sufficient for most people. It's a losing battle, but I intend to do what I can.
