### ISSUE TITLE
Enhance time spoofing

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#48]
#21 Added the possibility to set a timezone, however reading on random-agent-spoofer bugtracker, it seems that there are several places where timezone has to be changed. I couldn't understand whether chameleon does that, hence my ticket. If chameleon hasn't that implemented probably it would be good adding such enhancement?

From: https://github.com/dillbyrne/random-agent-spoofer/issues/66

_"Currently only the time zone offset is spoofed.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toGMTString
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString"_

_"Some date integer functions were originally included in the spoofing but they were dropped as they were causing page timeouts. Date locale strings will need to be set using the language headers for all the spoffed attributes to match. The selection of the time zone abbreviation is currently randomly selected when a timezone has been chosen. This could be improved to allow users to select the abbreviation in addition to the timezone."_

_"Time based fuctions such as getHours() need to be spoofed in such a way as to not break functionality like the previous version. Moving the date/time spoofing logic into the inject script will probably address the breakage as the functions will return updated but spoofed data each time they are called."_

Does chameleon changes

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toGMTString

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

?

**Comment by sereneblue** [comment]
It looks like `toGMTString` has been deprecated so it's no longer relevant (it's still spoofed). Chameleon does spoof the locale string. Everything appears to work when visiting `browserspy.dk`.
