### ISSUE TITLE
Non Default TimeZone prevents me to read my email on Tutanota

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#480]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

## Expected Behavior
I should be able to read the email I received on my tutanota.com account
## Current Behavior
When TimeZone is set to something other than "default", I can't access to most of the emails I received in my inbox. 

## Relevant settings

{
  "config": {
    "enabled": true,
    "notificationsEnabled": true,
    "theme": "light",
    "hasPrivacyPermission": true
  },
  "excluded": [],
  "headers": {
    "blockEtag": true,
    "enableDNT": false,
    "referer": {
      "disabled": false,
      "xorigin": 0,
      "trimming": 0
    },
    "spoofAcceptLang": {
      "enabled": true,
      "value": "en-US"
    },
    "spoofIP": {
      "enabled": false,
      "option": 0,
      "rangeFrom": "",
      "rangeTo": ""
    }
  },
  "ipRules": [],
  "options": {
    "cookieNotPersistent": true,
    "cookiePolicy": "reject_trackers",
    "blockMediaDevices": false,
    "blockCSSExfil": false,
    "disableWebRTC": true,
    "firstPartyIsolate": true,
    "limitHistory": false,
    "protectKBFingerprint": {
      "enabled": false,
      "delay": 34
    },
    "protectWinName": false,
    "resistFingerprinting": true,
    "screenSize": "1366x768",
    "spoofAudioContext": false,
    "spoofClientRects": false,
    "spoofFontFingerprint": false,
    "spoofMediaDevices": false,
    "timeZone": "default",
    "trackingProtectionMode": "always",
    "webRTCPolicy": "disable_non_proxied_udp",
    "webSockets": "allow_all"
  },
  "profile": {
    "selected": "none",
    "interval": {
      "option": 0,
      "min": 1,
      "max": 1
    }
  },
  "version": "0.21.12.1",
  "whitelist": {
    "enabledContextMenu": false,
    "defaultProfile": "none",
    "rules": []
  }
}
## Context (Environment)

FF 83/84 on Windows 10

**Comment by sereneblue** [comment]
Hi @Kraxys,

Thanks for reporting this issue! I've identified the issue in the timezone spoofing implementation. It should be fixed in the next update.
