### ISSUE TITLE
Audio context spoofing doesn't work.

### ISSUE THREAD

**Issue by gnu-ewm** [sereneblue/chameleon#481]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Chameleon doesn't spoof audio context. Enabled spoofing audio context returns real fingerprint. Disabled audio context spoofing returns in Cover Your Tracks 'randomized by first party domain'.

## Context (Environment)
Firefox 84, Linux

**Comment by sereneblue** [comment]
Hi @gnu-ewm,

It does seem to work. I tested with v0.21.12 and I got a different value when I enabled audio context spoofing. It's probably best to compare the values from right to left. There's a very slight difference with the last few digits.

**Comment by Thorin-Oakenpants** [comment]
@sereneblue .. check your invites
