### ISSUE TITLE
window.name protection sends a constant non usual http header

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#482]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

## Expected Behavior
window.name protection should not send any  special constant data making easier to correlate your browsing activities.

## Current Behavior
But I tested window.name protection on ip-check.info. One on the second page the one you reach after having clicked on your IP on the first page), window.name is declared protected, and no special http header relative to the window.name protection does appear. But if you reload the page, then you see the browser has sent to the site a pragma header with "no cache" value. Sending each time a **same and non usual**  value may help to correlate your browsing activities

Interestingly, the canvablocker's winow.name protection has the same behavior: a pragma/no cache http header is sent when reloading the page on ip-check.info. So maybe, sending this http header is necessary in order the window.name protection to work. BUT I performed the same test with [JonDoBrowser](https://jondobrowser.jondos.de/releases/current/jondobrowser-install-win64_en-US.exe), and window.name was protected ("anonymized") without any header being sent, even after reloading the page several time.

On the other hand, this JonDoBrowser version in based on FF 52 ESR, and it's a fork of FF, possibly having been modified at levels unreachable for web extensions.

## Relevant settings

Only window.name protection ticked

## Context (Environment)

FF 84 on W10

**Comment by sereneblue** [comment]
@Kraxys I think this may simply be a change between the Firefox versions or a preference related to caching. Cache related headers can't be modified according to [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeSendHeaders).
