### ISSUE TITLE
Random profile being IE causes some sites not let you in

### ISSUE THREAD

**Issue by jadenconcord** [sereneblue/chameleon#483]
I use the random profile mode in Chameleon and it is really awesome. However, many sites recently don't let you use the site if it detects you have Internet Explorer. This is annoying for me because I sometimes have to change the profile every half an hour or so. Could there be a way to not set IE browsers on random profiles?

Sorry if this is not a proper bug report, I will remove this if that is the case but I have wanted to notify contributors of this issue.  Thank you for the development of Chameleon. there is nothing that compares to this awesome extension!

**Comment by sereneblue** [comment]
Hi @jadenconcord,

Thank you for the kind words. You can exclude certain profiles from being used when a random profile option is selected by clicking the checkbox next to the profile name. More details can be found in the [wiki](https://sereneblue.github.io/chameleon/wiki/profile).
