### ISSUE TITLE
Unable to get IP info for TimeZone and Accept Language

### ISSUE THREAD

**Issue by bm92aWJldnJvcw** [sereneblue/chameleon#484]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
It sets the TimeZone and Accept Language using current IP's info without any error.

## Current Behavior
It shows "Unable to get IP info" when TimeZone and/or Accept Language is set to fetch from current IP's info.

What source is used to get IP info? and if I could use own API url to do it better and fail proof?
Please resolve this as soon as possible because I only see this extension giving the option to set language and timezone easily. 
Latest FireFox Stable PC

**Comment by sereneblue** [comment]
Hi @RkxBQ0Jyb3NUZXN0MUpTT04,

Chameleon uses https://ipaci.co to get the timezone and language information. There isn't a fallback source if ipapi.co is down but there is the [IP rule editor](https://sereneblue.github.io/chameleon/wiki/ip-rules) that you can use. It allows you to manually specify a timezone/language to be used for an IP address/range.

**Comment by RkxBQ0Jyb3NUZXN0MUpTT04** [comment]
Thanks for the reply @sereneblue

So if I could know how I can change this API url to something like ipinfo io which didn't fail for any of my IP checks.
I don't know much about coding it... 

may be an option to set custom url with own token (which ipinfo io provides for free accounts)
The IP rule editor is ok but not for one who uses different IP mostly and it's not fully automatic.
I've also experienced unable to get IP info error alot, the only big flaw for me in the usage.

**Comment by sereneblue** [comment]
@RkxBQ0Jyb3NUZXN0MUpTT04 ipinfo doesn't provide the data that Chameleon really needs if you want the process to be automatic: timezone and language information. If you visit https://ipapi.co/json with the IPs you're using does it return an IP with additonal data? Are you getting the "Unable to get IP info" error using that process or with the IP rule editor? I'm not sure how often you're changing your IP address. Chameleon only checks when certain settings are changed and on startup. I'm not sure if Chameleon fits your use case.

**Comment by RkxBQ0Jyb3NUZXN0MUpTT04** [comment]
I see... I have to use it while setting these two values in two different sections manually by searching on internet about the IP and it's language/timezone info...
I don't know which service would directly feed with language tags... it's just an issue of ipapi not having the info about IPs I usually use and they won't be static all the time too, mostly self-hosted vpns on hostings. 
ipinfo doesn't seem to give it in language tags either... 

If you want to close the issue you can.
Thanks for the info about backend of the extension and your time ofcourse.

**Comment by sereneblue** [comment]
> I see... I have to use it while setting these two values in two different sections manually by searching on internet about the IP and it's language/timezone info...
> I don't know which service would directly feed with language tags... it's just an issue of ipapi not having the info about IPs I usually use and they won't be static all the time too, mostly self-hosted vpns on hostings.
> ipinfo doesn't seem to give it in language tags either...
> 
> If you want to close the issue you can.
> Thanks for the info about backend of the extension and your time ofcourse.

**Comment by Kotoki1337** [comment]
ipaci.co possible not working, do you guys have plans to change other API to fix this issue? This problem has been going on for a week

**Comment by sereneblue** [comment]
> ipaci.co is possible down, do you guys have plans to change other API to fix this issue? This problem has been going on for a week

https://ipapi.co/json isn't down. Are you using Tor/VPN/etc?

**Comment by Kotoki1337** [comment]
> > ipaci.co is possible down, do you guys have plans to change other API to fix this issue? This problem has been going on for a week
> 
> https://ipapi.co isn't down. Are you using Tor/VPN/etc?

Whether I use VPN or not, I cant using ipapi.co. can you using it normally? I hope chameleon can add multiple API

**Comment by DGjone44** [comment]
> 
> 
> Hi @RkxBQ0Jyb3NUZXN0MUpTT04,
> 
> Chameleon uses https://ipaci.co to get the timezone and language information. There isn't a fallback source if ipapi.co is down but there is the [IP rule editor](https://sereneblue.github.io/chameleon/wiki/ip-rules) that you can use. It allows you to manually specify a timezone/language to be used for an IP address/range.

Is there any USA IP ranges or timezone file that I can import to your extension at once?

**Comment by DGjone44** [comment]
Ipapi.co works fine in browser but addon can not fetch.

**Comment by sereneblue** [comment]
> > > ipaci.co is possible down, do you guys have plans to change other API to fix this issue? This problem has been going on for a week
> > 
> > 
> > https://ipapi.co isn't down. Are you using Tor/VPN/etc?
> 
> Whether I use VPN or not, I cant using ipapi.co. can you use it normally? I hope chameleon can add multiple API

I can access ipapi.co normally. I think it's a good idea to add a fallback but I'm not sure what could be used. An alternative would need both timezone and language data.

> Is there any USA IP ranges or timezone file that I can import to your extension at once?

How often is your IP address changing? If you're using a VPN, you may be able to obtain the IP range somewhere. It's much easier to create the IP range if you narrow it down to an ISP/known IP ranges (data centers).

> Ipapi.co works fine in browser but addon can not fetch.

I haven't been able to replicate this. Can you try inspecting the network request that Chameleon makes to ipapi?

Open the Browser Console by pressing `CTRL+SHIFT+J`.

Make sure that XHR is selected so your console looks something like this:
![image](https://user-images.githubusercontent.com/14242625/106075624-fe91bb80-60db-11eb-8278-8e43d21d5f76.png)

Switch the  timezone in Chameleon to a non-IP value, then switch back to IP. This should trigger the request to ipapi. What response do you get?

I just realized that IPv6 could cause some problems; Chameleon only supports IPv4. Perhaps that's the issue?

**Comment by DGjone44** [comment]
Thank you so much!
I will act on your reply soon. Thank you.

**Comment by Kotoki1337** [comment]
![image](https://user-images.githubusercontent.com/35394151/106158928-37ef2780-61bf-11eb-8016-97858f481038.png)

**Comment by DGjone44** [comment]
XHR Response is below.


### Please turn JavaScript on and reload the page.
### DDoS protection by Cloudflare
### Ray ID:

**Comment by DGjone44** [comment]
Seems like ipapi.co implemented Cloudflare recently.

**Comment by sereneblue** [comment]
@DGjone44 @Kotoki1337 Thanks. Cloudflare does make this a bit more complicated. Hm, I may have to build and host an alternative somewhere. I'll see what I can do.

**Comment by DGjone44** [comment]
> 
> 
> @DGjone44 @Kotoki1337 Thanks. Cloudflare does make this a bit more complicated. Hm, I may have to build and host an alternative somewhere. I'll see what I can do.

Excellent, Thank you

**Comment by sereneblue** [comment]
@DGjone44 @Kotoki1337 I've created a serverless function available here: https://keen-mccarthy-93a21c.netlify.app/.netlify/functions/geoip. I don't think you'll encounter the issue with Cloudflare with this URL. Please let me know if it works well for you. It also supports some IPv6 ranges.

**Comment by Kotoki1337** [comment]
![image](https://user-images.githubusercontent.com/35394151/106348736-58c09580-6303-11eb-84bf-f7ea23cd7ba0.png)
work for me

**Comment by DGjone44** [comment]
> 
> 
> @DGjone44 @Kotoki1337 I've created a serverless function available here: https://keen-mccarthy-93a21c.netlify.app/.netlify/functions/geoip. I don't think you'll encounter the issue with Cloudflare with this URL. Please let me know if it works well for you. It also supports some IPv6 ranges.

Thank you. How do I use this url in addon.

**Comment by sereneblue** [comment]
> > @DGjone44 @Kotoki1337 I've created a serverless function available here: https://keen-mccarthy-93a21c.netlify.app/.netlify/functions/geoip. I don't think you'll encounter the issue with Cloudflare with this URL. Please let me know if it works well for you. It also supports some IPv6 ranges.
> 
> Thank you. How do I use this url in addon.

It will be available in Chameleon soon, most likely within a few days.

**Comment by sereneblue** [comment]
Chameleon v0.21.18 now uses a serverless function for IP location information.

**Comment by bm92aWJldnJvcw** [comment]
@sereneblue Thanks for this update! It does work on any/all of my VPNs used now... so it is perfect! Flawless, much appreciated.
