### ISSUE TITLE
Custom useragent missing

### ISSUE THREAD

**Issue by classmate01** [sereneblue/chameleon#485]
Hello!
Where is the insert custom useragent in the latest version of this addon?

Thanks!

**Comment by sereneblue** [comment]
@classmate01 To simplify development, custom user agents has been removed from Chameleon since v0.20.0.

**Comment by DGjone44** [comment]
Thanks for this addon.

Please increase no. of useragents. Also do not delete past user agents as user agent is changed on version upgrade. Please make some way so that i can keep old user agent on version update.

Please add donation BTC address or Paypal email.

**Comment by classmate01** [comment]
Oh i see.. okay..
I plan to put chrome v88 on it. I guess i'll just have to wait for the updated UA. I dont wanna go back to older version :)

**Comment by sereneblue** [comment]
> Thanks for this addon.
> 
> Please increase no. of useragents. Also do not delete past user agents as user agent is changed on version upgrade. Please make some way so that i can keep old user agent on version update.

Chameleon is currently designed to use the latest version of the listed browsers; an exception was made for Firefox ESR. It'd take some work to add support for older versions and I'm not sure it's really worth it. I believe most people have auto-updates enabled so older versions shouldn't be around after an update is available.  What is your use case in regards to using an old user agent?

> 
> Please add donation BTC address or Paypal email.

https://sereneblue.github.io/chameleon/donate

> Oh i see.. okay..
> I plan to put chrome v88 on it. I guess i'll just have to wait for the updated UA. I dont wanna go back to older version :)

Sorry for the delay, an update will be released later today with an updated profile list.

**Comment by DGjone44** [comment]
> 
> 
> > Thanks for this addon.
> > Please increase no. of useragents. Also do not delete past user agents as user agent is changed on version upgrade. Please make some way so that i can keep old user agent on version update.
> 
> Chameleon is currently designed to use the latest version of the listed browsers; an exception was made for Firefox ESR. It'd take some work to add support for older versions and I'm not sure it's really worth it. I believe most people have auto-updates enabled so older versions shouldn't be around after an update is available. What is your use case in regards to using an old user agent?
> 
> > Please add donation BTC address or Paypal email.
> 
> https://sereneblue.github.io/chameleon/donate
> 
> > Oh i see.. okay..
> > I plan to put chrome v88 on it. I guess i'll just have to wait for the updated UA. I dont wanna go back to older version :)
> 
> Sorry for the delay, an update will be released later today with an updated profile list.

Thank you.


I have multiple browser profiles set where I need unique browser user agent for each.
Current desktop list is not that much large for Windows and Mac OS

**Comment by DGjone44** [comment]
>  Please add donation BTC address or Paypal email.

> > https://sereneblue.github.io/chameleon/donate

I donated some bucks to Mozilla 

> Thank you for your generous gift
> 
> Your donation will go right to work protecting the web, keeping it open and available to all. We’ve emailed you a donation receipt; if it’s missing, please check your junk/spam folders, then contact us at 

You sent a payment of $5.00 USD to Mozilla Foundation

**Comment by sereneblue** [comment]
> 
> I have multiple browser profiles set where I need unique browser user agent for each.
> Current desktop list is not that much large for Windows and Mac OS

There _should_ only be a handful of user agents used these days. Vivaldi/Brave and some other Chrome-based browsers sometimes lie about their user agents. As I mentioned before, considering most users have auto-updates enabled, old version only stick around for a few days or so. I'm open to adding Brave/Vivaldi if that helps.

> > Please add donation BTC address or Paypal email.
> 
> > > https://sereneblue.github.io/chameleon/donate
> 
> I donated some bucks to Mozilla
> 
> > Thank you for your generous gift
> > Your donation will go right to work protecting the web, keeping it open and available to all. We’ve emailed you a donation receipt; if it’s missing, please check your junk/spam folders, then contact us at
> 
> You sent a payment of $5.00 USD to Mozilla Foundation

Thank you for donating.

**Comment by classmate01** [comment]
Hello!
Normally, how many random "mobile" useragent do we have if we choose for example *Android 9?* and Chrome 88
I only see 5 random UA in mine

**Comment by sereneblue** [comment]
> Hello!
> Normally, how many random "mobile" useragent do we have if we choose for example _Android 9?_ and Chrome 88
> I only see 5 random UA in mine

Yes, there are only 5 devices for Android 9 + Chrome 88. The list of devices can be found here: https://github.com/sereneblue/chameleon/blob/master/src/lib/devices.ts. I suggest using `Random Android Browsers` and excluding the profiles you don't want to use. There's about 20 or so devices across the 4 Android versions.
