### ISSUE TITLE
How to setting random screen size in feature Spoof screen size?

### ISSUE THREAD

**Issue by DarKWinGTM** [sereneblue/chameleon#486]
How to setting random screen size in feature Spoof screen size?

# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by sereneblue** [comment]
Hi @DarKWinGTM, if you select `Profile` as your screen resolution and use one of the random profile options with an interval, your screen resolution may change when the profile changes.

**Comment by DarKWinGTM** [comment]
> Hi @DarKWinGTM, if you select `Profile` as your screen resolution and use one of the random profile options with an interval, your screen resolution may change when the profile changes.

Thanks,

It's posible or not to have feature for user can add custom(Alot list) to user agent to random list ?, I mean add custom user agent to mainly list.

**Comment by sereneblue** [comment]
> > Hi @DarKWinGTM, if you select `Profile` as your screen resolution and use one of the random profile options with an interval, your screen resolution may change when the profile changes.
> 
> Thanks,
> 
> It's posible or not to have feature for user can add custom(Alot list) to user agent to random list ?, I mean add custom user agent to mainly list.

No, it's not possible. There is another open issue about that [here](https://github.com/sereneblue/chameleon/issues/485#issuecomment-768678428).
