### ISSUE TITLE
Spoof media device causes enumerateDevices to hang

### ISSUE THREAD

**Issue by sereneblue** [sereneblue/chameleon#487]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

Spoofing media devices should not cause function call to hang.

## Current Behavior

Spoofing media devices causes the enumerateDevices function call to hang.

## Context (Environment)

Issue originally reported here:
https://github.com/arkenfox/TZP/issues/30

Issue occurs when iframes are on page.

**Comment by sereneblue** [comment]
This should be resolved as of v0.21.18.

**Comment by Thorin-Oakenpants** [comment]
Hey sereneblue

The timeout no longer happens 👍 , but I don't think it's actually spoofing anything. Done several tests in several sessions (firefox), and I always get the same result: i.e the same number of types (and the format/logic of the groupId and deviceId is consistent with Firefox)

What is it meant to spoof like? Random number of devices? Is it meant to try and match the UA spoof (like plugins does)?

**Comment by sereneblue** [comment]
@Thorin-Oakenpants Chameleon's media device spoofing spoofs the label of the media device. For example, if you're using a Mac profile, your webcam's label will appear as `FaceTime HD Camera (Built-in).` They don't appear unless the camera/mic permission is granted and it's kind of difficult to see because it doesn't appear in Firefox's UI but if you write some code to log the label. The deviceId and groupId are already anonymized by Firefox.

**Comment by Thorin-Oakenpants** [comment]
Thanks :)

I do read a device `label` [1], but it's not via gUM (getUserMedia) and is always blank, even on chromium, so it might be a standard now - IDK. Different label :)

gUM and permission prompts, I want to avoid. Anything that causes scary prompts is not generically FP viable: such as asking for camera permissions on sites that do not need it: no site will use that. That said, sites that do require permissions can FP that info: I read a lot last night about some mitigation ideas

[1]
```js
	devices.forEach(function(d) {
		/// snip
		if (d.label.length > 0) {
			strPad = ("label: ").padStart(pad)
			str += "<br>"+strPad+d.label
		}
```

**Comment by sereneblue** [comment]
@Thorin-Oakenpants Yes, if the camera/mic permission isn't granted, the label will be blank. A user suggested that I add the feature because it _could_ be used as a fingerprint if they wanted to use their camera/mic instead of blocking them.

**Comment by Kraxys** [comment]
> 
> 
> @Thorin-Oakenpants Yes, if the camera/mic permission isn't granted, the label will be blank. A user suggested that I add the feature because it _could_ be used as a fingerprint if they wanted to use their camera/mic instead of blocking them.

I'm not sure whether I fully understand. 
I tested  this spoofing feature with a Portable FF93 on Win10  (Cham. v0.22.13), in browsing on the site https://webrtc.github.io/samples/src/content/devices/input-output/

Using different profiles, I get exactly the same things when I select "Spoof media device" and when I don't select it.
I never get "FaceTime HD Camera (Built-in)" when using a Mac profile.
