### ISSUE TITLE
How to find extensions config

### ISSUE THREAD

**Issue by DarKWinGTM** [sereneblue/chameleon#488]
How to find config of chameleon.

I config extensions as custom, I want to copy this config to other profile, But can not find config in pref.js, I copy all storage config(browser-extension-data\{{EXTENSIONS ID}}\storage.js) but config was not stick with this file.

How to collect all config ?

Thanks

# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [+] I am running the latest version
- [+] I checked the documentation and found no answer
- [+] I checked to make sure that this issue has not already been filed

## Context (Environment)

Waterfox Classic 2021.1

**Comment by sereneblue** [comment]
> How to find config of chameleon.
> 
> I config extensions as custom, I want to copy this config to other profile, But can not find config in pref.js, I copy all storage config(browser-extension-data{{EXTENSIONS ID}}\storage.js) but config was not stick with this file.
> 
> How to collect all config ?
> 
> Thanks
> # Prerequisites
> 
> Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**
> 
>     * [+] I am running the latest version
> 
>     * [+] I checked the documentation and found no answer
> 
>     * [+] I checked to make sure that this issue has not already been filed
> 
> 
> ## Expected Behavior
> ## Current Behavior
> ## Relevant settings
> ## Context (Environment)
> 
> Waterfox Classic 2021.1

Please refer to the wiki page [here](https://sereneblue.github.io/chameleon/wiki/getting-started).

**Comment by DGjone44** [comment]
I have a similar query , Is it possible to manually import all desktop user agents from past year. It would be nice.

**Comment by sereneblue** [comment]
> I have a similar query , Is it possible to manually import all desktop user agents from past year. It would be nice.

No, it's not possible. Currently, the user agents are programmatically generated from various bits of info like the OS, browser version, device model, etc. This makes things a lot easier to maintain. 
The developer guide goes into some detail about how the browser profiles work: https://sereneblue.github.io/chameleon/wiki/developer-guide.
