### ISSUE TITLE
Allow manual/custom spoofing of Javascript-based OS identifiers

### ISSUE THREAD

**Issue by propolisor** [sereneblue/chameleon#49]
The built-in user agent options do spoof these, but you're not able to do so with a custom user agent, making the option somewhat worthless as can be seen on a site like ip-check.info where your real OS is easily detected with a custom UA. These options should be manually spoofable.

Also it would be a good idea to add in user agent options for TorBrowser on various OSes, as it has caused an uproar with its refusal to spoof user agents anymore and will likely drive some users to your project looking to spoof different versions of it.

**Comment by sereneblue** [comment]
If you're using a user agent for a popular browser (Firefox/Chrome/etc) on a common platform (any of the ones listed on the profile tab), Chameleon should automatically pick certain settings for your spoofed browser profile. I took a quick look and there are a few things things I've missed; will fix in the next update. Are you trying to use a user agent from something uncommon like a video game console?

Tor Browser uses the Firefox ESR user agent which is now included in the list of profiles. I've updated them in a recent commit.

Although I'm open to adding a manual feature for users to specify certain properties, I don't think it's really needed if you're using a typical user agent.

**Comment by propolisor** [comment]
TorBrowser's UA is simpler than any of the UAs you have available for Firefox ESR. It is "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0" whereas the two user agents you have for Firefox ESR are "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" and "Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0".

Anyway I'm not trying to do anything beyond that but I suppose that's just the nature of customization: you never know what the user might need, so it's best to give them as many options as possible..

**Comment by sereneblue** [comment]
Thanks for catching that, I'll update the user agents. I'll fix the current custom implementation so that it properly spoofs the other properties as well.

I've thought about it for a bit, but I think the current method is good enough considering that it should work for every modern browser. If a user needs to manually spoof certain things, they can use the whitelist (if it's for a few select sites).

**Comment by propolisor** [comment]
Does the whitelist functionality allow you to spoof those Javascript-based identifiers? Also, would it be difficult to apply its granularity to a more generalized system?

**Comment by sereneblue** [comment]
Yes, the whitelist allows you to spoof those identifiers. It wouldn't be difficult to make it a more generalized system, however, there's no reason to. As long as you're using a typical browser for the useragent, Chameleon will automatically detect the correct information. You'd really have to go out of your way to find something that Chameleon can't detect.

The only value that you'd probably want to change is the screen resolution.
