### ISSUE TITLE
Language error identified by Japanese IP

### ISSUE THREAD

**Issue by Kotoki1337** [sereneblue/chameleon#492]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

1. Change **Spoof Accept Language** to **IP**.
2. Connect to any Japan proxy
3. The Language will be **Acholi** not Japanese

## Current Behavior

Make it correct

## Relevant settings

![image](https://user-images.githubusercontent.com/35394151/110948550-73fbd780-837c-11eb-8732-ec75293cf4ae.png)
![image](https://user-images.githubusercontent.com/35394151/110948528-6d6d6000-837c-11eb-9c85-19a886bd4eac.png)

## Context (Environment)

Windows 2004
Firefox 86.0.1 (64-bit)
Cgameleon v0.12.20

**Comment by sereneblue** [comment]
Hi @Kotoki1337, thanks for reporting this issue. This should be fixed in v0.21.21.
