### ISSUE TITLE
Disable Full Notification

### ISSUE THREAD

**Issue by FrozenVertx** [sereneblue/chameleon#495]
Hi,
I have a problem with browser notification.
I enabled Timezone Spoof to IP for changing timezone when IP changes.
I disabled notification on Chameleon.
But whenever I start Firefox (Nighty) Chameleon it show assigned time zone in browser notification.

Why it show notification if I disabled it? If it is bug then please fix it because sometimes it show notification and sometimes not.

Thanks

**Comment by sereneblue** [comment]
Hi @FrozenVertx,

The notification is displayed when the browser is first opened and when the browser profile changes. It's shown even when notifications are disabled to inform users of the IP data that Chameleon uses. If there is an issue with the IP, the user will most likely catch it sooner from the notification than manually checking the browser popup panel.

**Comment by FrozenVertx** [comment]
Ok I see I get IP notification after disabling it. Can you please clear me which notifications are disabled? And Can make any submenu for notification to disable this notification as well.

**Comment by sereneblue** [comment]
@FrozenVertx Notifications appear when the browser profile is changed or when the IP info is obtained for timezone or language spoofing. The current notification option only disables the first one. Adding another toggle just for IP notifications doesn't seem like the right way to go about this issue. The next update will respect the user's notifications preferences.

**Comment by sereneblue** [comment]
@FrozenVertx This is resolved in v0.21.23.
