### ISSUE TITLE
User Agent spoofing not working on Firefox 88

### ISSUE THREAD

**Issue by Asiier** [sereneblue/chameleon#496]
- [✔] I am running the latest version
- [✔] I checked the documentation and found no answer
- [✔] I checked to make sure that this issue has not already been filed

## Expected Behavior
- User agent spoofing working.

## Current Behavior
- User agent spoofing working. No matter what setting are being used.

## Relevant settings

`{
  "config": {
    "enabled": true,
    "notificationsEnabled": false,
    "theme": "dark",
    "hasPrivacyPermission": true
  },
  "excluded": [],
  "headers": {
    "blockEtag": true,
    "enableDNT": true,
    "referer": {
      "disabled": true,
      "xorigin": 0,
      "trimming": 0
    },
    "spoofAcceptLang": {
      "enabled": true,
      "value": "en-US"
    },
    "spoofIP": {
      "enabled": true,
      "option": 0,
      "rangeFrom": "",
      "rangeTo": ""
    }
  },
  "ipRules": [],
  "options": {
    "cookieNotPersistent": false,
    "cookiePolicy": "reject_trackers",
    "blockMediaDevices": false,
    "blockCSSExfil": true,
    "disableWebRTC": true,
    "firstPartyIsolate": false,
    "limitHistory": true,
    "protectKBFingerprint": {
      "enabled": true,
      "delay": 1
    },
    "protectWinName": true,
    "resistFingerprinting": true,
    "screenSize": "1920x1080",
    "spoofAudioContext": false,
    "spoofClientRects": true,
    "spoofFontFingerprint": false,
    "spoofMediaDevices": true,
    "timeZone": "Etc/UTC",
    "trackingProtectionMode": "always",
    "webRTCPolicy": "disable_non_proxied_udp",
    "webSockets": "block_3rd_party"
  },
  "profile": {
    "selected": "win4-gcr",
    "interval": {
      "option": 60,
      "min": 1,
      "max": 1
    }
  },
  "version": "0.21.23.1",
  "whitelist": {
	  ...
  }
}`

## Context (Environment)

Firefox 88 on Windows 10 20H2.

[Proof](https://imgur.com/XiHNFcc)

[Using another user agent spoofer](https://imgur.com/TRP2bA2)

**Comment by sereneblue** [comment]
@Asiier I couldn't replicate the issue with Firefox 88 on Linux and Windows. Do you see any errors in the developer console when you load the page?

**Comment by Asiier** [comment]
@sereneblue 
I have tried the using Firefox Developer (89.0b5) and everything working as intended. So must be something with my other extension or with the current installation of Firefox 88.
I'm not seeing anything on the console log.
I have tried as opening a private tab and disabling all the add-ons but Chameleon. This is **not** working either.

[Using only Chameleon](https://imgur.com/vK6bn8d)

I have tried other webpages and get the same results.
Anywhere else that I should look or provide? Is there a way of enabling logging on extension?

**Comment by Asiier** [comment]
@sereneblue 
I have tried the using Firefox Developer (89.0b5) and everything working as intended. So must be something with my other extension or with the current installation of Firefox 88.
I'm not seeing anything on the console log.
I have tried as opening a private tab and disabling all the add-ons but Chameleon. This is **not** working either.

[Using only Chameleon](https://imgur.com/vK6bn8d)

I have tried other webpages and get the same results.
Anywhere else that I should look or provide? Is there a way of enabling logging on extension?

**Comment by sereneblue** [comment]
@Asiier Try uninstall/reinstalling Chameleon. If that doesn't fix it, check to see if Chameleon is able to spoof something else like the screen size, timezone, or the headers (https://httpbin.org/headers). If the user agent isn't spoofed in the headers, it would seem that Chameleon isn't working at all (possibly a bug somewhere?). Try checking the Browser Console for any errors that might be relevant (CTRL+SHIFT+J).

**Comment by Asiier** [comment]
@sereneblue 
Yep, uninstalling and reinstall fix it. I thought everything else was working, but indeed nothing was working.
Well, thank you for the support!
