### ISSUE TITLE
Add "Custom Profile" in Profile Section

### ISSUE THREAD

**Issue by FrozenVertx** [sereneblue/chameleon#499]
Hi,
I want to suggest a feature to add Custom profile option for user-agents that is userdefined. If generally set any custom profile and then switch to predefined profile for ex-Random Profile (desktop) then after switching my previous one is disappear If I want it then I have to set browser again. So Please add that option so that I change profile quickly.

Thanks for giving time.

**Comment by sereneblue** [comment]
Hi @FrozenVertx,

You can already quickly change your profile if you're using the random profile options. Can you clarify your suggestion (preferably with a use case)?

**Comment by FrozenVertx** [comment]
Ok ,
Let Say I Set user-agent  - Ubuntu Chrome or Firefox 88 for General Browsering
Now I open site that I temporary want to switch my above useragent to RealProfile.
Now after setting Real Profile Now I want to change my useragent to above one.
So Now to choose above I have to go Random Profile(desktop) then Click on Linux then scroll down to last and then choose I have to choose Ubuntu Firefox/Chrome 88.

I want that you Make Another Option below Random Profiles,etc to Set useragent of my choice to quickly switch to it in one click just like Random Profiles(mobile) or others. **Just useragent of my choice**.

I change useragent quickly because some sites that require cloudfare as protection to verify break in my browser and some other sites. After setting to real Profile They work fine and also I don't want to whitelist that sites.

**Comment by sereneblue** [comment]
Thanks for clarifying. Why don't you want to use the whitelist? That's essentially why it exists. It provides a lot of flexibility for using specific profiles for pages/domains.

**Comment by FrozenVertx** [comment]
Hmm,
Because on those temporary site where i toggle real profile, my chameleon extension is on with all enabled injections like block media,limit tab history etc.  But when I whitelist any site site I only see these 4 option to toggle - websocket,referer,protect window name,timezone spoofing. I really don't know that , on whitelist site the above injections are disabled or enabled by default, In short whitelisting doesn't give full control to which rule I want to enable or disable on that site it only give above 4 options So I prefer to temporary switch to Real Profile and also it applied faster than whitelisting.

I also use whitelist on regularly visited sites but on Temporary sites(that cause break due to cloudfare) I use realprofile.

**Comment by sereneblue** [comment]
I see. I think it would be better to expand the whitelist functionality with a few additional spoofing options. The whitelist should disable everything except the options you explicitly enable in the whitelist. There are some Firefox level preferences like cookies/tracking protection/etc that still apply, but the injection options and headers shouldn't be spoofed.

**Comment by FrozenVertx** [comment]
I think its really better Idea. Can you tell me why Cloudflare protected sites break (I mean they wait then reload,wait .... not redirect to particular site) all time,But after switching to real profile it works. Is there any problem in spoofing browser-agent.

**Comment by sereneblue** [comment]
Cloudflare is probably using feature detection to detect the actual browser. Since the spoofed browser doesn't match the actual browser, it might look like a bot depending on the IP. I'm going to do some more testing to figure out why spoofing the browser with a profile that matches my actual browser profile triggers a loop.
