### ISSUE TITLE
Gesturify stopped working

### ISSUE THREAD

**Issue by alpha-and-omega** [sereneblue/chameleon#50]
Sadly after activating chameleon my Gesturify gestures stopped working.
Probably related to screen size spoofing.
Any way to fix this ?

**Comment by sereneblue** [comment]
I'm not sure what caused the issue although it's probably the resist fingerprinting option or screen spoofing. Can you paste the exported settings?

**Comment by alpha-and-omega** [comment]
Yes, disabling "resist fingerprinting" solves the problem, thanks!
