### ISSUE TITLE
Chameleon compare Random User-Agent

### ISSUE THREAD

**Issue by gegemon2012** [sereneblue/chameleon#505]
Hello!
I decided to test your plugin Chameleon v0.21.27 for Firefox and compare it with its analogue Random User-Agent, which has not been supported for a long time. In your plugin, there is no way to set an agent change every time you visit the page. Also, the process of adding a site is less convenient, even taking into account the context menu. For example, in R U-A, the domain is automatically sent to the whitelist, it is worth disabling the plugin on the domain page and removed from the list after enabling the plugin on the domain page. Can this functionality be released in your plugin?

**Comment by sereneblue** [comment]
Hi @gegemon2012,

Random user agents per page load will not be added as a feature to Chameleon. The whitelist context menu will be improved to support quickly adding a domain to individual rule sets as part of an update to the whitelist.

**Comment by sereneblue** [comment]
The context menu has been improved in v0.22.0. You can now add/remove a domain to a whitelist rule directly from the context menu.
