### ISSUE TITLE
extension becomes unusable after Accept Language set to IP

### ISSUE THREAD

**Issue by bm92aWJldnJvcw** [sereneblue/chameleon#506]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
It should change accept language based on IP without getting stuck or useless.

## Current Behavior
It gets stuck if you set accept language to IP. This is experienced on PC firefox browser too! whereas setting timezone to IP has no issues. so currently I can't use accept languages setting

## Relevant settings
default everything.

## Context (Environment)
FireFox Nightly for Android with extension collection. 
and FireFox stable.
with few extensions such as CanvasBlocker, Clear URLs etc.

**Comment by sereneblue** [comment]
@bm92aWJldnJvcw Can you clarify how Chameleon becomes unusable? I'm not able to replicate this issue.

**Comment by bm92aWJldnJvcw** [comment]
@sereneblue it is happening only when I'm connected to any VPN, in my case windscribe or aws hosted shadowsocks VPN. sorry for the late reply.

**Comment by sereneblue** [comment]
@bm92aWJldnJvcw I've located the issue. This is fixed in v0.22.1. Thanks for reporting!
