### ISSUE TITLE
Options not enforced with real profile

### ISSUE THREAD

**Issue by anmull** [sereneblue/chameleon#509]
## Expected Behavior

Profile is separate from the other options selected and font spoofing will work regardless of profile.

## Current Behavior

If I select the real profile, font spoofing no longer works and most likely other settings as well. This can also be confirmed by visiting DuckDuckGo with font spoofing enabled, but using the real profile.

## Context

Firefox 89.0.2

## Extra

The issue here is that if I have RFP enabled the user agent reduces my uniqueness so the real profile is better than choosing a Windows option. If I choose real profile, the options I select elsewhere do not work so my uniqueness increases, font spoofing for example.

Ideally we would be able to clone a profile and edit it to the exact details we want. Chameleon is the only extension I've found that properly spoofs navigator attributes so it's important to be able to customize the user agent but also be able to keep the appropriate values for navigator attributes.

**Comment by sereneblue** [comment]
Hi @anmull,

If you're using RFP with your real profile, font spoofing won't do much. RFP already limits the fonts. All of the other options should still work but they might not be needed with RFP active.

**Comment by anmull** [comment]
> Hi @anmull,
> 
> If you're using RFP with your real profile, font spoofing won't do much. RFP already limits the fonts. All of the other options should still work but they might not be needed with RFP active.

That's not what I'm seeing under the fonts section of cover your tracks

Spoofing Off "One in x browsers have this value: 123.96"
Spoofing On "One in x browsers have this value: 11.13"

**Comment by sereneblue** [comment]
> > Hi @anmull,
> > If you're using RFP with your real profile, font spoofing won't do much. RFP already limits the fonts. All of the other options should still work but they might not be needed with RFP active.
> 
> That's not what I'm seeing under the fonts section of cover your tracks
> 
> Spoofing Off "One in x browsers have this value: 123.96"
> Spoofing On "One in x browsers have this value: 11.13"


Enabling RFP should whitelist only system fonts so I'm curious why it's actually providing more information compared to Chameleon's font spoofing. It looks like font spoofing is working fine. I've tested with Real Profile and a few Windows profiles. For reference, these were my results:

Spoofing Off + RFP:  One in x browsers have this value: 123720.0 
Spoofing On + RFP:  One in x browsers have this value: 11.2

**Comment by anmull** [comment]
> > > Hi @anmull,
> > > If you're using RFP with your real profile, font spoofing won't do much. RFP already limits the fonts. All of the other options should still work but they might not be needed with RFP active.
> > 
> > 
> > That's not what I'm seeing under the fonts section of cover your tracks
> > Spoofing Off "One in x browsers have this value: 123.96"
> > Spoofing On "One in x browsers have this value: 11.13"
> 
> Enabling RFP should whitelist only system fonts so I'm curious why it's actually providing more information compared to Chameleon's font spoofing. It looks like font spoofing is working fine. I've tested with Real Profile and a few Windows profiles. For reference, these were my results:
> 
> Spoofing Off + RFP: One in x browsers have this value: 123720.0
> Spoofing On + RFP: One in x browsers have this value: 11.2

Agreed, it was concerning to see especially if it means other information could be leaking when it shouldn't.

Regarding real vs fake with spoofing, I'm still seeing my real profile exposing more fonts and I'm not sure why. As long as I'm using a profile font spoofing works, but once I go back to the real, which is actually the RFP Windows user agent it becomes more unique

RFP+Spoofing+Win10/FF68: One in x browsers have this value: 11.2
RFP+Spoofing+Real (RFP Win): One in x browsers have this value: 124.12

If you're not experiencing the issue, is there something specific I can look for on my end to see if I can find out what is happening?

**Comment by sereneblue** [comment]
> > > > Hi @anmull,
> > > > If you're using RFP with your real profile, font spoofing won't do much. RFP already limits the fonts. All of the other options should still work but they might not be needed with RFP active.
> > > 
> > > 
> > > That's not what I'm seeing under the fonts section of cover your tracks
> > > Spoofing Off "One in x browsers have this value: 123.96"
> > > Spoofing On "One in x browsers have this value: 11.13"
> > 
> > 
> > Enabling RFP should whitelist only system fonts so I'm curious why it's actually providing more information compared to Chameleon's font spoofing. It looks like font spoofing is working fine. I've tested with Real Profile and a few Windows profiles. For reference, these were my results:
> > Spoofing Off + RFP: One in x browsers have this value: 123720.0
> > Spoofing On + RFP: One in x browsers have this value: 11.2
> 
> Agreed, it was concerning to see especially if it means other information could be leaking when it shouldn't.
> 
> Regarding real vs fake with spoofing, I'm still seeing my real profile exposing more fonts and I'm not sure why. As long as I'm using a profile font spoofing works, but once I go back to the real, which is actually the RFP Windows user agent it becomes more unique
> 
> RFP+Spoofing+Win10/FF68: One in x browsers have this value: 11.2
> RFP+Spoofing+Real (RFP Win): One in x browsers have this value: 124.12
> 
> If you're not experiencing the issue, is there something specific I can look for on my end to see if I can find out what is happening?

My previous results were from Linux + RFP. I believe that might have caused the strange numbers. Using Windows 10 and RFP, I'm getting a better result:
Spoofing Off: One in x browsers have this value: 20.36
Spoofing On: One in x browsers have this value: 11.34 

What OS are you using?

**Comment by anmull** [comment]
> > > > > Hi @anmull,
> > > > > If you're using RFP with your real profile, font spoofing won't do much. RFP already limits the fonts. All of the other options should still work but they might not be needed with RFP active.
> > > > 
> > > > 
> > > > That's not what I'm seeing under the fonts section of cover your tracks
> > > > Spoofing Off "One in x browsers have this value: 123.96"
> > > > Spoofing On "One in x browsers have this value: 11.13"
> > > 
> > > 
> > > Enabling RFP should whitelist only system fonts so I'm curious why it's actually providing more information compared to Chameleon's font spoofing. It looks like font spoofing is working fine. I've tested with Real Profile and a few Windows profiles. For reference, these were my results:
> > > Spoofing Off + RFP: One in x browsers have this value: 123720.0
> > > Spoofing On + RFP: One in x browsers have this value: 11.2
> > 
> > 
> > Agreed, it was concerning to see especially if it means other information could be leaking when it shouldn't.
> > Regarding real vs fake with spoofing, I'm still seeing my real profile exposing more fonts and I'm not sure why. As long as I'm using a profile font spoofing works, but once I go back to the real, which is actually the RFP Windows user agent it becomes more unique
> > RFP+Spoofing+Win10/FF68: One in x browsers have this value: 11.2
> > RFP+Spoofing+Real (RFP Win): One in x browsers have this value: 124.12
> > If you're not experiencing the issue, is there something specific I can look for on my end to see if I can find out what is happening?
> 
> My previous results were from Linux + RFP. I believe that might have caused the strange numbers. Using Windows 10 and RFP, I'm getting a better result:
> Spoofing Off: One in x browsers have this value: 20.36
> Spoofing On: One in x browsers have this value: 11.34
> 
> What OS are you using?

I'm using macOS

**Comment by Thorin-Oakenpants** [comment]
> My previous results were from Linux + RFP

RFP only covers some Linux distros, it's gated
- https://hg.mozilla.org/mozilla-central/file/tip/gfx/thebes/gfxFcPlatformFontList.cpp#l1866
- https://searchfox.org/mozilla-central/search?path=StandardFonts*.inc

**Comment by anmull** [comment]
> > My previous results were from Linux + RFP
> 
> RFP only covers some Linux distros, it's gated
> 
>     * [hg.mozilla.org/mozilla-central/file/tip/gfx/thebes/gfxFcPlatformFontList.cpp#l1866](https://hg.mozilla.org/mozilla-central/file/tip/gfx/thebes/gfxFcPlatformFontList.cpp#l1866)
> 
>     * [searchfox.org/mozilla-central/search?path=StandardFonts*.inc](https://searchfox.org/mozilla-central/search?path=StandardFonts*.inc)

If RFP is returning different font lists depending on the OS/distro, then the statement that it makes everyone look alike is false. It would actually make almost as easy to fingerprint because of fonts being returned.

With that said, wouldn't the statements about not using anti-fingerprint extensions on arkenfox wiki be  wrong in certain cases? Font spoofing being one of them

**Comment by Thorin-Oakenpants** [comment]
> the statement that it makes everyone look alike

- who claimed that?
- RFP aims attempts to lower entropy. There are some things that can't be lied about, such as your OS. Providing same fonts results per OS is still the same as providing the same fonts for all OSes
   - e.g. OS detected as Mac, fonts are a,b,c, OS detected as Windows, fonts are c,d,e
   - e.g. OS detected as Mac, fonts are a,b,c, OS detected as Windows, fonts are a,b,c
   - ^ there is literally ZERO difference in entropy between the two, because, you know, the OS cannot be hidden

What makes you think the test at cover your tracks is real world, and that the entropy figures are any good

> wouldn't the statements about not using anti-fingerprint extensions on arkenfox wiki be wrong in certain cases

No. Extensions leak. Extensions are good for naive scripts (and most are naive), I mean, FFS, even the FPJS Pro demo is fooled by a random canvas, but an advanced one will eat you for breakfast, spit out your bones, grind said bones into powder for aphrodisiac purposes and sell it on the black market, and then invest the money in cryptocurrencies whilst hobnobbing with Elon :)

**Comment by anmull** [comment]
> > the statement that it makes everyone look alike
> 
>     * who claimed that?

I worded that wrong. What I meant was that it makes certain parts look alike (UA, resolution, etc).

> 
>     * RFP aims attempts to lower entropy. There are some things that can't be lied about, such as your OS. Providing same fonts results per OS is still the same as providing the same fonts for all OSes
>       
>       * e.g. OS detected as Mac, fonts are a,b,c, OS detected as Windows, fonts are c,d,e
>       * e.g. OS detected as Mac, fonts are a,b,c, OS detected as Windows, fonts are a,b,c
>       * ^ there is literally ZERO difference in entropy between the two, because, you know, the OS cannot be hidden
> 

I found a good Stack Exchange response that clarified a little bit about fonts, but this is where I was coming from.

I understand it is to lower entropy and to do that pieces of information need to be similar more often so more visitors look alike. RFP changes the user agent to be a Windows UA to reduce entropy in that area, but in the case of fonts it is returning fonts that are unique to the real OS.

If the goal is to reduce entropy when possible why would you not return the same fonts regardless of OS, just like returning the same UA regardless of OS. Why even bother changing the UA to Windows if by fonts alone you're telling them I'm on a Mac.

The SE response did clarify this is because of system fonts, but even that seems like something that can be solved by installing the fonts that would be returned by a Windows OS and then return the appropriate list.

> 
> What makes you think the test at cover your tracks is real world, and that the entropy figures are any good

I'm not saying it is real world or even that high quality, but it does provide one view of what other sites may see and what I'm seeing is that spoofing the fonts significantly lowered the bits in the font fingerprint.

> 
> > wouldn't the statements about not using anti-fingerprint extensions on arkenfox wiki be wrong in certain cases
> 
> No. Extensions leak. Extensions are good for naive scripts (and most are naive), I mean, FFS, even the FPJS Pro demo is fooled by a random canvas, but an advanced one will eat you for breakfast, spit out your bones, grind said bones into powder for aphrodisiac purposes and sell it on the black market, and then invest the money in cryptocurrencies whilst hobnobbing with Elon :)

Leaks I understand. How I understood the anti-fingerprint section of the extension page was it was saying RFP alone was better than RFP and an extension even if the extension reduced a lot of entropy by more than it added. From my limited knowledge and what I was seeing in testing, Chameleon's font spoofing had more benefit than not having it installed.

I'm not trying to make it seem like I know that much about fingerprinting, just looking for the best options.

**Comment by Thorin-Oakenpants** [comment]
> just like returning the same UA regardless of OS

You're conflating _why_ the UA is handled like it is in RFP/Tor Browser

- The UA via JS returns all four possible OSes: otherwise things can break, blame the websites
- The HTTP Header returns only two because it doesn't break things and helps to reduce easy entropy for when JS is disabled, e.g. Tor Slider at safest, or if sites don't use JS to detect the OS and solely rely on HTTP Headers

Ultimately you cannot hide the OS from JS (it is IMPOSSIBLE), or even from passive fingerprinting (TCP/IP characteristics) - but that doesn't mean that sometimes you can just try and make life harder for the bastards

> fonts

Do you have any idea how BIG bundling fonts would be? It's a no go (the only exception here is something like Tails, which is a an OS). And that's not even taking into consideration all users - even Safari, just on desktops, wanted to return all the same fonts, and found it impossible, due to user needs and the diversity/complexity of extra languages/font packs etc. And some of those are massive (think ideographs and CJK etc) - so the only solution that had was to create several (not sure how many) different "buckets"

Given that the OS cannot be hidden, there is zero point bundling fonts, when you can just leverage what the OS already provides. It's not perfect (e.g. a user can uninstall system fonts), but it's close for Windows and probably Mac. Still room for some improvement e.g. Win7 and Win10 seem to have about three distinct groups each (and Win7 will soon be EOL, so no need to worry about that) - that's not bad considering that ~200mn users are on windows and only six buckets, eventually only three buckets - of course that assumes everyone uses RFP, but that's not important in the science or math of _how_ to reduce entropy in this metric, it's just a final well-known step reqired to get numbers up

> what I'm seeing is that spoofing the fonts significantly lowered the bits in the font fingerprint

entropy and bits aren't the same thing, but I know what you mean - the fact is that the data is tainted and totally off it's rocker

> and what I was seeing in testing, Chameleon's font spoofing had more benefit than not having it installed

because you looked at tainted off-its-rocker entropy figures. Look it depends on what you're trying to do and whop you're trying to fool, and I'm not 100% sure what Chameleon does for fonts. If it's randomized then great, naive scripts will get sucked in

**Comment by anmull** [comment]
> > just like returning the same UA regardless of OS
> 
> You're conflating _why_ the UA is handled like it is in RFP/Tor Browser
> 
>     * The UA via JS returns all four possible OSes: otherwise things can break, blame the websites
> 
>     * The HTTP Header returns only two because it doesn't break things and helps to reduce easy entropy for when JS is disabled, e.g. Tor Slider at safest, or if sites don't use JS to detect the OS and solely rely on HTTP Headers
> 
> 
> Ultimately you cannot hide the OS from JS (it is IMPOSSIBLE), or even from passive fingerprinting (TCP/IP characteristics) - but that doesn't mean that sometimes you can just try and make life harder for the bastards
> 
> > fonts
> 
> Do you have any idea how BIG bundling fonts would be? It's a no go (the only exception here is something like Tails, which is a an OS). And that's not even taking into consideration all users - even Safari, just on desktops, wanted to return all the same fonts, and found it impossible, due to user needs and the diversity/complexity of extra languages/font packs etc. And some of those are massive (think ideographs and CJK etc) - so the only solution that had was to create several (not sure how many) different "buckets"
> 
> Given that the OS cannot be hidden, there is zero point bundling fonts, when you can just leverage what the OS already provides. It's not perfect (e.g. a user can uninstall system fonts), but it's close for Windows and probably Mac. Still room for some improvement e.g. Win7 and Win10 seem to have about three distinct groups each (and Win7 will soon be EOL, so no need to worry about that) - that's not bad considering that ~200mn users are on windows and only six buckets, eventually only three buckets - of course that assumes everyone uses RFP, but that's not important in the science or math of _how_ to reduce entropy in this metric, it's just a final well-known step reqired to get numbers up
> 
> > what I'm seeing is that spoofing the fonts significantly lowered the bits in the font fingerprint
> 
> entropy and bits aren't the same thing, but I know what you mean - the fact is that the data is tainted and totally off it's rocker
> 
> > and what I was seeing in testing, Chameleon's font spoofing had more benefit than not having it installed
> 
> because you looked at tainted off-its-rocker entropy figures. Look it depends on what you're trying to do and whop you're trying to fool, and I'm not 100% sure what Chameleon does for fonts. If it's randomized then great, naive scripts will get sucked in

Thanks for clarifying. I see what you're saying.

I read the extensions page again and saw the notes about these testing sites being unreliable due to all the tests tainting the results.

My comment about installing fonts was more of an "aftermarket" change like user.js is, but you clarify why that won't help anything.
