### ISSUE TITLE
Add the possiblity to have more than one custome agent

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#51]
Right now if you want to use a custom agent you are limited to one.
It would be great if you could add more than one (with a "+" icon) and to have like: custom agent #1, custom agent #2 and so on. It would give more flexibility to users.

**Comment by WPFilmmaker** [comment]
I was thinking on a per site specific thing?Like website developed for a specific website (IE before now chrome).

**Comment by sereneblue** [comment]
That's an edge case that goes a little beyond this extension. I don't think there's too many websites that a user would need a specific user agent (outside of a corporate environment). They could either toggle the profile when visiting X site or use the whitelist effectively.

**Comment by WPFilmmaker** [comment]
Your point is reasonable. You can close this ticket ;-)
