### ISSUE TITLE
[Feature Request] Add Current OS and Browser on Chameleon Badge

### ISSUE THREAD

**Issue by FrozenVertx** [sereneblue/chameleon#513]
Hi,
As already inbuilt in addon when I hover on Icon It shows me OS - Browser (Ex- **Linux-Firefox 89**).
I just want this to show on Chameleon Badge like Lnx-Fx or something like that, just like adblockers show no. of ads block on badges.
Its really helpful when profiles set to random and you quickly want to see current browser,OS without hovering on addon.
If any Word limitation on badges then adding only first character of OS or Browser is also enough to find out current one.

I hope you add this feature

**Comment by sereneblue** [comment]
Hi @FrozenVertx,

I think the current solution is the best approach. I've tested using the badge text with text like 'M/C' or 'L/F' and it's a bit difficult to read.

**Comment by FrozenVertx** [comment]
Hmm, I see Its really difficult to read M/C ,you can also make an option to choose any one of them according to userchoice, like only FF or Win.

**Comment by sereneblue** [comment]
> Hmm, I see Its really difficult to read M/C ,you can also make an option to choose any one of them according to userchoice, like only FF or Win.

I think the browser is more valuable in the badge. I can add support for this in the next update.
