### ISSUE TITLE
Grant Permission To Modify Settings?

### ISSUE THREAD

**Issue by 0pLuS0** [sereneblue/chameleon#514]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

## Expected Behavior
Just enable and disable options without needing to Grant?

## Current Behavior
I have used Chamelon in the past, and never had to Grant permissions to modify settings, now I have to?

## Context (Environment)

68.12.0 ESR - Linux

I attached a screen shot all these options are grayed out, I don't understand this? The Standard and Cookie settings are both like this?

![Options](https://user-images.githubusercontent.com/36190223/125238610-6d796e80-e322-11eb-8649-12a534d896c7.jpg)

**Comment by sereneblue** [comment]
Hi @0pLuS0,

Before v0.21.0, Chameleon automatically used the privacy permissions to modify the above settings. This could cause some conflict with other extensions//user preferences who do not want Chameleon to control the above preferences. New installs require the user to explicitly grant Chameleon permission to change those settings.

**Comment by 0pLuS0** [comment]
I click it, nothing happens, all it does is open up this Dashboard.

![Dash](https://user-images.githubusercontent.com/36190223/125377847-a53af180-e3c8-11eb-8fca-7df511174a26.jpg)

**Comment by 0pLuS0** [comment]
Sorry, since I'm using Firefox 68.12.0 ESR I need to use an older Legacy Build of Chamelon?

**Comment by 0pLuS0** [comment]
My mistake I thought I had a legacy version installed already, because I knew about this before, not sure what happened, but I installed the latest one and it's work now.

THANKS
