### ISSUE TITLE
Ability to randomize spoofed screen size

### ISSUE THREAD

**Issue by myartsev** [sereneblue/chameleon#515]
Would be nice to have an option for randomly changing the spoofed screen size, either on each page load or after x amount of time.

**Comment by sereneblue** [comment]
Hi @myartsev, 

This can be achieved by setting the screen resolution option to "Profile" and using the random profile options with a specific interval.

**Comment by myartsev** [comment]
@sereneblue oh interesting - does each random profile have a different screen resolution?
Ideally I was looking for a more fine grained setting: keeping the profile (OS + browser) the same while randomizing the screen resolution.

But maybe there's a reason these things are tied together. Mind pointing me to the code which sets the screen resolution upon picking a random profile? Not very familiar with the code base :)

**Comment by sereneblue** [comment]
@myartsev Random desktop profiles can have a variety of user agents (Macs have certain resolutions). Mobile profiles have a specific device user agent/resolution. When the profile changes, either by the interval or when the user changes a setting that affects the profile, the screen resolution may change. If you're using a specific browser profile, you can achieve the functionality you're looking for: exclude all other browser profiles, set the screen resolution option to `Profile` and set a desired interval.

The relevant functions in the code are located below:

https://github.com/sereneblue/chameleon/blob/master/src/lib/chameleon.ts#L139
https://github.com/sereneblue/chameleon/blob/master/src/lib/inject.ts#L154

**Comment by myartsev** [comment]
Fantastic, thank you!
