### ISSUE TITLE
Cant enable  firstparty.isolate

### ISSUE THREAD

**Issue by spphinslove** [sereneblue/chameleon#516]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

## Expected Behavior
enable firstparty.isolate
## Current Behavior
cant enable firstparty.isolate,and seems like it will disable firstparty.isolate after addon update or random
## Relevant settings
firstparty.isolate

## Context (Environment)
[chameleon_1627651838480.zip](https://github.com/sereneblue/chameleon/files/6907862/chameleon_1627651838480.zip)

Windows11 and last firefox

**Comment by sereneblue** [comment]
Hi @spphinslove, to enable First Party isolation, you need to grant the privacy permission to Chameleon. It seems you're already using another extension or manually configured the cookie policy option. Thanks by the way for attaching your settings; it seems Chameleon is missing an option for the cookie policy. 

If Chameleon is granted the privacy permission, it will assume control of all of the other related privacy options. If you don't want to do that, you can manually enable First Party Isolation (`privacy.firstparty.isolate`) using about:config.
