### ISSUE TITLE
Add another language

### ISSUE THREAD

**Issue by mezysinc** [sereneblue/chameleon#519]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by mezysinc** [comment]
Can you add ptbr to crowdin ?

**Comment by sereneblue** [comment]
Hi @mezysinc,

I've added Portuguese, Brazilian on Crowdin. Thank you.
