### ISSUE TITLE
Add Browser Exclusion

### ISSUE THREAD

**Issue by FrozenVertx** [sereneblue/chameleon#520]
Hi,
I am currently using Random Profile (Desktop) on my Firefox. When Chameleon Rotates BA(Browser Agents) it also include IE(Internet Explorer) that is outdated and sites complains for old browser and break. As there is no option available to use user chosen OS and Browser at same time ,if I exclude IE from browser list then Chameleon rotates BA around one OS.
So please Add an Option to exclude particular Browser or OS from Predefined Profiles to complete exclusion.

**Comment by sereneblue** [comment]
Hi @FrozenVertx,

If you want to use a specific profile, you can always just select it in the list. If you want to use only Windows + Firefox profiles, you can select "Random Windows browsers" and exclude the non-Firefox profiles. There's a lot of flexibility to use only the profiles you want. I believe what you're looking for is already provided by Chameleon.

**Comment by FrozenVertx** [comment]
Sorry it's my fault I can't explain problem well. I want BA rotates including all OS(Windows,Mac,Linux,etc) and Browsers(Firefox,Chrome,etc.) except IE. For Example If now I have Chrome+Mac then on next change may be Firefox+Windows or Linux+Edge anything but not Internet Explorer as a browser. I want to rotates about multiOS and also Exclude IE(outdated) from them. I hope this time you understand the problem.

**Comment by sereneblue** [comment]
> Sorry it's my fault I can't explain problem well. I want BA rotates including all OS(Windows,Mac,Linux,etc) and Browsers(Firefox,Chrome,etc.) except IE. For Example If now I have Chrome+Mac then on next change may be Firefox+Windows or Linux+Edge anything but not Internet Explorer as a browser. I want to rotates about multiOS and also Exclude IE(outdated) from them. I hope this time you understand the problem.

This can be achieved by excluding the Internet Explorer profiles and selecting one of the Random profile options. A random profile will be selected from the list of non-excluded profiles.

**Comment by FrozenVertx** [comment]
Yes, it Works! I am unaware of this Feature, 
_**Thanks**_  😊
