### ISSUE TITLE
Consider adding Firefox 91 ESR and deprecate no longer supported Firefox ESR (68, 78)

### ISSUE THREAD

**Issue by whatbh** [sereneblue/chameleon#522]
## Expected Behavior

Newly available Firefox 91 ESR should be added and no longer supported versions (68, 78) should be removed. 

## Current Behavior

Firefox 68 ESR and Firefox 78 ESR are being available as user agent profiles. But Firefox 68 ESR has been deprecated and Firefox 78 ESR is going to be deprecated soon (02 Nov 2021 [^1]). Spoofing user agents with unsupported versions of browser will only risk increasing the user's uniqueness (like using Windows XP nowadays). On the other hand, new Firefox ESR (91) is not available to use. 

[^1]: https://endoflife.date/firefox

**Comment by Azirine** [comment]
Firefox 91.3 ESR was released earlier today.

**Comment by sereneblue** [comment]
The v0.22.14 update uses ESR 78 & 91.
