### ISSUE TITLE
First Party Isolation deprecated

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#526]
# Prerequisites

- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

I just noticed in reading the [Arkenfox user.js](https://github.com/arkenfox/user.js) file that the preference _firstparty.isolation_ is now deprecated. Moreover it is said that 
this pref is replaced with network partitioning (FF85+) and Total Cookies Partitioning, and that and enabling FPI disables those two.

So, could you update Chameleon in order to take account of that?

**Comment by whatbh** [comment]
You can avoid giving Chameleon "Privacy permissions" and it is leaving Firefox's Enhanced Tracking Protection (ETP) untouched at all, that includes Total Cookie Partitioning (a.k.a. dynamics First Party Isolation) and Resist Fingerprinting. 
If you've already enabled it and it's interfering with built–in ETP, you can revoke its permission by clicking on "Remove privacy permissions" and it will return control of dFPI to Firefox's hand. 

<img width="1287" alt="Screen Shot 2022-02-08 at 4 05 24 PM" src="https://user-images.githubusercontent.com/91888303/152954247-a3912243-4537-4dd2-b9a3-ae7ed63bf946.png">

**Comment by Thorin-Oakenpants** [comment]
> that the preference _firstparty.isolation_ is now deprecated

it's not deprecated, it is still there and used by Tor Browser - note: they also have other patches to do with networking and various state
- such as being in Private Window mode, they do have service workers which are not partitioned by FPI
- such as HTTP3

For Firefox users, the better option is dFPI/TCP as it is actively maintained and tested etc by mozilla engineers and is more likely to have gaps found and patched

from the v96 changelog
> - tl;dr: FPI sooner or later is going to cause problems and/or you will miss out on usability and protections
>    - FPI is not maintained upstream: mozilla do not want the extra engineering and complexity of two code paths
>    - FPI has already missed out on extra partitioning (such as service workers)
>    - FPI has already been on the cusp of missing out on extra partitioning (such as websockets) - I was lucky enough to spot this and alert sysrqb to get it into ESR91.1+. We won't always be so lucky
>    - FPI will likely miss out on future partitioning in the pipeline (such as 308 redirects, pool parties, etc)
>    - TCP _is_ actively worked on
>    - TCP works better with sanitizing
>    - TCP is being rolled out to all Firefox users (in ETP Standard)
>    - ETP Strict comes with extra benefits
>    - blah blah blah
>    - FYI: currently the only non-partitioned item in TCP is blobs - see [1686111](https://bugzilla.mozilla.org/show_bug.cgi?id=1686111) and  `privacy.partition.bloburl_per_agent_cluster`

**Comment by sereneblue** [comment]
It looks like the cookie policy can enable dFPI. I'll continue to look into this and will probably put a message near the FPI option to inform users about the changes. I'll remove the FPI option when the WebExtension API is removed.
