### ISSUE TITLE
FONTS spoofing invalid

### ISSUE THREAD

**Issue by 11fen** [sereneblue/chameleon#527]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ *] I checked the documentation and found no answer
- [* ] I checked to make sure that this issue has not already been filed

## Context (Environment)

Firefox Release  97
Chameleon  0.22.20.2
win10  ltsc  x64

FONTS spoofing invalid 
test   http://f.vision/

**Comment by sereneblue** [comment]
Hi @11fen,

Thanks for reporting, there does seem to be an issue. I'll look into this and will hopefully have this resolved in the next update.

**Comment by sereneblue** [comment]
@11fen This is now resolved in v0.22.22.
