### ISSUE TITLE
Protect keyboard fingerprint - creates a lot of lag typing

### ISSUE THREAD

**Issue by 0pLuS0** [sereneblue/chameleon#529]
## Expected Behavior
I expect when I use the browser, typing in it and on websites will be smooth/fast/fluid

## Current Behavior
When typing in Firefox ESR 91.7.1 address bar, or on a website online, typing is lagged and sticky.

The problem I figured out is when using ```Protect keyboard fingerprint```  on ```1``` when I type in Firefox, or on the internet the typing lags/stutters it's not smooth. But as soon as I unchecked this option it's good.

I read here on the Wiki it's suppose to be sluggish, there is no way to make this smooth without the lag?

## Context (Environment)
[chameleon_1648522105100.json.txt](https://github.com/sereneblue/chameleon/files/8367676/chameleon_1648522105100.json.txt)

## Browser

Firefox ESR 91.7.1

It's mentioned on the Wiki that the way you type can be used to fingerprint you. Fingerprint us in what way, how? I don't really understand the benefit of this, when using all the other options in Chameleon that spoof our OS and browser, etc...

Also for the Delay time, is there a preference to use, that is recommended? For whatever reason I can't remember now, I had it on 1..

THANKS

**Comment by sereneblue** [comment]
Hi @0pLuS0,

WebExtensions shouldn't affect the address bar input. Are you experiencing sluggish input when this feature is not enabled? What site are you experiencing issues with? To learn more about why some users might enable this feature: https://paul.reviews/behavioral-profiling-the-password-you-cant-change/. I don't have any personal recommendations for the setting. There's a floor of 30ms so you probably don't need much on top of that to shield your privacy. You can test with the sites mentioned in the link above.

**Comment by 0pLuS0** [comment]
There's not lag when I'm not using Protect keyboard fingerprint.

I use KeePassXC to log into sites requiring usernames/passwords.

https://keepassxc.org/

Maybe you are familiar with it, it has an Auto Type feature that will auto type the username/password, when it doesn't I see it stutter/lag slightly, because of the Protect keyboard fingerprint.

As I mentioned I have the delay on 1, I assumed this will allow it to type as fast as it can?

![kbd_finger](https://user-images.githubusercontent.com/36190223/161154303-69daac7a-3cce-4a2d-af8d-1a7b11b615dc.jpg)

**Comment by 0pLuS0** [comment]
In the Auto-Type preferences I personally use ```Ctrl+Z``` as my keyboard shortcut to have it auto type., you can use anything you  like.

![keepassxc](https://user-images.githubusercontent.com/36190223/161344055-f6912726-f69e-4587-97ea-0c391b0fcef4.jpg)

Next, if you go to a site, where you have several accounts, with the latest version of KeePassXC, at least in Linux, it will display all your entries in KeePassXC, be sure to make a Window Association.

![window_associate](https://user-images.githubusercontent.com/36190223/161344139-6394c32d-a4ca-48ea-8562-18389815db3f.jpg)

Click the + plus sign like you see, then on the right, window title, put it on the website like you see, now KeePassXC will show you only your accounts, this is also useful, if you also have only one account and the Auto-Type isn't working, because KeePassXC needs an association.

**Comment by sereneblue** [comment]
@0pLuS0 I did some testing, I can kind of see what you're referring to. There is a difference with auto type + protect keyboard fingerprint on/off. It's not surprising given what's happening. If you type your username/password manually, you wouldn't notice the delay (depending on your config) because it would be in between your keystrokes. People generally can't type fast enough to notice the difference if their config has a low delay. However, KeePassXC doesn't have that natural delay. You're probably better off disabling this feature since it's not really needed for your use case.

**Comment by 0pLuS0** [comment]
@sereneblue 

Are you saying, when using KeePassXC's Auto-Type feature we don't need to use the ```Protect keyboard fingerprint``` option?

If so, I'm assuming this would also go for any other password app, that has a similar feature, we can disable this?

THANKS

**Comment by sereneblue** [comment]
@0pLuS0 Yes, protect keyboard fingerprinting isn't needed if you're using KeePassXC's Auto-Type feature. Also, the same applies for other password managers.
