### ISSUE TITLE
Problem with window.name protection on ip-check.info

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#53]
Checking "protect window.name" and enabling script injection make me my browser remain stuck on the homepage of http://ip-check.info, without being able to go to the results page (and to check whether the protection has worked or not).

**Comment by sereneblue** [comment]
I had problems with that too. I'm not sure what's causing the issue though. Please let me know if you can find an alternative website that also checks that property. It *should* be spoofed; if you check the value in the console window it's an empty string. I'm going to look into this a bit more.

**Comment by Kraxys** [comment]
For the moment, I haven't found any other site testing the window.name property. 

But I found something maybe useful for your investigation: The FF addon [Canvas Blocker](https://addons.mozilla.org/en-US/firefox/addon/canvasblocker) is able to protect window.name too, but without somewhat breaking the site ip-check.info (it's an "expert feature" of this addon, you have to check *"expert mode"* and then *"Protect window API"*). So maybe you could compare the codes.

**Comment by sereneblue** [comment]
Thanks for the information!
