### ISSUE TITLE
Random TLS Fingerprint with useragent support?

### ISSUE THREAD

**Issue by hkfsc** [sereneblue/chameleon#531]
RT

**Comment by hkfsc** [comment]
https://chris124567.github.io/2021-06-15-websites-lying-user-agent/
You wont be able to login Google account when you are using the FF browser but spoofed its UA with Chrome UAs.

**Comment by sereneblue** [comment]
Hi @hkfsc, there's not much I can do to resolve the TLS fingerprint issue. It does seem possible to spoof this fingerprint. I believe someone can write a custom proxy that implements TLS spoofing but it's a large amount of work to implement that and also integrate into a WebExtension.
