### ISSUE TITLE
Can I make the chameleon preserve the fingerprint on a browser restart?

### ISSUE THREAD

**Issue by milos8893** [sereneblue/chameleon#532]
Can I make the chameleon preserve the fingerprint on a browser restart?
It sounds logical for it to change the fingerprint only when requested.

**Comment by sereneblue** [comment]
Hi @milos8893, you can the same browser profile that should generally maintain the same fingerprint but it depends on any other options that you enable. Some options like audio context spoofing will change when the browser profile changes or when the browser restarted.
