### ISSUE TITLE
grant permission to modify setting

### ISSUE THREAD

**Issue by xxjoe2** [sereneblue/chameleon#535]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
grant proper permission to modify setting
## Current Behavior
click on grant permission button, redirects to browser app permission settings or the wiki page
## Relevant settings
option -> standard

## Context (Environment)

iceraven/mull android 10

question:
which particular permissions do i need to grant to chameleon? and how/where to grant it?

thanks a lot

**Comment by sereneblue** [comment]
Hi @xxjoe2,

Thanks for reporting this issue. This is actually a bug caused because of the new version numbers in Firefox 100+. I'll release a fix soon.

**Comment by xxjoe2** [comment]
> Hi @xxjoe2,
> 
> Thanks for reporting this issue. This is actually a bug caused because of the new version numbers in Firefox 100+. I'll release a fix soon.
> 
> EDIT: v0.22.31 fixes this issue on desktop. Chameleon's legacy build allows support for this on Android, however, that's only for FF 68 and older. The release version/dev build don't allow you to request permissions on Fenix. It's a bit difficult to test as well since Mozilla made sideloading difficult. I may be able to remove this restriction once I'm able to test this.

thanks for your prompt reply
however i have a problem. how do i install the xpi file on android to mull/iceraven?

**Comment by sereneblue** [comment]
@xxjoe2 Fenix does not currently have a way to grant optional permissions which is part of the reason why the legacy version of Chameleon exists. There is a workaround to sideload extensions in Fenix, unfortunately, it's not permanent. It looks like there has been some recent progress on this issue by Mozilla. Hopefully, it'll be resolved soon.

**Comment by xxjoe2** [comment]
> @xxjoe2 Fenix does not currently have a way to grant optional permissions which is part of the reason why the legacy version of Chameleon exists. There is a workaround to sideload extensions in Fenix, unfortunately, it's not permanent. It looks like there has been some recent progress on this issue by Mozilla. Hopefully, it'll be resolved soon.

yeah i just learnt that too last nite but i dono it's yet to resolve
so ok thanks a lot
