### ISSUE TITLE
Ho to use custom/provided user agent?

### ISSUE THREAD

**Issue by tansy** [sereneblue/chameleon#537]
I was trying to user user agent I have and there is no place to actually set it up. Even in whitelist, which is quite nicely customizable there are only pre set agents on the list. This is not very useful if you have a specific one to use in mind. For me I tried to recycle my phone's user agent but it's not on the list. Neither browser nor system is not there. 
Another situation is when one tries to use already existing authorization and has to provide identical user agent or it won't work. 

Is there any way to provide user agent somehow?

**Comment by sereneblue** [comment]
Hi @tansy,

It is not possible to add a custom user agent to Chameleon. If possible, you can try using Chameleon on a mobile device if you have an Android device and whitelist the site to use a specific desktop profile.  What is your use case for authorization using a user agent?

**Comment by tansy** [comment]
> What is your use case for authorization using a user agent?

To have same credentials like on other device. By using same session id or cookies and user agent I can use my credentials on other device. There are situations like that when site/service allows only one login or I have "registered" specific device there and want to do something there appearing like from that device.

It would be possible to add edit control box above/below combo box with presets. Maybe with radio button beside that would make sure use knows what they are doing entering their own user agent string.

**Comment by sereneblue** [comment]
Adding custom user agent support is outside the scope of Chameleon's v0.2x.x profiles. The whitelist should be enough if you can use Chameleon on your mobile device (or iOS Safari, the user agent should be identical with the profiles). If not, you may be able to use an extension like `User-Agent Switcher and Manager` for that specific site side by side with Chameleon (whitelist using your real profile). That _should_ work.
