### ISSUE TITLE
options button 

### ISSUE THREAD

**Issue by Stickman-1** [sereneblue/chameleon#538]
Where is the options ? 😎😛

![Screenshot_2022-08-07-13-57-05-56_50ecd26a21c2c56ce608de5e94733463](https://user-images.githubusercontent.com/102072078/183282470-58ba46d3-679c-4a32-aa2e-9cb916706b84.jpg)

**Comment by sereneblue** [comment]
Hi @Stickman-1,

Chameleon's options can be opened by visiting a website and selecting it from the add-ons menu option.

![image](https://user-images.githubusercontent.com/14242625/183303076-e3348898-4761-4fb1-bbbf-39048fef95a4.png)

**Comment by Stickman-1** [comment]
![IMG_20220808_180221](https://user-images.githubusercontent.com/102072078/183418841-0f207dd6-7ca4-4384-b439-5f26ed54877b.jpg)

Still not working asking to modify settings but where is grant permission settings

**Comment by Stickman-1** [comment]
@sereneblue

**Comment by sereneblue** [comment]
Mozilla has not implemented the UI to request optional permissions in Fenix so there's not much that can be done until that's resolved.
