### ISSUE TITLE
Ho to compile zip into xpi?

### ISSUE THREAD

**Issue by kileyturney** [sereneblue/chameleon#539]
I am want to install add-on from source code (zip), but when I am do it, I have error "This add-on could not be installed because it appears to be corrupt."
I am understand that this package is not signed, but I need to install it?

I am have FF Nightly (105.0a1)
download zip from github
unzip it to folder. Go to root folder of add-on. Select all files and zip it by 7-zip (compression: Normal, method: Deflate, dictionary size: 32, word size: 32, CPU:4)
Then drag&drop to FF and got current message that file is corrupt.
How need to compile? Or how to install add-on from sources?

**Comment by kileyturney** [comment]
ok. I am try to zip not all folders only src. And add-on is installed. I am see icon on nav bar, but when click on it I got message "<% if (NODE_ENV === 'development') { %> <% } %>"
why not working?

**Comment by kileyturney** [comment]
so, I am install node and etc. In command line go to root folder of chameleon. And run 
`node scripts\build-zip.js`
In the folder 'dist' I am get two files zip and xpi, but each have 1kb size. What wrong?

**Comment by kileyturney** [comment]
not working. I am copy data from scripts to dist. 
run build-zip.js 
Get xpi file
Install it in FF
And again get message "<% if (NODE_ENV === 'development') { %> <% } %>"

**Comment by sereneblue** [comment]
Hi @kileyturney,

To compile Chameleon, from source after install dependenices, run `npm run build && npm run build-zip`.
