### ISSUE TITLE
Updating UserAgent (manually)

### ISSUE THREAD

**Issue by rguejm02** [sereneblue/chameleon#544]
How can we update the useragent manually like for example the ver.104 (from chameleon) to v.105 which is the latest
Just wanna keep them updated everytime chrome releases new ver..

Thanks in advance!

**Comment by sereneblue** [comment]
There isn't a way to update the user agents manually. I try to bundle updates together and spend some time to review changes before releasing updates so there could be a ~1 week delay between browser updates and a new Chameleon release. I've released an update with several updated profiles.
