### ISSUE TITLE
chameleon strips quotes from getComputedStyle  ... getPropertyValue("font-family")

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [sereneblue/chameleon#546]
on TZP I test for whether or not documents fonts are allowed: in Firefox this is a pref  `browser.display.use_document_fonts` where 1 = allow and 0 = block.

I do this by having an element set up
```html
		<div class="cssDocFont" id="divDocFont">line height</div>
```

```css
.cssDocFont {
	font-family: "Times New Roman", Times, serif;
}
```

and I check like this
```js
		let el = dom.divDocFont
		let font = getComputedStyle(el).getPropertyValue("font-family")
		log_debug("doc font", font)
		let fontDocEnabled = (font.slice(1,16) == "Times New Roman" ? true : false)
```

results
- when enabled the font is `"Times New Roman", Times, serif`
- when disabled the font is `serif, "Times New Roman", Times`
- with chameleon font protection the font loses it's quote marks: it instead becomes `Times New Roman, Times, serif` or `serif, Times New Roman, Times`

this is a very tell tale sign of tampering

BTW, IDK what the font protection is trying to do: it doesn't affect any of TZP's 11 font enumerating or measuring methods - it does affect the font fallback method, which no one uses as it's very slow (and which TZP has as a manual test: it also provides a diff output)

**Comment by sereneblue** [comment]
@Thorin-Oakenpants Thanks, I've made a commit that fixes this issue. It will be available in the next update.

Font spoofing operates by whitelisting fonts based on the profile. Essentially passes this test: https://webbrowsertools.com/font-fingerprint/.

**Comment by Thorin-Oakenpants** [comment]
> Essentially passes this test

That test is extremely weak and somewhat flawed AFAICT (and I'm not _that_ interested in debugging it). It returns `N/A`, which is it's way of saying whether or not the font is detected (or supported). It seems to have a very weird way of deciding if something is "supported", but I need to look at it a bit more. It's also not accurate, and says I have lots of fonts that I don't.

```js
supported: function(font) {
	var defaultwidth = {},
		defaultheight = {},
		span = document.createElement("span"),
		basefonts = ["monospace", "sans-serif", "serif"];
	for (var index in span.style.fontSize = "72px", span.innerHTML = "00qqMMrrlliiee11", basefonts) span.style.fontFamily = basefonts[index], document.body.appendChild(span), defaultwidth[basefonts[index]] = span.offsetWidth, defaultheight[basefonts[index]] = span.offsetHeight, document.body.removeChild(span);
	var supported = !1;
	for (var index in basefonts) {
		span.style.fontFamily = font + "," + basefonts[index], document.body.appendChild(span);
		var width = span.offsetWidth !== defaultwidth[basefonts[index]],
			height = span.offsetHeight !== defaultheight[basefonts[index]];
		document.body.removeChild(span), supported = supported || width || height
	}
	return supported
}
```

The accuracy here doesn't really matter. Without chameleon, a bunch of fonts have sizes returned. With chameleon, most are now "N/A".

If you look at the description of what that test is doing, this is exactly what TZP does. TZP measures in 11 different ways (well, seven ways, and then four of those slightly differently to get decimal precision). Chameleon has zero effect on TZP (or creep, it shouldn't but I didn't check yet) - I will check chameleon against a range of online tests later

That is, you measure three base fonts (monospace, serif. sans-serif), then for each font you measure with each fallback - so "Font, monospace", "Font, serif", "Font, sans-serif". If the width or height differ to the base font (or fallback), then the font was loaded. This test is clearly not doing that (and I'm not _that_ interested in it TBH) properly, and/or it's just allowing something stupid to trigger supported = false

Here is an example: https://arkenfox.github.io/TZP/tests/fontdebug.html
- chameleon has zero effect on this test
- this test has two extra basefonts: the top half is our base measurements
- the bottom half shows testing e.g. "Arial, monospace" the size changed and the font was detected (hence green)
- the red is the size didn't change, and that's because the default sans-serif font for Firefox en-US **_is_** "Arial" (which is why you test at least against three basefonts)
![example](https://user-images.githubusercontent.com/16656956/194784490-594c5e34-2b94-4e80-8307-3c1021c9dc92.png)

> by whitelisting fonts based on the profile

So without diving into that's site code, I'm struggling to see what it is that chameleon is actually doing. Now to be fair, I've only noticed it fails to do anything in TZP (and the font lists there are OS specific), but I have chameleon's UA spoofed as Linux, and it does not change ANY of the font hashes on TZP

So the whitelisting doesn't work. I'm struggling to understand what exactly it is that chameleon does here - how do you "block" fonts not on the "whitelist"?

Also, I find this a very odd method. You don't control the OS nor what fonts are installed, and you cannot hide the OS. Limiting fonts to system fonts (i.e those that come with the OS) is a legit way to remove entropy. There will still be some entropy, due to OS versions and optional language fonts (provided by the OS) - but when you try to impose e.g. a windows list on a mac user, that's just insane and does more harm that good. I get that you're trying to remove information paradoxes with ua spoofing, but more often than not this just makes it worse.

**Comment by Thorin-Oakenpants** [comment]
OK, maybe it's just how TZP (and creepy) do things

https://fingerprintjs.github.io/fingerprintjs/ (the standard method)

without chameleom
```
  "fonts": {
    "value": [
      "Arabic Typesetting",
      "Arial Unicode MS",
      "Batang",
      "Calibri",
      "Century Gothic",
      "Franklin Gothic",
      "HELV",
      "Leelawadee",
      "Levenim MT",
      "Lucida Bright",
      "MS Mincho",
      "MS Outlook",
      "MS Reference Specialty",
      "MS UI Gothic",
      "MYRIAD PRO",
      "Marlett",
      "Meiryo UI",
      "Microsoft Uighur",
      "Minion Pro",
      "Monotype Corsiva",
      "PMingLiU",
      "Segoe UI Light",
      "SimHei",
      "Small Fonts",
      "TRAJAN PRO",
      "Vrinda"
    ],
```

with chameleon (spoofing as linux)
```
  "fonts": {
    "value": [],
```

Still, the point remains: zero fonts found on the linux list when claiming to be linux: information paradoxes just make things worse

**Comment by Thorin-Oakenpants** [comment]
confirmed original issue fixed
