### ISSUE TITLE
Inconvenience when using it together with a VPN and Youtube.

### ISSUE THREAD

**Issue by movementoutside** [sereneblue/chameleon#548]
Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Current Behavior
When using a VPN, and you connect to a country other than the one in which you are geographically located, Youtube pops up a window (in the form of a warning) asking what Youtube's cookie policy is and whether I want to accept it or not (and if I don't respond to either option it won't allow me to use YouTube). 

This means that I have to disable Chameleon and, among other inconveniences, the day and time of my computer (which is my real geographic location) is revealed and Youtube obviously contrasts this information with the IP provided by the VPN (NordVPN).

On the other hand, this inconvenience does not happen when I use the VPN connected to a server in the country where I am geographically located (to think...).

I hope I can help with this project and its improvement.
When I can I will make a donation.
Thank you very much for your attention. Regards.

## Relevant settings
[chameleon_1666915252554.json.txt](https://github.com/sereneblue/chameleon/files/9883772/chameleon_1666915252554.json.txt)

## Context (Environment)
Windows 10 Pro 10.0.18363.1500, Firefox 106.0.2 (64-bit)

**Comment by sereneblue** [comment]
Hi @movementoutside,

Can you clarify what the issue is? I'm not sure why you need to disable Chameleon when using a VPN.

**Comment by movementoutside** [comment]
Hello, good morning. I don't understand what clarification you need, because all the relevant information is described above.
Thank you very much. I look forward to your reply.
Regards.

**Comment by sereneblue** [comment]
@movementoutside I'm not sure how Chameleon is relevant to the issue you're facing. What is the behavior that you expect? The cookie policy is tied to the IP address from the VPN, something Chameleon can't change.

**Comment by movementoutside** [comment]
Hello sereneblue, thank you for your reply. I understand what you are saying, but I don't think it is related to the source of the problem. These days I will try to make a video (or sequence of images) that I can upload here so you can see it better.
Regards.

**Comment by movementoutside** [comment]
Hello Sereneblue. Today I tried to make the video but the original problem didn't appear (I could take the matter as solved), which seems strange to me because for months the problem had been happening. Anyway, if it appears again I will try to inform you if you like it.

Thank you very much for your attention. Regards.

**Comment by sereneblue** [comment]
> Hello Sereneblue. Today I tried to make the video but the original problem didn't appear (I could take the matter as solved), which seems strange to me because for months the problem had been happening. Anyway, if it appears again I will try to inform you if you like it.
> 
> Thank you very much for your attention. Regards.

Glad to hear the problem no longer appears. Feel free to open this issue if it reappears.
