### ISSUE TITLE
Custom User agent strings

### ISSUE THREAD

**Issue by UltraBlackLinux** [sereneblue/chameleon#551]
Hey there,
I frequently use this addon to switch user agents, and I would like to request more user agents into the list of UAs or maybe even custom user agents.
I don't know how compatible this addon is with other UA-Switchers, so I'm asking this here.

If you don't want to add a feature to allow custom user agents, please add [the microsoft teams desktop UA](https://stackoverflow.com/questions/58875837/microsoft-teams-user-agent)

They recently added yet more features to get you to use the desktop app and from past experiences this is all just fake. They originally wanted you to use chrome to get all features, and now you either need a browser extension, or to see somebody's video, the desktop app:

![screenshot-20221109-183342](https://user-images.githubusercontent.com/62404294/200903514-69ba8276-babb-4979-8941-880fe75b1ee1.png)

I don't want such tracking garbage on my machine and sadly need Teams for school, so I would be really happy if there was some way to use the app's UA via this addon.

Thanks!

Edit: I was told that MS Edge has "full" teams support, and while I still need to test that, I assume the teams problem is resolved, but custom user agents are still useful or other desktop clients

**Comment by sereneblue** [comment]
This has been requested before in #537. Custom user agents are outside the scope of Chameleon. I may revisit that for v0.30. You can use another extension for custom user agent support with Chameleon as mentioned in the linked issue.
