### ISSUE TITLE
Browserprint.info Sometimes Detects My PC's True Screen Size

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#56]
[Browserprint.info](https://browserprint.info) is performing 3 screen size tests, 2 of them being labelled as "DEPRECATED", and the third using Flash. 

The Flash test (when obviously enabling the Flash Pluging) gives strange results: It displays as screen size neither my screen's true size, nor the spoofed one I have selected in Chameleon.

The first deprecated test, *"Screen Size and Colour Depth"*, is always fooled by Chameleon.  

The second "deprecated" one, *"Screen Size (CSS)"*, not so much. It is really too often able to display the true size of my screen.

**Comment by Kraxys** [comment]
So, in that case, would it be possible to prevent these informations from being transmitted?

**Comment by sereneblue** [comment]
If you use NoScript/uMatrix I don't think there's much to worry about. Most sites use 3rd party trackers so if you don't whitelist them, the information shouldn't get transmitted.

I did some research and there is a way to spoof these values. It looks like you'd need to compile a modified version of FF's source code.
