### ISSUE TITLE
Fingerprint Resisting Fail

### ISSUE THREAD

**Issue by valiantgenomics** [sereneblue/chameleon#561]
Firstly, I want to start off by saying that this is by far THE BEST fingerprint resisting/user-agent-switcher add-on.

The only add-on which is able to spoof Deviceinfo.me successfully.

Thank you so much for your hard and selfless work! It's truly appreciated. You are an unsung hero in my eyes.

But unfortunately, https://abrahamjuliot.github.io/creepjs/ absolutely blasts through chameleon like it doesn't exist.

Any idea why?

I've enabled every single option within chameleon, to absolutely no avail.

My true operating system (Linux) is still shown. The core web browser is still visible.

I also run ublockorigin and canvasblocker concurrently.

I'm using Linux Pop!_OS 22.04 LTS x86_64 and Firefox 113.0.2 (64-bit) flatpak.

Please let me know.

**EDIT:** Silly me, I just noticed that this issue has already been opened. Sorry for not finding it sooner.

**Comment by sereneblue** [comment]
Haha, no worries. Thank you for the kinds words!
