### ISSUE TITLE
Protect Window name interferes with basic javascript variables

### ISSUE THREAD

**Issue by UltraBlackLinux** [sereneblue/chameleon#569]
## Summary
The "Protect window name" option somehow messes with a small snippet of javascript here: https://samples.kb6.de/downloads.php

If you check at the very bottom of the page, there is an email address. If you disable chameleon, it pops up in it's entirety (`mail@example.com`). If you enable chameleon with the aforementioned option enabled, the javascript no longer produces a full email address, as `name` is empty (as can be checked in the console - `console.log(name)`) (`@example.com`). This is the snippet used (redacted to prevent spam):
```js
<script language="JavaScript" type="text/javascript">var name = "mail"; var domain = "example.com"; document.write('<a href=\"mailto:' + name + '@' + domain + '\">'); document.write(name + '@' + domain + '</a>')</script>
```
I was not able to get it to empty the `name` variable in a simple html document containing the script. 

Why is this happening?

## Context (Environment)

117.0, Arch Linux

**Comment by sereneblue** [comment]
@UltraBlackLinux This was an issue with implementation for how the window.name is overwritten. Settings variables in JS bind to the window scope. So the above 
`var name = "mail";` is the same as `window.name = '"mail";`. Chameleon's window.name protection would overwrite window.name's getter and always return an empty string. I've corrected this to only clear window.name on initial page load which resolves this issue.

**Comment by UltraBlackLinux** [comment]
awesome, thank you!
