### ISSUE TITLE
Mouseover/hover hints in the popup menu

### ISSUE THREAD

**Issue by peter-kehl** [sereneblue/chameleon#570]
Thank you for Chameleon.

Latest version from addons.mozilla.org `0.22.49.1` from 2nd October (2023). Current Firefox `118.0.1` on current Manjaro (stable Arch), x64. Plenty of other extensions, but I doubt they could affect this.

Problem: Firefox toolbar > Chameleon button > the popup > the left vertical bar > icons like the Globe, <>... ending with a Settings (wheel) icon are missing a mouseover/title. I wouldn't make sense of them except for the last one (the Settings wheel).

Solution: Please add title/alt (or as appropriate).

**Comment by peter-kehl** [comment]
This may seem trivial to you, and established users, because you know it. But for someone knew it's unclear if those icons are actually tabs, or buttons that action something. And since the user knows this is security-related, it should be clear/upfront.

**Comment by sereneblue** [comment]
Hi @peter-kehl, 

Sure, that sounds good. This change will be included in the next update.

**Comment by sereneblue** [comment]
This was added in the latest update.
