### ISSUE TITLE
ClientRecs Only "Half Spoofed"

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#58]
Instead of testing for _ClientRects_ Spoofing on [browserleaks.com](https://browserleaks.com/rects), I tried to use [kkapsner.github.io/CanvasBlocker/test](https://kkapsner.github.io/CanvasBlocker/test/ ) to perform DOMRect test.

With v0.8.16 **and** v0.8.15, _Element.getClientRects_ and _Element.getBoundingClientRect_ are spoofed, but neither _Range.getClientRects_ nor _Range.getBoundingClientRect_, leading to a fingerprint, the related hashes remaining the same.

**Comment by sereneblue** [comment]
Nice find! Using the site I realized that Chameleon wasn't spoofing the values properly.The values should all be the same on page load. This will be fixed in the next update.

Thanks for the great feedback! :)
