### ISSUE TITLE
Graphical glitches all over, firefox-125

### ISSUE THREAD

**Issue by just-paja** [sereneblue/chameleon#581]
# Prerequisites

- [✓] I am running the latest version
- [✓] I checked the documentation and found no answer
- [✓] I checked to make sure that this issue has not already been filed

## Expected Behavior

Graphics are rendered with lesser quality, but still "readable".

## Current Behavior

With chameleon extension installed in firefox-125, the browser fails to render specific graphic elements even in the Firefox UI. All of these happen when the Chameleon extension is enabled in firefox and Chameleon itself is in disabled state. The problematic graphic elements are usually rendered as colorful vertical lines.

![Snímek obrazovky z 2024-05-07 12-05-56](https://github.com/sereneblue/chameleon/assets/1508022/88b15742-6ae2-449a-8acc-827243c662ee)

### Some examples

1. Tab favicon fails for specific icons, this is two Gitlab tabs (right before activation of Chameleon, left after activation of Chameleon)

![Snímek obrazovky z 2024-05-07 12-05-01](https://github.com/sereneblue/chameleon/assets/1508022/eed6b413-12a8-431e-ab55-550b2db564bf)

2. Visual effects on Google Meet video. The video works without visual effects.

![Snímek obrazovky z 2024-05-07 12-04-38](https://github.com/sereneblue/chameleon/assets/1508022/e076a1de-8319-436b-91c2-78feb155f9b5)

3. Figma

![Snímek obrazovky z 2024-05-07 12-07-14](https://github.com/sereneblue/chameleon/assets/1508022/e2f7a688-3b60-4bb8-97c3-d113010b1d4f)

I encountered more, but I figured that three examples should be enough. When I disable the extension in firefox extension manager, everything works as usual.

## Relevant settings

This happens using the default settings (I used "Reset to default").

```
{
  "config": {
    "enabled": false,
    "notificationsEnabled": false,
    "theme": "light",
    "reloadIPStartupDelay": 0,
    "hasPrivacyPermission": true
  },
  "excluded": [],
  "headers": {
    "blockEtag": false,
    "enableDNT": false,
    "referer": {
      "disabled": false,
      "xorigin": 0,
      "trimming": 0
    },
    "spoofAcceptLang": {
      "enabled": false,
      "value": "default"
    },
    "spoofIP": {
      "enabled": false,
      "option": 0,
      "rangeFrom": "",
      "rangeTo": ""
    }
  },
  "ipRules": [],
  "options": {
    "cookieNotPersistent": false,
    "cookiePolicy": "reject_trackers_and_partition_foreign",
    "blockMediaDevices": false,
    "blockCSSExfil": false,
    "disableWebRTC": false,
    "firstPartyIsolate": false,
    "limitHistory": false,
    "protectKBFingerprint": {
      "enabled": false,
      "delay": 1
    },
    "protectWinName": false,
    "resistFingerprinting": true,
    "screenSize": "default",
    "spoofAudioContext": false,
    "spoofClientRects": false,
    "spoofFontFingerprint": false,
    "spoofMediaDevices": false,
    "timeZone": "default",
    "trackingProtectionMode": "always",
    "webRTCPolicy": "default_public_interface_only",
    "webSockets": "allow_all"
  },
  "profile": {
    "selected": "none",
    "interval": {
      "option": 0,
      "min": 1,
      "max": 1
    },
    "showProfileOnIcon": true
  },
  "version": "0.22.57.2",
  "whitelist": {
    "enabledContextMenu": false,
    "defaultProfile": "none",
    "rules": []
  }
}
```

## Context (Environment)

```
firefox-125.0.3
Linux 6.8.9-arch1-1
```

I actually switched graphic cards recently and the problem was both on nvidia and still persists on amdgpu.

**Comment by sereneblue** [comment]
Hi @just-paja,

Are you still experiencing this issue with Firefox 126? I'm not sure how Chameleon is affecting the browser UI like that. Have you tried disabling the resist fingerprinting option?

**Comment by just-paja** [comment]
Hello @sereneblue,

thank you for coming back to me. I tried in firefox-126 and the problem still remains. However. after disabling the "Resist fingerprinting" option, it goes away. I'd expect the extension to avoid doing any changes to browser behaviour when it says that "it is off", but perhaps that might be just me misunderstanding the functionality :-)

**Comment by sereneblue** [comment]
Hi @just-paja,

Yes, I should clarify this in the wiki. Some options, when enabled, toggle Firefox browser settings. Disabling Chameleon through the Chameleon UI or using the whitelist only affect the browser profiles, injection and some of the standard options. Disabling the extension in the Firefox settings removes Chameleon's control of browser settings.
