### ISSUE TITLE
SyntaxError: redeclaration of let settings -     inject resource://gre/modules/ExtensionContent.sys.mjs:581 - AsyncFunctionNext self-hosted:852

### ISSUE THREAD

**Issue by slrslr** [sereneblue/chameleon#584]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ -] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

At https://blank.page/ and other pages, F12 key, reload page, Console tab of the Dev. console.

> SyntaxError: redeclaration of let settings[some string:1:1](blob:moz-extension://string of the chameleon extension/other string)
>     <anonymous> blob:moz-extension://string of the chameleon extension/other string/some string:1
>     **inject resource://gre/modules/ExtensionContent.sys.mjs:581
>     AsyncFunctionNext self-hosted:852**

such error shows also on other websites. Can you please get rid of it? It is making debuging worse from the layman point of view.

Chameleon version 0.22.59.1 (Last Updated June 25, 2024)
Firefox 115.12.0esr (64-bit)

**Comment by sereneblue** [comment]
Hi @slrslr,

I'm not able to replicate this issue. Can you export your settings so that I can try to reproduce that error message?

**Comment by slrslr** [comment]
@sereneblue sure, thanks for Your kind reply. **[Here is](https://bin.disroot.org/?7183b688b57468c9#AoELak2pgE7v2T8E5HQCYKFrUaFLYiydUo5z5GFU5AjU)** the configuration export.

**Comment by sereneblue** [comment]
Thanks @slrslr. I still haven't been able to reproduce this issue. It looks like Firefox might be injecting the content script twice but that doesn't seem quite right. Can you try with the latest ESR (128)?

**Comment by slrslr** [comment]
> Can you try with the latest ESR (128)?

I have tried latest version:
128.1.0esr
129.0.2

and i can not reproduce this issue, so I am closing this. Thank you.
