### ISSUE TITLE
`navigator.plugins` is not an instance of `PluginArray`, causing false positive BotD detection

### ISSUE THREAD

**Issue by AJGranowski** [sereneblue/chameleon#586]
## Expected Behavior

```js
navigator.plugins instanceof PluginArray === true
```

Expected BotD result:

```js
JSON.stringify(await BotD.load().then((bd) => bd.detect())) 
```

```
'{"bot":false}' 
```

## Current Behavior

```js
navigator.plugins instanceof PluginArray === false
```

This discrepancy causes false positive BotD detection as a headless chrome bot. Disabling Chameleon or changing [this line in BotD](https://github.com/fingerprintjs/BotD/blob/45f086bb2cd040c29fc940d8d6e44170e6194b5e/src/sources/plugins_array.ts#L10) to return `true` causes BotD to correctly return a not-bot result.

You can probe the BotD detector using https://xcancel.com/search [[1]](https://xcancel.com/static/v1/iife.min.js)

```js
JSON.stringify(await BotD.load().then((bd) => bd.detect())) 
```

```
'{"bot":true,"botKind":"headless_chrome"}'
```

## Context (Environment)

Chameleon v0.22.60  
Firefox 128.0 (64-bit) on Windows 10

Related to [BotD#171](https://github.com/fingerprintjs/BotD/issues/171).

**Comment by sereneblue** [comment]
@AJGranowski Thanks! This will be fixed in the next update.
