### ISSUE TITLE
Reading manifest: Warning processing browser_specific_settings.gecko_android.id: An unexpected property was found ...

### ISSUE THREAD

**Issue by slrslr** [sereneblue/chameleon#587]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [- ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Hello, after updating https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions to supposedly latest Firefox release (128.0) on Debian 11, I hav elaunched it and went to Fiefox page:
about:debugging#/runtime/this-firefox
clicked "Extensions" and near Chameleon I can see:
```
Warning details

Reading manifest: Warning processing browser_specific_settings.gecko_android.id: An unexpected property was found in the WebExtension manifest.

Warning details

Reading manifest: Warning processing version_name: An unexpected property was found in the WebExtension manifest.
```

manifest.json contains:

```
{
  "name": "Chameleon",
  "description": "__MSG_extDescription__",
  "author": "sereneblue",
  "version": "0.22.60.1",
  "version_name": "0.22.60",
  "manifest_version": 2,
  "browser_specific_settings": {
    "gecko": {
      "id": "{anonymized}",
      "strict_min_version": "68.0a1"
    },
    "gecko_android": {
      "id": "{anonymized}",
      "strict_min_version": "68.0a1"
    }
  },
  "default_locale": "en",
  "icons": {
    "48": "icons/icon.svg",
    "128": "icons/icon.svg"
  },
  "browser_action": {
    "default_icon": "icons/icon.svg",
    "default_popup": "popup/popup.html"
  },
  "background": {
    "scripts": [
      "background.js"
    ]
  },
  "permissions": [
    "<all_urls>",
    "alarms",
    "contextMenus",
    "notifications",
    "storage",
    "tabs",
    "webRequest",
    "webRequestBlocking"
  ],
  "optional_permissions": [
    "privacy"
  ]
}
```

**Comment by sereneblue** [comment]
Hi @slrslr,

You can ignore those warning messages. Unexpected keys in the manifest.json file will display those errors. `gecko_android.id` is used to enable Firefox for Android support and `version_name` is used to display a friendlier version name to users (ex. v0.22.60-rc vs 0.22.60.0).
