### ISSUE TITLE
Is Chameleon suggesting 100% unique UserAgent fingerprint?

### ISSUE THREAD

**Issue by slrslr** [sereneblue/chameleon#589]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

Hello,

Firefox 129.0 (64-bit)
Chameleon v0.22.61
Current Profile:
Win 8.1 / Firefox 128 ESR
Default Screen
GMT

under such profile, webpage https://amiunique.org/fingerprint displayed:
`1 - User agent 0.00 % | Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0`

Under different profile again 0.00 %:
`1 - User agent 0.00 % | Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:115.0) Gecko/20100101 Firefox/115.0`

important part is that 0% similarity ratio, like if it is a 100% unique. What do you think about that please?

https://myip.ms/browse/myip/1/agentID/5315647
https://useragents.io/uas/mozilla-5-0-windows-nt-6-3-win64-x64-rv128-0-gecko-20100101-firefox-128-0_5628239551fdb44619b3a4f5b93a8a82

About second provided UserAgent other testing tool also reports very high uniqueness:
https://coveryourtracks.eff.org saying "One in x browsers have this value: 6164.8"

**Comment by sereneblue** [comment]
Hi @slrslr, thanks for reporting. I just checked and it looks like Firefox 115 is the latest officially supported version of Firefox for Windows 7, 8, and 8.1. I've removed those browser profiles and will push in the next update. Whitelist profiles and settings that used these profiles will be updated to map to the Firefox 115 ESR profile.
