### ISSUE TITLE
BuildID enhancement

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#59]
In v0.8.17, the buildID leak is adressed in blocking it. Nothing is send as buildID. It's an interresting  workaround, but sending nothing as buildID is not a typical behavior (at least for FF browsers). So, not sending a buildID may be a kind of fingerprint in itself.... It would be better to spoof it, thanks to some injection. But the faking would have to be a little tricky: The faked buildid must not refer to a date before the  release date of the spoofed UA. Maybe a could spoofing strategy could be to spoof  BuildID y year+month+day of the spoofed UA's release, the hour, minutes and second being random.

**Comment by sereneblue** [comment]
You can find the build in about:config using this key: `browser.startup.homepage_override.buildID`. I don't think the build ID represents the date of the release. Looking at the installs I have, it looks like it's around the time the user installed it. I'm not too sure what it actually represents.
