### ISSUE TITLE
Can't add rule to the whitelist

### ISSUE THREAD

**Issue by razgithub** [sereneblue/chameleon#592]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

Allow adding a host in the LAN to the whitelist by hostname, e.g. 'alice' in URLs.

Maybe allow disabling the check? (or allow saving the rule after giving the user a warning, considering it may be uncommon to use hostnames without domain, and typically a mistake?)

## Current Behavior

In the Whitelist Rule Editor, Chameleon checks for the validity rules and rejects single names, except for 'localhost'.

In a LAN setting, single host names are used, and they should be allowed as a URL.

## Relevant settings

I don't think any setting is relevant.

## Context (Environment)

Arch Linux, Librewolf 129.0.1-1, Chameleon v0.22.63.

**Comment by sereneblue** [comment]
Hi @razgithub,

This is fixed in v0.22.65.

**Comment by razgithub** [comment]
Oh, hi!

Amazing response time. And using new URL seems much more elegant than regex.

Thanks a lot @sereneblue !
