### ISSUE TITLE
Lost Chameleon v0.22.67 settings, whitelist in a Firefox 128.4.0esr

### ISSUE THREAD

**Issue by slrslr** [sereneblue/chameleon#597]
# Prerequisites

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

In Firefox 128.4.0esr I have Chameleon v0.22.67 which I found it in a default state (without my settings and a whitelist).
I have recently moved from a non-ESR version of a Firefox to the mentioned lower version of a Firefox ESR (--allow-downgrade flag). I do not remember if Chameleon settings survived the change of the browser on same profile, but now I see it is gone/disappeared.

Please which file holds the settings, since I am keeping backups of my Firefox profile folder.
Inside $HOME/.mozilla/firefox/myprofile.default-release/browser-extension-data/ I have not found any file containing "chameleon" in name or content.

Beside recovering Firefox backup, other option is that you have FIrefox addons sync. enabled so the Chameleon data may be found on other device.

**Comment by sereneblue** [comment]
Hi @slrslr,

Chameleon does not currently support Firefox Sync. I'm not sure how Mozilla stores the actual extension data. If you have backups of the Firefox profile, you can try restoring the profile and exporting the Chameleon settings from there, if the restore is successful.
