### ISSUE TITLE
Details still retrieved correctly by https://amiunique.org/fp despite spoofing

### ISSUE THREAD

**Issue by GLLM** [sereneblue/chameleon#6]
hi !
thanks for the hard work on this extension.

I've visited https://amiunique.org/fp to check my new spoofed profile and when I check the details of the fingerprint, this site still gets the below correctly
* screen size, despite the spoofing I've activated
* platfrm (I expected this would be impacted by the user agent sent)

Am I expecting too much ?
GLLM

**Comment by sereneblue** [comment]
Did you try generating a new fingerprint? Sometimes the force fingerprinting button doesn't appear on the page. Did you enable script injection? I'm not experiencing any issues with Firefox 60.

![image](https://user-images.githubusercontent.com/14242625/41613025-7627bdac-73c2-11e8-89fe-e06684212620.png)

**Comment by GLLM** [comment]
Hi !

thanks for your reply. Indeed with the _Enable Script injection_, it works.
I think whatever setting requires the _Enable Script injection_ to be set to ON should pop up a warning about this pre-requisite.

One funny setting could be to be able to set, at once, the different settings values to the most comon ones ... so that one get lost in the mass of users.

thanks.

**Comment by sereneblue** [comment]
Good suggestion. I've made the UI a little more clear about which options require script injection. The next public release will contain these changes.

I think it's best for the user to actively select their preferred settings, however, I'll add a recommended list to the wiki.
