### ISSUE TITLE
WebRTC Local IP Leakage Management.

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#60]
As for FF 42 and higher it is possible to prevent local IP addresses leakage via WebRTC *without completely disabling WebRTC features*. This can be done by various other extensions, such as uBlock Origin or Privacy Badger. For FF 60 ESR,  it seems to suffice to set in _about: config_ the preference **media.peerconnection.ice.proxy_only** to **true** (correct me if I'm wrong). Currently, _Chameleon_ doesn't address the local IP WebRTC leakage issue.

As _Chameleon_ is a spoofing/faking tool, would it be possible that a _fake_ local ip address would be sent instead of nothing as the others extensions above currently do?

**Comment by sereneblue** [comment]
Unfortunately, there isn't a clear way to do something like that.

I didn't include it in Chameleon because uBlock Origin already does it and I'm sure almost every Chameleon user is also using uBlock.

**Comment by smed79** [comment]
> I'm sure almost every Chameleon user is also using uBlock.

I use **Chameleon** with [**Adblock Plus**](https://adblockplus.org/) and I'm sure I'm not the only one 🤔
The requested feature is useful, so please 🙏 reconsider your decision.

**Comment by sereneblue** [comment]
You should really consider using uBlock Origin, it's the better extension: more features, better memory usage and doesn't whitelist ads.

Unfortunately, I won't be reconsidering this feature.

**Comment by Kraxys** [comment]
> Unfortunately, there isn't a clear way to do something like that.
> 
> I didn't include it in Chameleon because uBlock Origin already does it and I'm sure almost every Chameleon user is also using uBlock.

I use uBlock too. And my request wasn't about to integrate in Chameleon a feature to prevent leakage, but to spoof it, with a random local IP. If you think it's not possible, this matter is closed. But if, one day, you get an idea to make it feasible, please don't hesitate to reconsider your position :)

**Comment by sereneblue** [comment]
@smed79 An adblock filter is a little different than adding a feature that's already been implemented in several extensions.

I looked at how it's handled with Quantum and it's simple enough to add. It'll be in the next release of Chameleon.

@Kraxys I like the idea but it's not possible to consistently spoof it using WebExtensions.

**Comment by smed79** [comment]
Thank you all very much for the tip and new feature.
