### ISSUE TITLE
Add Optionnally Sending HTTP_UPGRADE_INSECURE_REQUESTS

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#67]
Sending the header [HTTP_UPGRADE_INSECURE_REQUESTS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade-Insecure-Requests) increase security a bit. I think it could be add to the Headers option.

NB: TBB send it.

**Comment by sereneblue** [comment]
HTTPS Everywhere does this for you but I'll add it to Chameleon.

**Comment by Kraxys** [comment]
> but I'll add it to Chameleon.
Thanks.

>HTTPS Everywhere does this for you.

This part of you reply is puzzling me: 1) I wasn't aware of that concerning HttpsEverywhere 2) I have this addon installed, but checking on ip-check.info never shows the green row "Upgrade-Insecure-Requests", as it does with TBB.

**Comment by sereneblue** [comment]
I searched before replying to see if any of the HTTPS redirection addons had this feature and it looks like HTTPS Everywhere does according to their changelog?

https://github.com/EFForg/https-everywhere/blob/6c6108d56a629e6952a4095a980f6fe6a25115ba/src/Changelog

I've already added it to Chameleon, just haven't pushed the commit yet. :) Working on a few open issues for a v0.9.0 release.
