### ISSUE TITLE
Spoofing canvas fingerprinting?

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#74]
Using https://browserleaks.com/canvas detects my correct OS despite chameleon.

https://multilogin.com/how-canvas-fingerprint-blockers-make-you-easily-trackable/ suggests to spoof rather block canvas:

"Your first instinct is probably to grab a browser extension that prevents the canvas image from loading. If it doesn’t load, they can’t track you – right? Wrong. Preventing the canvas image from loading is an identifier in itself. Although the canvas fingerprint will not be sent,  the fact that you did not load the canvas image will be.  So, you will be sorted into a very small group of tech-savvy users who are also blocking fingerprints, and from there, your ordinary fingerprints will sometimes be enough to identify you completely."

This addon creates noises to the fingerprint: https://addons.mozilla.org/en-US/firefox/addon/no-canvas-fingerprinting/?src=cb-dl-hotness but as October 2018 it doesn't seem to be working, at the least for me.

In addition it blocks the "broswer statistics" part of browserleaks test...so I am not able to judge completely its effectiveness. It is BSD licensed so maybe you can look at the source code if it helps.

What do you think? Could chameleon spoof such fingerprinting?

**Comment by Kraxys** [comment]
@WPFilmmaker: Concerning spoofing Canvas, the extension [**CanvasBlocker**](https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/) do that very well  (and many other things: It spoofs Window.name, History, Webgl, ClientRects, Audio...), and it is frequently updated. So you can use it. 

Let see what Sereneblue thinks about your request, but I think our dev only has 24h in his/her day, and while some overlapping between Chameleon & CanvasBlocker  is not a bad thing, developing more spoofing features that are already available elsewhere (and efficiently implemented) would be a waste of resources.  I think its better to dedicate these resources in developing original features.

**Comment by sereneblue** [comment]
Thanks for all the help @Kraxys. :+1:  

@WPFilmmaker You should use CanvasBlocker. It's [one](https://github.com/sereneblue/chameleon/wiki/Recommended-Setup#recommended-addons) of the addons I recommend to use with Chameleon. ;) It creates a unique fingerprint on every page load. The browsers statistics doesn't show when it's enabled.
