### ISSUE TITLE
Question on the whitelist

### ISSUE THREAD

**Issue by 3ibsand** [sereneblue/chameleon#75]
Hello.
Sorry for my english :) Sereneblue, thanks so much for your great extension 🥇

But there was one question. When I use the whitelist, other sites also see the real profile. Am I doing something wrong?

Example (enable script injection - on)

![image 21](https://user-images.githubusercontent.com/44104203/46898644-b3642800-ce93-11e8-82ba-138f6744b66e.png)

Set TimeZone = + 1

Result on test sites: Browser TimeZone = IP TimeZone

 Enable whitelist (requires script injection) - off
 Use real profile for whitelist - off

Checker sites: Browser TimeZone +1

And with other parameters (injection) as well.

Thank ))

**Comment by sereneblue** [comment]
Your English is fine. :) 

I've located the bug and its fixed in v0.9.2. Please let me know if there are any other issues.
