### ISSUE TITLE
True OS Detected and Screen Resolution Inconsistencies When Profile Is Mobile

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#76]
The site [FakeVision](http://f.vision/) is able to detect my true platform (Windows).

Edit 1: The site  [WhatLeaks](https://whatleaks.com/) is able to detect my true platform too. In that case, through "Passive OS Fingerprinting" relying on network/TCP properties. But very probably there is nothing a browser extension can do against that.

Edit 2: Performing "Advanced Tests" on FakeVision shows that this site is guessing true OS through Passive OS Fingerprinting too.

Also It seems that mobile spoofing may  lead to some inconsistencies, with e.g screen resolution 414×736 **and** viewport: 1286×606.

(Or maybe I still haven't well understood what you replied to me [here](https://github.com/sereneblue/chameleon/issues/73#issuecomment-428391319)??).

**Comment by sereneblue** [comment]
The viewport is the visible area of a web page. That's the issue with mobile screen spoofing. Most likely the user's viewport is going to be larger than the spoofed screen resolution. There's not much advice I can offer besides making your browser window smaller or use the responsive design mode.

There's nothing I can do about the passive OS fingerprint. Firefox's Private Browsing and Tor Browser also leak that information. Keep in mind that Chameleon won't prevent you from being tracked. If you use it with a few other addons, your information generally won't be leaked.
