### ISSUE TITLE
Screen Resolution Bug

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#77]
When in "Profile" checking "True Profile" and in "Script Injecting Options" checking "Script Injection" and selecting "Profile" for screen size spoofing, I get, eg on Browserleaks:
 **Screen Resolution	null×null 24-bit TrueColor**

I think in that case the screen resolution should be the true screen resolution of my device.

**Comment by sereneblue** [comment]
I'll fix this in the next commit.
