### ISSUE TITLE
HSTS Fingerprinting

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#78]
On [FakeVision](http://f.vision/) site, I get fingerprinted through HSTS.

Could there be a way for Chameleon to prevent that?

**Comment by sereneblue** [comment]
This is the first I've heard of HSTS tracking. It's a shame that a security feature is being weaponized against users. There's no end to this arms race.

I believe Mozilla has also added some limited protection with Private Browsing. I'm not sure yet if an extension is capable of fixing this but I do think it'd be preferable for this to be fixed in the browser.

**Comment by Atavic** [comment]
I totally agree with what serenblue said above, and I have concluded that in-browser solutions will be sparser and sparser in the future. That said, HSTS gives improved security and reduced privacy, particularly it's max age value of one year in the header response:

```Strict-Transport-Security: max-age=31536000```

**Comment by Kraxys** [comment]
@Atavic: I think to that hijacking a security feature is really a shame. In this case, I consider the potential privacy issue to be acute as the identifying data seem to persist from a browsing session to an other even when using Private Mode. There is a balance between security, privacy and usability to find, but it's a pity to have to arbitrate between security and privacy.
I have a question: The purpose of HSTS being to automatically redirects HTTP requests to HTTPS for the target site, in which way could it be replaced by the 3 addons [HttpsEveryWhere](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/) + [SmartHttps](https://addons.mozilla.org/en-US/firefox/addon/smart-https-revived/) + [ConsistentHttps](https://addons.mozilla.org/en-US/firefox/addon/consistent-https/) ?

**Comment by Atavic** [comment]
Yes, a shame that's so common. You have to delete browser history or right-click and choose *Forget About This Site* on a specific history URL. In my commonly used browser (a FF fork) I use SmartHTTPS.

**Comment by sereneblue** [comment]
Yes, HTTPS Everywhere/SmartHTTPS should mitigate this issue.
