### ISSUE TITLE
[Request] Spoofing WebRTC Local IP Leakage

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#79]
It is possible to prevent WebRTC from leaking **local** IP address, eg for FireFox in setting the preference **media.peerconnection.ice.proxy_only** to **True**.

 But where it possible to **spoof** this local leaking IP with a local random one (instead of blocking any leakage)??

**Comment by sereneblue** [comment]
You previously made an issue about this.

https://github.com/sereneblue/chameleon/issues/60
