### ISSUE TITLE
[UI] Popover view broken when opened in Firefox overflow menu

### ISSUE THREAD

**Issue by Retia-Adolf** [sereneblue/chameleon#80]
![image](https://user-images.githubusercontent.com/34053927/47223024-b38a8900-d3a7-11e8-98c4-808253aece54.png)

![image](https://user-images.githubusercontent.com/34053927/47223241-4aefdc00-d3a8-11e8-901d-9f1e0e115fc1.png)

1. Overflow menu is bulged;
2. If anyone of these `Random Profile` were chosen, custom interval textbox would be out of visible area.

Environment: Firefox Developer Edition 64.0b1 (64-bit), Windows

**Comment by sereneblue** [comment]
This is fixed in v0.9.5.
