### ISSUE TITLE
Chameleon Settings not persisting over time in Android

### ISSUE THREAD

**Issue by AedraSylene** [sereneblue/chameleon#83]
Whenever I make changes to any settings in Chameleon on Android, they all revert back to default after some time.

I've tried a bit of troubleshooting and ultimately thought I fixed it when I disabled the Battery Optimization for Firefox, but that just delayed the reset longer instead of stopping it (from less than an hour to a few hours).  I also enabled notifications in hopes to prevent it from reverting but even with active notifications in the notification drawer, Chameleon's settings reset to default (although, again, it takes longer/several hours).

I'm not sure if this is an Android issue or Chameleon.  Other add-ons in Firefox are not reverting their settings.  It's extremely frustrating to have to go back and re-enable all my settings every time I open Firefox.  (I also can't find where to import my saved settings either, which would make it a lot faster.)  

Browser:  Firefox for Android 62.0.2
Chameleon:  version 0.9.5
Android:  8.1.0  (Samsung)

**Comment by sereneblue** [comment]
It's probably a Chameleon bug but I'm not sure why I haven't noticed any issues using the desktop version. I'll take a look at this after I've closed some of the other issues.

**Comment by sereneblue** [comment]
This should be fixed in v0.9.9. Please reopen this issue if you're still having issues.
