### ISSUE TITLE
Google Login no longer possible since 0.9.4 or 0.9.5 update

### ISSUE THREAD

**Issue by kekkc** [sereneblue/chameleon#84]
Hi,

I discovered an issue since the last update:
- it's no longer possible for me to login on google.com ("Your browser has cookies disabled. Make sure your cookies are enabled and try again. Learn more") or other sites (e.g. pixiv.net)
- on Github the login was possible, but after clicking to create this issue, I got an error message as well ("your browser did sth. unexpected")

thought this is related to the recent FF63 changes, but I allow all cookies and it certainly works with Chameleon deactivated. 

The strange thing is that I even discover these issues with Chameleon activated, but no  options selected: the real profile is sent, no activated options / script injection. Chameleon should be de facto deactivated with no options selected, but still seems to cause these issues.

Anyone else experiencing this or any ideas what could cause this?

**Comment by sereneblue** [comment]
I have confirmed this issue. I wonder if this is also related to the issue that's causing https://github.com/sereneblue/chameleon/issues/81.

**Comment by sereneblue** [comment]
Please reopen this issue if you're having issues with v0.9.7.

**Comment by kekkc** [comment]
Fixed! Many thanks for the quick reaction & UA updates, you're amazing ;)
