### ISSUE TITLE
Request Concerning Time Spoofing

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#85]
Now that Chameleon's Time Spoofing feature is working better than the ones provided by the 2 others dedicated addons available on AMO [(**Change TimeZone**](https://addons.mozilla.org/en-US/firefox/addon/change-timezone-time-shift) and [**SpoofTimeZone**](https://addons.mozilla.org/en-US/firefox/addon/spoof-timezone)), there is a very cool feature from SpoofTimeZone which maybe could be ported to Chameleon: This feature allows SpoofTimeZone's user to **automatically** (at least at start) adjust the TimeZone of his browser to the time zone of the IP it is using (just check _"automatically update time zone based on my IP address_" in SpoofTimeZone preferences). 

Such a feature is a little bugged in SpoofTimeZone (cause 1) this addon's time spoofing is not perfect and 2) this addon's preferences are resetting  at random starts from time to time), but if ported to Chameleon I think it could work perfectly,  and it would make much easier the life of proxy/vpn users (in my case, having to think to adjust my time zone to the proxy server in use every time I start my browser is a hassle; I regularly forget it, keeping the last time zone in use, resulting eg in using a server in Mexico with a russian time zone, which is very bad).

**Comment by sereneblue** [comment]
Sure, this sounds like a good idea. I'll take a look at it after I fix one of the other issues.

**Comment by 3ibsand** [comment]
Sereneblue, thanks. Very usfule with vpn. Brilliant functionality!
