### ISSUE TITLE
blocks flash 

### ISSUE THREAD

**Issue by jahnson** [sereneblue/chameleon#86]
Just a day or so ago chameleon stopped flash content from working.  
Disable chameleon, flash content plays, enable chameleon, it does not.  I have looked through the documentation and tried changing several settings, to no avail.  
Flash is enabled in the FF permissions for the relevant sites.  
I am using FF 63 32b under W7-64, and updated the flash player today.  
I despise flash as much as the next person, but some sites that I use include it, so I have no choice.

**Comment by sereneblue** [comment]
Chameleon doesn't do anything to flash, so it's probably another issue that's causing problems. What website are you experiencing issues with? What version of Chameleon are you using?

**Comment by jahnson** [comment]
To answer your questions: an example of a web site that was not working was tennis24.com.  I was using 0.9.7 I think - I had updated addons before posting this issue.  
I asked FF now again to update addons and it appears that I have 0.9.9.  
Right now it appears to be working again.  Thank you for the repair.

**Comment by jahnson** [comment]
Interestingly, another site where flash did not work is the flash player version check:
https://helpx.adobe.com/flash-player.html

Now when I go there and click on "Check Now" it reports "Sorry, Flash Player is either not installed or not enabled."  However, below that it does correctly report the version of flash player that is installed!  Further below in part 5 there is an animation which is supposed to play if the flash player is installed.  That animation does not play.  
When I disable Chameleon, it reports "Congratulations, your computer has the latest Flash Player installed." and the animation in part 5 plays.  
So with Chameleon enabled, something is not quite 100% yet.

**Comment by sereneblue** [comment]
What settings are you using with Chameleon? I'm not experiencing any issues with the animation with a fresh install of v0.9.9 or modifying a few of the spoofing options.

**Comment by jahnson** [comment]
Basically like the casual user in the documentation: 
Enable notifications
change every hour
windows browsers (all excluded except versions of FF) 
spoof if-none-match (Etags) 
spoof source referrer 
enable script injection 
screen size spoofing 
time zone set 
enable tracking protection 
resist fingerprinting 
webrtc policy: only use public interface 
cookie options: allow all (then I use settings in FF to control these)

**Comment by sereneblue** [comment]
Resist fingerprinting is the cause of this issue. It isn't listed under the recommended setup section of the wiki because it breaks a lot of sites.

More info about that option and flash player here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1317846
