### ISSUE TITLE
Recent Changes Make Left Click Functionality No More Work On Some Sites

### ISSUE THREAD

**Issue by Heri0n** [sereneblue/chameleon#87]
Since **last version** (0.9.7) I have problems to access to  left clicking functionalities with my mouse on some sites. 

For example, by clicking on the magnifying glass on site [boursorama](https://www.boursorama.com/) I can no longer make the search field be displayed.

And on news site [LeMonde](https://www.lemonde.fr/) I can con longer access to **some** articles when left clicking on their titles (most of the time left clicking works, but for some articles it doesn't no more work).  For example, go to the section "_Les plus partagés_" (right on the 1st page). There, I can no more access to half of the articles when left clicking on their displayed titles.

I tried to find which Chameleon's feature could be the culprit. After several tests,  and in a not very intuitive way (at least for me), this culprit seems to be the **Timezone spoofing feature**, which is somewhat consistent as the code of this feature has just been changed (cf bug #82):   As soon as I set in Chameleon Timezone to "default", without changing anything else, left clicking works again.

I use FF 63 on windows 8.1.

Tested with Chameleon as the sole extension.

Edit: Same with FF 62.

**Comment by sereneblue** [comment]
Nice work debugging the issue! I've identified the problem but the fix may take some work. I have to find a cleaner way to fix #82 without breaking sites.

**Comment by sereneblue** [comment]
Turned out to be a simple fix. Please test with v0.9.8 and let me know if you're still having issues. :)

**Comment by Heri0n** [comment]
The bug seems now completely fixed. You're amazing! Thank you!
