### ISSUE TITLE
Can't change ip address

### ISSUE THREAD

**Issue by JIACHENG135** [sereneblue/chameleon#88]
![new text document 2](https://user-images.githubusercontent.com/31320373/47599466-562ca400-d974-11e8-9385-a6936f75e1ce.jpg)
![image](https://user-images.githubusercontent.com/31320373/47599471-72c8dc00-d974-11e8-81ab-f110f3bf1600.png)
here is my settings. I want to change my ip address randomly. But failed. Can you give me some hint? Thanks

**Comment by sereneblue** [comment]
https://github.com/sereneblue/chameleon/wiki/Headers

Please read the relevant section for headers.

Chameleon will not change your IP address.It spoofs some header values that can trick some sites. You'll need a proxy or VPN.

**Comment by smed79** [comment]
@JIACHENG135 To change your ip address, a [VPN](https://en.wikipedia.org/wiki/Virtual_private_network) or [Proxy](https://en.wikipedia.org/wiki/Proxy_server) is required.

PS: Using [Tor](https://en.wikipedia.org/wiki/Tor_(anonymity_network)) is an alternative.

**Comment by JIACHENG135** [comment]
Thank you for your reply！I got the point. I am trying to use OpenVpn to do
that.
