### ISSUE TITLE
Some Bug in IP TimeZone Spoofing

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#90]
Thanks for the new feature "IP TimeZone Spoofing". But there is a little bug: When using an IP in California, Chameleon send a correct notification ("using America/Los_Angeles as timezone"), bug in testing on [Spoof-Timezone](https://add0n.com/spoof-timezone.html), the "DateTimeFormat method" displayed   (both MainfFrame and IFrame) are "IP" instead of "America/Los_Angeles".

Also when using a vpn server in Zurich, the notification sent by Chameleon is "using Europe/Berlin as timezone".

**Comment by sereneblue** [comment]
It's not a bug. ;)

It's using one of the timezones listed here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
Multiple labels can map to a specific timezone.

UTC -08:00 = US/Pacific 
                  = America/Los_Angeles
                  = America/Tijuana
                  = America/Vancouver

I'll make the notification a little more descriptive in the next update since it may be confusing. Ex
UTC-08:00/Time_In_That_Location

**Comment by Kraxys** [comment]
> 
> 
> It's not a bug. ;)
> 
> It's using one of the timezones listed here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
> Multiple labels can map to a specific timezone.


I think your reply mostly relates to the second part of my previous post ("_Also when using a vpn server in Zurich..."_)., but concerning the first part, I don't understand how it could not be a bug: The timezone string **displayed** by the test site add0n.com/spoof-timezone.html is "IP"   (these 2 letters) instead of (in this example) "America/Los_Angeles", "America/Tijuana", or "America/Vancouver".

**Comment by sereneblue** [comment]
Oh, I did misunderstand you. That's an odd bug. I wonder what's causing the issue.
