### ISSUE TITLE
Issues In TimeZone detection when using the feature "TimZone according IP"

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#91]
When selecting spoofing TimeZone according to IP, sometimes the TimeZone doesn't match the IP.

Steps to reproduce:

1a) set up a proxy connection and close browser
or
1b) close browser, change VPN server

Then
2a) restart browser and test the time zone on [SpoofTimeZone site](https://add0n.com/spoof-timezone.html)

The test very often shows  IP qand TimeZone and/or TimeZone location don't match.

But when I replace step 2a) by

2b): In chameleon select a fixed time zone spoofing (eg GMT -12 Pacific Kwajalein, or even "default"))
and then
3) In Chameleon select TimeZone spoofing according IP

Then he TimeZone and the TimeZone location instantaneously perfectly match the IP.

**EDIT:** Can't reproduce the problem now. Maybe the above issue is due to some delay involving FoxyProxy (I used it to easily change IP).

**Comment by sereneblue** [comment]
Chameleon uses https://ipapi.co to get the timezone for the IP. ipapi uses Cloudflare so it may block your IP address if you're using a low quality IP address. If that happens, the timezone is set to UTC.

**Comment by Kraxys** [comment]
> 
> 
> Chameleon uses https://ipapi.co to get the timezone for the IP. ipapi uses Cloudflare so it may block your IP address if you're using a low quality IP address. If that happens, the timezone is set to UTC.

Make sense. I think you can close this thread.
