### ISSUE TITLE
don't open the wiki page automatically after every update

### ISSUE THREAD

**Issue by sixpointzero** [sereneblue/chameleon#93]
It seems that this add-on is being updated quite frequently these days which might be a good thing. However, the GitHub wiki page of this add-on opens up automatically after every update. Frankly speaking, its a bit annoying.

Can you add an option to disable opening the wiki page after every update?

Thanks for making this add-on.

**Comment by sereneblue** [comment]
Sorry for the trouble.

Looks like I implemented it wrong; it should only open the wiki on the first install. I'll fix this ASAP.
