### ISSUE TITLE
Change profile at every restart/close

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#94]
I think it would be a nice addition having such option to add randomness. Right now it is possible specifying only minutes.

**Comment by sereneblue** [comment]
Chameleon already does this. If you use one of the random options, you'll get a new profile when you restart Firefox. You can verify this by visiting https://browserleaks.com/javascript after restarting Firefox.

**Comment by WPFilmmaker** [comment]
@sereneblue Thanks for the info! Do I have to set "no" to "change periodically"?

**Comment by sereneblue** [comment]
No, you don't have to set the interval if you only want the profile to change when the browser restarts. It's random so it may reuse the same profile.
