### ISSUE TITLE
Display of new random profile seems to be broken

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#95]
When I click "refresh" I don't see the pop-up with the new random profile :/ Is it broken only for me? On FF 62 and Lubuntu 18.04 works.

I am on Lubuntu 16.04.3, FF 63.0, chameleon 0.9.16.

**Comment by sereneblue** [comment]
Did you enable notifications?

**Comment by WPFilmmaker** [comment]
@WPFilmmaker Duh I had not :( I overlook that there was a notification button. You can close sorry:)
