### ISSUE TITLE
Accept Language Issue

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#98]
I'm using Chameleon 0.98.

I generally use EN (US) as acccept language.
But this time, I was curious to see what happen when changing it.

Si I switched, in Chameleon/Headers, from en (US) to Russian.

Test on ip-check.info then showed thant the language string which was sent was
 **ru-RU ru;q=0.8,en-US;q=0.5,en;q=0.3**

I think It shoud just have been **ru-RU** or something like that. Testing with other language showed the same thing: Always "en-US" fragments remained sticked in the sent language string.

Moreover, I nowhere find any mean on Chameleon GUI to adjust languages to IP (announced as a new feature in v. 0.98).

**Comment by sereneblue** [comment]
I used the accept-language values from the localized Firefox versions that can be found here: https://www.mozilla.org/en-US/firefox/all/.

The IP option can be found in the accept-language dropdown (first option).

**Comment by Kraxys** [comment]
> 
> 
> I used the accept-language values from the localized Firefox versions that can be found here: https://www.mozilla.org/en-US/firefox/all/.
>
Ok. Just tested it with a portable FF in Russian. The language string match.

> The IP option can be found in the accept-language dropdown (first option).
>
Just tested it. After selecting "IP" in header/Spoof Accept Language, ip-check.info found no language at all. The Language line is blank.

**Comment by sereneblue** [comment]
Can you visit https://ipapi.co/json with the IPs you're using and post the languages it detects?

**Comment by Kraxys** [comment]
> 
> 
> Can you visit https://ipapi.co/json with the IPs you're using and post the languages it detects?

On this site:

the row Languages when using Russian FF and a Russian IP is:
>Languages	"ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,av,sah,nog"

the row Languages when using English FF, Russian IP and Chameleon is:
>languages	"ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,av,sah,nog"

exactly the same.




 russian IP + Chameleon:
> languages	"ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,av,sah,nog"

**Comment by sereneblue** [comment]
Wow, that's a lot of languages. ipapi uses the IP address to determine the language so Chameleon won't change anything. It's probably a bug in Chameleon that's causing issues; I'll fix this soon.
