### ISSUE TITLE
Still some issue with language spoofing per IP

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#99]
I performed further tests. Some spoofing language bugs have been fixed, but some remains:
 
On https://whoer.net/#extended

**1) With Russian FF Portable**.
HTTP_ACCEPT_LANGUAGE = ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
JavaScript:  ru-RU 

**2) With English FF Portable with Russian IP and Chameleon set to Language = IP**:
HTTP_ACCEPT_LANGUAGE = kk,ru;q=0.8,ru-RU;q=0.6,en-US;q=0.4,en;q=0.2
Javascript: kk 

**3) With English FF Portable and Chameleon set to Language = Russian**:
HTTP_ACCEPT_LANGUAGE = ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
JavaScript: ru-RU 

So spoofing a fixed language seems to perfectly match this time, but spoofing language per IP still doesn't.

**Comment by sereneblue** [comment]
Oh, I see what the issue is. It's the way that Chameleon detects the language. It's using Kazakh instead of Russian because it finds that first in the list of languages (Kazakh also has Russian in the header). Just needs a little tweak to get the correct value.

**Comment by sereneblue** [comment]
Can you try the latest commit?

If you don't know how to load Chameleon from source:
Download and extract the repository from the repo page, select the `Debug addon` option in the dropdown on `about:addons`, click `Load Temporary Add-on` and select the `manifest.json` file from the `src` folder in the repo directory.

**Comment by Kraxys** [comment]
> 
> 
> Can you try the latest commit?
> 

Just tested. The language per IP does match this time. :) .... At least for Russian!

EDIT: Tested with a romanian IP. The site https://whoer.net/#extended still detects some langugage inconsistency (the site doesn't tell which one).  I will have to compare with a Romanian FF portable

... And with a Swiss IP and a norvegian IP Chameleon set en-US as language  (header + JS). Maybe these IP are somewhat recognized as a US one but it's weird because they are everywhere recognized as swiss and norvegian respectively

**Comment by sereneblue** [comment]
Can you post the languages value for those IPs when you visit https://ipapi.co/json?

**Comment by sereneblue** [comment]
I've found the issue, however, this is a little complicated. For Swiss IPs, the languages returned by ipapi are `de-CH,fr-CH,it-CH,rm`. Chameleon would use Romansh for the language because it's the only language with de-CH in it's header value. For most country IPs it should be more accurate.

**Comment by sereneblue** [comment]
If you're still having issues with the latest version, feel free to reopen this issue.

**Comment by Kraxys** [comment]
I performed more extensive tests in several countries, with at least 2 different vpn servers in each country (and most of the time, 3 servers).
I set Chameleon with latest commit with "IP" for TimeZone and Language, and tested them both.

**Results**: TimeZone was always correct (Time and geolocation). But there qare still several problems with language.

**Details**:
* For servers in Canada, Germany, Great Britain, Iceland, Russia and Sweden, the languages were correct.

**Issues detected:**

**Australia:**
HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.5 -> wrong
on ipapi.co/json: languages	"en-AU"


**Denmark:** 
HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.5  ->wrong
on ipapi.co/json: languages	"da-DK,en,fo,de-DK"


**Czech Republic:** 
HTTP_ACCEPT_LANGUAGE: cs,sk;q=0.8,en-US;q=0.5,en;q=0.3  -> whoer.net not happy -> something subtle still wrong
on ipapi.co/json: languages	"cs,sk"


**France:**
HTTP_ACCEPT_LANGUAGE en-US,en;q=0.5   -> wrong
on ipapi.co/json: languages  "fr-FR,frp,br,co,ca,eu,oc"
(should be fr-FR, more representative for most of french people)


**Luxemburg:** 
HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.5 ->wrong
on ipapi.co/json: languages	"lb,de-LU,fr-LU"


**Netherlands** (many vpn servers here):
HTTP_ACCEPT_LANGUAGE en-US,en;q=0.5 -> wrong
on ipapi.co/json:  languages	"nl-NL,fy-NL"


**Norway:**
HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.5 -> wrong
on ipapi.co/json:  languages	"no,nb,nn,se,fi"


**Romania:**
HTTP_ACCEPT_LANGUAGE: ro-RO,ro;q=0.8,en-US;q=0.6,en-GB;q=0.4,en;q=0.2  -> seems Ok but whoer.net not happy -> something subtle still wrong
on ipapi.co/json:  languages	"ro,hu,rom"


**Singapore:**
HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.5 -> wrong
on ipapi.co/json:  languages	"cmn,en-SG,ms-SG,ta-SG,zh-SG"


**Switzerland:**
HTTP_ACCEPT_LANGUAGE:  en-US,en;q=0.5  -> wrong
on ipapi.co/json:  languages	"de-CH,fr-CH,it-CH,rm"
Already discuted, but language should be de-CH or fr-CH as most swiss people are speaking german or french.

**Comment by sereneblue** [comment]
Ah, I guess it's a permission issue for reopening issues. For future reference, commenting on a closed issue is fine. :)

Thanks for the extensive testing! I'll have to do some digging to find some of the values. I'm curious what's causing issues. Czech Republic, Denmark, France, Netherlands, Norway, and Romania should be working correctly, probably needs a little more tweaking.

For the others, I'm not sure if there is a specific value for those countries or if users from those countries download one of the other builds (ex Swiss users use the German FF version).

**Comment by sereneblue** [comment]
I've made a few changes, won't create a commit until this issue is resolved.

Australia:
Returns en-US 

Czech Republic:
Works

Denmark:
Works

France:
Works

Luxemburg:
Returns en-US

Netherlands:
Works

Norway:
Works

Romania:
Works

Singapore:
Returns en-US

Switzerland:
Returns de,en-US;q=0.7,en;q=0.3

I'm looking into the accept-language header values for other browsers.

**Comment by Kraxys** [comment]
> 
> 
> I've made a few changes, won't create a commit until this issue is resolved.
> 

> Norway:
> Works
>

Just Checked with a Norway server and Chameleon **0.9.20**. 

I get:
HTTP_ACCEPT_LANGUAGE : sq,sq-AL;q=0.8,en-US;q=0.5,en;q=0.3   -> bad.
Javascript: sq

Do you used the same 0.9.20 version for your tests, a some mote advanced version?

**Comment by sereneblue** [comment]
It's the current version I'm working on that will be v0.9.21.

**Comment by Kraxys** [comment]
> 
> 
> It's the current version I'm working on that will be v0.9.21.
> 
> EDIT:
> Australia, Hong Kong, and Switzerland should work now
>
Yes, I confirm after tests. Denmark works, too.


But Fot **Netherlands** and **Norway**, HTTP_ACCEPT_LANGUAGE header is **empty**, an javascript is **en-US**.

Also for **France**, I get the correct language with one server, but  but with an other near Paris, the  HTTP_ACCEPT_LANGUAGE **n**l,en-US;q=0.7,en;q=0.3 ans javascript is **nl**.
